### ISSUE TITLE
OpenSSL server sends cookie extension in CertificateRequest

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#10413]
Using master as of 6ed12cec7216

When OpenSSL is configured with certificate based client authentication and a TLS 1.3 connection is established, the server will send CertificateRequest message with a `cookie` extension inside.

This is an explicit RFC 8446 violation that will cause interoperability issues with correct TLS 1.3 implementations, section 4.2:
```
   The table below indicates the messages where a given extension may
   appear, using the following notation: CH (ClientHello),
   SH (ServerHello), EE (EncryptedExtensions), CT (Certificate),
   CR (CertificateRequest), NST (NewSessionTicket), and
   HRR (HelloRetryRequest).  If an implementation receives an extension
   which it recognizes and which is not specified for the message in
   which it appears, it MUST abort the handshake with an
   "illegal_parameter" alert.
```
```
   +--------------------------------------------------+-------------+
   | Extension                                        |     TLS 1.3 |
   +--------------------------------------------------+-------------+
...
   | cookie (RFC 8446)                                |     CH, HRR |
```

   <details><summary>reproducer</summary><p>

Note: requires python environment with `six` installed (`pip install six`)
```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tomato42/tlsfuzzer/pull/611 is merged
git checkout certificate-request-extensions
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-certificate-request.py -k localhost.key -c localhost.crt -s "ecdsa_secp256r1_sha256 ecdsa_secp384r1_sha384 ecdsa_secp521r1_sha512 ed25519 ed448 rsa_pss_pss_sha256 rsa_pss_pss_sha384 rsa_pss_pss_sha512 rsa_pss_rsae_sha256 rsa_pss_rsae_sha384 rsa_pss_rsae_sha512 rsa_pkcs1_sha256 rsa_pkcs1_sha384 rsa_pkcs1_sha512 sha224+ecdsa sha1+ecdsa rsa_pkcs1_sha224 rsa_pkcs1_sha1"
popd
kill $openssl_pid
```

   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
verify depth is 1
Using default temp DH parameters
ACCEPT
depth=1 O = Example CA
verify return:1
depth=0 CN = John Smith
verify return:1
depth=1 O = Example CA
verify return:1
depth=0 CN = John Smith
verify return:1
^C
```

   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

verify extensions in CertificateRequest ...
Error encountered while processing node <tlsfuzzer.expect.ExpectCertificateRequest object at 0x7f06faf8d750> (child: <tlsfuzzer.expect.ExpectCertificate object at 0x7f06faf8da50>) with last message being: <tlslite.messages.Message object at 0x7f06faf90890>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-certificate-request.py", line 329, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 227, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1270, in process
    self._compare_extensions(cert_request)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 509, in _compare_extensions
    for i in diff)))
AssertionError: Server sent unexpected extension(s): 47

with certificate ...
OK

check sigalgs in cert request ...
OK

sanity ...
OK

Test to verify if server accepts empty certificate messages and
advertises only expected signature algotithms in Certificate
Request message

version: 3

Test end
successful: 4
failed: 1
  'verify extensions in CertificateRequest'
```

   </p></details>

**Comment by tomato42** [comment]
Side note: if you have ideas on how to possibly cause the server to send other extensions, I can test that and verify that only RFC 8446 valid extensions are present.

**Comment by tomato42** [comment]
facepalm.jpg

I've misread 44 as 47 and 47 is `certificate_authorities` which can be in CertifiateRequest
