### ISSUE TITLE
Cross compiling 1.1.1d for ARM

### ISSUE THREAD

**Issue by samuelsesa** [openssl/openssl#10646]
Hello all
I'm finding some issues to update from openssl-1.1.0f to openssl-1.1.1d
This options where used in 1.1.0f: (it worked nice)
./Configure --cross-compile-prefix=$(CHOST)- --prefix=$(DIR_INSTALL) shared linux-generic32
Using this options on openssl-1.1.1d generated libssl.so that gets in "for loop" in function ssl_cipher_process_rulestr ad infinitum

So I tried with openssl-1.1.1a and it works nice.
Should I change the compilation options in 1.1.1d?

I tried compiling 1.1.1a with better options:
./Configure linux-armv4 -march=armv6 -D__ARM_MAX_ARCH__=8
But it generates errors in assembler configuration:
crypto/sha/keccak1600-armv4.S: Assembler messages:
crypto/sha/keccak1600-armv4.S:2203: Error: ']' expected -- `vst1.64 {q4},[r0:64]'
[... many lines ... ]
make[3]: *** [crypto/sha/keccak1600-armv4.o] Error 1

Are this options correct for 1.1.1a?

Thanks for your time.

**Comment by simplelins** [comment]
https://github.com/openssl/openssl/issues/9507

**Comment by samuelsesa** [comment]
Thanks!
I understand that my problem was detected on 1.1.1a and is already fixed.

Anyway, I would like to compile version 1.1.1d in my development

This is my config output:

```
~/buildroot/output/build/libopenssl-1.1.1c$ perl configdata.pm --dump
Command line (with current working directory = .):

    /usr/bin/perl ./Configure --cross-compile-prefix=arm-none-linux-gnueabi- --prefix=~/Bin/imx shared linux-armv4 -march=armv6 -D__ARM_MAX_ARCH__=8

Perl information:

    /usr/bin/perl
    5.26.1 for i686-linux-gnu-thread-multi-64int

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    buildtest-c\+\+
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    idea
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    shared
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng                [cross-compiling] 
    asan                    [default]         OPENSSL_NO_ASAN
    crypto-mdebug           [default]         OPENSSL_NO_CRYPTO_MDEBUG
    crypto-mdebug-backtrace [default]         OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    devcryptoeng            [default]         OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128     [default]         OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                     [default]         OPENSSL_NO_EGD
    external-tests          [default]         OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer          [default]         OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl                [default]         OPENSSL_NO_FUZZ_AFL
    heartbeats              [default]         OPENSSL_NO_HEARTBEATS
    md2                     [default]         OPENSSL_NO_MD2 (skip crypto/md2)
    msan                    [default]         OPENSSL_NO_MSAN
    rc5                     [default]         OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                    [default]         OPENSSL_NO_SCTP
    ssl-trace               [default]         OPENSSL_NO_SSL_TRACE
    ubsan                   [default]         OPENSSL_NO_UBSAN
    unit-test               [default]         OPENSSL_NO_UNIT_TEST
    weak-ssl-ciphers        [default]         OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                    [default]         
    zlib-dynamic            [default]         
    ssl3                    [default]         OPENSSL_NO_SSL3
    ssl3-method             [default]         OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    aes_asm_src => "aes_cbc.c aes-armv4.S bsaes-armv7.S aesv8-armx.S",
    aes_obj => "aes_cbc.o aes-armv4.o bsaes-armv7.o aesv8-armx.o",
    apps_aux_src => "",
    apps_init_src => "",
    apps_obj => "",
    bf_asm_src => "bf_enc.c",
    bf_obj => "bf_enc.o",
    bn_asm_src => "bn_asm.c armv4-mont.S armv4-gf2m.S",
    bn_obj => "bn_asm.o armv4-mont.o armv4-gf2m.o",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cast_asm_src => "c_enc.c",
    cast_obj => "c_enc.o",
    cflags => "-pthread",
    chacha_asm_src => "chacha-armv4.S",
    chacha_obj => "chacha-armv4.o",
    cmll_asm_src => "camellia.c cmll_misc.c cmll_cbc.c",
    cmll_obj => "camellia.o cmll_misc.o cmll_cbc.o",
    cppflags => "",
    cpuid_asm_src => "armcap.c armv4cpuid.S",
    cpuid_obj => "armcap.o armv4cpuid.o",
    cxxflags => "-std=c++11 -pthread",
    defines => [  ],
    des_asm_src => "des_enc.c fcrypt_b.c",
    des_obj => "des_enc.o fcrypt_b.o",
    disable => [  ],
    dso_extension => ".so",
    dso_scheme => "dlfcn",
    ec_asm_src => "ecp_nistz256.c ecp_nistz256-armv4.S",
    ec_obj => "ecp_nistz256.o ecp_nistz256-armv4.o",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread",
    exe_extension => "",
    includes => [  ],
    keccak1600_asm_src => "keccak1600-armv4.S",
    keccak1600_obj => "keccak1600-armv4.o",
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE",
    lib_defines => [  ],
    md5_asm_src => "",
    md5_obj => "",
    modes_asm_src => "ghash-armv4.S ghashv8-armx.S",
    modes_obj => "ghash-armv4.o ghashv8-armx.o",
    module_cflags => "-fPIC",
    module_cxxflags => "",
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    padlock_asm_src => "",
    padlock_obj => "",
    perlasm_scheme => "linux32",
    poly1305_asm_src => "poly1305-armv4.S",
    poly1305_obj => "poly1305-armv4.o",
    rc4_asm_src => "rc4_enc.c rc4_skey.c",
    rc4_obj => "rc4_enc.o rc4_skey.o",
    rc5_asm_src => "rc5_enc.c",
    rc5_obj => "rc5_enc.o",
    rmd160_asm_src => "",
    rmd160_obj => "",
    sha1_asm_src => "sha1-armv4-large.S sha256-armv4.S sha512-armv4.S",
    sha1_obj => "sha1-armv4-large.o sha256-armv4.o sha512-armv4.o",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_extension => ".so.\$(SHLIB_VERSION_NUMBER)",
    shared_extension_simple => ".so",
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
    uplink_aux_src => "",
    uplink_obj => "",
    wp_asm_src => "wp_block.c",
    wp_obj => "wp_block.o",

Recorded environment:

    AR = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPPFLAGS = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LDFLAGS = 
    LDLIBS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = arm-none-linux-gnueabi-ar
    ARFLAGS         = r
    CC              = arm-none-linux-gnueabi-gcc
    CFLAGS          = -Wall -O3 -march=armv6
    CPPDEFINES      = __ARM_MAX_ARCH__=8
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CROSS_COMPILE   = arm-none-linux-gnueabi-
    CXX             = arm-none-linux-gnueabi-g++
    CXXFLAGS        = -Wall -O3 -march=armv6
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /usr/bin/perl
    RANLIB          = arm-none-linux-gnueabi-ranlib
    RC              = arm-none-linux-gnueabi-windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
```

**Comment by mattcaswell** [comment]
> Using this options on openssl-1.1.1d generated libssl.so that gets in "for loop" in function ssl_cipher_process_rulestr ad infinitum

What does this mean? Does this occur as a result of a particular function call into libssl you are making? Are you setting a specific cipher string - if so what is it.

Please provide more details about what you are actually doing when you encounter this problem.

**Comment by samuelsesa** [comment]
My program generates a core and this is the back trace

[New Thread 2381]
Reading symbols from /lib/libcrypt.so.1...done.
Loaded symbols for /lib/libcrypt.so.1
Reading symbols from /usr/lib/libssl.so.1.1...done.
Loaded symbols for /usr/lib/libssl.so.1.1
Reading symbols from /usr/lib/libcrypto.so.1.1...done.
Loaded symbols for /usr/lib/libcrypto.so.1.1
Reading symbols from /usr/lib/libz.so.1...done.
Loaded symbols for /usr/lib/libz.so.1
Reading symbols from /lib/libm.so.6...done.
Loaded symbols for /lib/libm.so.6
Reading symbols from /lib/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libdl.so.2
Reading symbols from /lib/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/librt.so.1
Reading symbols from /usr/lib/libpam.so.0...done.
Loaded symbols for /usr/lib/libpam.so.0
Reading symbols from /lib/libc.so.6...done.
Loaded symbols for /lib/libc.so.6
Reading symbols from /lib/libpthread.so.0...done.
Loaded symbols for /lib/libpthread.so.0
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/ld-linux.so.3...done.
Loaded symbols for /lib/ld-linux.so.3
Reading symbols from /lib/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib/libnss_files.so.2
Reading symbols from /mnt/flash/linux/libccp.so...done.
Loaded symbols for /mnt/flash/linux/libccp.so
Reading symbols from /mnt/flash/linux/libevccp.so...done.
Loaded symbols for /mnt/flash/linux/libevccp.so
Reading symbols from /mnt/flash/linux/libwsetcli.so...done.
Loaded symbols for /mnt/flash/linux/libwsetcli.so
Reading symbols from /usr/lib/libxsdset.so...done.
Loaded symbols for /usr/lib/libxsdset.so
Reading symbols from /lib/libstdc++.so.6...done.
Loaded symbols for /lib/libstdc++.so.6
Core was generated by `web_server'
Program terminated with signal 4, Illegal instruction.
#0  0x400849b0 in ssl_cipher_process_rulestr () from /usr/lib/libssl.so.1.1
Name collision between pc3 pc3
Name collision between vt102 vt102
Name collision between adm+sgr adm+sgr
Name collision between dumb dumb
Name collision between unknown unknown
Name collision between glasstty glasstty
Name collision between vt52 vt52
Name collision between wy50 wy50
Name collision between wy60 wy60
Name collision between wy160 wy160
Name collision between oldsun oldsun
Name collision between sun-il sun-il
Name collision between sun sun
Name collision between sun-ss5 sun-ss5
Name collision between sun-type4 sun-type4
Name collision between xterm-r6 xterm-r6
Name collision between xterm xterm
Name collision between tvi925 tvi925
(gdb) bt
#0  0x400849b0 in ssl_cipher_process_rulestr () from /usr/lib/libssl.so.1.1
#1  0x400857cc in ssl_create_cipher_list () from /usr/lib/libssl.so.1.1
#2  0x4008d1f4 in SSL_CTX_new () from /usr/lib/libssl.so.1.1
#3  0x000105c0 in http_ssl_load ()
#4  0x0000ed34 in main ()

**Comment by mattcaswell** [comment]
Hmmm, so this is just in a C file not even in assembler so I guess the Configure/cross compile options are wrong for this platform. But I know nothing about ARM so I'll step back to see if others have suggestions.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input
