### ISSUE TITLE
libcrypto.so seg fault

### ISSUE THREAD

**Issue by sophieyfang** [openssl/openssl#10671]
We are using this library to call stackdriver api. Intermittently, we saw this segmentation fault error after 2-8 hrs running.

Below are the coredump snippet
Detailed implementation of [wg_curl_get_or_post](https://github.com/Stackdriver/collectd/blob/fe702faadeee9a12c17336a4d718e6a677303098/src/write_gcm.c#L562)

```
(gdb) bt
#0  0x00007f8ec7826075 in ?? () from /lib64/libcrypto.so.1.0.0
#1  0x00007f8ec782664c in lh_retrieve () from /lib64/libcrypto.so.1.0.0
#2  0x00007f8ec7828c2b in ?? () from /lib64/libcrypto.so.1.0.0
#3  0x00007f8ec78294ea in ERR_get_state () from /lib64/libcrypto.so.1.0.0
#4  0x00007f8ec78296ff in ERR_clear_error () from /lib64/libcrypto.so.1.0.0
#5  0x00007f8ec803c0a8 in ?? () from /usr/lib64/libcurl.so.4
#6  0x00007f8ec7ff4c41 in ?? () from /usr/lib64/libcurl.so.4
#7  0x00007f8ec7ff0d31 in ?? () from /usr/lib64/libcurl.so.4
#8  0x00007f8ec7ff2014 in ?? () from /usr/lib64/libcurl.so.4
#9  0x00007f8ec8011666 in ?? () from /usr/lib64/libcurl.so.4
#10 0x00007f8ec8012143 in curl_multi_perform () from /usr/lib64/libcurl.so.4
#11 0x00007f8ec8008d08 in curl_easy_perform () from /usr/lib64/libcurl.so.4
#12 0x00007f8ec8264fc1 in wg_curl_get_or_post (response=response@entry=0x7f8ebb7fce08, url=0x21c6f10 "https://monitoring.googleapis.com/v3/projects/stackdriverxxxx/collectdTimeSeries",
    body=body@entry=0x7f8e8005eda0 "{\"name\":\"project/xxxx-xx\",\"resource\":{\"type\":\"gce_instance\",\"labels\":{\"instance_id\":\"xxxxx\",\"zone\":\"us-central1-a\"}},\"collectdVersion\":\"stackdriver_agent/6.0.0-1.sles1"..., headers=headers@entry=0x7f8ebb7fce30, num_headers=num_headers@entry=2, silent_failures=silent_failures@entry=false) at src/write_gcm.c:602
#13 0x00007f8ec8269fd4 in wg_transmit_unique_segment (ctx=ctx@entry=0x21ffd00, queue=queue@entry=0x21c6fe0, list=list@entry=0x7f8e98054670) at src/write_gcm.c:3933
#14 0x00007f8ec826ab9a in wg_transmit_unique_segments (list=<optimized out>, queue=<optimized out>, ctx=<optimized out>) at src/write_gcm.c:3857
#15 wg_process_queue (ctx=<optimized out>, queue=<optimized out>, stats=<optimized out>) at src/write_gcm.c:3675
#16 0x00007f8ec9e4f74a in start_thread () from /lib64/libpthread.so.0
#17 0x00007f8ec998af6d in clone () from /lib64/libc.so.6

```

Reproduce code snippet:

```
int main() {
  char *response = NULL;
  char *url = "https://monitoring.googleapis.com/v3/projects/stackdriver-xxxx/timeSeries";
  char *body = "{\"timeSeries\":[{\"resource\":{\"type\":\"gce_instance\",\"labels\":{\"instance_id\":\"xxxx\",\"zone\":\"us-east1-c\"}},\"metric\":{\"type\":\"agent.googleapis.com/agent/uptime\",\"labels\":{\"version\":\"stackdriver_agent/6.0.0-1.stretch\"}},\"metricKind\":\"CUMULATIVE\",\"valueType\":\"INT64\",\"points\":[{\"interval\":{\"startTime\":\"2019-12-19T20:35:33.406834284Z\",\"endTime\":\"2019-12-20T10:11:36.405598639Z\"},\"value\":{\"int64Value\":135363}}]},{\"resource\":{\"type\":\"gce_instance\",\"labels\":{\"instance_id\":\"xxxxx\",\"zone\":\"us-east1-c\"}},\"metric\":{\"type\":\"agent.googleapis.com/agent/memory_usage\",\"labels\":{}},\"metricKind\":\"GAUGE\",\"valueType\":\"DOUBLE\",\"points\":[{\"interval\":{\"startTime\":\"2019-12-19T10:11:36.405598639Z\",\"endTime\":\"2019-12-20T10:11:36.405598639Z\"},\"value\":{\"doubleValue\":1269092352.000000}}]},{\"resource\":{\"type\":\"gce_instance\",\"labels\":{\"instance_id\":\"xxx\",\"zone\":\"us-east1-c\"}},\"metric\":{\"type\":\"agent.googleapis.com/agent/streamspace_size_throttling\",\"labels\":{}},\"metricKind\":\"GAUGE\",\"valueType\":\"DOUBLE\",\"points\":[{\"interval\":{\"startTime\":\"2019-12-19T10:11:36.405598639Z\",\"endTime\":\"2019-12-20T10:11:36.405598639Z\"},\"value\":{\"doubleValue\":0.000000}}]},{\"resource\":{\"type\":\"gce_instance\",\"labels\":{\"instance_id\":\"xxx\",\"zone\":\"us-east1-c\"}},\"metric\":{\"type\":\"agent.googleapis.com/agent/streamspace_size\",\"labels\":{}},\"metricKind\":\"GAUGE\",\"valueType\":\"DOUBLE\",\"points\":[{\"interval\":{\"startTime\":\"2019-12-19T10:11:37.405603695Z\",\"endTime\":\"2019-12-20T10:11:37.405603695Z\"},\"value\":{\"doubleValue\":447817.000000}}]}]}"; 
  const char *headers[] = {"Authorization: Bearer xxxxxxx", "Content-Type: application/json"};
  int num_headers = 2;
  _Bool silent_failures = 0;
  while( 1 ){
    wg_curl_get_or_post (
      &response, 
      url, 
      body,
      headers,
      num_headers,
      silent_failures);
    sleep(2);
  }
  return 0;
}
```

**Comment by mattcaswell** [comment]
Presumably this is OpenSSL 1.0.2. Have thread locking callbacks been set up? This might be a question you need to pose with the curl team.

**Comment by sophieyfang** [comment]
After setting the callbacks, the segfault stops.  Thanks!
