### ISSUE TITLE
duplicated key_shared in TLS 1.3 ClientHello are not detected

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#10844]
When OpenSSL receives a ClientHello it does not check if the key_shares sent by client use unique groups, it doesn't implement the check specified in https://tools.ietf.org/html/rfc8446#section-4.2.8:
```
   Clients MUST NOT offer multiple KeyShareEntry values
   for the same group.  Clients MUST NOT offer any KeyShareEntry values
   for groups not listed in the client's "supported_groups" extension.
   Servers MAY check for violations of these rules and abort the
   handshake with an "illegal_parameter" alert if one is violated.
```

reproducer: https://github.com/tomato42/tlsfuzzer/pull/553
`
PYTHONPATH=. python scripts/test-tls13-ffdhe-groups.py  'ffdhe2048 - duplicated key share entry'`

tlsfuzzer output:
```
ffdhe2048 - duplicated key share entry ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f40ed45a810> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f40ed45a850>) with last message being: <tlslite.messages.Message object at 0x7f40ed427610>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-ffdhe-groups.py", line 470, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    RecordHeader2)))
AssertionError: Unexpected message from peer: Handshake(server_hello)

Basic FFDHE group tests in TLS 1.3
Check if invalid, malformed and incompatible group key_shares are
rejected by server
version: 1

Test end
successful: 0
failed: 1
  'ffdhe2048 - duplicated key share entry'
```

OpenSSL master (6a165fab239ec5b00) prints no output on this error

(this is related, but different issue than described in #10843)

**Comment by kaduk** [comment]
Since this is specified merely as "servers MAY check", it's unlikely to be a high priority for the development team, though I expect we'd look at pull requests that implement the check.

**Comment by nhorman** [comment]
marking as coommunity issue.  @tomato42 shall I assign it to you to create a PR?

**Comment by tomato42** [comment]
sorry, focusing on post-quantum now so it's highly unlikely I'll pick it any time soon

**Comment by t8m** [comment]
Please note we are looking for community help implementing this issue. Please comment if you are interested in implementing this feature or if you have reasons why this feature is important enough so we should consider implementing it with higher priority than other requested features. The issue will be closed after 3 months otherwise.

**Comment by t8m** [comment]
This issue was closed because it was marked with the help wanted label and there was no interest in implementing this issue or any other activity for more than 2 months.
