### ISSUE TITLE
TLS 1.3 invalid key_share entries are incorrectly handled

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#10843]
When TLS 1.3 ClientHello includes an ECDHE key share with encoded point at infinity (single byte `0x00`), or a FFDHE key share with value outside allowed range (==1 or ==p), the message is rejected with `internal_error` alert instead of `illegal_parameter`.

This is with current master 6a165fab239 and 1.1.1 (902a97b5869e)

tlsfuzzer script from https://github.com/tomato42/tlsfuzzer/pull/553

`PYTHONPATH=. python scripts/test-tls13-ecdhe-curves.py`

output:
```
...
secp384r1 - point at infinity ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7fbfd645d3d0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7fbfd645d450>) with last message being: <tlslite.messages.Message object at 0x7fbfd63a7d50>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-ecdhe-curves.py", line 348, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 237, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1680, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"
...
Test end
successful: 30
failed: 3
  'secp256r1 - point at infinity'
  'secp384r1 - point at infinity'
  'secp521r1 - point at infinity'
```

OpenSSL output:
```
...
40:C7:04:34:37:7F:00:00:error:elliptic curve routines:EC_POINT_get_affine_coordinates:point at infinity:crypto/ec/ec_lib.c:884:
40:C7:04:34:37:7F:00:00:error:elliptic curve routines:ecdh_simple_compute_key:point arithmetic failure:crypto/ec/ecdh_ossl.c:87:
40:C7:04:34:37:7F:00:00:error:SSL routines::internal error:ssl/s3_lib.c:4864:
...
```

Same issue with current 1.1.1 branch:
```
140455911028544:error:1012506A:elliptic curve routines:EC_POINT_get_affine_coordinates:point at infinity:crypto/ec/ec_lib.c:850:
140455911028544:error:1010109B:elliptic curve routines:ecdh_simple_compute_key:point arithmetic failure:crypto/ec/ecdh_ossl.c:87:
140455911028544:error:1424E044:SSL routines:ssl_derive:internal error:ssl/s3_lib.c:4814:
```

For FFDHE it's the `PYTHONPATH=. python scripts/test-tls13-ffdhe-groups.py` script

```
...
ffdhe6144 - p as key share ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f1f3c77dad0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1f3c77db10>) with last message being: <tlslite.messages.Message object at 0x7f1f3c6cb550>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-ffdhe-groups.py", line 470, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 237, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1680, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

ffdhe2048 - 1 as key share ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f1f3c7d0990> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1f3c7d09d0>) with last message being: <tlslite.messages.Message object at 0x7f1f3c6cb910>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-ffdhe-groups.py", line 470, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 237, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1680, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

ffdhe3072 - right 0-padded key_share ...
OK

ffdhe8192 - right 0-padded key_share ...
OK

ffdhe6144 - empty key share entry in key_share ext ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f1f3c77dd90> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1f3c77ddd0>) with last message being: <tlslite.messages.Message object at 0x7f1f3c6cbdd0>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-ffdhe-groups.py", line 470, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 237, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1680, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "decode_error"
...
Test end
successful: 32
failed: 30
  'ffdhe2048 - 1 as key share'
  'ffdhe2048 - all bits set key share'
  'ffdhe2048 - duplicated key share entry'
  'ffdhe2048 - empty key share entry in key_share ext'
  'ffdhe2048 - p as key share'
  'ffdhe2048 - p-1 as key share'
  'ffdhe3072 - 1 as key share'
  'ffdhe3072 - all bits set key share'
  'ffdhe3072 - duplicated key share entry'
  'ffdhe3072 - empty key share entry in key_share ext'
  'ffdhe3072 - p as key share'
  'ffdhe3072 - p-1 as key share'
  'ffdhe4096 - 1 as key share'
  'ffdhe4096 - all bits set key share'
  'ffdhe4096 - duplicated key share entry'
  'ffdhe4096 - empty key share entry in key_share ext'
  'ffdhe4096 - p as key share'
  'ffdhe4096 - p-1 as key share'
  'ffdhe6144 - 1 as key share'
  'ffdhe6144 - all bits set key share'
  'ffdhe6144 - duplicated key share entry'
  'ffdhe6144 - empty key share entry in key_share ext'
  'ffdhe6144 - p as key share'
  'ffdhe6144 - p-1 as key share'
  'ffdhe8192 - 1 as key share'
  'ffdhe8192 - all bits set key share'
  'ffdhe8192 - duplicated key share entry'
  'ffdhe8192 - empty key share entry in key_share ext'
  'ffdhe8192 - p as key share'
  'ffdhe8192 - p-1 as key share'
```
(duplicated key shares are filed as #10844)

OpenSSL master output:
```
...
40:97:D3:F2:90:7F:00:00:error:Diffie-Hellman routines:compute_key:invalid public key:crypto/dh/dh_key.c:216:
40:97:D3:F2:90:7F:00:00:error:SSL routines::internal error:ssl/s3_lib.c:4864:
...
```

**Comment by nhorman** [comment]
@tomato42 given that 1.1.1 is out of support, is this still an issue on 3.3?

**Comment by tomato42** [comment]
While I see it in openssl-3.0.0 I don't see it in openssl-3.0.14,  openssl-3.1.0, and similarly current master, it behaves correctly, so looks to be fixed in current branches
