### ISSUE TITLE
remove NETSCAPE_CERT_SEQUENCE

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#1177]

**Comment by levitte** [comment]
Is this something you intend to do, or are you asking someone else to pick the gauntlet?

Either way, is this advisable pre 1.2.0?  Feature removal 'n all that?

**Comment by richsalz** [comment]
it's just an unassigned issue for now.

**Comment by richsalz** [comment]
Anyone can make a pull request, and the OpenSSL team reviews it.  (Approval needs two openssl people, one must be on the OMC.)  There are concerns about compatibility, but the next release after 1.1.1 is probably going to be okay.  In short: go for it!

**Comment by JohnAZoidberg** [comment]
Alright!
I suppose you want to remove all functionality regarding the Netscape certificate sequences, including the nseq command?

What about the other Netscape structures? (NETSCAPE_SPKAC and NETSCAPE_SPKI)

**Comment by t-j-h** [comment]
I don't see the benefit in removing these items myself.

**Comment by richsalz** [comment]
It's dead code.

**Comment by levitte** [comment]
We can't remove public code immediately, but we *can* decide to mark it deprecated.  I'd support such a move.

**Comment by minfrin** [comment]
We are in the  process of formalising "Signed Public Key and Challenge" into an RFC, and thus solving the long standing "it's not standardised" problem.

Would it make sense to deprecate NETSCAPE_SPKI and rename NETSCAPE_SPKI to SPKAC?

**Comment by richsalz** [comment]
Sorry, still the same question:  are you *using* this stuff, or just *documenting* it?

**Comment by minfrin** [comment]
Both, we are _using_ this stuff at https://redwax.eu/rs/docs/latest/mod/mod_spkac.html, and we are _documenting_ it at https://datatracker.ietf.org/doc/draft-leggett-spkac/.

We're doing the same with the Microsoft CertEnroll / CSR at https://redwax.eu/rs/docs/latest/mod/mod_csr.html and https://interop.redwax.eu/rs/csr/. If it needs implementing, we're implementing it. If it needs documenting, we're documenting it. If it needs standardisation, we're standardising it.

For further clarification, https://redwax.eu/rs/docs/latest/mod/mod_spkac.html has been used in production for eight years. It is not dead code.

**Comment by richsalz** [comment]
Not dead, just not clear it needs to still be supported.  Thanks for your explanation tho.

**Comment by sahanaprasad07** [comment]
currently on master, running  'openssl spkac' results in a seg fault.

(gdb) run spkac
Program received signal SIGSEGV, Segmentation fault.
0x0000000000478a75 in app_load_config_internal ()
(gdb) bt
#0  0x0000000000478a75 in app_load_config_internal ()
#1  0x000000000046cc59 in spkac_main ()
#2  0x0000000000444c09 in do_cmd ()
#3  0x0000000000422457 in main ()

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

@sahanaprasad07 please open a new issue for the segfault

**Comment by richsalz** [comment]
Here's the PR for QuicTLS: https://github.com/quictls/quictls/pull/189 if you want to use it.

**Comment by t8m** [comment]
Let's consider this for 4.0.
