### ISSUE TITLE
The call to the api X509_STORE_CTX_get_by_subject crashes with the error in top stack trace frame showing __pthread_rwlock_wrlock_full

### ISSUE THREAD

**Issue by vjkumaraffirmed** [openssl/openssl#11813]
Hi,

I upgraded to openSSL 1.1.1d from openSSL 1.0.x version and I am facing the below crash. The same function pkixip_add2stores_cert never used to crash when i was using old open SSL version 1.0.x.

My application function pkixip_add2stores_cert will be calling the API X509_STORE_CTX_get_by_subject () to check if the X509 cert is there in the cert store or not. If it is not there then my application will call the API X509_STORE_add_cert to add it to the store

NOTE, in my application the end-entity cert is added first time tot he store in the application init time but if I try to add the same certificate from another flow then my application is calling X509_STORE_CTX_get_by_subject() to check if it is already present in the store or not. At this time, it crashes.

Below is the call stack, pls confirm if this problem exists in openSSL 1.1.1d and what is the fix for the same.

Back trace
============
#0  __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x69405b7265747375) at pthread_rwlock_common.c:576
#1  __GI___pthread_rwlock_wrlock (rwlock=0x69405b7265747375) at pthread_rwlock_wrlock.c:27
#2  0x00007fa4f9bdab99 in CRYPTO_THREAD_write_lock () from /opt/thoroughbred/lib/libcrypto.so.1.1
#3  0x00007fa4f9be9e3d in X509_STORE_CTX_get_by_subject () from /opt/thoroughbred/lib/libcrypto.so.1.1
#4  0x00007fa4f54ef8cd in pkixip_add2stores_cert (x=0x5646cabdb020) at x509.c:536
#5  0x00007fa4f54bdd61 in handle_cpa_thr (a=0x5646cab28bb0) at cps.c:349
#6  0x00007fa4f54bd472 in thrpool_req (func=0x7fa4f54bdcd9 <handle_cpa_thr>, arg=0x5646cab28bb0, tid=0x0, prio=11) at /anroot/projects/tos/apps/sendd/sendd-master/include/thrpool.h:68
#7  0x00007fa4f54bdffe in snd_handle_cpa (b=0x5646cbf35600) at cps.c:426
#8  0x00007fa4f54c280d in snd_recv_pkt (b=0x5646cbf35600, ifi=2, in=1, pkt=0x5646cb4f7030) at proto.c:828
#9  0x00007fa4f54c2444 in process_sendd_recv_pkt (ndp_pkt=0x5646cbe80940 "n", pkt_len=676, ifi=2, in=1, msg=0x5646cb4f7030) at proto.c:736
#10 0x00007fa4f6987df8 in Sendd::recvSenddPktFromFP (this=0x5646cb214000, pMsg=0x5646cb4f7030) at Sendd.cpp:567
#11 0x00007fa4f6a0c4ce in SenddTaskMsgCallback::Callback (this=0x5646cad07b80) at SenddTaskMsgCallback.cpp:50
#12 0x00005646c892e45f in TOS::MsgService::CMsgService::dispatchMsg (this=0x5646caeac000, pcHdr=0x5646cb59a000, pMsg=0x5646cb59a042 "\b\225\001\020\214\001\030=\"\244\005n", msgLen=766, hd
l=17, packet=0x5646cadd08d0) at MsgService.cpp:1787
#13 0x00005646c8acb850 in TOS::IPC::ConnectionMgr::processSocket (this=0x5646cae50000) at ConnectionMgr.cpp:1954
#14 0x00005646c8971bc1 in TOS::MsgServiceEventCallback::process (this=0x5646cacb77f0, data=1) at MsgServiceEventCallback.cpp:52
#15 0x00005646c8908476 in TOS::CScheduler::dispatcher (arg=0x5646cabadd40) at CScheduler.cpp:715
#16 0x00007fa4fa2befa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#17 0x00007fa4f9dc94cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by kaduk** [comment]
What is the actual nature of the crash -- SIGSEGV?  Is the faulting address reported?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4  dev, barring further input

**Comment by t8m** [comment]
Closing as the issue was labeled as inactive for extended period of time and there was no additional input.
Please add a comment if you have any further information to support reopening the issue.
