### ISSUE TITLE
 Error: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Vidz51** [openssl/openssl#12015]
I had an application which is using aerospike , and one of the prerequisites was to have openssl. 
I executed this command 
sudo yum install gcc-c++ openssl-devel zlib-devel

However when i tried to run the my application inside docker image I am getting following error:
2020-06-02 13:03:52: Error: libssl.so.1.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.<anonymous> (/opt/service/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
    at Function._load (/opt/service/node_modules/@sentry/node/dist/integrations/console.js:41:47)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/service/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/service/node_modules/aerospike/lib/aerospike.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

Reference I followed :https://www.npmjs.com/package/aerospike#Prerequisites

Please help

**Comment by levitte** [comment]
You might want to check the version of the 'openssl-devel' package.

**Comment by Vidz51** [comment]
Hi Richard

Thank you for reply, I did check the package and update it. I am
using openssl 1.1.1, in centOS 7

I am using aerospike in my node application. Now getting following error:

2020-06-02 16:00:35: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9'
not found (required by
/opt/service/node_modules/aerospike/build/Release/aerospike.node)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
at Module.load (internal/modules/cjs/loader.js:986:32)
at Function.Module._load (internal/modules/cjs/loader.js:879:14)
at Function.
(/opt/service/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:172:43)
at Function._load
(/opt/service/node_modules/@sentry/node/dist/integrations/console.js:41:47)
at Module.require (internal/modules/cjs/loader.js:1026:19)
at require (internal/modules/cjs/helpers.js:72:18)
at bindings (/opt/service/node_modules/bindings/bindings.js:112:48)
at Object. (/opt/service/node_modules/aerospike/lib/aerospike.js:19:31)
at Module._compile (internal/modules/cjs/loader.js:1138:30)

Kindly suggest a solution

**Comment by levitte** [comment]
I suggest you talk with the CentOS folks or the aerospike folks. This is not at all within our scope.

**Comment by t8m** [comment]
You should be able to do something like: yum install 'libstdc++.so.6(CXXABI_1.3.9)(64bit)' if there is a CentOS package that provides such library. Closing as this is not really related to OpenSSL.
