### ISSUE TITLE
OpenSSL 3.0.0 RNG fork-safety regression? [security?]

### ISSUE THREAD

**Issue by nmathewson** [openssl/openssl#12377]
Earlier versions of OpenSSL would take some pains to ensure that calling fork() was was safe in the presence of an RNG.  This appears to be gone with the OpenSSL 3.0.0 code.

Specifically: when I write a program that calls RAND_bytes() in the main process, then forks several times, and each child process calls RAND_bytes(), I get the same result from RAND_bytes() in every one of the child processes.  This is still the case when the child processes call RAND_poll(), which suggests to me that something is deeply wrong.

OpenSSL 1.1.1 behaves as expected in this case.

Found by Tor's unit tests. (I don't want to get preachy, but I'd strongly recommend that OpenSSL adds a regression test for this case: this is exactly the kind of a thing we worry about an RNG doing.)

Here is a demo program:
```
#include <openssl/rand.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>

int should_poll = 1;

void
check_rand_status(void)
{
	if (RAND_status() != 1) {
		puts("RAND_status is unhappy!");
	} else {
		// puts("RAND_status says everything is fine...e");
	}
}

void
try_rand(void)
{
	unsigned u;
	check_rand_status();
	if (should_poll)
		RAND_poll();
	check_rand_status();
	int r = RAND_bytes((void*)&u, sizeof(u));
	if (r == 0) {
		printf("Process %d: error!\n", (int)getpid());
	} else {
		printf("Process %d: rng value is %u.\n",
		       (int)getpid(), u);
	}
	check_rand_status();
}

int main(int argc, char **argv)
{
	check_rand_status();
	try_rand();
	check_rand_status();
	for (int i = 0; i < 8; ++i) {
		pid_t child;
		if ((child = fork())) {
			// parent.
		} else {
			try_rand();
			exit(0);
		}
	}
	return 0;
}
```

Here is an example output from openssl-master:
```
Process 680496: rng value is 1796322885.
Process 680497: rng value is 345659543.
Process 680498: rng value is 345659543.
Process 680499: rng value is 345659543.
Process 680500: rng value is 345659543.
Process 680501: rng value is 345659543.
Process 680502: rng value is 345659543.
Process 680503: rng value is 345659543.
Process 680504: rng value is 345659543.
```

Here is an example output from openssl 1.1.1g:
```
Process 680544: rng value is 2039804308.
Process 680545: rng value is 2038236718.
Process 680546: rng value is 1374486369.
Process 680547: rng value is 2441531771.
Process 680548: rng value is 892829712.
Process 680549: rng value is 1349569669.
Process 680550: rng value is 3048351340.
Process 680551: rng value is 2647008208.
Process 680552: rng value is 1731649072.
```

All tests run on Fedora 32.

**Comment by mspncp** [comment]
Looks like a bug, indeed. But I have no clue yet, what the problem is.

> Found by Tor's unit tests. (I don't want to get preachy, but I'd strongly recommend that OpenSSL adds a regression test for this case: this is exactly the kind of a thing we worry about an RNG doing.)

Incidentally, we do have a test which checks the reseed-after-fork. And it succeeds on master.

https://github.com/openssl/openssl/blob/8c330e1939d6b7db93a963116354ef80ca0babb3/test/drbgtest.c#L727-L751

**Comment by mspncp** [comment]
@nmathewson thanks for your reproducer. A `git bisect` identified commit 28bdbe1aaa474ae8cd83e520d02e463e46ce89d9 as the one which introduced the issue.

cc @p-steuer

**Comment by mspncp** [comment]
I simplified the reproducer a little bit

```C
#include <openssl/rand.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>

void
try_rand(void)
{
	unsigned u;
	int r = RAND_bytes((void*)&u, sizeof(u));
	if (r == 0) {
		printf("Process %d: error!\n", (int)getpid());
	} else {
		printf("Process %d: rng value is %u.\n",
			   (int)getpid(), u);
	}
}

int main(int argc, char **argv)
{
	pid_t child;

	try_rand();
	fork();
	try_rand();

	return 0;
}
```
There is only one fork, and after it both the parent and the child produce identical output:

```
Process 455: rng value is 4135033203.
Process 455: rng value is 56762851.
Process 456: rng value is 56762851.
```

**Comment by mattcaswell** [comment]
Why didn't our test pick this up?

**Comment by mspncp** [comment]
Because the test only checks whether a reseeding occurs. And indeed, I just verified that the child reseeds with fresh entropy. But somehow the entropy does not enter the internal state of the ctr-drbg. Maybe because of some cached internal state? I think we'll might need help from @p-steuer to analyze this.

Here's how you can check in gdb that the child breaks at rand_pool_acquire_entropy and drbg_ctr_reseed:

```
start
set pagination off
set follow-fork-mode child

b rand_pool_acquire_entropy
b drbg_ctr_reseed
b fork

commands 2 3 4
bt
c
end
```

**Comment by mspncp** [comment]
```
msp@msppc:~/openssl/issues/12377-rng-fork-safety$ gdb --args check-fork-safety
GNU gdb (Gentoo 9.1 vanilla) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from check-fork-safety...
(gdb) start
Temporary breakpoint 1 at 0x1209: file check-fork-safety.c, line 24.
Starting program: /home/msp/openssl/issues/12377-rng-fork-safety/check-fork-safety 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:24
24		try_rand();
(gdb) set pagination off
(gdb) set follow-fork-mode child
(gdb) b rand_pool_acquire_entropy
Breakpoint 2 at 0x7ffff7ddbf7d: file crypto/rand/rand_unix.c, line 616.
(gdb) b drbg_ctr_reseed
Breakpoint 3 at 0x7ffff7dd5b8e: file crypto/rand/drbg_ctr.c, line 298.
(gdb) b fork
Breakpoint 4 at 0x7ffff7a6b010: file ../sysdeps/nptl/fork.c, line 56.
(gdb) commands 2 3 4
Type commands for breakpoint(s) 2 3 4, one per line.
End with a line saying just "end".
>bt
>c
>end
(gdb) c
Continuing.

Breakpoint 2, rand_pool_acquire_entropy (pool=0x555555569ae0) at crypto/rand/rand_unix.c:616
616	        int attempts = 3;
#0  rand_pool_acquire_entropy (pool=0x555555569ae0) at crypto/rand/rand_unix.c:616
#1  0x00007ffff7dda484 in rand_drbg_get_entropy (drbg=0x5555555681f0, pout=0x7fffffffd568, entropy=256, min_len=32, max_len=2147483647, prediction_resistance=0) at crypto/rand/rand_lib.c:184
#2  0x00007ffff7dd8575 in RAND_DRBG_instantiate (drbg=0x5555555681f0, pers=0x7ffff7efed30 <ossl_pers_string> "OpenSSL NIST SP 800-90A DRBG", perslen=28) at crypto/rand/drbg_lib.c:626
#3  0x00007ffff7dd9833 in drbg_setup (ctx=0x7ffff7fca9e0 <default_context_int>, parent=0x0, drbg_type=0) at crypto/rand/drbg_lib.c:1194
#4  0x00007ffff7dd7782 in drbg_ossl_ctx_new (libctx=0x7ffff7fca9e0 <default_context_int>) at crypto/rand/drbg_lib.c:178
#5  0x00007ffff7d9129c in openssl_ctx_generic_new (parent_ign=0x0, ptr_ign=0x0, ad=0x7ffff7fca9e8 <default_context_int+8>, index=2, argl_ign=0, argp=0x7ffff7f9fcc0 <drbg_ossl_ctx_method>) at crypto/context.c:172
#6  0x00007ffff7d9406a in CRYPTO_alloc_ex_data (class_index=16, obj=0x0, ad=0x7ffff7fca9e8 <default_context_int+8>, idx=2) at crypto/ex_data.c:422
#7  0x00007ffff7d9157b in openssl_ctx_get_data (ctx=0x7ffff7fca9e0 <default_context_int>, index=5, meth=0x7ffff7f9fcc0 <drbg_ossl_ctx_method>) at crypto/context.c:248
#8  0x00007ffff7dd7924 in drbg_get_global (libctx=0x0) at crypto/rand/drbg_lib.c:254
#9  0x00007ffff7dd9c00 in OPENSSL_CTX_get0_public_drbg (ctx=0x0) at crypto/rand/drbg_lib.c:1390
#10 0x00007ffff7ddb807 in RAND_bytes_ex (ctx=0x0, buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:890
#11 0x00007ffff7ddb857 in RAND_bytes (buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:899
#12 0x000055555555519e in try_rand () at check-fork-safety.c:11
#13 0x000055555555520e in main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:24
Process 4886: rng value is 1860451527.

Breakpoint 4, __libc_fork () at ../sysdeps/nptl/fork.c:56
56	../sysdeps/nptl/fork.c: No such file or directory.
#0  __libc_fork () at ../sysdeps/nptl/fork.c:56
#1  0x0000555555555213 in main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:25
[Attaching after Thread 0x7ffff797cb80 (LWP 4886) fork to child process 4890]
[New inferior 2 (process 4890)]
[Detaching after fork from parent process 4886]
[Inferior 1 (process 4886) detached]
Process 4886: rng value is 2581031847.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Switching to Thread 0x7ffff797cb80 (LWP 4890)]

Thread 2.1 "check-fork-safe" hit Breakpoint 2, rand_pool_acquire_entropy (pool=0x55555556b370) at crypto/rand/rand_unix.c:616
616	        int attempts = 3;
#0  rand_pool_acquire_entropy (pool=0x55555556b370) at crypto/rand/rand_unix.c:616
#1  0x00007ffff7dda484 in rand_drbg_get_entropy (drbg=0x5555555681f0, pout=0x7fffffffd518, entropy=256, min_len=32, max_len=2147483647, prediction_resistance=0) at crypto/rand/rand_lib.c:184
#2  0x00007ffff7dd8aeb in RAND_DRBG_reseed (drbg=0x5555555681f0, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8, prediction_resistance=0) at crypto/rand/drbg_lib.c:737
#3  0x00007ffff7dd91f2 in RAND_DRBG_generate (drbg=0x5555555681f0, out=0x55555556b240 "", outlen=32, prediction_resistance=0, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8) at crypto/rand/drbg_lib.c:930
#4  0x00007ffff7dda403 in rand_drbg_get_entropy (drbg=0x5555555ed3d0, pout=0x7fffffffd678, entropy=256, min_len=32, max_len=2147483647, prediction_resistance=0) at crypto/rand/rand_lib.c:169
#5  0x00007ffff7dd8aeb in RAND_DRBG_reseed (drbg=0x5555555ed3d0, adin=0x55555564f730 "\032\023", adinlen=24, prediction_resistance=0) at crypto/rand/drbg_lib.c:737
#6  0x00007ffff7dd91f2 in RAND_DRBG_generate (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4, prediction_resistance=0, adin=0x55555564f730 "\032\023", adinlen=24) at crypto/rand/drbg_lib.c:930
#7  0x00007ffff7dd93da in RAND_DRBG_bytes (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4) at crypto/rand/drbg_lib.c:979
#8  0x00007ffff7ddb82b in RAND_bytes_ex (ctx=0x0, buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:892
#9  0x00007ffff7ddb857 in RAND_bytes (buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:899
#10 0x000055555555519e in try_rand () at check-fork-safety.c:11
#11 0x0000555555555218 in main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:26

Thread 2.1 "check-fork-safe" hit Breakpoint 3, drbg_ctr_reseed (drbg=0x5555555681f0, entropy=0x5555555edb10 ">S\376\v<\216j\a2\035F\373\a\253i\206\022\207H\321D\361\233$", entropylen=32, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8) at crypto/rand/drbg_ctr.c:298
298	    RAND_DRBG_CTR *ctr = &drbg->data.ctr;
#0  drbg_ctr_reseed (drbg=0x5555555681f0, entropy=0x5555555edb10 ">S\376\v<\216j\a2\035F\373\a\253i\206\022\207H\321D\361\233$", entropylen=32, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8) at crypto/rand/drbg_ctr.c:298
#1  0x00007ffff7dd8b72 in RAND_DRBG_reseed (drbg=0x5555555681f0, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8, prediction_resistance=0) at crypto/rand/drbg_lib.c:747
#2  0x00007ffff7dd91f2 in RAND_DRBG_generate (drbg=0x5555555681f0, out=0x55555556b240 "", outlen=32, prediction_resistance=0, adin=0x7fffffffd5e8 "\320\323^UUU", adinlen=8) at crypto/rand/drbg_lib.c:930
#3  0x00007ffff7dda403 in rand_drbg_get_entropy (drbg=0x5555555ed3d0, pout=0x7fffffffd678, entropy=256, min_len=32, max_len=2147483647, prediction_resistance=0) at crypto/rand/rand_lib.c:169
#4  0x00007ffff7dd8aeb in RAND_DRBG_reseed (drbg=0x5555555ed3d0, adin=0x55555564f730 "\032\023", adinlen=24, prediction_resistance=0) at crypto/rand/drbg_lib.c:737
#5  0x00007ffff7dd91f2 in RAND_DRBG_generate (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4, prediction_resistance=0, adin=0x55555564f730 "\032\023", adinlen=24) at crypto/rand/drbg_lib.c:930
#6  0x00007ffff7dd93da in RAND_DRBG_bytes (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4) at crypto/rand/drbg_lib.c:979
#7  0x00007ffff7ddb82b in RAND_bytes_ex (ctx=0x0, buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:892
#8  0x00007ffff7ddb857 in RAND_bytes (buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:899
#9  0x000055555555519e in try_rand () at check-fork-safety.c:11
#10 0x0000555555555218 in main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:26

Thread 2.1 "check-fork-safe" hit Breakpoint 3, drbg_ctr_reseed (drbg=0x5555555ed3d0, entropy=0x55555556b240 "O\313Z\255\352\226Di\017$\002\337a\"\303\350~\330\375\335\061\063\022\350\211\374\270,?m\310", <incomplete sequence \340>, entropylen=32, adin=0x55555564f730 "\032\023", adinlen=24) at crypto/rand/drbg_ctr.c:298
298	    RAND_DRBG_CTR *ctr = &drbg->data.ctr;
#0  drbg_ctr_reseed (drbg=0x5555555ed3d0, entropy=0x55555556b240 "O\313Z\255\352\226Di\017$\002\337a\"\303\350~\330\375\335\061\063\022\350\211\374\270,?m\310", <incomplete sequence \340>, entropylen=32, adin=0x55555564f730 "\032\023", adinlen=24) at crypto/rand/drbg_ctr.c:298
#1  0x00007ffff7dd8b72 in RAND_DRBG_reseed (drbg=0x5555555ed3d0, adin=0x55555564f730 "\032\023", adinlen=24, prediction_resistance=0) at crypto/rand/drbg_lib.c:747
#2  0x00007ffff7dd91f2 in RAND_DRBG_generate (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4, prediction_resistance=0, adin=0x55555564f730 "\032\023", adinlen=24) at crypto/rand/drbg_lib.c:930
#3  0x00007ffff7dd93da in RAND_DRBG_bytes (drbg=0x5555555ed3d0, out=0x7fffffffd7e0 "", outlen=4) at crypto/rand/drbg_lib.c:979
#4  0x00007ffff7ddb82b in RAND_bytes_ex (ctx=0x0, buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:892
#5  0x00007ffff7ddb857 in RAND_bytes (buf=0x7fffffffd7e0 "", num=4) at crypto/rand/rand_lib.c:899
#6  0x000055555555519e in try_rand () at check-fork-safety.c:11
#7  0x0000555555555218 in main (argc=1, argv=0x7fffffffd908) at check-fork-safety.c:26
Process 4890: rng value is 2581031847.
[Inferior 2 (process 4890) exited normally]
(gdb) 
```

**Comment by mspncp** [comment]
I had a look at the patch (28bdbe1aaa474ae8cd83e520d02e463e46ce89d9) and went through the code in the debugger, but I wasn't able to find the problem (yet).

**Comment by mspncp** [comment]
>> Why didn't our test pick this up?

> Because the test only checks whether a reseeding occurs.

And yes, the test needs to be improved to also verify that  the outcome is different.

**Comment by mspncp** [comment]
> Found by Tor's unit tests. (I don't want to get preachy, but I'd strongly recommend that OpenSSL adds a regression test for this case: this is exactly the kind of a thing we worry about an RNG doing.)

@nmathewson we surely will!

**Comment by nmathewson** [comment]
> > Found by Tor's unit tests. (I don't want to get preachy, but I'd strongly recommend that OpenSSL adds a regression test for this case: this is exactly the kind of a thing we worry about an RNG doing.)
> 
> @nmathewson we surely will!

Great -- that will also help make sure that the issue isn't present in any other drbgs :)

**Comment by p-steuer** [comment]
Thanks for reporting. Im looking into it.

**Comment by mspncp** [comment]
> Found by Tor's unit tests.

@nmathewson just for curiousity: could you point me to the exact location this test that was failing? I had a quick look on GitHub and didn't find it right away.

**Comment by nmathewson** [comment]
> > Found by Tor's unit tests.
> 
> @nmathewson just for curiousity: could you point me to the exact location of this test that was failing? I had a quick look on GitHub and didn't find it right away.

We aren't running with openssl 3.0.0 on github -- it's too unstable IMO.  I found this bug as part of an effort to get our code building and tests passing with openssl 3.0.0.

The funny thing about this issue is that no single test found it -- we have a test driver that forks to run different unit tests in separate processes, and we were hitting an error case when multiple tests generated the same "random" filename to use for temporary data.

**Comment by p-steuer** [comment]
Ive been debugging this one the whole day. Heres what i got:

The fork is correctly detected and the child DRBGs are reseeded.

Also, the problem seems unrelated to the optimizations done in my commit : I can go back to old counter increment and roll back the AES-ECB vs blockwise AES optimizations and the problem persists.

It looks like it is caused by identical AES-CTR contexts being used in both child and parent's generate operation.

The following diff solved the problem :
```
diff --git a/providers/implementations/rands/drbg_ctr.c b/providers/implementations/rands/drbg_ctr.c
index 48fb7ebd3d..97de408060 100644
--- a/providers/implementations/rands/drbg_ctr.c
+++ b/providers/implementations/rands/drbg_ctr.c
@@ -405,6 +405,10 @@ static int drbg_ctr_generate(PROV_DRBG *drbg,
 
     memset(out, 0, outlen);
 
+    if (!EVP_CipherInit_ex(ctr->ctx_ctr, ctr->cipher_ctr,
+                           NULL, ctr->K, NULL, -1))
+        return 0;
+
     do {
         if (!EVP_CipherInit_ex(ctr->ctx_ctr,
                                NULL, NULL, NULL, ctr->V, -1))

```
(The diff is from master but it should apply to the drbg_ctr.c file also before the move to providers/...)

However, i still did not figure out, why the EVP interface requires to re-initialize the context after the fork. My first guess was that AES-ECB and AES-CTR context's keys are out of sync, but just updating the key here is not sufficient :
```
+    if (!EVP_CipherInit_ex(ctr->ctx_ctr, NULL, NULL, ctr->K, NULL, -1)) // still fails
```

**Comment by p-steuer** [comment]
PR is up: https://github.com/openssl/openssl/pull/12385

Labeled WIP because id like to understand first what is going on.

**Comment by mspncp** [comment]
> Also, the problem seems unrelated to the optimizations done in my commit : I can go back to old counter increment and roll back the AES-ECB vs blockwise AES optimizations and the problem persists.

What do you mean with "go back to old counter increment"? Did you revert 28bdbe1aaa entirely or just parts of it? I'm asking, because during bisection, commit 4b5371913e (the predecessor of yours) was tested as 'good':

```
4d6d787c49 AES CTR-DRGB: add test for 32-bit counter overflow
28bdbe1aaa (refs/bisect/bad) AES CTR-DRGB: performance improvement
4b5371913e (refs/bisect/good-4b5371913ed9bb4bfd8a55a30458932799296ab9) DOCS: Use "command" not "tool" or "utility"
```

**Comment by p-steuer** [comment]
> Did you revert 28bdbe1 entirely or just parts of it? I'm asking because during bisection, commit 4b53719 (the predecessor of yours) was tested as 'good'

No, the bisect is right: it is definitely caused by my drbg optimization commit. I only reverted the change replacing the blockwise AES loop by an AES-CTR operation in the generate function (while keeping all other changes, including the counter increment change). And this turned out to solve the problem. That gave me headaches , since loop(AES(ctr),ctr++) should be equivalent to AES-CTR(0) from a theoretical point of view.  Regarding implementation aspects, the main difference is that the latter needs an extra AES-CTR context. And that somehow seems to cause the problem with fork.

**Comment by p-steuer** [comment]
I could not reproduce it with the 1.1.1 branch which has a backport of 28bdbe1 (which is 53eb05bdf00d7237e3b12976c2ac38d68206eb13).

That leads me to the conclusion that there has to be something wrong with cipher 3.0 contexts' fork safety in general, and my commit just exposes that.

So while PR #12385 fixes this particular drbg problem, i think it would just hide the general problem again.

**Comment by mspncp** [comment]
> That leads me to the conclusion that there has to be something wrong with 3.0 cipher contexts' fork safety in general, and my commit just exposes that.

Thanks for the analysis @p-steuer. Looks like one of the New Core specialists (@paulidale @levitte @mattcaswell ?) needs to take a deeper look.

**Comment by p-steuer** [comment]
I moved my commit backwards on master and put it right in front of the 1.1.1 label. Then i did a bisect ...
```
21038fa52b386fa0b3884567c68dd62e47eae903 is the first bad commit
commit 21038fa52b386fa0b3884567c68dd62e47eae903
Author: Matt Caswell <matt@openssl.org>
Date:   Mon Apr 8 17:19:59 2019 +0100

    Implement AES CTR ciphers in the default provider
    
    Reviewed-by: Paul Dale <paul.dale@oracle.com>
    (Merged from https://github.com/openssl/openssl/pull/8700)

 crypto/evp/evp_enc.c                              |  3 +++
 providers/common/ciphers/aes.c                    | 11 +++++++++++
 providers/common/include/internal/provider_algs.h |  3 +++
 providers/default/defltprov.c                     |  3 +++
 4 files changed, 20 insertions(+)

```

The commit id is obv. wrong due to the rebase on top of my commit.
The real commit id is 819a7ae9fc7721f675757c0925821f91b20dfc8f .

Since the commit does nothing special besides moving AES-CTR to the default provider, it occurs to me that either the default provider or providers in general are not fork safe.

**Comment by mspncp** [comment]
> I moved my commit backwards on master and put it right in front of the 1.1.1 label. Then i did a bisect ...

Cool. I'll remember that trick...

**Comment by mspncp** [comment]
> Since the commit does nothing special besides moving AES-CTR to the default provider, it occurs to me that either the default provider or providers in general are not fork safe.

If @p-steuer's conjecture is correct, then  we might need some help from the core architects of the new 3.0 architecture (@mattcaswell @levitte) to find the root cause of this issue.

**Comment by mattcaswell** [comment]
I've spent quite a bit of time on this. I think the root cause of this issue is #12405. We are re-initialising the underlying DRBG with a new key and IV, but the re-initialisation is not taking effect.

**Comment by p-steuer** [comment]
So i finally figured this one out ...

I simplified @mspncp  's minimal example in the following way:
```
#include <openssl/rand.h>
#include <openssl/crypto.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>

void try_rand(size_t buflen)
{
        unsigned char buf[16];
        int r = RAND_bytes(buf, buflen);

        if (r == 0) {
                printf("Process %d: error!\n", (int)getpid());
        } else {
                printf("Process %d: rng value is %s.\n",
                (int)getpid(), OPENSSL_buf2hexstr(buf, buflen));
        }
}

int main(int argc, char **argv)
{
        pid_t child;

        try_rand(16 - atoi(argv[1]));
        fork();
        try_rand(16);
        return 0;
}
```

I observed that for inputs n in {0, ..., 15}, the first n bytes would be equal e.g. :
```past@past-VirtualBox:~/Projects/test/openssl/fork$ ./test 0
Process 101702: rng value is 38:A8:E8:03:F0:9C:11:D6:B9:40:42:46:42:29:10:2B.
Process 101702: rng value is C6:21:E1:7C:1A:97:02:58:EA:30:96:F3:00:67:28:59.
Process 101703: rng value is 22:34:FE:B6:BA:2D:7A:F5:48:97:AE:63:63:73:D1:A2.
past@past-VirtualBox:~/Projects/test/openssl/fork$ ./test 1
Process 101704: rng value is 73:CE:D3:30:15:A0:E0:EE:42:C2:94:EA:2D:A1:89.
Process 101704: rng value is 5B:60:F2:2E:E8:E8:4E:39:CB:68:01:F7:66:BA:F7:D5.
Process 101705: rng value is 5B:F1:D4:A2:DE:32:74:6D:06:B6:A3:46:C4:BB:11:DA.
past@past-VirtualBox:~/Projects/test/openssl/fork$ ./test 8
Process 101706: rng value is FB:39:9D:F0:37:77:50:44.
Process 101706: rng value is 86:A8:00:B7:92:A2:7F:2A:E3:7E:E3:DD:EB:CB:FB:8C.
Process 101707: rng value is 86:A8:00:B7:92:A2:7F:2A:FC:E7:43:93:A4:6B:81:A4.
past@past-VirtualBox:~/Projects/test/openssl/fork$ ./test 15
Process 101708: rng value is 21.
Process 101708: rng value is A2:BE:B3:BE:90:7C:BE:EF:CB:D6:1B:F8:D8:7B:FB:E5.
Process 101709: rng value is A2:BE:B3:BE:90:7C:BE:EF:CB:D6:1B:F8:D8:7B:FB:3A.
past@past-VirtualBox:~/Projects/test/openssl/fork$ ./test 16
Process 101710: rng value is .
Process 101710: rng value is 37:78:0E:9D:C8:D6:60:CD:66:4A:18:A9:E0:6D:B7:DD.
Process 101711: rng value is F1:19:8A:50:00:54:55:E3:42:BD:2A:40:AB:89:9E:AD.
```

I concluded that the provider code does not discard the discard the leftover AES-CTR keystream bytes when EVP_CipherInit_ex is used to reset the key or iv: So if there is a number of random bytes generated before the fork, that is not a multiple of 16 (AES block size), the leftover keystream bytes will be stored in the context. So the random byte generation in both parent and child will first consume those leftovers before producing random bytes based on the (correctly reseeded) internal state of the drbg's.

This explanation in line with my previous observations : Providing a non-null cipher argument to EVP_CipherInit_ex would hide the problem, because the whole context is reallocated and reset in this case.

Also a first experimental fix solves the problem:
```
past@past-VirtualBox:~/Projects/test/openssl$ git diff
diff --git a/providers/implementations/ciphers/ciphercommon.c b/providers/implementations/ciphers/ciphercommon.c
index a8905d1242..4b7495de50 100644
--- a/providers/implementations/ciphers/ciphercommon.c
+++ b/providers/implementations/ciphers/ciphercommon.c
@@ -151,6 +151,16 @@ static int cipher_generic_init_internal(PROV_CIPHER_CTX *ctx,
 {
     ctx->enc = enc ? 1 : 0;
 
+    if (key != NULL || iv != NULL) {
+        switch (ctx->mode) {
+        case EVP_CIPH_CTR_MODE:
+            ctx->num = 0;
+            break;
+        default:
+            break;
+        }
+    }
+
     if (iv != NULL && ctx->mode != EVP_CIPH_ECB_MODE) {
         if (!cipher_generic_initiv(ctx, iv, ivlen))
             return 0;

```

**Comment by mattcaswell** [comment]
> I concluded that the provider code does not discard the discard the leftover AES-CTR keystream bytes 

Ha! Yeah, looks like we were both looking at this. I had the same theory - but you've taken it one step further. I expect your fix will also solve #12405.

**Comment by mattcaswell** [comment]
I wonder if there are other modes beyond CTR which might suffer from a similar problem?

**Comment by richsalz** [comment]
Perhaps #12406 is a good way to address this, making it possible for providers to do the right thing themselves.

**Comment by p-steuer** [comment]
Possibly at least the stream cipher modes. Probably the following lines from the legacy code didnt makee it to providers:
```
    if (!(EVP_CIPHER_flags(EVP_CIPHER_CTX_cipher(ctx)) & EVP_CIPH_CUSTOM_IV)) {                      
        switch (EVP_CIPHER_CTX_mode(ctx)) {                                                          
                                                                                                     
        case EVP_CIPH_STREAM_CIPHER:                                                                 
        case EVP_CIPH_ECB_MODE:                                                                      
            break;                                                                                   
                                                                                                     
        case EVP_CIPH_CFB_MODE:                                                                      
        case EVP_CIPH_OFB_MODE:                                                                      
                                                                                                     
            ctx->num = 0;   // <------------------------------                                                                         
            /* fall-through */                                                                       
                                                                                                     
        case EVP_CIPH_CBC_MODE:                                                                      
                                                                                                     
            OPENSSL_assert(EVP_CIPHER_CTX_iv_length(ctx) <=                                          
                           (int)sizeof(ctx->iv));                                                    
            if (iv)                                                                                  
                memcpy(ctx->oiv, iv, EVP_CIPHER_CTX_iv_length(ctx));                                 
            memcpy(ctx->iv, ctx->oiv, EVP_CIPHER_CTX_iv_length(ctx));                                
            break;                                                                                   
                                                                                                     
        case EVP_CIPH_CTR_MODE:                                                                      
            ctx->num = 0;          // <----------------------------------------                                                                  
            /* Don't reuse IV for CTR mode */                                                        
            if (iv)                                                                                  
                memcpy(ctx->iv, iv, EVP_CIPHER_CTX_iv_length(ctx));                                  
            break;                                                                                   
                                                                                                     
        default:                                                                                     
            return 0;                                                                                
        }                                                                                            
    }
```

**Comment by p-steuer** [comment]
Adding different patterns of key/iv (re-)initialization the KATs would have caught the regression.

**Comment by mattcaswell** [comment]
Possibly there are other fields that should be reset besides `num`?

*Probably* we can just reset `num` regardless of the mode?

**Comment by p-steuer** [comment]
The comment in the legacy context said its used for cfb/ofb/ctr modes and thats exactly when the legacy code reset it, see the above switch.

    int num;                    /* used by cfb/ofb/ctr mode */

The new code puts it a bit more general:

    /*
     * num contains the number of bytes of |iv| which are valid for modes that
     * manage partial blocks themselves.
     */
    unsigned int num;

Anyway, id say it must be zeroised for all modes that use it while it doesnt matter for the other modes.
Of course the above comment could also be understood in the sense that it is used for something different than stroing key stream leftovers of stream cipher modes e.g., plaintext leftovers for blockcipher modes (but it think buf and bufsz are used in that case).

**Comment by mspncp** [comment]
Cool.  I'm just about to finish my improved reseed after fork test, which is able to detect the current issue. So we can put the pieces together.

My test not only verifies that all DRBGs are reseeded, bu talso sends the output of the private and public DRBG to the parent for comparison. Currently the test uses a fixed buffer size for the random output (sizeof(unsigned int)), but it looks like I should enhance it to test variable length output as well.

**Comment by mspncp** [comment]
See #12407

**Comment by mspncp** [comment]
Thank you again @nmathewson for reporting this important security issue. It would have deserved a CVE if it had slipped into the final release.
