### ISSUE TITLE
Add hardware randomizer capability on NonStop x86 architecture

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#12903]
The default implementation of randomization functions do not include the hardware randomizer available on HPE NonStop x86. This is needed because the operating system does not support `/dev/random` or `/dev/urandom` and EGD is not allowed by FIPS.

This applies to version 3.0.0. I am volunteering to implement this capability.

Note: This capability is not available for the NonStop Itanium port.

**Comment by rsbeckerca** [comment]
There are two possible calls available to do this in the operating system:

```
int _rdrand64(uint64* val);
```
and
```
int _rdrand16(unsigned short* val)
```
There is also a real time clock available but it is unlikely to be particularly random in any CPU-bound process.

With this, I am looking at the best place to insert the code. Thinking `rand_unix.c` as a variant of `OPENSSL_RAND_SEED_OS` but not using `DEVRANDOM`.

**Comment by paulidale** [comment]
The code already supports the RDRAND and RDSEED instructions on x86 look in `providers/implementations/rands/seeding`.

BTW, it ought to be possible to justify EGD as an entropy source as part of a FIPS validation.

**Comment by rsbeckerca** [comment]
> 
> 
> The code already supports the RDRAND and RDSEED instructions on x86 look in `providers/implementations/rands/seeding`.
> 
> BTW, it ought to be possible to justify EGD as an entropy source as part of a FIPS validation.

I'm really unsure how to plug those calls into the existing structure in `rand_cpu_x86.c`. The `_rdrand64` is not that standard in C or POSIX.

**Comment by rsbeckerca** [comment]
This is what I came up with as far as a patch for adding support in this platform. It may be the wrong place, but it's something. I can put this into a pull request at this point. Comments would be appreciated:

```
diff --git a/providers/implementations/rands/seeding/rand_cpu_x86.c b/providers/implementations/rands/seeding/rand_cpu_x86.c
index fd47de9ad0..9097d1d8e7 100644
--- a/providers/implementations/rands/seeding/rand_cpu_x86.c
+++ b/providers/implementations/rands/seeding/rand_cpu_x86.c
@@ -13,8 +13,13 @@
 #include "prov/seeding.h"

 #ifdef OPENSSL_RAND_SEED_RDCPU
+# if defined(OPENSSL_SYSNAME_TANDEM) && defined(_TNS_X_TARGET)
+#  include <builtin.h> /* _rdrand64 */
+#  include <string.h> /* memcpy */
+# else
 size_t OPENSSL_ia32_rdseed_bytes(unsigned char *buf, size_t len);
 size_t OPENSSL_ia32_rdrand_bytes(unsigned char *buf, size_t len);
+#endif

 /*
  * Acquire entropy using Intel-specific cpu instructions
@@ -35,9 +40,36 @@ size_t prov_acquire_entropy_from_cpu(RAND_POOL *pool)

     bytes_needed = rand_pool_bytes_needed(pool, 1 /*entropy_factor*/);
     if (bytes_needed > 0) {
+
         buffer = rand_pool_add_begin(pool, bytes_needed);

         if (buffer != NULL) {
+#if defined(OPENSSL_SYSNAME_TANDEM) && defined(_TNS_X_TARGET)
+            size_t bytes_remaining = bytes_needed;
+            while (bytes_remaining > 0) {
+                /* Always use 64 bit fetch, then use the lower bytes as needed. */
+                /* The platform is big-endian. */
+                unsigned long long random_value = 0;
+                if (_rdrand64(&random_value) != 0) {
+                    unsigned char *random_buffer = (unsigned char *)&random_value;
+                    if (bytes_remaining > sizeof(random_value)) {
+                        memcpy(buffer, random_buffer, sizeof(random_value));
+                        bytes_remaining -= sizeof(random_value);
+                    } else {
+                        memcpy(buffer,
+                            random_buffer + (sizeof(random_value) - bytes_remaining),
+                            bytes_remaining);
+                        bytes_remaining = 0;
+                    }
+                } else
+                    break;
+            }
+            if (bytes_remaining == 0) {
+                rand_pool_add_end(pool, bytes_needed, 8 * bytes_needed);
+            } else {
+                rand_pool_add_end(pool, 0, 0);
+            }
+#else
             /* Whichever comes first, use RDSEED, RDRAND or nothing */
             if ((OPENSSL_ia32cap_P[2] & (1 << 18)) != 0) {
                 if (OPENSSL_ia32_rdseed_bytes(buffer, bytes_needed)
@@ -52,6 +84,7 @@ size_t prov_acquire_entropy_from_cpu(RAND_POOL *pool)
             } else {
                 rand_pool_add_end(pool, 0, 0);
             }
+#endif
         }
     }
```

**Comment by rsbeckerca** [comment]
`generate_config_and_load()` returned `NULL` and set `ret=1` and `verify=0`. The actual problem is that the module does not appear to load at line 231: `ret = module_init(md, name, value, cnf);` where `ret=-1`.
```
#0  module_run (cnf=<value optimized out>, name=<value optimized out>,
    value=<value optimized out>, flags=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:237
#1  0x7fb711ca in CONF_modules_load (cnf=0x80946c0,
    appname=<value optimized out>, flags=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/conf/conf_mod.c:136
#2  0x70045b30 in generate_config_and_load (prov_name=0x8050076 "fips",
    section=0x8050098 "fips_sect", module_mac=0x6ffffd60 "\221SGg]ZMPWe",
    module_mac_len=32, conditional_errors=1, security_checks=1)
```
Down in `module_init()`, the code `ret = pmod->init(imod, cnf);` returns 0. The code executes `provider_conf_init`. Eventually, I'm in `ossl_provider_find`, which returns `NULL` at line 233. Drilling down:

```
#0  internal_find (st=0x8066a80, data=0x6ffff940, ret_val_options=2)
    at /home/ituglib/randall/openssl-3.0/crypto/stack/stack.c:292
#1  0x7fccba7a in OPENSSL_sk_find (st=<value optimized out>,
    data=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/stack/stack.c:317
#2  0x7fc4b820 in ossl_provider_find (libctx=<value optimized out>,
    name=<value optimized out>, noconfig=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/provider_core.c:230
#3  0x7fc4a8c2 in provider_conf_load (libctx=<value optimized out>,
    name=<value optimized out>, value=<value optimized out>,
    cnf=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/provider_conf.c:118
```
And ossl_bsearch returns null, so it's not finding something here:
```
#0  0x7fc3bfb0 in ossl_bsearch (key=<value optimized out>, base=0x8066b00,
    num=<value optimized out>, size=4, cmp=<value optimized out>,
    flags=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/bsearch.c:43
#1  0x7fccb969 in internal_find (st=0x8066a80, data=0x6ffff940,
    ret_val_options=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/stack/stack.c:309
#2  0x7fccba7a in OPENSSL_sk_find (st=<value optimized out>,
    data=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/stack/stack.c:317
#3  0x7fc4b820 in ossl_provider_find (libctx=<value optimized out>,
    name=<value optimized out>, noconfig=<value optimized out>)
    at /home/ituglib/randall/openssl-3.0/crypto/provider_core.c:230
```
That's all I have.
