### ISSUE TITLE
test: LeakSanitizer reports memory leaks in test_rand on master

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#13016]
https://travis-ci.com/github/openssl/openssl/jobs/391552471

```
=================================================================
==5702==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 1 - iteration 5
# ------------------------------------------------------------------------------
=================================================================
==5704==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 2 - iteration 10
# ------------------------------------------------------------------------------
=================================================================
==5706==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 3 - iteration 15
# ------------------------------------------------------------------------------
=================================================================
==5708==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 4 - iteration 4
# ------------------------------------------------------------------------------
=================================================================
==5711==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 5 - iteration 9
# ------------------------------------------------------------------------------
=================================================================
==5713==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 6 - iteration 14
# ------------------------------------------------------------------------------
=================================================================
==5715==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 7 - iteration 3
# ------------------------------------------------------------------------------
=================================================================
==5717==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 8 - iteration 8
# ------------------------------------------------------------------------------
=================================================================
==5719==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 9 - iteration 13
# ------------------------------------------------------------------------------
=================================================================
==5726==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 10 - iteration 2
# ------------------------------------------------------------------------------
=================================================================
==5728==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 11 - iteration 7
# ------------------------------------------------------------------------------
=================================================================
==5732==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 12 - iteration 12
# ------------------------------------------------------------------------------
=================================================================
==5734==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 13 - iteration 1
# ------------------------------------------------------------------------------
=================================================================
==5745==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 14 - iteration 6
# ------------------------------------------------------------------------------
=================================================================
==5751==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 15 - iteration 11
# ------------------------------------------------------------------------------
=================================================================
==5753==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
        # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:348
        # [256] compared to [0]
        # ERROR: (bool) 'test_drbg_reseed_in_child(primary, public, private, presult) == true' failed @ test/drbgtest.c:421
        # false
        # ERROR: (bool) 'test_rand_reseed_on_fork(primary, public, private) == true' failed @ test/drbgtest.c:526
        # false
        not ok 16 - iteration 16
# ------------------------------------------------------------------------------
    not ok 3 - test_rand_fork_safety
# ------------------------------------------------------------------------------
=================================================================
==5633==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f8989485b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x556f58b88301 in CRYPTO_malloc crypto/mem.c:184
    #2 0x556f58b8832c in CRYPTO_zalloc crypto/mem.c:191
    #3 0x556f58b9e9af in CRYPTO_THREAD_lock_new crypto/threads_pthread.c:33
    #4 0x556f590c5d64 in drbg_enable_locking providers/implementations/rands/drbg.c:793
    #5 0x556f58b5f785 in EVP_RAND_enable_locking crypto/evp/evp_rand.c:95
    #6 0x556f58b613be in EVP_RAND_CTX_new crypto/evp/evp_rand.c:336
    #7 0x556f58baacd1 in rand_new_drbg crypto/rand/rand_lib.c:471
    #8 0x556f58baba40 in RAND_get0_public crypto/rand/rand_lib.c:559
    #9 0x556f58b05722 in run_multi_thread_test test/drbgtest.c:697
    #10 0x556f58b05ac8 in test_multi_thread test/drbgtest.c:780
    #11 0x556f58b0902f in run_tests test/testutil/driver.c:321
    #12 0x556f58b0a4ec in main test/testutil/main.c:30
    #13 0x7f8987e93b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
../../util/wrap.pl ../../test/drbgtest => 1
not ok 1
# ------------------------------------------------------------------------------
# Looks like you failed 1 test of 2.05-test_rand.t ..................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by levitte** [comment]
Another that I can't reproduce on my machine, just as with #13017...  that gets me to suspect it's a tool version issue.  All the failures are on Bionic, so that may be a factor for reproducing this.

**Comment by paulidale** [comment]
Is this still happening?  The CIs look to be clean.
