### ISSUE TITLE
[SSL] malloc failure (_ssl.c:2607)

### ISSUE THREAD

**Issue by vitalerter** [openssl/openssl#13078]
Hi,
I use python 3.8.2 , my code running asyncio-mqtt library to connect the mqtt broker.
During the code run I get an error:

`ERROR 2020-10-06 08:59:45,391 client 17392 19700 failed to receive on socket: [SSL] malloc failure (_ssl.c:2607)`

them broker disconnected and I get other error:
```
ERROR 2020-10-06 08:59:45,835 worker 17392 19104 Log processing error (queue size: 2106490): 
Traceback (most recent call last):
  File "C:\Users\maxim\envs\cloud_device_management_env\lib\site-packages\logstash_async\worker.py", line 145, in _process_event
    self._write_event_to_database()
  File "C:\Users\maxim\envs\cloud_device_management_env\lib\site-packages\logstash_async\worker.py", line 195, in _write_event_to_database
    self._database.add_event(self._event)
  File "C:\Users\maxim\envs\cloud_device_management_env\lib\site-packages\logstash_async\database.py", line 94, in add_event
    connection.execute(query, (event, False))
MemoryError
```
Thanks for help

**Comment by mattcaswell** [comment]
This does not seem to be an OpenSSL error.
