### ISSUE TITLE
Random Crash issue in __memcpy_ssse3_back while BIO_do_connect

### ISSUE THREAD

**Issue by vinothM139** [openssl/openssl#13259]
(gdb)                                                                                                                                                                        #0  0x00007f0f252a0ae2 in __memcpy_ssse3_back () from /lib64/libc.so.6                                                                                                       #1  0x00007f0f2249709f in SHA1_Update () from /lib64/libcrypto.so.10                                                                                                         #2  0x00007f0f22546cc7 in ssleay_rand_add.part.0 () from /lib64/libcrypto.so.10                                                                                              #3  0x00007f0f224f19fd in bnrand () from /lib64/libcrypto.so.10                                                                                                              #4  0x00007f0f224f1650 in bn_rand_range () from /lib64/libcrypto.so.10                                                                                                       #5  0x00007f0f2252f07e in ecdsa_sign_setup () from /lib64/libcrypto.so.10                                                                                                    #6  0x00007f0f2252f4f5 in ecdsa_do_sign () from /lib64/libcrypto.so.10                                                                                                       #7  0x00007f0f2252f8ab in ECDSA_sign_ex () from /lib64/libcrypto.so.10                                                                                                       #8  0x00007f0f2252f919 in ECDSA_sign () from /lib64/libcrypto.so.10                                                                                                          #9  0x00007f0f2250dc60 in pkey_ec_sign () from /lib64/libcrypto.so.10                                                                                                        #10 0x00007f0f225531de in EVP_SignFinal () from /lib64/libcrypto.so.10                                                                                                       #11 0x00007f0f225c114b in fips_pkey_signature_test () from /lib64/libcrypto.so.10                                                                                            #12 0x00007f0f2250b145 in EC_KEY_generate_key () from /lib64/libcrypto.so.10                                                                                                 #13 0x00007f0f26e21aa5 in ssl3_send_client_key_exchange () from /lib64/libssl.so.10                                                                                          #14 0x00007f0f26e25480 in ssl3_connect () from /lib64/libssl.so.10                                                                                                           #15 0x00007f0f26e2ef1e in ssl23_connect () from /lib64/libssl.so.10                                                                                                          #16 0x00007f0f26e52d0c in ssl_ctrl () from /lib64/libssl.so.10                                                                                                               #17 0x00007f0f26140225 in BIO_ctrl () from /usr/cachelogic/lib/libadbe_dme.so
--

**Comment by vinothM139** [comment]
I`m in 

openssl version                                                                                        
  OpenSSL 1.0.2k-fips  26 Jan 2017
--

**Comment by kaduk** [comment]
1.0.2 is EOL.
You might want to confirm with, e.g., valgrind that you do not have any memory-safety issues in your application that might be corrupting things.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input

**Comment by t8m** [comment]
Closing as the issue was labeled as inactive for extended period of time and there was no additional input.
Please add a comment if you have any further information to support reopening the issue.
