### ISSUE TITLE
Try to build openssl dllwrap libeay32.dll and ssleay32.dll cross compile fails

### ISSUE THREAD

**Issue by YvesR** [openssl/openssl#1326]
Hello,
A ruby gem, tiny_tds, use openssl to connect secured sql server with freetds.

At the moment the current version uses 1.0.2g which let the system compile everything.
After compile the build setup creates the libeay32.dll and ssleay32.dll for Windows (I am using Mac OS and do CROSS_COMPILE).
So in my case I made sure everything build correct using 1.0.2g.

As 1.1.0 fixes some errors that causes 100% CPU on Windows servers I want to switch to this version to make tests and when 1.1.0 finally gets releases switch to this version asap.

The current build I use is able to compile openssl in general but fails on dllwrap commans.
It uses `(perl util/mkdef.pl 32 libeay >libeay32.def)` and `(perl util/mkdef.pl 32 ssleay >ssleay32.def)` to build it. As I learned from documentation the new perl scripts wants additional parameters `ssl` and/or `crypto`.

So I tried to add ssl parameter but then run into following error:
<details>
```
cd tmp/x86-mingw32/tiny_tds/2.0.0
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -I. ../../../../ext/tiny_tds/extconf.rb --disable-lookup --enable-cross-build
../../../../ext/tiny_tds/extconf.rb:14: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
checking for sybfront.h... no
Extracting openssl-1.1.0-pre5.tar.gz into tmp/i686-w64-mingw32/ports/openssl/1.1.0-pre5... OK
Running 'configure' for openssl 1.1.0-pre5... OK
Running 'compile' for openssl 1.1.0-pre5... OK
Running 'mkdef-libeay32' for openssl 1.1.0-pre5... OK
Running 'mkdef-ssleay32' for openssl 1.1.0-pre5... OK
Running 'dllwrap-libeay32' for openssl 1.1.0-pre5... ERROR, review '/Users/rausch/Documents/_Projekte/tiny_tds/tmp/x86-mingw32/tiny_tds/2.0.0/tmp/i686-w64-mingw32/ports/openssl/1.1.0-pre5/dllwrap-libeay32.log' to see what happened. Last lines are:
========================================================================
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x63c): undefined reference to `SSL_CTX_has_client_custom_ext'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x640): undefined reference to `SSL_ct_is_enabled'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x644): undefined reference to `SSL_get0_peer_scts'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x648): undefined reference to `SSL_CTX_set_ct_validation_callback'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x64c): undefined reference to `SSL_CTX_ct_is_enabled'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x650): undefined reference to `SSL_set_default_read_buffer_len'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x654): undefined reference to `SSL_CTX_set_default_read_buffer_len'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x658): undefined reference to `SSL_has_pending'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x65c): undefined reference to `SSL_CIPHER_get_auth_nid'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x660): undefined reference to `SSL_CIPHER_get_kx_nid'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x664): undefined reference to `SSL_CIPHER_is_aead'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x668): undefined reference to `SSL_SESSION_up_ref'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x66c): undefined reference to `SSL_CTX_set0_ctlog_store'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x670): undefined reference to `SSL_CTX_get0_ctlog_store'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x674): undefined reference to `SSL_enable_ct'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x678): undefined reference to `SSL_CTX_enable_ct'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x67c): undefined reference to `SSL_CTX_get_ciphers'
libeay32-1.1.0-pre5-i686-w64-mingw32.exp:fake:(.edata+0x680): undefined reference to `SSL_SESSION_get0_hostname'
collect2: error: ld returned 1 exit status
i686-w64-mingw32-dllwrap: i686-w64-mingw32-gcc exited with status 1
========================================================================
/usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete dllwrap-libeay32 task (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `chdir'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
	from ../../../../ext/tiny_tds/extconf.rb:178:in `compile'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
	from ../../../../ext/tiny_tds/extconf.rb:128:in `block in cook_and_activate'
	from ../../../../ext/tiny_tds/extconf.rb:120:in `block in chdir_for_build'
	from ../../../../ext/tiny_tds/extconf.rb:119:in `chdir'
	from ../../../../ext/tiny_tds/extconf.rb:119:in `chdir_for_build'
	from ../../../../ext/tiny_tds/extconf.rb:127:in `cook_and_activate'
	from ../../../../ext/tiny_tds/extconf.rb:319:in `<main>'
rake aborted!
Command failed with status (1): [/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby ...]
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:191:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:188:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => native => native:x86-mingw32 => native:tiny_tds:x86-mingw32 => tmp/x86-mingw32/stage/lib/tiny_tds/2.0/tiny_tds.so => copy:tiny_tds:x86-mingw32:2.0.0 => tmp/x86-mingw32/tiny_tds/2.0.0/tiny_tds.so => tmp/x86-mingw32/tiny_tds/2.0.0/Makefile
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v /Users/rausch/Documents/_Projekte/tiny_tds:/Users/rausch/Documents/_Projekte/tiny_tds -e UID\=1000 -e GID\=1000 -e USER\=rausch -e GROUP\=_staff -e ftp_proxy\= -e http_proxy\= -e https_proxy\= -e RCD_HOST_RUBY_PLATFORM\=x86_64-darwin15 -e RCD_HOST_RUBY_VERSION\=2.3.1 -e RCD_IMAGE\=larskanis/rake-compiler-dock:0.5.1 -w /Users/rausch/Documents/_Projekte/tiny_tds --rm -i -t larskanis/rake-compiler-dock:0.5.1 runas sigfw bash -c \ \ \ \ bundle\ \&\&\ rake\ cross\ native\ gem\ RUBY_CC_VERSION\=2.0.0:2.1.6:2.2.2:2.3.0\ CFLAGS\=\"-Wall\"'
']
/Users/rausch/Documents/_Projekte/tiny_tds/Rakefile:96:in `block in <top (required)>'
/Users/rausch/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/rausch/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => gem:windows
(See full trace by running task with --trace)
```
</details>

Using crypto generate this:
<details>
```
Running 'configure' for openssl 1.1.0-pre5... OK
Running 'compile' for openssl 1.1.0-pre5... OK
Running 'mkdef-libeay32' for openssl 1.1.0-pre5... OK
Running 'mkdef-ssleay32' for openssl 1.1.0-pre5... OK
Running 'dllwrap-libeay32' for openssl 1.1.0-pre5... ERROR, review '/Users/rausch/Documents/_Projekte/tiny_tds/tmp/x86-mingw32/tiny_tds/2.0.0/tmp/i686-w64-mingw32/ports/openssl/1.1.0-pre5/dllwrap-libeay32.log' to see what happened. Last lines are:
========================================================================
libcrypto.a(b_addr.o):b_addr.c:(.text+0xcb): undefined reference to `_imp__getnameinfo@28'
libcrypto.a(b_addr.o):b_addr.c:(.text+0x1d0): undefined reference to `gai_strerrorW'
libcrypto.a(b_addr.o):b_addr.c:(.text+0x750): undefined reference to `_imp__freeaddrinfo@4'
libcrypto.a(b_addr.o):b_addr.c:(.text+0xa7b): undefined reference to `_imp__getaddrinfo@16'
libcrypto.a(b_addr.o):b_addr.c:(.text+0xac3): undefined reference to `gai_strerrorW'
collect2: error: ld returned 1 exit status
i686-w64-mingw32-dllwrap: i686-w64-mingw32-gcc exited with status 1
========================================================================
*** ../../../../ext/tiny_tds/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../ext/tiny_tds
	--curdir
	--ruby=/usr/local/rake-compiler/ruby/i686-w64-mingw32/ruby-2.0.0-p645/bin/ruby
	--help
	--enable-lookup
	--disable-lookup
	--with-freetds-dir
	--without-freetds-dir
	--with-freetds-include
	--without-freetds-include=${freetds-dir}/include
	--with-freetds-lib
	--without-freetds-lib=${freetds-dir}/
	--enable-system-freetds
	--disable-system-freetds
	--enable-system-iconv
	--disable-system-iconv
	--enable-system-openssl
	--disable-system-openssl
	--enable-gnutls
	--disable-gnutls
	--enable-openssl
	--disable-openssl
	--enable-cross-build
/usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Failed to complete dllwrap-libeay32 task (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `chdir'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
	from ../../../../ext/tiny_tds/extconf.rb:178:in `compile'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
	from ../../../../ext/tiny_tds/extconf.rb:128:in `block in cook_and_activate'
	from ../../../../ext/tiny_tds/extconf.rb:120:in `block in chdir_for_build'
	from ../../../../ext/tiny_tds/extconf.rb:119:in `chdir'
	from ../../../../ext/tiny_tds/extconf.rb:119:in `chdir_for_build'
	from ../../../../ext/tiny_tds/extconf.rb:127:in `cook_and_activate'
	from ../../../../ext/tiny_tds/extconf.rb:319:in `<main>'
rake aborted!
Command failed with status (1): [/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby ...]
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:191:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:188:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => native => native:x86-mingw32 => native:tiny_tds:x86-mingw32 => tmp/x86-mingw32/stage/lib/tiny_tds/2.0/tiny_tds.so => copy:tiny_tds:x86-mingw32:2.0.0 => tmp/x86-mingw32/tiny_tds/2.0.0/tiny_tds.so => tmp/x86-mingw32/tiny_tds/2.0.0/Makefile
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v /Users/rausch/Documents/_Projekte/tiny_tds:/Users/rausch/Documents/_Projekte/tiny_tds -e UID\=1000 -e GID\=1000 -e USER\=rausch -e GROUP\=_staff -e ftp_proxy\= -e http_proxy\= -e https_proxy\= -e RCD_HOST_RUBY_PLATFORM\=x86_64-darwin15 -e RCD_HOST_RUBY_VERSION\=2.3.1 -e RCD_IMAGE\=larskanis/rake-compiler-dock:0.5.1 -w /Users/rausch/Documents/_Projekte/tiny_tds --rm -i -t larskanis/rake-compiler-dock:0.5.1 runas sigfw bash -c \ \ \ \ bundle\ \&\&\ rake\ cross\ native\ gem\ RUBY_CC_VERSION\=2.0.0:2.1.6:2.2.2:2.3.0\ CFLAGS\=\"-Wall\"'
']
/Users/rausch/Documents/_Projekte/tiny_tds/Rakefile:96:in `block in <top (required)>'
/Users/rausch/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/rausch/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => gem:windows
(See full trace by running task with --trace)
```
</details>

Tried to find some documentation about build changes but failed. 
Is there anything I miss here? Is there a detailed how-to or documentation how to create those dllwrap with 1.1.0?

**Comment by zhaozg** [comment]
missing link to Ws2_32.lib, ?

**Comment by YvesR** [comment]
Where should they be located? 
I checked 1.0.2 folders and see there are win32dll.bat that build those libs?
It seems (I am new to all this, sry) that they are created in build as well, so they are missing in my case. Any hint where I can look? 

This are the current parameters I use:
`CROSS_COMPILE=i686-w64-mingw32- CFLAGS=-DDSO_WIN32 ./Configure no-shared --prefix=/Users/rausch/Documents/_Projekte/tiny_tds/ports/i686-w64-mingw32 mingw`

The rake-dock-compiler uses mingw to build it.

**Comment by levitte** [comment]
For the calls of `util/mkdef.pl`, you should replace `libeay` with `crypto` and `ssleay` with `ssl`.  So in `extconf.rb`, the lines https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/extconf.rb#L175-L176 should be rewritten as follows:

``` ruby
        execute "mkdef-libeay32", "(perl util/mkdef.pl 32 crypto >libeay32.def)"
        execute "mkdef-ssleay32", "(perl util/mkdef.pl 32 ssl >ssleay32.def)"
```

Also, as @zhaozg points out, you're not linking with all the needed external libraries.  The minimum set the default OpenSSL builds link with are ws2_32, gdi32, advapi32, crypt32 and user32.  On Debian and associate dists, those are available in the package `mingw-w64-i686-dev`.

Now, just a note, you might want to check out what the build OpenSSL 1.1.0 does if you allow it to build shared libraries.  There's been quite a bit of change, the build will now generate these for mingw:

    libcrypto.dll.a
    libcrypto-1_1.dll
    libssl.dll.a
    libssl-1_1.dll

and these for mingw64:

    libcrypto.dll.a
    libcrypto-1_1-x64.dll
    libssl.dll.a
    libssl-1_1-x64.dll

**Comment by YvesR** [comment]
Thank you for the information.
