### ISSUE TITLE
Crash in CMS_verify (OpenSSL 3.0.0-alpha9)

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#13624]
After `cms = d2i_CMS_bio(bio, NULL)`, a crash can occur with `CMS_verify(cms, NULL, NULL, NULL, NULL, CMS_NO_SIGNER_CERT_VERIFY)`:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CMS_SignerInfo_verify (si=0x13199499080) at crypto/cms/cms_sd.c:833
833         fetched_md = EVP_MD_fetch(ctx->libctx, name, ctx->propq);
(gdb) p si->cms_ctx
$1 = (const CMS_CTX *) 0x0
(gdb) bt
#0  CMS_SignerInfo_verify (si=0x13199499080) at crypto/cms/cms_sd.c:833
#1  0x0000012f19e7822b in CMS_verify (cms=<optimized out>, certs=<optimized out>, store=0x0,
    dcont=0x0, out=0x0, flags=<optimized out>) at crypto/cms/cms_smime.c:378
```

The reason for this is that the signer info `si` doesn't have its `cms_ctx` set, so `ctx` is `NULL`.
This in turn is due to what looks like a logic error on line 41 in `d2i_CMS_bio()`:

https://github.com/openssl/openssl/blob/c30566777973d624eb42779086600e4453d1141a/crypto/cms/cms_io.c#L36-L42

If passed in `NULL`, or a pointer to `NULL`, the `d2i` family of functions will allocate a new struct.
This will have its libctx resolved only if it was passed a pointer to `NULL`, but not if it was passed `NULL`.

I think the `&& cms != NULL` part in this conditional should be dropped. Indeed, doing this resolves this crash and the code works as expected from OpenSSL 1.1.1. Of course, I can easily rewrite the code to avoid this problem, but it looks like a bug.

The same problem seems to be present in `SMIME_read_CMS_ex` (note `SMIME_read_CMS` just below)
https://github.com/openssl/openssl/blob/c30566777973d624eb42779086600e4453d1141a/crypto/cms/cms_io.c#L100-L101
and in `d2i_CMS_ContentInfo`:
https://github.com/openssl/openssl/blob/c30566777973d624eb42779086600e4453d1141a/crypto/cms/cms_lib.c#L37-L38

**Comment by botovq** [comment]
Here is a reproducer. With OpenSSL 1.1.1i it prints "OK", with OpenSSL 3.0.0-alpha9 it crashes as described above
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CMS_SignerInfo_verify (si=0x78cdcc1ab80) at crypto/cms/cms_sd.c:833
833         fetched_md = EVP_MD_fetch(ctx->libctx, name, ctx->propq);
(gdb) bt
#0  CMS_SignerInfo_verify (si=0x78cdcc1ab80) at crypto/cms/cms_sd.c:833
#1  0x0000078a87eeb11b in CMS_verify (cms=<optimized out>, certs=<optimized out>, store=0x0,
    dcont=0x0, out=0x0, flags=<optimized out>) at crypto/cms/cms_smime.c:378
#2  0x0000078a87cc3445 in main () at cms_verify.c:251
```

```C
#include <stdio.h>
#include <string.h>

#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/cms.h>

const unsigned char mft[] = {
    0x30, 0x80, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86,
    0xf7, 0x0d, 0x01, 0x07, 0x02, 0xa0, 0x80, 0x30,
    0x80, 0x02, 0x01, 0x03, 0x31, 0x0f, 0x30, 0x0d,
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03,
    0x04, 0x02, 0x01, 0x05, 0x00, 0x30, 0x80, 0x06,
    0x0b, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01,
    0x09, 0x10, 0x01, 0x1a, 0xa0, 0x80, 0x24, 0x80,
    0x04, 0x81, 0xbf, 0x30, 0x81, 0xbc, 0x02, 0x01,
    0x33, 0x18, 0x0f, 0x32, 0x30, 0x31, 0x39, 0x30,
    0x35, 0x31, 0x35, 0x31, 0x32, 0x32, 0x34, 0x33,
    0x36, 0x5a, 0x18, 0x0f, 0x32, 0x30, 0x31, 0x39,
    0x30, 0x38, 0x31, 0x35, 0x31, 0x32, 0x32, 0x34,
    0x33, 0x36, 0x5a, 0x06, 0x09, 0x60, 0x86, 0x48,
    0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x30, 0x81,
    0x89, 0x30, 0x51, 0x16, 0x2c, 0x32, 0x61, 0x37,
    0x64, 0x64, 0x31, 0x64, 0x37, 0x38, 0x37, 0x64,
    0x37, 0x39, 0x33, 0x65, 0x34, 0x63, 0x38, 0x61,
    0x66, 0x35, 0x36, 0x65, 0x31, 0x39, 0x37, 0x64,
    0x34, 0x65, 0x65, 0x64, 0x39, 0x32, 0x61, 0x66,
    0x36, 0x62, 0x61, 0x31, 0x33, 0x2e, 0x63, 0x65,
    0x72, 0x03, 0x21, 0x00, 0xc1, 0x51, 0x46, 0xe0,
    0x4d, 0x0e, 0xbc, 0x83, 0x54, 0x13, 0xcd, 0x94,
    0xd8, 0xff, 0x3a, 0xbe, 0x1e, 0xfe, 0x24, 0x26,
    0x1e, 0x8a, 0x11, 0xe4, 0xf8, 0x8a, 0xea, 0x18,
    0x16, 0x60, 0x7f, 0x12, 0x30, 0x34, 0x16, 0x0f,
    0x72, 0x69, 0x70, 0x65, 0x2d, 0x6e, 0x63, 0x63,
    0x2d, 0x74, 0x61, 0x2e, 0x63, 0x72, 0x6c, 0x03,
    0x21, 0x00, 0xa6, 0xef, 0x40, 0xd1, 0x4a, 0x8b,
    0xa3, 0x6e, 0xb1, 0x84, 0x05, 0xa6, 0x56, 0x1f,
    0x38, 0xad, 0x36, 0xc8, 0xfd, 0x3c, 0xc4, 0xdc,
    0xc1, 0xe3, 0x6f, 0x0f, 0xc0, 0xeb, 0x9d, 0xee,
    0xd8, 0x74, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xa0, 0x80, 0x30, 0x82, 0x04, 0x46, 0x30, 0x82,
    0x03, 0x2e, 0xa0, 0x03, 0x02, 0x01, 0x02, 0x02,
    0x02, 0x00, 0xd9, 0x30, 0x0d, 0x06, 0x09, 0x2a,
    0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x0b,
    0x05, 0x00, 0x30, 0x16, 0x31, 0x14, 0x30, 0x12,
    0x06, 0x03, 0x55, 0x04, 0x03, 0x13, 0x0b, 0x72,
    0x69, 0x70, 0x65, 0x2d, 0x6e, 0x63, 0x63, 0x2d,
    0x74, 0x61, 0x30, 0x1e, 0x17, 0x0d, 0x31, 0x39,
    0x30, 0x35, 0x31, 0x35, 0x31, 0x32, 0x32, 0x34,
    0x33, 0x36, 0x5a, 0x17, 0x0d, 0x31, 0x39, 0x30,
    0x38, 0x31, 0x35, 0x31, 0x32, 0x32, 0x34, 0x33,
    0x36, 0x5a, 0x30, 0x33, 0x31, 0x31, 0x30, 0x2f,
    0x06, 0x03, 0x55, 0x04, 0x03, 0x13, 0x28, 0x34,
    0x36, 0x65, 0x62, 0x30, 0x38, 0x30, 0x65, 0x66,
    0x64, 0x30, 0x31, 0x61, 0x39, 0x31, 0x39, 0x37,
    0x35, 0x64, 0x36, 0x62, 0x61, 0x36, 0x61, 0x63,
    0x30, 0x36, 0x62, 0x62, 0x65, 0x61, 0x31, 0x31,
    0x38, 0x35, 0x31, 0x31, 0x39, 0x31, 0x64, 0x30,
    0x82, 0x01, 0x22, 0x30, 0x0d, 0x06, 0x09, 0x2a,
    0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01,
    0x05, 0x00, 0x03, 0x82, 0x01, 0x0f, 0x00, 0x30,
    0x82, 0x01, 0x0a, 0x02, 0x82, 0x01, 0x01, 0x00,
    0xbd, 0x4d, 0x66, 0x1b, 0xe6, 0x2e, 0x3c, 0x17,
    0xa5, 0xfc, 0x9c, 0x79, 0x4e, 0x56, 0xc3, 0xf0,
    0xc5, 0x50, 0x7e, 0x0e, 0x85, 0x9d, 0xff, 0x5f,
    0x92, 0x53, 0x0d, 0xb2, 0xed, 0x91, 0x6e, 0x54,
    0x57, 0xc1, 0x30, 0x6b, 0x2c, 0xd6, 0x44, 0x8a,
    0xce, 0xcb, 0x08, 0x5d, 0xc3, 0x63, 0x2c, 0x32,
    0xf0, 0x76, 0x83, 0xed, 0x8b, 0x10, 0x0b, 0xc9,
    0x10, 0x06, 0x2f, 0x48, 0x45, 0x7f, 0xd4, 0x6c,
    0xd6, 0x6f, 0x92, 0xea, 0x69, 0xf6, 0xae, 0x24,
    0x70, 0x4a, 0xf9, 0x4a, 0x76, 0xef, 0x80, 0x8d,
    0x7d, 0x7a, 0xd5, 0x7b, 0x66, 0x94, 0x41, 0x17,
    0x61, 0x1f, 0x60, 0x8d, 0xbd, 0x0a, 0x34, 0xf2,
    0x1a, 0xc1, 0x9e, 0xce, 0x70, 0xee, 0x4e, 0x23,
    0x62, 0x82, 0x42, 0x44, 0xea, 0xe9, 0xe2, 0x2d,
    0xcb, 0x56, 0x9e, 0xdc, 0xdb, 0x4a, 0x4e, 0x0b,
    0x40, 0xe9, 0xfe, 0x98, 0xb5, 0xf1, 0x47, 0xe3,
    0xb0, 0x9c, 0x90, 0x9e, 0xb2, 0xe3, 0x04, 0xc7,
    0xc0, 0xa0, 0xe7, 0xef, 0x24, 0xdb, 0xab, 0x6e,
    0x89, 0x92, 0x69, 0xde, 0xef, 0xef, 0x6a, 0xa8,
    0xc8, 0xe0, 0x0c, 0x9e, 0x1d, 0xc5, 0x35, 0x6a,
    0x45, 0x6b, 0x61, 0x44, 0xa5, 0xd2, 0xc6, 0x4a,
    0x7d, 0xb8, 0x0d, 0xb2, 0x11, 0x03, 0x14, 0xa6,
    0xb4, 0xe9, 0x7e, 0x99, 0x66, 0xf3, 0xae, 0xe0,
    0x66, 0x1e, 0xc3, 0x77, 0xed, 0x41, 0xf6, 0xea,
    0xa3, 0xae, 0x9e, 0xc4, 0x89, 0x22, 0x83, 0x1f,
    0x82, 0x3a, 0x5e, 0x4d, 0x31, 0x77, 0xd7, 0x44,
    0x98, 0x8f, 0x1f, 0xd2, 0x1a, 0xd6, 0x3b, 0x54,
    0xb9, 0x6b, 0xa7, 0xbe, 0x3f, 0x48, 0x5e, 0x77,
    0xba, 0xcb, 0x46, 0x24, 0x49, 0x51, 0xd1, 0x04,
    0x86, 0x80, 0x71, 0xd8, 0x73, 0x87, 0xa2, 0x80,
    0x30, 0xf0, 0x28, 0x82, 0xa2, 0xd8, 0x08, 0x3a,
    0x72, 0x6e, 0xde, 0x3e, 0xea, 0x39, 0x69, 0x75,
    0x02, 0x03, 0x01, 0x00, 0x01, 0xa3, 0x82, 0x01,
    0x7f, 0x30, 0x82, 0x01, 0x7b, 0x30, 0x1d, 0x06,
    0x03, 0x55, 0x1d, 0x0e, 0x04, 0x16, 0x04, 0x14,
    0x46, 0xeb, 0x08, 0x0e, 0xfd, 0x01, 0xa9, 0x19,
    0x75, 0xd6, 0xba, 0x6a, 0xc0, 0x6b, 0xbe, 0xa1,
    0x18, 0x51, 0x19, 0x1d, 0x30, 0x1f, 0x06, 0x03,
    0x55, 0x1d, 0x23, 0x04, 0x18, 0x30, 0x16, 0x80,
    0x14, 0xe8, 0x55, 0x2b, 0x1f, 0xd6, 0xd1, 0xa4,
    0xf7, 0xe4, 0x04, 0xc6, 0xd8, 0xe5, 0x68, 0x0d,
    0x1e, 0xbc, 0x16, 0x3f, 0xc3, 0x30, 0x0e, 0x06,
    0x03, 0x55, 0x1d, 0x0f, 0x01, 0x01, 0xff, 0x04,
    0x04, 0x03, 0x02, 0x07, 0x80, 0x30, 0x44, 0x06,
    0x08, 0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x01,
    0x01, 0x04, 0x38, 0x30, 0x36, 0x30, 0x34, 0x06,
    0x08, 0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30,
    0x02, 0x86, 0x28, 0x72, 0x73, 0x79, 0x6e, 0x63,
    0x3a, 0x2f, 0x2f, 0x72, 0x70, 0x6b, 0x69, 0x2e,
    0x72, 0x69, 0x70, 0x65, 0x2e, 0x6e, 0x65, 0x74,
    0x2f, 0x74, 0x61, 0x2f, 0x72, 0x69, 0x70, 0x65,
    0x2d, 0x6e, 0x63, 0x63, 0x2d, 0x74, 0x61, 0x2e,
    0x63, 0x65, 0x72, 0x30, 0x4c, 0x06, 0x08, 0x2b,
    0x06, 0x01, 0x05, 0x05, 0x07, 0x01, 0x0b, 0x04,
    0x40, 0x30, 0x3e, 0x30, 0x3c, 0x06, 0x08, 0x2b,
    0x06, 0x01, 0x05, 0x05, 0x07, 0x30, 0x0b, 0x86,
    0x30, 0x72, 0x73, 0x79, 0x6e, 0x63, 0x3a, 0x2f,
    0x2f, 0x72, 0x70, 0x6b, 0x69, 0x2e, 0x72, 0x69,
    0x70, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x72,
    0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
    0x79, 0x2f, 0x72, 0x69, 0x70, 0x65, 0x2d, 0x6e,
    0x63, 0x63, 0x2d, 0x74, 0x61, 0x2e, 0x6d, 0x66,
    0x74, 0x30, 0x41, 0x06, 0x03, 0x55, 0x1d, 0x1f,
    0x04, 0x3a, 0x30, 0x38, 0x30, 0x36, 0xa0, 0x34,
    0xa0, 0x32, 0x86, 0x30, 0x72, 0x73, 0x79, 0x6e,
    0x63, 0x3a, 0x2f, 0x2f, 0x72, 0x70, 0x6b, 0x69,
    0x2e, 0x72, 0x69, 0x70, 0x65, 0x2e, 0x6e, 0x65,
    0x74, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69,
    0x74, 0x6f, 0x72, 0x79, 0x2f, 0x72, 0x69, 0x70,
    0x65, 0x2d, 0x6e, 0x63, 0x63, 0x2d, 0x74, 0x61,
    0x2e, 0x63, 0x72, 0x6c, 0x30, 0x18, 0x06, 0x03,
    0x55, 0x1d, 0x20, 0x01, 0x01, 0xff, 0x04, 0x0e,
    0x30, 0x0c, 0x30, 0x0a, 0x06, 0x08, 0x2b, 0x06,
    0x01, 0x05, 0x05, 0x07, 0x0e, 0x02, 0x30, 0x21,
    0x06, 0x08, 0x2b, 0x06, 0x01, 0x05, 0x05, 0x07,
    0x01, 0x07, 0x01, 0x01, 0xff, 0x04, 0x12, 0x30,
    0x10, 0x30, 0x06, 0x04, 0x02, 0x00, 0x01, 0x05,
    0x00, 0x30, 0x06, 0x04, 0x02, 0x00, 0x02, 0x05,
    0x00, 0x30, 0x15, 0x06, 0x08, 0x2b, 0x06, 0x01,
    0x05, 0x05, 0x07, 0x01, 0x08, 0x01, 0x01, 0xff,
    0x04, 0x06, 0x30, 0x04, 0xa0, 0x02, 0x05, 0x00,
    0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86,
    0xf7, 0x0d, 0x01, 0x01, 0x0b, 0x05, 0x00, 0x03,
    0x82, 0x01, 0x01, 0x00, 0x28, 0x87, 0xb8, 0x6c,
    0x4a, 0xcb, 0x3a, 0x39, 0x0e, 0xee, 0xe4, 0x7b,
    0x49, 0xf3, 0x02, 0x88, 0x7b, 0xf7, 0x07, 0xb5,
    0x77, 0x80, 0xc0, 0xd6, 0xd5, 0xb2, 0x8f, 0x57,
    0x3f, 0x18, 0xda, 0x8e, 0x1a, 0x7a, 0x95, 0x35,
    0x8c, 0x95, 0xe9, 0xba, 0x6e, 0xae, 0xb9, 0xa3,
    0xb4, 0x56, 0xb9, 0xe8, 0xe6, 0xcf, 0xfa, 0xef,
    0x61, 0xf1, 0x5a, 0x14, 0xdf, 0x2d, 0x69, 0x12,
    0x4a, 0x3b, 0x82, 0xee, 0x23, 0x8a, 0x15, 0x7b,
    0x37, 0x76, 0xef, 0xa7, 0x95, 0xd4, 0x58, 0x3c,
    0x09, 0x26, 0x2c, 0x65, 0x57, 0x6a, 0xb9, 0xc1,
    0xf6, 0xff, 0xcb, 0x1b, 0x0b, 0xc9, 0x39, 0x0a,
    0x37, 0x89, 0x43, 0xe8, 0x17, 0x3a, 0x96, 0x94,
    0xf8, 0x6f, 0x5e, 0xfb, 0x63, 0x99, 0x07, 0x0b,
    0x92, 0x7b, 0x30, 0x73, 0x1c, 0xf6, 0xea, 0x79,
    0xfb, 0xa6, 0xf4, 0x88, 0x21, 0x26, 0x01, 0x57,
    0xd1, 0x16, 0x77, 0xf0, 0x31, 0xb6, 0x68, 0xf8,
    0x96, 0xfd, 0x7f, 0x54, 0xd7, 0xc2, 0x0e, 0xca,
    0x30, 0xc6, 0x17, 0x64, 0x58, 0x59, 0xd0, 0x8c,
    0x61, 0x3c, 0x33, 0x50, 0xf7, 0x52, 0x0a, 0xa0,
    0x8f, 0x27, 0x5b, 0x43, 0x81, 0xb6, 0x62, 0xe6,
    0x0a, 0x71, 0x9f, 0x2d, 0xca, 0x48, 0x94, 0x1a,
    0x00, 0x36, 0x6c, 0x91, 0xcd, 0x28, 0x2a, 0x7b,
    0x04, 0xbf, 0x36, 0x25, 0x5b, 0x0f, 0xba, 0x96,
    0x37, 0xee, 0x7f, 0x84, 0xcf, 0xe2, 0x28, 0xfa,
    0xdc, 0x6b, 0xc9, 0x6d, 0x6b, 0xe0, 0x11, 0xd0,
    0xeb, 0x71, 0xa1, 0xae, 0x9f, 0x4b, 0x15, 0xf0,
    0x43, 0xcc, 0xb7, 0x73, 0x29, 0x66, 0x3b, 0x48,
    0xfe, 0xe9, 0x01, 0x04, 0xf5, 0x6a, 0xb1, 0xcb,
    0xf1, 0xa4, 0xd9, 0x68, 0xde, 0x3b, 0x56, 0x6a,
    0x0b, 0x61, 0xb5, 0x55, 0xec, 0x81, 0xf2, 0x3c,
    0xa6, 0x87, 0x63, 0xbf, 0x11, 0xd0, 0x33, 0x63,
    0xe6, 0x44, 0xf5, 0xce, 0x00, 0x00, 0x31, 0x82,
    0x01, 0xac, 0x30, 0x82, 0x01, 0xa8, 0x02, 0x01,
    0x03, 0x80, 0x14, 0x46, 0xeb, 0x08, 0x0e, 0xfd,
    0x01, 0xa9, 0x19, 0x75, 0xd6, 0xba, 0x6a, 0xc0,
    0x6b, 0xbe, 0xa1, 0x18, 0x51, 0x19, 0x1d, 0x30,
    0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65,
    0x03, 0x04, 0x02, 0x01, 0x05, 0x00, 0xa0, 0x6b,
    0x30, 0x1a, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86,
    0xf7, 0x0d, 0x01, 0x09, 0x03, 0x31, 0x0d, 0x06,
    0x0b, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01,
    0x09, 0x10, 0x01, 0x1a, 0x30, 0x1c, 0x06, 0x09,
    0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x09,
    0x05, 0x31, 0x0f, 0x17, 0x0d, 0x31, 0x39, 0x30,
    0x35, 0x31, 0x35, 0x31, 0x32, 0x32, 0x34, 0x33,
    0x36, 0x5a, 0x30, 0x2f, 0x06, 0x09, 0x2a, 0x86,
    0x48, 0x86, 0xf7, 0x0d, 0x01, 0x09, 0x04, 0x31,
    0x22, 0x04, 0x20, 0x16, 0x26, 0x71, 0x19, 0x16,
    0x99, 0x0b, 0x69, 0x24, 0xc1, 0xc8, 0x23, 0x67,
    0x3f, 0x69, 0xac, 0xe6, 0x63, 0xfc, 0xaa, 0x2a,
    0x17, 0xbb, 0x1e, 0x8f, 0xcd, 0xa4, 0x56, 0x85,
    0xd5, 0x36, 0x05, 0x30, 0x0d, 0x06, 0x09, 0x2a,
    0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01,
    0x05, 0x00, 0x04, 0x82, 0x01, 0x00, 0xb3, 0x0b,
    0x8c, 0xeb, 0xd0, 0x4c, 0xce, 0x25, 0x04, 0xf9,
    0x63, 0x64, 0xfb, 0x28, 0xef, 0x1b, 0x63, 0x07,
    0x73, 0x01, 0x9d, 0xe9, 0x5e, 0xc9, 0x65, 0x73,
    0xab, 0xda, 0x41, 0x6e, 0xca, 0x9e, 0x82, 0x6e,
    0x28, 0xe8, 0xaf, 0x8a, 0x92, 0x61, 0xeb, 0x5f,
    0xbb, 0x75, 0xc8, 0x77, 0x00, 0x01, 0x9c, 0x9e,
    0xf5, 0x70, 0xdf, 0x27, 0x58, 0xcc, 0x1d, 0x95,
    0x41, 0x31, 0xc8, 0x23, 0xa7, 0xe1, 0xab, 0xdb,
    0xd1, 0xc0, 0xe1, 0x81, 0xcb, 0xd7, 0xfb, 0xa9,
    0x12, 0x7a, 0x46, 0x72, 0xab, 0x82, 0xe1, 0xee,
    0x98, 0x10, 0x3f, 0x27, 0x75, 0x1a, 0x50, 0x87,
    0x1e, 0x16, 0x86, 0xf1, 0x4a, 0x43, 0x81, 0x33,
    0x2f, 0xfd, 0x48, 0x7c, 0x99, 0x6a, 0xb8, 0xcd,
    0xcf, 0x10, 0xe7, 0x77, 0x93, 0xd8, 0x51, 0x99,
    0x47, 0x54, 0xeb, 0xb7, 0x15, 0xd4, 0xb0, 0xba,
    0x6f, 0x28, 0xb7, 0x2e, 0xfc, 0x29, 0xd4, 0x54,
    0x9f, 0x84, 0xd6, 0x54, 0x51, 0x9d, 0x8b, 0x1a,
    0xdc, 0x5e, 0x3f, 0x6e, 0x43, 0x26, 0x89, 0xc3,
    0x9e, 0x23, 0x39, 0xa3, 0x18, 0x27, 0xad, 0xd6,
    0x4a, 0x8e, 0xe6, 0x2b, 0x0a, 0xea, 0x3f, 0x10,
    0xa4, 0x90, 0xe0, 0x3a, 0xd1, 0xfb, 0x3e, 0x0b,
    0xfd, 0x77, 0x4a, 0x35, 0xb8, 0x3b, 0xcb, 0x64,
    0xaf, 0xbf, 0xe5, 0xbf, 0x55, 0x49, 0x3a, 0x33,
    0x1d, 0x05, 0x66, 0xb6, 0xfa, 0x9f, 0xdb, 0x00,
    0x3f, 0x01, 0x76, 0xcf, 0x1e, 0xde, 0x00, 0x40,
    0x0e, 0x36, 0x8a, 0x3e, 0x4a, 0xd2, 0xdb, 0xbc,
    0x79, 0x48, 0x55, 0x57, 0x71, 0x92, 0x42, 0x2b,
    0xf0, 0xf0, 0xeb, 0x5c, 0x8f, 0x7e, 0x19, 0x91,
    0x7f, 0xec, 0xad, 0x3b, 0x20, 0x37, 0xed, 0x3a,
    0x09, 0xf8, 0xfb, 0xfa, 0x87, 0xfe, 0x2b, 0x71,
    0xbf, 0xf0, 0x4f, 0x6b, 0x5a, 0x24, 0xe2, 0x46,
    0xf0, 0x49, 0x54, 0x4e, 0x26, 0x4e, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
};

int
main(void)
{
        BIO *mft_bio, *data_bio;
        CMS_ContentInfo *cms;
        long len;

        if ((mft_bio = BIO_new_mem_buf(mft, sizeof(mft))) == NULL) {
                fprintf(stderr, "BIO_new_mem_buf failed\n");
                return 1;
        }
        if ((cms = d2i_CMS_bio(mft_bio, NULL)) == NULL) {
                fprintf(stderr, "d2i_CMS_bio failed\n");
                return 1;
        }
        if (!CMS_verify(cms, NULL, NULL, NULL, NULL, CMS_NO_SIGNER_CERT_VERIFY)) {
                fprintf(stderr, "CMS_verify failed\n");
                return 1;
        }

        printf("OK\n");

        return 0;
}
```

**Comment by slontis** [comment]
Ok - looking further the code is following a bad pattern that is used in other CMS code.. A alternate PR is coming. I hope you dont mind me using your data as a test case?

**Comment by botovq** [comment]
Thanks. I certainly do not mind.  I should perhaps say that I do not own
the copyright on the data.  It's the hex encoding of an expired RPKI
manifest, downloaded from RIPE.

http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

**Comment by slontis** [comment]
Thanks for the source.. that probably means I cant use it in openssl tests :)
