### ISSUE TITLE
pyca-cryptography test is currently broken

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14425]
The test is broken as can be seen in the failed run here:
https://github.com/openssl/openssl/pull/14416/checks?check_run_id=2030501177
```
------------------------------------------------------------------
Testing OpenSSL using Python Cryptography:
   CWD:                /home/runner/work/openssl/openssl/test-runs/test_external
   SRCTOP:             ../..
   BLDTOP:             ../..
   OpenSSL version:    3.0.0-alpha13-dev
------------------------------------------------------------------
New python executable in /home/runner/work/openssl/openssl/venv-pycrypto/bin/python2
Also creating executable in /home/runner/work/openssl/openssl/venv-pycrypto/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Processing /home/runner/work/openssl/openssl/pyca-cryptography
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/runner/work/openssl/openssl/venv-pycrypto/bin/python2 /home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmps8TkmN
       cwd: /tmp/pip-req-build-Vk0STL
  Complete output (21 lines):
  Traceback (most recent call last):
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 14, in <module>
      from setuptools_rust import RustExtension
    File "/tmp/pip-build-env-A5d8i3/overlay/lib/python2.7/site-packages/setuptools_rust/__init__.py", line 8, in <module>
      from .tomlgen import tomlgen_rust, find_rust_extensions
    File "/tmp/pip-build-env-A5d8i3/overlay/lib/python2.7/site-packages/setuptools_rust/tomlgen.py", line 191
      yield dep, toml.loads(f"{dep} = {options}")[dep]
                                               ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/runner/work/openssl/openssl/venv-pycrypto/bin/python2 /home/runner/work/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmps8TkmN Check the logs for full command output.
../../util/wrap.pl sh ../../test/recipes/95-test_external_pyca_data/cryptography.sh => 1
not ok 1 - running Python Cryptography tests
# ------------------------------------------------------------------------------
#   Failed test 'running Python Cryptography tests'
#   at test/recipes/95-test_external_pyca.t line 27.
# Looks like you failed 1 test of 1.95-test_external_pyca.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```
Apparently there is something wrong with the virtualenv on the Ubuntu release that Github CI uses?

**Comment by t8m** [comment]
Perhaps @tiran can give some hints?

**Comment by paulidale** [comment]
@jon-oracle ?

**Comment by tiran** [comment]
PyCA cryptography 3.4 has dropped support for Python 2. You need to update to Python 3.6 or newer. Python 3.5 and older don't support f-strings.

https://cryptography.io/en/latest/changelog.html#v3-4

**Comment by t8m** [comment]
I've got further with this run:
https://github.com/t8m/openssl/runs/2031788975

But it still looks like I am missing some prerequisites or so.
Here is the test script:
https://github.com/t8m/openssl/blob/pyca-test-fix/test/recipes/95-test_external_pyca_data/cryptography.sh

**Comment by tiran** [comment]
You are missing the vectors package. ``pip3 install ./vectors/`` should do the trick.

**Comment by reaperhulk** [comment]
`cryptography` won't compile against OpenSSL 3.0.0 alphas at this time. https://github.com/pyca/cryptography/pull/5250

It appears there are also some separate build problems -- I'd suggest looking at https://github.com/pyca/cryptography/blob/f86e0dae0d91f7fe7fea425ecc1ac465bbff5117/.github/workflows/ci.yml to see how we compile custom OpenSSL for testing.

https://github.com/openssl/openssl/issues/13560 is the only remaining blocker for merging 3.0.0 support into our main tree, which would allow the test harness to be updated.
