### ISSUE TITLE
stack-buffer-overflow in evp_test.c:36

### ISSUE THREAD

**Issue by geeknik** [openssl/openssl#1454]
Originally reported to the security team but was deemed not a security issue. I quote: `It’s a test program; it’s not installed.  It expects the input format to be followed, and if not it can crash.  When normally invoked, it’s given a properly-formatted file.` 

Now my response to that is, okay, that is all well and good, but if it expects a properly formatted file, then it shouldn't do bad things when the file isn't properly formatted. As such, I consider this to be related to ce7a223. 

Command line:
`echo = > test | ./evp_test test`

Result: 

```
==22066==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc64a679ef at pc 0x0000004c057d bp 0x7ffc64a678b0 sp 0x7ffc64a678a8
READ of size 1 at 0x7ffc64a679ef thread T0
    #0 0x4c057c in remove_space /home/geeknik/openssl/test/evp_test.c:36:5
    #1 0x4c057c in parse_line /home/geeknik/openssl/test/evp_test.c:77
    #2 0x4c057c in process_test /home/geeknik/openssl/test/evp_test.c:426
    #3 0x4c057c in main /home/geeknik/openssl/test/evp_test.c:569
    #4 0x7ff36104db44 in __libc_start_main /build/glibc-uPj9cH/glibc-2.19/csu/libc-start.c:287
    #5 0x4bec1c in _start (/home/geeknik/openssl/test/evp_test+0x4bec1c)

Address 0x7ffc64a679ef is located in stack of thread T0 at offset 143 in frame

    #0 0x4becff in main /home/geeknik/openssl/test/evp_test.c:547

  This frame has 3 object(s):
    [32, 112) 'tmpbuf.i'
    [144, 10384) 'buf' <== Memory access at offset 143 underflows this variable
    [10640, 10768) 't'
```

**Comment by mattcaswell** [comment]
Fixed by 533b178db6
