### ISSUE TITLE
It shows Segmentation fault when I run openssl (v3.0.0) in ARM

### ISSUE THREAD

**Issue by HaveYouTall** [openssl/openssl#14866]
I typed following codes to install openssl v3.0.0 - alpha14
```bash
./config no-asm -static --prefix=/home/hyt/openssl-v3.0.0-out --cross-compile-prefix=aarch64-linux-gnu-

# Before use make to compile, I delete the codes related with "-m64" in Makefile.
make

make install
```
And then I moved to openssl-v3.0.0-out directory and ran `qemu-aarch64 ./openssl`  It showed 
``` bash
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

Could anyone help me with this?

By the way, when I did the same thing with OpenSSL v1.1.1k, it worked very well.

**Comment by paulidale** [comment]
> # Before use make to compile, I deleted the codes related with "-m64" in Makefile.

Does it work without modifying the Makefile?

**Comment by HaveYouTall** [comment]
> > Before use make to compile, I deleted the codes related with "-m64" in Makefile.
> 
> Does it work without modifying the Makefile?

No, it would fail when compiling .

**Comment by slontis** [comment]
configuring this way doesn't even work for linux..

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000857d2c in __register_frame_info_bases.part.0 ()
#2  0x0000000000402141 in frame_dummy ()
#3  0x0000000000000001 in ?? ()
#4  0x000000000077fb9c in __libc_csu_init ()
#5  0x000000000077f2ee in __libc_start_main ()
#6  0x000000000040205e in _start ()


It also gets these kind of warnings when building:
````
${LDCMD:-gcc} -pthread -m64 -Wall -O0 -g -L.  -static \
	-o test/x509aux \
	test/x509aux-bin-x509aux.o \
	test/libtestutil.a -lcrypto -ldl -pthread 
/usr/bin/ld: ./libcrypto.a(libcrypto-lib-b_addr.o): in function `BIO_lookup_ex':
/home/shane/work/OpenSSL/openssl/crypto/bio/b_addr.c:713: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ./libcrypto.a(libcrypto-lib-b_sock.o): in function `BIO_gethostbyname':
/home/shane/work/OpenSSL/openssl/crypto/bio/b_sock.c:123: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
````

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input.

**Comment by t8m** [comment]
Closing as the issue was labeled as inactive for extended period of time and there was no additional input.
Please add a comment if you have any further information to support reopening the issue.
