### ISSUE TITLE
what's the reason of this problem?

### ISSUE THREAD

**Issue by okayabc** [openssl/openssl#14989]
```
#0  0x00007f3fd8a9efd7 in raise () from /lib64/libc.so.6
#1  0x00007f3fd8aa03aa in abort () from /lib64/libc.so.6
#2  0x00007f3fd8ade164 in __libc_message () from /lib64/libc.so.6
#3  0x00007f3fd8ae35d6 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f3fd8ae441b in _int_free () from /lib64/libc.so.6
#5  0x00007f3fdb075b9d in CRYPTO_free () from /usr/local/openssl/lib/libcrypto.so.1.0.0
#6  0x00007f3fdb0d4b10 in BN_clear_free () from /usr/local/openssl/lib/libcrypto.so.1.0.0
#7  0x00007f3fdb0d599e in BN_CTX_free () from /usr/local/openssl/lib/libcrypto.so.1.0.0
#8  0x00007f3fdb10370a in RSA_eay_private_decrypt () from /usr/local/openssl/lib/libcrypto.so.1.0.0
#9  0x00007f3fdadae330 in ssl3_get_client_key_exchange () from /usr/local/openssl/lib/libssl.so.1.0.0
#10 0x00007f3fdadb08f7 in ssl3_accept () from /usr/local/openssl/lib/libssl.so.1.0.0
#11 0x00000000006d1055 in do_handshake (bev_ssl=0x7f3f40334420) at bufferevent_openssl.c:1031
#12 0x00000000006d1720 in be_openssl_handshakeeventcb (fd=<optimized out>, what=<optimized out>, ptr=0x7f3f40334420) at bufferevent_openssl.c:1079
#13 0x00000000006bdfc2 in event_persist_closure (ev=<optimized out>, base=0x7f3f40000900) at event.c:1639
#14 event_process_active_single_queue (base=base@entry=0x7f3f40000900, activeq=0x7f3f40000d70, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1698
#15 0x00000000006be6c7 in event_process_active (base=0x7f3f40000900) at event.c:1799
#16 event_base_loop (base=0x7f3f40000900, flags=0) at event.c:2041

    ```

**Comment by FdaSilvaYY** [comment]
From issue opening documentation :
> Please remember to tell us in what OpenSSL version you found the issue.

Is it a Random or systematic crash ?
What is calling OpenSSL ? your custom app or something else ?

**Comment by okayabc** [comment]
It is a random crash.
The openssl version is 1.0.2.
Libevent call openssl.

**Comment by mattcaswell** [comment]
Unfortunately the answer here is "upgrade to a newer version of OpenSSL". 1.0.2 is EOL.
