### ISSUE TITLE
Incorrect handling of ClientHello messages without signature_algorithms extension (e.g. TLS 1.1 or TLS 1.0)

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#15484]
When negotiating TLS 1.2, it's permissible to send a ClientHello that omits the `signature_algorithms` extension.
Specifically, when the extension is omitted, the server is supposed to behave as if support of SHA-1 signatures was advertised, see [section 7.4.1.4.1](https://datatracker.ietf.org/doc/html/rfc5246#page-47).

Problem exists when the OpenSSL server is configured not to support SHA-1 signatures. In such case, when a ClientHello without the `signature_algorithms` extension is received, the server aborts the connection with `illegal_parameter` Alert. At the same time, when an equivalent ClientHello, with `signature_algorithms` extension listing just SHA-1 mechanisms is received, it's rejected with the expected alert: `handshake_failure`. Also, when the server is reconfigured with support for SHA-1 signatures, an extension-less ClientHello is accepted.

Note that this happens for connections that use RSA key exchange, where server does not perform any signatures...

Using current master (pre-beta1): bfd6b619b6ccba

Reproducer:
```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www -sigalgs RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA256:rsa_pss_pss_sha256:rsa_pss_rsae_sha256 -no_renegotiation -cipher DEFAULT:@SECLEVEL=0
```
In another console:
```
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python3 scripts/test-sig-algs-renegotiation-resumption.py --no-renego
```
tlsfuzzer output:
```
...
without signature_algorithms and signature_algorithms_cert ext ...
Error encountered while processing node ExpectServerHello() (child: <tlsfuzzer.expect.ExpectCertificate object at 0x7f38245e4af0>) with last message being: <tlslite.messages.Message object at 0x7f3824571430>
Error while processing
Traceback (most recent call last):
  File "scripts/test-sig-algs-renegotiation-resumption.py", line 880, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)

...
```
OpenSSL output:
```
40A75389187F0000:error:0A000178:SSL routines:tls1_set_server_sigalgs:no shared signature algorithms:ssl/t1_lib.c:1712:
read R BLOCK
read R BLOCK
40A75389187F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3300:
read R BLOCK
read R BLOCK
read R BLOCK
read R BLOCK
read R BLOCK
read R BLOCK
```

**Comment by tomato42** [comment]
When the SHA-1 is disabled and DH ciphersuites are the only advertised by client, the server handles it even worse, by sending `internal_error` Alert message.

Reproducer (server side is the same):
```
PYTHONPATH=. python3 -u scripts/test-sig-algs-renegotiation-resumption.py --no-renego -d
```

tlsufzzer output:
```
...
without signature_algorithms and signature_algorithms_cert ext ...
Error encountered while processing node ExpectServerHello() (child: <tlsfuzzer.expect.ExpectCertificate object at 0x7f9090bfdc40>) with last message being: <tlslite.messages.Message object at 0x7f9090b9c5b0>
Error while processing
Traceback (most recent call last):
  File "scripts/test-sig-algs-renegotiation-resumption.py", line 880, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 232, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Alert(fatal, internal_error)

...
```
OpenSSL output:
```
ACCEPT
read R BLOCK
read R BLOCK
4027C8027D7F0000:error:0A000178:SSL routines:tls1_set_server_sigalgs:no shared signature algorithms:ssl/t1_lib.c:1712:
read R BLOCK
4027C8027D7F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3300:
read R BLOCK
read R BLOCK
read R BLOCK
read R BLOCK
read R BLOCK
```

**Comment by tomato42** [comment]
This also happens when the OpenSSL server and client are configured to make a TLS 1.0 connection but SECLEVEL doesn't permit SHA-1 signatures, the server then sends `internal_error` Alert.
