### ISSUE TITLE
openssl rsa -modulus segfaults: bn_expand_internal: Assertion `b->top <= words' failed

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#15899]
I'm getting a segfault on OpenSSL 3.0.0 development branch (commit 59a783d05ae379335f70261126d19859ae5a855d) when printing the RSA modulus of a certificate. The command ``openssl x509 -noout -modulus -in httpd.crt`` fails with a segfault about half of the time. It's not fully reproducible. Valgrind complains that a *coditional jump or move depends on uninitialised value*. The problem is line ``BIGNUM *n;`` at ``apps/x509.c:946``.

```
$ LD_LIBRARY_PATH=$(pwd) apps/openssl version
OpenSSL 3.0.0-beta2-dev  (Library: OpenSSL 3.0.0-beta2-dev )
```

```
$ for i in {1..10}; do LD_LIBRARY_PATH=$(pwd) apps/openssl x509 -noout -modulus -in /tmp/httpd.crt; done
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
openssl: crypto/bn/bn_lib.c:287: bn_expand_internal: Assertion `b->top <= words' failed.
Aborted (core dumped)
openssl: crypto/bn/bn_lib.c:287: bn_expand_internal: Assertion `b->top <= words' failed.
Aborted (core dumped)
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
openssl: crypto/bn/bn_lib.c:287: bn_expand_internal: Assertion `b->top <= words' failed.
Aborted (core dumped)
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
openssl: crypto/bn/bn_lib.c:287: bn_expand_internal: Assertion `b->top <= words' failed.
Aborted (core dumped)
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
openssl: crypto/bn/bn_lib.c:287: bn_expand_internal: Assertion `b->top <= words' failed.
Aborted (core dumped)
```

## stacktrace
```
(gdb) bt
#0  0x00007ffff78382a2 in raise () from /lib64/libc.so.6
#1  0x00007ffff78218a4 in abort () from /lib64/libc.so.6
#2  0x00007ffff7821789 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007ffff7830a16 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff7b222e0 in bn_expand_internal (b=0x5054a0, words=32) at crypto/bn/bn_lib.c:287
#5  0x00007ffff7b22344 in bn_expand2 (b=0x5054a0, words=32) at crypto/bn/bn_lib.c:305
#6  0x00007ffff7b2396c in bn_wexpand (a=0x5054a0, words=32) at crypto/bn/bn_lib.c:1020
#7  0x00007ffff7b22af0 in BN_lebin2bn (s=0x7fffffffca10 "", len=256, ret=0x5054a0) at crypto/bn/bn_lib.c:566
#8  0x00007ffff7b22c11 in BN_native2bn (s=0x7fffffffc910 "\267K\251(\365\277<\036\213\211S8\276it\204\273\251\365!f", len=2048, ret=0x5054a0) at crypto/bn/bn_lib.c:602
#9  0x00007ffff7c69267 in OSSL_PARAM_get_BN (p=0x7fffffffd110, val=0x7fffffffd1f8) at crypto/params.c:912
#10 0x00007ffff7c459b5 in EVP_PKEY_get_bn_param (pkey=0x54c010, key_name=0x4d281d "n", bn=0x7fffffffd1f8) at crypto/evp/p_lib.c:2137
#11 0x00000000004828ee in x509_main (argc=0, argv=0x7fffffffd6e0) at apps/x509.c:949
#12 0x000000000044bc3a in do_cmd (prog=0x504810, argc=5, argv=0x7fffffffd6e0) at apps/openssl.c:414
#13 0x000000000044b869 in main (argc=5, argv=0x7fffffffd6e0) at apps/openssl.c:295
```

## cert

```
$ LD_LIBRARY_PATH=$(pwd) apps/openssl x509 -text -in /tmp/httpd.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 9 (0x9)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = IPA.TEST, CN = Certificate Authority
        Validity
            Not Before: Jun 24 14:21:29 2021 GMT
            Not After : Jun 25 14:21:29 2023 GMT
        Subject: O = IPA.TEST, CN = server.example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:92:0c:71:f2:4f:8d:3f:d8:94:79:b1:ba:27:16:
                    3b:22:d6:99:d6:d0:11:35:08:4f:92:a8:73:dc:43:
                    e4:23:fb:22:4a:40:11:0e:56:ad:da:06:7d:b2:c4:
                    51:7e:ea:25:b0:e6:36:e0:e9:8f:58:35:e6:21:c4:
                    29:d3:5b:71:27:7b:56:00:7f:94:ed:ac:e2:0b:d1:
                    6a:e9:7a:fd:f0:a2:7f:ec:03:19:92:8f:f3:9b:06:
                    c1:43:0d:e4:81:cf:6e:37:80:2b:a5:f8:84:27:23:
                    96:ae:eb:2c:54:c0:35:80:70:9a:8b:75:cf:65:d9:
                    b4:7d:34:55:7f:da:3e:83:52:d8:c8:b2:1a:6a:ba:
                    f4:d2:80:87:02:df:33:b5:f4:b2:80:b6:ab:27:e3:
                    e2:59:ed:62:d0:7f:69:4f:f9:8c:61:4c:69:e1:c8:
                    66:fb:c9:f0:f6:86:81:d4:f1:0f:90:ae:36:d9:27:
                    d6:41:45:c1:e1:41:90:f0:bd:87:c9:12:f9:95:ec:
                    89:08:c8:0a:d1:51:b3:23:81:05:8d:67:86:3b:d3:
                    55:41:bc:68:16:3f:d5:4c:3d:e8:04:43:3f:e1:45:
                    a4:28:de:4b:2c:0c:33:ee:89:ef:00:66:21:f5:a9:
                    bb:84:74:69:be:38:53:89:8b:1e:3c:bf:f5:28:a9:
                    4b:b7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
```

```
-----BEGIN CERTIFICATE-----
MIIFKjCCA5KgAwIBAgIBCTANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhJUEEu
VEVTVDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIxMDYyNDE0
MjEyOVoXDTIzMDYyNTE0MjEyOVowMDERMA8GA1UECgwISVBBLlRFU1QxGzAZBgNV
BAMMEnNlcnZlci5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJIMcfJPjT/YlHmxuicWOyLWmdbQETUIT5Koc9xD5CP7IkpAEQ5WrdoG
fbLEUX7qJbDmNuDpj1g15iHEKdNbcSd7VgB/lO2s4gvRaul6/fCif+wDGZKP85sG
wUMN5IHPbjeAK6X4hCcjlq7rLFTANYBwmot1z2XZtH00VX/aPoNS2MiyGmq69NKA
hwLfM7X0soC2qyfj4lntYtB/aU/5jGFMaeHIZvvJ8PaGgdTxD5CuNtkn1kFFweFB
kPC9h8kS+ZXsiQjICtFRsyOBBY1nhjvTVUG8aBY/1Uw96ARDP+FFpCjeSywMM+6J
7wBmIfWpu4R0ab44U4mLHjy/9SipS7cCAwEAAaOCAcowggHGMB8GA1UdIwQYMBaA
FKZD7SVXSJ6l+B8249X8n6I3I7igMDoGCCsGAQUFBwEBBC4wLDAqBggrBgEFBQcw
AYYeaHR0cDovL2lwYS1jYS5pcGEudGVzdC9jYS9vY3NwMA4GA1UdDwEB/wQEAwIE
8DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwcwYDVR0fBGwwajBooDCg
LoYsaHR0cDovL2lwYS1jYS5pcGEudGVzdC9pcGEvY3JsL01hc3RlckNSTC5iaW6i
NKQyMDAxDjAMBgNVBAoMBWlwYWNhMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRo
b3JpdHkwHQYDVR0OBBYEFMf9od/wwzRYk9gsvCKhq5E+0ofXMIGjBgNVHREEgZsw
gZiCEnNlcnZlci5leGFtcGxlLmNvbYIPaXBhLWNhLmlwYS50ZXN0oDAGCisGAQQB
gjcUAgOgIgwgSFRUUC9zZXJ2ZXIuZXhhbXBsZS5jb21ASVBBLlRFU1SgPwYGKwYB
BQICoDUwM6AKGwhJUEEuVEVTVKElMCOgAwIBAaEcMBobBEhUVFAbEnNlcnZlci5l
eGFtcGxlLmNvbTANBgkqhkiG9w0BAQsFAAOCAYEAbvF+cfcxQwkeHZOkVrZuldTQ
KfVef9Qc4AZ3jEBiJ0UaWj+r03XJs7L3x8Sol7PY/dQfm/IoTQPV7K1ERstDCS0y
og47pfr4NOHqtk96Q8MqFw2TGWIzxkT2fQib3WxH3V39L8zRIFmQWdXQNHuxKU2e
yf+9mPybnei+zhfgyaIIHK8EGd75aVDd+ANa6RYiTE7nIpTo27ZUR2ADTqgQ/ZiC
4dJ40Bq0bYGRMWpAVrRJC5KPxEvH/bEoBClJlgQ09irnc5BPzG64+mW/Xzr/7yGO
oV8rn6e6XnILSdD5t0TZ3YSBcrjlScWYqFDoxJcGo6icHCMr46aqq2WAZn4WonUa
G/U3LqeUR4RrFcvB4kkpe/EIHjTjb6fiymydTA7YjalYis3yH/owIJsDCsDGOe+5
NpeuOm1/zCKARIQmtoukniNEoDzGHc79osdOqq1Jw/z+0NDen6jAJqYN/ZVnk24s
g63+r7kDvzZd6cO5jt/9t37uMXYKqzSwyLWmIba9
-----END CERTIFICATE-----
```

## valgrind

```
$ LD_LIBRARY_PATH=$(pwd) valgrind apps/openssl x509 -noout -modulus -in /tmp/httpd.crt
==636624== Memcheck, a memory error detector
==636624== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==636624== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==636624== Command: apps/openssl x509 -noout -modulus -in /tmp/httpd.crt
==636624== 
==636624== Conditional jump or move depends on uninitialised value(s)
==636624==    at 0x4A2DA56: BN_lebin2bn (bn_lib.c:550)
==636624==    by 0x4A2DC10: BN_native2bn (bn_lib.c:602)
==636624==    by 0x4B74266: OSSL_PARAM_get_BN (params.c:912)
==636624==    by 0x4B509B4: EVP_PKEY_get_bn_param (p_lib.c:2137)
==636624==    by 0x4828ED: x509_main (x509.c:949)
==636624==    by 0x44BC39: do_cmd (openssl.c:414)
==636624==    by 0x44B868: main (openssl.c:295)
==636624== 
Modulus=920C71F24F8D3FD89479B1BA27163B22D699D6D01135084F92A873DC43E423FB224A40110E56ADDA067DB2C4517EEA25B0E636E0E98F5835E621C429D35B71277B56007F94EDACE20BD16AE97AFDF0A27FEC0319928FF39B06C1430DE481CF6E37802BA5F884272396AEEB2C54C03580709A8B75CF65D9B47D34557FDA3E8352D8C8B21A6ABAF4D2808702DF33B5F4B280B6AB27E3E259ED62D07F694FF98C614C69E1C866FBC9F0F68681D4F10F90AE36D927D64145C1E14190F0BD87C912F995EC8908C80AD151B32381058D67863BD35541BC68163FD54C3DE804433FE145A428DE4B2C0C33EE89EF006621F5A9BB847469BE3853898B1E3CBFF528A94BB7
```

**Comment by slontis** [comment]
Crashes every time for me.. Fix coming up.. The BIGNUM being passed through is uninitialized which means bad things are going to happen. There are a few of these that need fixing. Thanks for finding this.

**Comment by slontis** [comment]
i.e the value of the variable n
passed into EVP_PKEY_get_bn_param(pkey, "n", &n);
must be either a created BN object OR NULL..

**Comment by paulidale** [comment]
@slontis, have a look at #15900 and #15908.
