### ISSUE TITLE
getrandom EAGAIN is not processed correctly

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16631]
The command 
`LD_LIBRARY_PATH=. strace -e inject=getrandom:error=EAGAIN apps/openssl rand -out ./testrand 1024`

causes a double-free with the following stack trace:
```
#0  0x00007f6d1c1aa9e5 in raise () from /lib64/libc.so.6
#1  0x00007f6d1c1938a4 in abort () from /lib64/libc.so.6
#2  0x00007f6d1c1ed007 in __libc_message () from /lib64/libc.so.6
#3  0x00007f6d1c1f4cdc in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f6d1c1f67ac in _int_free () from /lib64/libc.so.6
#5  0x00007f6d1c698820 in cleanup_entropy (outlen=0, out=0xa30490 "\020\017\243", drbg=0x9d32f0) at providers/implementations/rands/drbg.c:259
#6  cleanup_entropy (outlen=0, out=0xa30490 "\020\017\243", drbg=0x9d32f0) at providers/implementations/rands/drbg.c:248
#7  ossl_prov_drbg_instantiate (drbg=0x9d32f0, strength=<optimized out>, prediction_resistance=<optimized out>, pers=<optimized out>, perslen=<optimized out>) at providers/implementations/rands/drbg.c:473
#8  0x00007f6d1c5640a4 in evp_rand_instantiate_locked (params=0x7ffd52b3bcb0, pstr_len=<optimized out>, pstr=0x0, prediction_resistance=0, strength=0, ctx=0x9b9da0) at crypto/evp/evp_rand.c:505
#9  EVP_RAND_instantiate (ctx=ctx@entry=0x9b9da0, strength=strength@entry=0, prediction_resistance=prediction_resistance@entry=0, pstr=pstr@entry=0x0, pstr_len=pstr_len@entry=0, params=params@entry=0x7ffd52b3bcb0)
    at crypto/evp/evp_rand.c:518
#10 0x00007f6d1c5c5d60 in rand_new_drbg (libctx=libctx@entry=0x0, parent=<optimized out>, reseed_interval=<optimized out>, reseed_interval@entry=256, reseed_time_interval=<optimized out>, reseed_time_interval@entry=3600, 
    use_df=<optimized out>, use_df@entry=1) at crypto/rand/rand_lib.c:599
#11 0x00007f6d1c5c685e in RAND_get0_primary (ctx=ctx@entry=0x0) at crypto/rand/rand_lib.c:646
#12 0x00007f6d1c5c6bd8 in RAND_get0_public (ctx=ctx@entry=0x0) at crypto/rand/rand_lib.c:677
#13 0x00007f6d1c5c6c80 in RAND_bytes_ex (ctx=0x0, buf=0x7ffd52b3bee0 "P\003", num=1024, strength=0) at crypto/rand/rand_lib.c:362
#14 0x000000000044d634 in rand_main (argc=<optimized out>, argv=<optimized out>) at apps/rand.c:123
#15 0x0000000000445078 in do_cmd (prog=prog@entry=0x9b0850, argc=argc@entry=4, argv=argv@entry=0x7ffd52b3d0d0) at apps/openssl.c:414
#16 0x0000000000422507 in main (argc=4, argv=0x7ffd52b3d0d0) at apps/openssl.c:295
```

**Comment by beldmit** [comment]
Thanks @tomato42 for the reproducer

**Comment by paulidale** [comment]
I'm not reproducing this locally.  Hmmm....

**Comment by beldmit** [comment]
Just rebuilt from scratch, still reproducable. 
./config shared -ggdb, last commit a7f58bdc1abe245dd09790e8f97d91df271578f4

**Comment by beldmit** [comment]
`LD_LIBRARY_PATH=. strace -e inject=getrandom:error=EAGAIN apps/openssl rand -out ./testrand 1024`
gives the following output:

```
openat(AT_FDCWD, "./testrand", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
futex(0x7fd13d0fe318, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(NULL)                               = 0x1471000
brk(0x1497000)                          = 0x1497000
getpid()                                = 262785
brk(NULL)                               = 0x1497000
brk(0x14b9000)                          = 0x14b9000
brk(NULL)                               = 0x14b9000
brk(0x14de000)                          = 0x14de000
brk(NULL)                               = 0x14de000
brk(0x14ff000)                          = 0x14ff000
getrandom(0x14e4980, 48, 0)             = -1 EAGAIN (Resource temporarily unavailable) (INJECTED)
shmget(0x72, 1, 000)                    = -1 ENOENT (No such file or directory)
uname({sysname="Linux", nodename="myvirt", ...}) = 0
writev(2, [{iov_base="free(): double free detected in "..., iov_len=40}, {iov_base="\n", iov_len=1}], 2free(): double free detected in tcache 2
) = 41
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd13cca1000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 262785
gettid()                                = 262785
tgkill(262785, 262785, SIGABRT)         = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=262785, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
```

**Comment by beldmit** [comment]
Fedora 33, if it matters

**Comment by paulidale** [comment]
I can reproduce it now.  I'm not going to look into it any further today.

**Comment by beldmit** [comment]
Simple reproducer to get rid of strace and made it more debuggable

```
diff --git a/providers/implementations/rands/seeding/rand_unix.c b/providers/implementations/rands/seeding/rand_unix.c
index 750afca58e..753c6e782c 100644
--- a/providers/implementations/rands/seeding/rand_unix.c
+++ b/providers/implementations/rands/seeding/rand_unix.c
@@ -333,6 +333,8 @@ static ssize_t sysctl_random(char *buf, size_t buflen)
  */
 static ssize_t syscall_random(void *buf, size_t buflen)
 {
+    errno = EAGAIN;
+    return -1;
     /*
      * Note: 'buflen' equals the size of the buffer which is used by the
      * get_entropy() callback of the RAND_DRBG. It is roughly bounded by
```

**Comment by beldmit** [comment]
Valgrind output:

```
==270715== Memcheck, a memory error detector
==270715== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==270715== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==270715== Command: apps/openssl rand -out ./testrand 1024
==270715== 
==270715== Invalid free() / delete / delete[] / realloc()
==270715==    at 0x483A9F5: free (vg_replace_malloc.c:538)
==270715==    by 0x4C0C6EF: cleanup_entropy (drbg.c:259)
==270715==    by 0x4C0C6EF: cleanup_entropy (drbg.c:248)
==270715==    by 0x4C0C6EF: ossl_prov_drbg_instantiate (drbg.c:473)
==270715==    by 0x4AD80A3: evp_rand_instantiate_locked (evp_rand.c:505)
==270715==    by 0x4AD80A3: EVP_RAND_instantiate (evp_rand.c:518)
==270715==    by 0x4B39D5F: rand_new_drbg (rand_lib.c:599)
==270715==    by 0x4B3A85D: RAND_get0_primary (rand_lib.c:646)
==270715==    by 0x4B3ABD7: RAND_get0_public (rand_lib.c:677)
==270715==    by 0x4B3AC7F: RAND_bytes_ex (rand_lib.c:362)
==270715==    by 0x44D633: rand_main (rand.c:123)
==270715==    by 0x445077: do_cmd (openssl.c:414)
==270715==    by 0x422506: main (openssl.c:295)
==270715==  Address 0x50bb5f0 is 0 bytes inside a block of size 48 free'd
==270715==    at 0x483A9F5: free (vg_replace_malloc.c:538)
==270715==    by 0x4C00D06: seed_get_seed (seed_src.c:208)
==270715==    by 0x4C0C296: get_entropy (drbg.c:241)
==270715==    by 0x4C0C546: ossl_prov_drbg_instantiate (drbg.c:451)
==270715==    by 0x4AD80A3: evp_rand_instantiate_locked (evp_rand.c:505)
==270715==    by 0x4AD80A3: EVP_RAND_instantiate (evp_rand.c:518)
==270715==    by 0x4B39D5F: rand_new_drbg (rand_lib.c:599)
==270715==    by 0x4B3A85D: RAND_get0_primary (rand_lib.c:646)
==270715==    by 0x4B3ABD7: RAND_get0_public (rand_lib.c:677)
==270715==    by 0x4B3AC7F: RAND_bytes_ex (rand_lib.c:362)
==270715==    by 0x44D633: rand_main (rand.c:123)
==270715==    by 0x445077: do_cmd (openssl.c:414)
==270715==    by 0x422506: main (openssl.c:295)
==270715==  Block was alloc'd at
==270715==    at 0x4839809: malloc (vg_replace_malloc.c:307)
==270715==    by 0x4C00CA7: seed_get_seed (seed_src.c:199)
==270715==    by 0x4C0C296: get_entropy (drbg.c:241)
==270715==    by 0x4C0C546: ossl_prov_drbg_instantiate (drbg.c:451)
==270715==    by 0x4AD80A3: evp_rand_instantiate_locked (evp_rand.c:505)
==270715==    by 0x4AD80A3: EVP_RAND_instantiate (evp_rand.c:518)
==270715==    by 0x4B39D5F: rand_new_drbg (rand_lib.c:599)
==270715==    by 0x4B3A85D: RAND_get0_primary (rand_lib.c:646)
==270715==    by 0x4B3ABD7: RAND_get0_public (rand_lib.c:677)
==270715==    by 0x4B3AC7F: RAND_bytes_ex (rand_lib.c:362)
==270715==    by 0x44D633: rand_main (rand.c:123)
==270715==    by 0x445077: do_cmd (openssl.c:414)
==270715==    by 0x422506: main (openssl.c:295)
==270715== 
8016F60400000000:error:1C8000BD:Provider routines:ossl_prov_drbg_instantiate:error retrieving entropy:providers/implementations/rands/drbg.c:456:
8016F60400000000:error:1200006C:random number generator:rand_new_drbg:error instantiating drbg:crypto/rand/rand_lib.c:600:
```
