### ISSUE TITLE
heap-buffer-overflow error produced with AddressSanitizer of test_eai_data file.

### ISSUE THREAD

**Issue by qd1332543** [openssl/openssl#16717]
A heap-buffer-overflow error produced with AddressSanitizer
This error occurs in the test phase after the compilation is successful.

The environment:
**OS**: Windows Server 2016 1607
**Compiler**: msvc 14.29.30133
**OpenSSL**: latest commit (398ae82) 

For other issues:
**The AddressSanitizer Error:**
```
==11500==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x02d39598 at pc 0x706587af bp 0x00b6fabc sp 0x00b6fab0
READ of size 4 at 0x02d39598 thread T0
    #0 0x706587ae in do_check_string F:\gitP\openssl\openssl\crypto\x509\v3_utl.c:827
    #1 0x70658d03 in do_x509_check F:\gitP\openssl\openssl\crypto\x509\v3_utl.c:932
    #2 0x3276d3 in do_cmd F:\gitP\openssl\openssl\apps\openssl.c:414
    #3 0x327ef3 in main F:\gitP\openssl\openssl\apps\openssl.c:293
    #4 0x372d4a in _scrt_common_main_seh d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #5 0x762562c3  (C:\Windows\System32\KERNEL32.DLL+0x6b8162c3)
    #6 0x77881b68  (C:\Windows\SYSTEM32\ntdll.dll+0x4b2e1b68)
    #7 0x77881b33  (C:\Windows\SYSTEM32\ntdll.dll+0x4b2e1b33)
0x02d39598 is located 0 bytes to the right of 8-byte region [0x02d39590,0x02d39598)
allocated by thread T0 here:
    #0 0x6fdee475  (C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\clang_rt.asan_dynamic-i386.dll+0x1003e475)
    #1 0x7059367b in CRYPTO_zalloc F:\gitP\openssl\openssl\crypto\mem.c:191
    #2 0x70430f5a in asn1_template_noexp_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:672
    #3 0x704309bb in asn1_template_ex_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:558
    #4 0x7042fdfe in asn1_item_embed_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:298
    #5 0x70430e03 in asn1_template_noexp_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:651
    #6 0x704309bb in asn1_template_ex_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:558
    #7 0x7042fa54 in asn1_item_embed_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:214
    #8 0x7042df3b in ASN1_item_d2i_ex F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:145
    #9 0x7042de38 in ASN1_item_d2i F:\gitP\openssl\openssl\crypto\asn1\tasn_dec.c:154
    #10 0x7065de87 in X509_get_ext_d2i F:\gitP\openssl\openssl\crypto\x509\x509_ext.c:104
    #11 0x3276d3 in do_cmd F:\gitP\openssl\openssl\apps\openssl.c:414
    #12 0x327ef3 in main F:\gitP\openssl\openssl\apps\openssl.c:293
    #13 0x372d4a in _scrt_common_main_seh d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #14 0x762562c3  (C:\Windows\System32\KERNEL32.DLL+0x6b8162c3)
    #15 0x77881b68  (C:\Windows\SYSTEM32\ntdll.dll+0x4b2e1b68)
    #16 0x77881b33  (C:\Windows\SYSTEM32\ntdll.dll+0x4b2e1b33)
SUMMARY: AddressSanitizer: heap-buffer-overflow F:\gitP\openssl\openssl\crypto\x509\v3_utl.c:827 in do_check_string
Shadow bytes around the buggy address:
  0x305a7260: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x305a7270: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x305a7280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x305a7290: fa fa fa fa fa fa 01 fa fa fa 00 fa fa fa 00 02
  0x305a72a0: fa fa 00 00 fa fa 00 fa fa fa 00 00 fa fa 00 fa
=>0x305a72b0: fa fa 00[fa]fa fa 00 fa fa fa 00 02 fa fa 00 00
  0x305a72c0: fa fa 00 fa fa fa 00 00 fa fa 00 fa fa fa 00 fa
  0x305a72d0: fa fa 00 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x305a72e0: fa fa fd fa fa fa 00 02 fa fa 00 00 fa fa 00 fa
  0x305a72f0: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa 00 fa
  0x305a7300: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11500==ABORTING
C:\Strawberry\perl\bin\perl.exe ..\..\util\wrap.pl ..\..\apps\openssl.exe verify -CAfile ..\..\test\certs\bad-othername-namec.pem -partial_chain -no_check_time -verify_email foo@example.com ..\..\test\certs\bad-othername-namec.pem => 1
not ok 12
# ------------------------------------------------------------------------------
#   Failed test at test\recipes\25-test_eai_data.t line 66.
# Looks like you failed 1 test of 12.25-test_eai_data.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests 
```
For other error messages, please refer to the attached file: [test_02_log.txt](https://github.com/openssl/openssl/files/7255959/test_02_log.txt)

**Operation steps：**
1. perl Configure VC-WIN32
2. nmake clean
3. where cl.exe
4. nmake
5. nmake test

**Comment by t8m** [comment]
Is this still relevant?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by davidben** [comment]
I believe this can now be closed. This was the ASan report referenced in https://openssl-library.org/news/secadv/20240903.txt

**Comment by t8m** [comment]
Yes, closing. Thank you again @davidben for the heads up.
