### ISSUE TITLE
crash in dasync engine/rsa cipher

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#16724]
Steps to reproduce the crash in e_dasync.c
```
OPENSSL_ENGINES=../engines
OPENSSL_CONF=test.conf

$ cat test.conf 
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_config

[ssl_config]
server = server_conf
client = client_conf

[server_conf]
Options = -EncryptThenMac

[client_conf]
Options = -EncryptThenMac

../util/shlib_wrap.sh ./openssl s_server -engine dasync -ssl_config server -cipher "AES128-SHA:@SECLEVEL=0" -tls1 

../util/shlib_wrap.sh ./openssl s_client -engine dasync -ssl_config client -cipher "AES128-SHA:@SECLEVEL=0" -tls1
Engine "dasync" set.
Connecting to ::1
CONNECTED(00000003)
depth=0 CN=server.example
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=server.example
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=server.example
verify return:1
Segmentation fault (core dumped)
```

this crashes in the client:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff6a4b9b3 in dasync_rsa_encrypt_init (ctx=0x7c99f0)
    at engines/e_dasync.c:868
#2  0x00007ffff762b750 in evp_pkey_asym_cipher_init (ctx=0x7c99f0, 
    operation=512, params=0x0) at crypto/evp/asymcipher.c:145
#3  0x00007ffff762b812 in EVP_PKEY_encrypt_init (ctx=0x7c99f0)
    at crypto/evp/asymcipher.c:167
#4  0x00007ffff7b95ee9 in tls_construct_cke_rsa (s=0x7b7a30, 
    pkt=0x7fffffffd270) at ssl/statem/statem_clnt.c:2861
#5  0x00007ffff7b97491 in tls_construct_client_key_exchange (s=0x7b7a30, 
    pkt=0x7fffffffd270) at ssl/statem/statem_clnt.c:3287
#6  0x00007ffff7b8e606 in write_state_machine (s=0x7b7a30)
    at ssl/statem/statem.c:852
#7  0x00007ffff7b8d91b in state_machine (s=0x7b7a30, server=0)
    at ssl/statem/statem.c:451
#8  0x00007ffff7b8d36e in ossl_statem_connect (s=0x7b7a30)
    at ssl/statem/statem.c:265
#9  0x00007ffff7b70d66 in ssl3_write_bytes (s=0x7b7a30, type=23, 
    buf_=0x704870, len=0, written=0x7fffffffd5d8)
    at ssl/record/rec_layer_s3.c:403
#10 0x00007ffff7b3bbb5 in ssl3_write (s=0x7b7a30, buf=0x704870, len=0, 
    written=0x7fffffffd5d8) at ssl/s3_lib.c:4428
#11 0x00007ffff7b4c51e in ssl_write_internal (s=0x7b7a30, buf=0x704870, num=0, 
```

but it will crash in the server when the client uses no dasync engine:
```
#1  0x00007ffff6a4ba5a in dasync_rsa_decrypt_init (ctx=0x7c8950) at engines/e_dasync.c:890
#2  0x00007ffff762b788 in evp_pkey_asym_cipher_init (ctx=0x7c8950, operation=1024, params=0x0) at crypto/evp/asymcipher.c:150
#3  0x00007ffff762bace in EVP_PKEY_decrypt_init (ctx=0x7c8950) at crypto/evp/asymcipher.c:209
#4  0x00007ffff7ba8777 in tls_process_cke_rsa (s=0x7ce510, pkt=0x7fffffffd550) at ssl/statem/statem_srvr.c:2909
#5  0x00007ffff7ba9c3a in tls_process_client_key_exchange (s=0x7ce510, pkt=0x7fffffffd550) at ssl/statem/statem_srvr.c:3306
#6  0x00007ffff7ba390c in ossl_statem_server_process_message (s=0x7ce510, pkt=0x7fffffffd550) at ssl/statem/statem_srvr.c:1199
#7  0x00007ffff7b8dec3 in read_state_machine (s=0x7ce510) at ssl/statem/statem.c:647
#8  0x00007ffff7b8d8db in state_machine (s=0x7ce510, server=1) at ssl/statem/statem.c:442
#9  0x00007ffff7b8d38d in ossl_statem_accept (s=0x7ce510) at ssl/statem/statem.c:270
#10 0x00007ffff7b501c5 in SSL_do_handshake (s=0x7ce510) at ssl/ssl_lib.c:3893
#11 0x00007ffff7b4ba2e in SSL_accept (s=0x7ce510) at ssl/ssl_lib.c:1735
#12 0x000000000046ca2e in init_ssl_connection (con=0x7ce510) at apps/s_server.c:2838
#13 0x000000000046c511 in sv_body (s=4, stype=1, prot=0, context=0x0) at apps/s_server.c:2702
#14 0x0000000000499d7b in do_server (accept_sock=0x6e7580 <accept_socket>, host=0x0, port=0x704710 "4433", family=0, type=1, protocol=0, 
    cb=0x46b34c <sv_body>, context=0x0, naccept=-1, bio_s_out=0x715e10) at apps/lib/s_socket.c:386
#15 0x000000000046ae04 in s_server_main (argc=0, argv=0x7fffffffde80) at apps/s_server.c:2231
#16 0x000000000044c849 in do_cmd (prog=0x702c40, argc=8, argv=0x7fffffffde80) at apps/openssl.c:414
#17 0x000000000044c481 in main (argc=8, argv=0x7fffffffde80) at apps/openssl.c:295
```

**Comment by beldmit** [comment]
Now it looks like a duplicate of #16738
