### ISSUE TITLE
Mem leak in s_client

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#16737]
#16392 introduced a mem leak in s_client:

````
=================================================================
==59912==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4b49ad in malloc (/home/matt/dev/openssl-write/apps/openssl+0x4b49ad)
    #1 0x7f351e61bdfb in CRYPTO_malloc /home/matt/dev/openssl-write/crypto/mem.c:184:12
    #2 0x7f351e61efdf in CRYPTO_strdup /home/matt/dev/openssl-write/crypto/o_str.c:24:11
    #3 0x7f351e28f333 in addr_strings /home/matt/dev/openssl-write/crypto/bio/bio_addr.c:246:25
    #4 0x7f351e28ee26 in BIO_ADDR_hostname_string /home/matt/dev/openssl-write/crypto/bio/bio_addr.c:281:9
    #5 0x5f5762 in init_client /home/matt/dev/openssl-write/apps/lib/s_socket.c:175:47
    #6 0x5738ce in s_client_main /home/matt/dev/openssl-write/apps/s_client.c:2010:9
    #7 0x540fe0 in do_cmd /home/matt/dev/openssl-write/apps/openssl.c:415:16
    #8 0x540769 in main /home/matt/dev/openssl-write/apps/openssl.c:295:11
    #9 0x7f351dc220b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
````

The function `BIO_ADDR_hostname_string` allocated memory that must be freed.

**Comment by t8m** [comment]
Already fixed by #16688
