### ISSUE TITLE
crash in tls1_cbc_remove_padding_and_mac with aes-cbc-hmac-sha cipher

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#16795]
This was fixed in master by #16693 but still open in 3.0 branch:
```
OPENSSL_ENGINES=../engines
OPENSSL_CONF=test.conf

$ cat test.conf 
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_config

[ssl_config]
server = server_conf
client = client_conf

[server_conf]
Options = -EncryptThenMac

[client_conf]
Options = -EncryptThenMac

../util/shlib_wrap.sh ./openssl s_server -engine dasync -ssl_config server -cipher "ECDHE-ECDSA-AES128-SHA:@SECLEVEL=0" -tls1 -cert ../test/certs/p256-server-cert.pem -key ../test/certs/p256-server-key.pem

../util/shlib_wrap.sh ./openssl s_client -engine dasync -ssl_config client -cipher "ECDHE-ECDSA-AES128-SHA:@SECLEVEL=0" -tls1

server will crash here:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b7bd59 in tls1_cbc_remove_padding_and_mac (reclen=0x7c5860, 
    origreclen=48, recdata=0x7cb8d8 "\024", mac=0x0, alloced=0x0, 
    block_size=16, mac_size=0, aead=1, libctx=0x0) at ssl/record/tls_pad.c:141
141	            *mac = NULL;
(gdb) bt
#0  0x00007ffff7b7bd59 in tls1_cbc_remove_padding_and_mac (reclen=0x7c5860, 
    origreclen=48, recdata=0x7cb8d8 "\024", mac=0x0, alloced=0x0, 
    block_size=16, mac_size=0, aead=1, libctx=0x0) at ssl/record/tls_pad.c:141
#1  0x00007ffff7b7944f in tls1_enc (s=0x7c45b0, recs=0x7c5858, n_recs=1, 
    sending=0, macs=0x0, macsize=0) at ssl/record/ssl3_record.c:1250
#2  0x00007ffff7b76a2c in ssl3_get_record (s=0x7c45b0)
    at ssl/record/ssl3_record.c:575
#3  0x00007ffff7b739fa in ssl3_read_bytes (s=0x7c45b0, type=22, 
    recvd_type=0x7fffffffd47c, buf=0x7c6370 "\001", len=4, peek=0, 
    readbytes=0x7fffffffd488) at ssl/record/rec_layer_s3.c:1348
#4  0x00007ffff7b9f05c in tls_get_message_header (s=0x7c45b0, 
    mt=0x7fffffffd4c0) at ssl/statem/statem_lib.c:1168
#5  0x00007ffff7b8dbf6 in read_state_machine (s=0x7c45b0)
    at ssl/statem/statem.c:587
#6  0x00007ffff7b8d866 in state_machine (s=0x7c45b0, server=1)
    at ssl/statem/statem.c:442
#7  0x00007ffff7b8d318 in ossl_statem_accept (s=0x7c45b0)
    at ssl/statem/statem.c:270
#8  0x00007ffff7b50150 in SSL_do_handshake (s=0x7c45b0) at ssl/ssl_lib.c:3893
#9  0x00007ffff7b4b9b9 in SSL_accept (s=0x7c45b0) at ssl/ssl_lib.c:1735
#10 0x000000000046c8fa in init_ssl_connection (con=0x7c45b0)
    at apps/s_server.c:2820
#11 0x000000000046c3dd in sv_body (s=4, stype=1, prot=0, context=0x0)
```

**Comment by bernd-edlinger** [comment]
OK Done.
