### ISSUE TITLE
[3.0.0] Multiple test failures on HP-UX 32bit

### ISSUE THREAD

**Issue by robmcgee-mag** [openssl/openssl#17067]
Hey guys,
We've got another issue with some HP-UX tests using the native compiler with a 32bit build. 64bit passes all tests on the same machine. I have tried to reduce compiler optimization to +O1 to no avail.

**Failing tests:**
```
Test Summary Report
-------------------
20-test_enc_more.t               (Wstat: 256 Tests: 137 Failed: 1)
  Failed test:  87
  Non-zero exit status: 1
30-test_evp.t                    (Wstat: 256 Tests: 103 Failed: 1)
  Failed test:  72
  Non-zero exit status: 1
30-test_evp_extra.t              (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
30-test_evp_libctx.t             (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
80-test_dtls_mtu.t               (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
80-test_ssl_new.t                (Wstat: 256 Tests: 30 Failed: 1)
  Failed test:  25
  Non-zero exit status: 1
80-test_ssl_old.t                (Wstat: 512 Tests: 11 Failed: 2)
  Failed tests:  3-4
  Non-zero exit status: 2
80-test_sslcorrupt.t             (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
90-test_bio_enc.t                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
90-test_sslapi.t                 (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=240, Tests=3375, 2331 wallclock secs (20.81 usr  2.37 sys + 1765.58 cusr 376.51 csys = 2165.27 CPU)
Result: FAIL
Makefile:1532: recipe for target 'run_tests' failed
gmake[1]: *** [run_tests] Error 1
```
**Build config:**
```
Command line (with current working directory = .):
    /opt/perl64/bin/perl ./Configure --prefix=/bamboo/hpux11_3/acc06_28/release32 hpux-ia64-cc shared enable-fips
Perl information:
    /opt/perl64/bin/perl
    5.20.1 for IA64.ARCHREV_0-thread-multi-LP64-ld
Enabled features:
    acvp-tests
    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    fips
    fips-securitychecks
    gost
    idea
    legacy
    loadereng
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method
Disabled features:
    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG
    asan                [default]        OPENSSL_NO_ASAN
    buildtest-c++       [default]
    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]        OPENSSL_NO_EGD
    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS
    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    ktls                [default]        OPENSSL_NO_KTLS
    makedepend          [unavailable]
    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]        OPENSSL_NO_MSAN
    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]        OPENSSL_NO_SCTP
    trace               [default]        OPENSSL_NO_TRACE
    ubsan               [default]        OPENSSL_NO_UBSAN
    unit-test           [default]        OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]
    zlib-dynamic        [default]
    ssl3                [default]        OPENSSL_NO_SSL3
    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD
Config target attributes:
    AR => "ar",
    ARFLAGS => "qc",
    CC => "cc",
    CFLAGS => "+O2",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    asm_arch => "ia64",
    bin_lflags => "-Wl,+s,+cdp,../:,+cdp,./:",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-Ae +DD32 +Olit=all -z",
    cppflags => "-D_REENTRANT",
    defines => [ "OPENSSL_BUILDING_OPENSSL", "_XOPEN_SOURCE", "_XOPEN_SOURCE_EXTENDED", "_HPUX_ALT_XOPEN_SOCKET_API" ],
    disable => [  ],
    dso_scheme => "dlfcn",
    enable => [  ],
    ex_libs => "-ldl -lpthread",
    includes => [  ],
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DB_ENDIAN",
    lib_defines => [  ],
    module_cflags => "+Z",
    module_cxxflags => undef,
    module_ldflags => "-b -Wl,-B,symbolic,+vnocompatwarnings,-z,+s,+cdp,../:,+cdp,./:",
    multilib => "/hpux32",
    perl_platform => "Unix",
    perlasm_scheme => "void",
    shared_cflag => "+Z",
    shared_defines => [  ],
    shared_ldflag => "-b -Wl,-B,symbolic,+vnocompatwarnings,-z,+s,+cdp,../:,+cdp,./:",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,+h,",
    shared_target => "self",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",
Recorded environment:
    AR =
    ARFLAGS =
    AS =
    ASFLAGS =
    BUILDFILE =
    CC =
    CFLAGS =
    CPP =
    CPPDEFINES =
    CPPFLAGS =
    CPPINCLUDES =
    CROSS_COMPILE =
    CXX =
    CXXFLAGS =
    HASHBANGPERL =
    LD =
    LDFLAGS =
    LDLIBS =
    MT =
    MTFLAGS =
    OPENSSL_LOCAL_CONFIG_DIR =
    PERL =
    RANLIB =
    RC =
    RCFLAGS =
    RM =
    WINDRES =
    __CNF_CFLAGS =
    __CNF_CPPDEFINES =
    __CNF_CPPFLAGS =
    __CNF_CPPINCLUDES =
    __CNF_CXXFLAGS =
    __CNF_LDFLAGS =
    __CNF_LDLIBS =
Makevars:
    AR              = ar
    ARFLAGS         = qc
    CC              = cc
    CFLAGS          = +O2
    CPPDEFINES      =
    CPPFLAGS        =
    CPPINCLUDES     =
    CXXFLAGS        =
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         =
    LDLIBS          =
    PERL            = /opt/perl64/bin/perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         =
NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile
build file:
    Makefile
build file templates:
    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
```

**Verbose test logs:**

```
../../util/wrap.pl ../../apps/openssl enc -chacha20 -k test -provider-path ../../providers -provider default -provider legacy -e -in ./testdatafile -out ./testdatafile.chacha20.cipher => 139
not ok 87 - chacha20

#   Failed test 'chacha20'
#   at test/recipes/20-test_enc_more.t line 60.
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
../../util/wrap.pl ../../apps/openssl enc -des -k test -provider-path ../../providers -provider default -provider legacy -e -in ./testdatafile -out ./testdatafile.des.cipher => 0
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
../../util/wrap.pl ../../apps/openssl enc -des -k test -provider-path ../../providers -provider default -provider legacy -d -in ./testdatafile.des.cipher -out ./testdatafile.des.clear => 0
```

```
../../util/wrap.pl ../../test/evp_test -config ../../test/default-and-legacy.cnf ../../test/recipes/30-test_evp_data/evpciph_chacha.txt => 139
not ok 72 - running evp_test -config ../../test/default-and-legacy.cnf evpciph_chacha.txt

#   Failed test 'running evp_test -config ../../test/default-and-legacy.cnf evpciph_chacha.txt'
#   at test/recipes/30-test_evp.t line 140.
    # Subtest: ../../test/evp_test
```

```
../../util/wrap.pl ../../test/evp_extra_test => 139
not ok 1 - running evp_extra_test

#   Failed test 'running evp_extra_test'
#   at test/recipes/30-test_evp_extra.t line 19.
    # Subtest: ../../test/evp_extra_test
    1..42
```

```
../../util/wrap.pl ../../test/evp_extra_test -context => 139
not ok 2 - running evp_extra_test with a non-default library context

#   Failed test 'running evp_extra_test with a non-default library context'
#   at test/recipes/30-test_evp_extra.t line 22.
    # Subtest: ../../test/evp_extra_test2
    1..9
```

```
../../util/wrap.pl ../../test/evp_libctx_test -config ../../test/default.cnf => 139
not ok 2 - running default evp_libctx_test

#   Failed test 'running default evp_libctx_test'
#   at test/recipes/30-test_evp_libctx.t line 37.
    # Subtest: ../../test/evp_libctx_test
    1..9
```

```
../../util/wrap.pl ../../test/evp_libctx_test -config ../../test/default-and-legacy.cnf => 139
not ok 3 - running default-and-legacy evp_libctx_test

#   Failed test 'running default-and-legacy evp_libctx_test'
#   at test/recipes/30-test_evp_libctx.t line 41.
# Looks like you failed 2 tests of 3.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests
```

```
# The results of this test will end up in test-runs/test_dtls_mtu
1..1
    # Subtest: ../../test/dtls_mtu_test
    1..1
    # INFO:  @ test/dtls_mtu_test.c:176
    # PSK-AES256-GCM-SHA384 OK
../../util/wrap.pl ../../test/dtls_mtu_test => 139
not ok 1 - running dtls_mtu_test

#   Failed test 'running dtls_mtu_test'
#   at test/recipes/80-test_dtls_mtu.t line 21.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

```
../../util/wrap.pl ../../test/ssl_test 25-cipher.cnf.none none => 139
    not ok 3 - running ssl_test 25-cipher.cnf

    #   Failed test 'running ssl_test 25-cipher.cnf'
    #   at test/recipes/80-test_ssl_new.t line 171.
../../util/wrap.pl /opt/perl64/bin/perl -I ../../util/perl ../../test/generate_ssl_tests.pl ../../test/ssl-tests/25-cipher.cnf.in default > 25-cipher.cnf.default => 0
    ok 4 - Getting output from generate_ssl_tests.pl.
    ok 5 # skip Skipping generated source test for 25-cipher.cnf
        # Subtest: ../../test/ssl_test
        1..1
            # Subtest: test_handshake
            1..9
            ok 1 - iteration 1
            ok 2 - iteration 2
            ok 3 - iteration 3
            ok 4 - iteration 4
            ok 5 - iteration 5
            ok 6 - iteration 6
            ok 7 - iteration 7
            ok 8 - iteration 8
../../util/wrap.pl ../../test/ssl_test 25-cipher.cnf.default default => 139
    not ok 6 - running ssl_test 25-cipher.cnf

    #   Failed test 'running ssl_test 25-cipher.cnf'
    #   at test/recipes/80-test_ssl_new.t line 171.
../../util/wrap.pl /opt/perl64/bin/perl -I ../../util/perl ../../test/generate_ssl_tests.pl ../../test/ssl-tests/25-cipher.cnf.in fips > 25-cipher.cnf.fips => 0
    ok 7 - Getting output from generate_ssl_tests.pl.
    ok 8 # skip Skipping generated source test for 25-cipher.cnf
        # Subtest: ../../test/ssl_test
        1..1
            # Subtest: test_handshake
            1..8
            ok 1 - iteration 1
            ok 2 - iteration 2
            ok 3 - iteration 3
            ok 4 - iteration 4
            ok 5 - iteration 5
            ok 6 - iteration 6
            ok 7 - iteration 7
            ok 8 - iteration 8
        ok 1 - test_handshake
../../util/wrap.pl ../../test/ssl_test 25-cipher.cnf.fips fips ../../test/fips-and-base.cnf => 0
    ok 9 - running ssl_test 25-cipher.cnf
    # Looks like you failed 2 tests of 9.
not ok 25 - Test configuration 25-cipher.cnf

#   Failed test 'Test configuration 25-cipher.cnf'
#   at /localhome/bamboo/bamboo-agent-home/xml-data/build-dir/ThirdParty/openssl/3.0.0/_src/openssl-3.0.0-src/openssl-3.0.0/util/perl/OpenSSL/Test.pm line 1296.
# Subtest: Test configuration 26-tls13_client_auth.cnf
    1..9
../../util/wrap.pl /opt/perl64/bin/perl -I ../../util/perl ../../test/generate_ssl_tests.pl ../../test/ssl-tests/26-tls13_client_auth.cnf.in none > 26-tls13_client_auth.cnf.none => 0
```

```
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher 'ECDHE-ECDSA-CHACHA20-POLY1305:@SECLEVEL=0' -ciphersuites '' -tls1_2 => 139
    not ok 36 - Testing ECDHE-ECDSA-CHACHA20-POLY1305:@SECLEVEL=0

    #   Failed test 'Testing ECDHE-ECDSA-CHACHA20-POLY1305:@SECLEVEL=0'
    #   at test/recipes/80-test_ssl_old.t line 497.
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher 'ECDHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0' -ciphersuites '' -tls1_2 => 139
    not ok 37 - Testing ECDHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0

    #   Failed test 'Testing ECDHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0'
    #   at test/recipes/80-test_ssl_old.t line 497.
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher 'DHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0' -ciphersuites '' -tls1_2 => 139
    not ok 38 - Testing DHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0

    #   Failed test 'Testing DHE-RSA-CHACHA20-POLY1305:@SECLEVEL=0'
    #   at test/recipes/80-test_ssl_old.t line 497.
Doing handshakes=1 bytes=256
TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES256-CCM8, 256 bits EC (prime256v1), temp key: 253 bits X25519, digest=SHA256
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher 'ECDHE-ECDSA-AES256-CCM8:@SECLEVEL=0' -ciphersuites '' -tls1_2 => 0
```

```
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites TLS_CHACHA20_POLY1305_SHA256 => 139
    not ok 121 - Testing

    #   Failed test 'Testing '
    #   at test/recipes/80-test_ssl_old.t line 497.
Doing handshakes=1 bytes=256
TLSv1.3, cipher TLSv1.3 TLS_AES_128_GCM_SHA256, 256 bits EC (prime256v1), temp key: 253 bits X25519, digest=SHA256
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -s_cert certD.ss -s_key keyD.ss -s_cert certE.ss -s_key keyE.ss -cipher '' -ciphersuites TLS_AES_128_GCM_SHA256 => 0
    ok 122 - Testing
    # Looks like you failed 4 tests of 122.
not ok 3 - Testing ciphersuites

#   Failed test 'Testing ciphersuites'
#   at /localhome/bamboo/bamboo-agent-home/xml-data/build-dir/ThirdParty/openssl/3.0.0/_src/openssl-3.0.0-src/openssl-3.0.0/util/perl/OpenSSL/Test.pm line 1296.
# Subtest: RSA/(EC)DHE/PSK tests
    1..6
Doing handshakes=10 bytes=256
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
DONE via BIO pair: TLSv1, cipher SSLv3 ADH-AES256-SHA, temp key: 1024 bits DH
Approximate total server time:   0.10 s
Approximate total client time:   0.08 s
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -v -bio_pair -tls1 -cipher ADH -dhe1024dsa -num 10 -f -time => 0
```

```
../../util/wrap.pl ../../test/ssl_old_test -psk 0102030405 -cipher '@SECLEVEL=2:DHE-PSK-AES128-CCM' => 139
    not ok 6 - test auto DH meets security strength

    #   Failed test 'test auto DH meets security strength'
    #   at test/recipes/80-test_ssl_old.t line 566.
    # Looks like you failed 1 test of 6.
not ok 4 - RSA/(EC)DHE/PSK tests

#   Failed test 'RSA/(EC)DHE/PSK tests'
#   at /localhome/bamboo/bamboo-agent-home/xml-data/build-dir/ThirdParty/openssl/3.0.0/_src/openssl-3.0.0-src/openssl-3.0.0/util/perl/OpenSSL/Test.pm line 1296.
# Subtest: Custom Extension tests
    1..1
Doing handshakes=1 bytes=256
TLSv1, cipher TLSv1.0 ECDHE-RSA-AES256-SHA, 2048 bits RSA, temp key: 253 bits X25519, digest=MD5-SHA1
../../util/wrap.pl ../../test/ssl_old_test -s_key ../../test/certs/ee-key.pem -s_cert certU.ss -c_key ../../test/certs/ee-key.pem -c_cert certU.ss -config ../../test/default-and-legacy.cnf -provider default -provider legacy -bio_pair -tls1 -custom_ext => 0
```

```
../../util/wrap.pl ../../test/sslcorrupttest ../../apps/server.pem ../../apps/server.pem => 139
not ok 1 - running sslcorrupttest

#   Failed test 'running sslcorrupttest'
#   at test/recipes/80-test_sslcorrupt.t line 19.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

```
not ok 1 - running bio_enc_test

#   Failed test 'running bio_enc_test'
#   at /localhome/bamboo/bamboo-agent-home/xml-data/build-dir/ThirdParty/openssl/3.0.0/_src/openssl-3.0.0-src/openssl-3.0.0/util/perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

```
not ok 1 - running sslapitest

#   Failed test 'running sslapitest'
#   at test/recipes/90-test_sslapi.t line 32.
    # Subtest: ../../test/sslapitest
```

I hope these are some use to you, some don't seem to give much detail when using verbose logging.
As always, any help is appreciated. :)

**Comment by paulidale** [comment]
There should be information **before** the failure message that provides the failure details.

**Comment by robmcgee-mag** [comment]
My bad, the output is a bit too verbose to make sense of. Here's the raw output:
[testoutput.txt](https://github.com/openssl/openssl/files/7566730/testoutput.txt)

**Comment by mattcaswell** [comment]
Looks like things are crashing with a common "chacha" theme. Possibly other issues. As an example:

````
../../util/wrap.pl ../../apps/openssl enc -chacha20 -k test -provider-path ../../providers -provider default -provider legacy -e -in ./testdatafile -out ./testdatafile.chacha20.cipher => 139
not ok 87 - chacha20
````

139 is typical of a segfault. Can you try the above "enc" command directly and see if you can replicate the crash?

**Comment by robmcgee-mag** [comment]
Yes, I get a core dump but it looks like it could be corrupted?
```
-bash-4.4$ pwd
/localhome/bamboo/bamboo-agent-home/xml-data/build-dir/ThirdParty/openssl/3.0.0/_src/openssl-3.0.0-src/openssl-3.0.0/test-runs/test_evp_more
-bash-4.4$ ../../util/wrap.pl ../../apps/openssl enc -chacha20 -k test -provider-path ../../providers -provider default -provider legacy -e -in ./testdatafile -out ./testdatafile.chacha20.cipher
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
-bash-4.4$ gdb -e ../../apps/openssl -c core
HP gdb 6.5 for HP Itanium (32 or 64 bit) and target HP-UX 11iv2 and 11iv3.
Copyright 1986 - 2011 Free Software Foundation, Inc.
Hewlett-Packard Wildebeest 6.5 (based on GDB) is covered by the
GNU General Public License. Type "show copying" to see the conditions to
change it and/or distribute copies. Type "show warranty" for warranty/support.


warning: Unknown symbols for 'core'; use the 'symbol-file' command.
Core was generated by `openssl'.
Program terminated with signal 11, Segmentation fault.
SEGV_MAPERR - Address not mapped to object
#0  0x60000000c62c8890 in <unknown_procedure> ()
(gdb) symbol-file
No symbol file now.
(gdb) bt
#0  0x60000000c62c8890 in <unknown_procedure> ()
warning: Attempting to unwind past bad PC 0x60000000c62c8890
#1  0x60000000c668db90 in <unknown_procedure> ()
(gdb)
```

**Comment by scott-zhong** [comment]
@mattcaswell I have reproduce this crash on HPUX 32-bit.  I used gdb to look into the core file and this is the stack trace.

```
$ ../../apps/openssl enc -chacha20 -k test -provider-path ../../providers -provider default -provider legacy -e -in ./testdatafile -out ./testdatafile.chacha20.cipher
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
Segmentation fault (core dumped)
$ gdb ../../apps/openssl  core
HP gdb 6.7 for HP Itanium (32 or 64 bit) and target HP-UX 11iv2 and 11iv3.
Copyright 1986 - 2011 Free Software Foundation, Inc.
Hewlett-Packard Wildebeest 6.7 (based on GDB) is covered by the
GNU General Public License. Type "show copying" to see the conditions to
change it and/or distribute copies. Type "show warranty" for warranty/support.
..
Core was generated by `openssl'.
Program terminated with signal 11, Segmentation fault.
SEGV_MAPERR - Address not mapped to object
#0  0x60000000c8008d70:0 in ChaCha20_ctr32+0x4b0 ()
   from /build/scottz/openssl-3.0.1-hpux-ipf32/libcrypto.so.3
(gdb) where
#0  0x60000000c8008d70:0 in ChaCha20_ctr32+0x4b0 ()
   from /build/scottz/openssl-3.0.1-hpux-ipf32/libcrypto.so.3
#1  0x60000000c8008000:0 in chacha20_cipher ()
    at ../openssl-3.0.1/providers/implementations/ciphers/cipher_chacha20_hw.c:89
#2  0x60000000c7fb1d30:0 in ossl_cipher_generic_stream_update ()
    at ../openssl-3.0.1/providers/implementations/ciphers/ciphercommon.c:469
#3  0x60000000c7fd1460:0 in EVP_EncryptUpdate ()
    at ../openssl-3.0.1/crypto/evp/evp_enc.c:628
#4  0x60000000c804b230:0 in EVP_CipherUpdate ()
    at ../openssl-3.0.1/crypto/evp/evp_enc.c:404
#5  0x60000000c81b7ca0:0 in enc_write ()
    at ../openssl-3.0.1/crypto/evp/bio_enc.c:266
#6  0x60000000c80c9c10:0 in bwrite_conv ()
    at ../openssl-3.0.1/crypto/bio/bio_meth.c:77
#7  0x60000000c7e4fbe0:0 in bio_write_intern ()
    at ../openssl-3.0.1/crypto/bio/bio_lib.c:362
#8  0x60000000c7e4fa30:0 in BIO_write ()
    at ../openssl-3.0.1/crypto/bio/bio_lib.c:381
#9  0x40c5000:0 in enc_main () at ../openssl-3.0.1/apps/enc.c:612
#10 0x40d0c60:0 in do_cmd () at ../openssl-3.0.1/apps/openssl.c:417
#11 0x406fde0:0 in main () at ../openssl-3.0.1/apps/openssl.c:311
```

**Comment by scott-zhong** [comment]
@t8m Yes, configure with no-asm make test passes.

**Comment by t8m** [comment]
Are the crashes only in Chacha20 or also in other assembler implementations? One option would be to just disable the chacha20 asm implementation on 32bit Itanium.

**Comment by scott-zhong** [comment]
@t8m Chacha20 was the one that crashes but there were other test failures that I had also reproduced (noted in the issue description).  These test failures do not occur when `no-asm` option was used in configure.

**Comment by johnkohl-hcl** [comment]
I've been able to build OpenSSL 3.0.9 with just chacha assembly disabled for HPUX 32-bit (native HP compiler) builds, and all tests are passing.  Other assembly code seems to work (passes tests at least).

What's a good way to separate out this one assembly module?  I did this, roughly:

* used a new asm_arch, something like `ia64_hpux32`
* updated all the assembly configurations in various build.info files to have definitions for xxx_ia64_hpux32 that are identical to regular xxx_ia64
* except for crypto/chacha/build.info, where I did *not* define `$CHACHAASM_ia64_hpux32`

But maybe there's a better way?  Some way to do inheritance/override of the assembly architecture?

**Comment by t8m** [comment]
Please submit a PR, we can discuss it there.

**Comment by bernd-edlinger** [comment]
I looked at the other (working) ia64 assembly sources for a while,
and think I see a difference here, but have no way to try it out.
Could you try this out for me?
```
--- a/crypto/chacha/asm/chacha-ia64.pl
+++ b/crypto/chacha/asm/chacha-ia64.pl
@@ -46,6 +46,8 @@ ChaCha20_ctr32:
        ADDP            @k[11]=4,$key
        .save           ar.lc,r3
        mov             r3=ar.lc                }
+{ .mmi;        ADDP            $out=0,$out
+       ADDP            $inp=0,$inp             }
 { .mmi;        ADDP            $key=0,$key
        ADDP            $counter=0,$counter
        .save           pr,r14
```

**Comment by johnkohl-hcl** [comment]
> 




> I looked at the other (working) ia64 assembly sources for a while,
> and think I see a difference here, but have no way to try it out.
> Could you try this out for me?

I can only test HP-UX itanium systems.  But looks good there:

For 32-bit HPUX, yes, that change eliminates all the exit code 139 (signal 11 failures) I was seeing in the test suites.
For 64-bit HPUX, with assembly enabled, the old code didn't hit any failures (passed all tests as of 3.0.9 for me), and the new code passes all the chacha tests.  (On master branch, my build environment can't run 04-test_bio_dgram.t nor 75-test_quicapi.t on any platforms, so those fail, but everything else passes for HP-UX 64-bit mode).

**Comment by bernd-edlinger** [comment]
Thanks for testing my idea, that is exactly what I was looking for.
See #21681
