### ISSUE TITLE
Random crash in bn_sqr8x_internal 

### ISSUE THREAD

**Issue by moweonlee** [openssl/openssl#17213]
For couple of years, we have encountered core dumps on several nginx web servers.

Here is the core dump that I have captured in openssl 1.1.1l + nginx-1.18.0 / centOS 6.5 server 

With this core dump, I think it would be in the middle of handshaking before key exchange.

But lack of my SSL knowledge prevents me going further than now. :)

I think it is pretty random and rare. But it would be better if it can be fixed in new release of openssl.

Any information would be appreciated. 

Thank you.

```
$ gdb ~/apps/nginx/sbin/nginx ./backup2 
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home1/irteam/apps/nginx/sbin/nginx...done.
[New Thread 14969]
Missing separate debuginfo for 
Try: yum --disablerepo='*' --enablerepo='*-debug*' install /usr/lib/debug/.build-id/15/4f1d503d0ff2425ff9fe5ae98c4ec246ad9b3e
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libpcre.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.0
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Core was generated by `nginx: worker process              '.
Program terminated with signal 7, Bus error.
#0  0x0000000000571a35 in bn_sqr8x_internal ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 nss-softokn-freebl-3.14.3-9.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) by
Undefined command: "by".  Try "help".
(gdb) bt
#0  0x0000000000571a35 in bn_sqr8x_internal ()
#1  0x00000000005713e5 in bn_power5 ()
#2  0x0000000000639f0f in BN_mod_exp_mont_consttime ()
#3  0x00000000005d798e in rsa_ossl_mod_exp ()
#4  0x00000000005d8387 in rsa_ossl_private_encrypt ()
#5  0x00000000005dad1e in pkey_rsa_sign ()
#6  0x00000000005a95f3 in EVP_DigestSignFinal ()
#7  0x000000000054147c in tls_construct_cert_verify ()
#8  0x0000000000535e45 in state_machine ()
#9  0x0000000000521a54 in SSL_do_handshake ()
#10 0x000000000048bc9d in ngx_ssl_handshake (c=0x7f623f92bd50) at src/event/ngx_event_openssl.c:1606
#11 0x000000000049f83a in ngx_http_ssl_handshake (rev=0x7f623f7a9a50) at src/http/ngx_http_request.c:753
#12 0x000000000048674a in ngx_epoll_process_events (cycle=0x12513a0, timer=<value optimized out>, flags=<value optimized out>) at src/event/modules/ngx_epoll_module.c:901
#13 0x000000000047c30d in ngx_process_events_and_timers (cycle=0x12513a0) at src/event/ngx_event.c:247
#14 0x000000000048472c in ngx_worker_process_cycle (cycle=0x12513a0, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:750
#15 0x0000000000482d70 in ngx_spawn_process (cycle=0x12513a0, proc=0x484699 <ngx_worker_process_cycle>, data=0x0, name=0x6d8fc5 "worker process", respawn=-3)
    at src/os/unix/ngx_process.c:199
#16 0x0000000000483aba in ngx_start_worker_processes (cycle=0x12513a0, n=8, type=-3) at src/os/unix/ngx_process_cycle.c:359
#17 0x0000000000484dc0 in ngx_master_process_cycle (cycle=0x12513a0) at src/os/unix/ngx_process_cycle.c:131
#18 0x000000000045ce47 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:382
```

And here is the location that exception raised. ( 0x0000000000571a35 )

```
(gdb) disassemble 0x0000000000571a35
Dump of assembler code for function bn_sqr8x_internal:
   0x0000000000571460 <+0>:     lea    0x20(%r10),%rbp
   0x0000000000571464 <+4>:     lea    (%rsi,%r9,1),%rsi
   0x0000000000571468 <+8>:     mov    %r9,%rcx
   0x000000000057146b <+11>:    mov    -0x20(%rsi,%rbp,1),%r14
---Omitted-- 
   0x0000000000571942 <+1250>:  mov    %r11,%r14
   0x0000000000571945 <+1253>:  mul    %rax
   0x0000000000571948 <+1256>:  neg    %r15
   0x000000000057194b <+1259>:  mov    0x28(%rdi),%r11
   0x000000000057194f <+1263>:  adc    %rax,%rbx
   0x0000000000571952 <+1266>:  mov    0x10(%rsi,%rbp,1),%rax
   0x0000000000571957 <+1271>:  mov    %rbx,0x10(%rdi)
   0x000000000057195b <+1275>:  adc    %rdx,%r8
   0x000000000057195e <+1278>:  mov    %r8,0x18(%rdi)
   0x0000000000571962 <+1282>:  sbb    %r15,%r15
   0x0000000000571965 <+1285>:  lea    0x40(%rdi),%rdi
   0x0000000000571969 <+1289>:  add    $0x20,%rbp
   0x000000000057196d <+1293>:  jne    0x571880 <bn_sqr8x_internal+1056>
   0x0000000000571973 <+1299>:  lea    (%r14,%r10,2),%r12
   0x0000000000571977 <+1303>:  addr32 shr $0x3f,%r10
   0x000000000057197c <+1308>:  lea    (%rcx,%r11,2),%r13
   0x0000000000571980 <+1312>:  shr    $0x3f,%r11
   0x0000000000571984 <+1316>:  or     %r10,%r13
   0x0000000000571987 <+1319>:  mov    -0x10(%rdi),%r10
   0x000000000057198b <+1323>:  mov    %r11,%r14
   0x000000000057198e <+1326>:  mul    %rax
   0x0000000000571991 <+1329>:  neg    %r15
   0x0000000000571994 <+1332>:  mov    -0x8(%rdi),%r11
   0x0000000000571998 <+1336>:  adc    %rax,%r12
   0x000000000057199b <+1339>:  mov    -0x8(%rsi),%rax
   0x000000000057199f <+1343>:  mov    %r12,-0x20(%rdi)
   0x00000000005719a3 <+1347>:  adc    %rdx,%r13
   0x00000000005719a6 <+1350>:  lea    (%r14,%r10,2),%rbx
   0x00000000005719aa <+1354>:  mov    %r13,-0x18(%rdi)
   0x00000000005719ae <+1358>:  sbb    %r15,%r15
   0x00000000005719b1 <+1361>:  shr    $0x3f,%r10
   0x00000000005719b5 <+1365>:  lea    (%rcx,%r11,2),%r8
   0x00000000005719b9 <+1369>:  shr    $0x3f,%r11
   0x00000000005719bd <+1373>:  or     %r10,%r8
   0x00000000005719c0 <+1376>:  mul    %rax
   0x00000000005719c3 <+1379>:  neg    %r15
   0x00000000005719c6 <+1382>:  adc    %rax,%rbx
   0x00000000005719c9 <+1385>:  adc    %rdx,%r8
   0x00000000005719cc <+1388>:  mov    %rbx,-0x10(%rdi)
   0x00000000005719d0 <+1392>:  mov    %r8,-0x8(%rdi)
   0x00000000005719d4 <+1396>:  movq   %xmm2,%rbp
   0x00000000005719d9 <+1401>:  xor    %rax,%rax
   0x00000000005719dc <+1404>:  lea    (%r9,%rbp,1),%rcx
   0x00000000005719e0 <+1408>:  lea    0x38(%rsp,%r9,2),%rdx
   0x00000000005719e5 <+1413>:  mov    %rcx,0x8(%rsp)
   0x00000000005719ea <+1418>:  lea    0x38(%rsp,%r9,1),%rdi
   0x00000000005719ef <+1423>:  mov    %rdx,0x10(%rsp)
   0x00000000005719f4 <+1428>:  neg    %r9
   0x00000000005719f7 <+1431>:  jmp    0x571a00 <bn_sqr8x_internal+1440>
   0x00000000005719f9 <+1433>:  nopl   0x0(%rax)
   0x0000000000571a00 <+1440>:  lea    (%rdi,%r9,1),%rdi
   0x0000000000571a04 <+1444>:  data32 mov (%rdi),%rbx
   0x0000000000571a08 <+1448>:  mov    0x8(%rdi),%r9
   0x0000000000571a0c <+1452>:  mov    0x10(%rdi),%r10
   0x0000000000571a10 <+1456>:  mov    0x18(%rdi),%r11
   0x0000000000571a14 <+1460>:  mov    0x20(%rdi),%r12
   0x0000000000571a18 <+1464>:  mov    0x28(%rdi),%r13
   0x0000000000571a1c <+1468>:  mov    0x30(%rdi),%r14
   0x0000000000571a20 <+1472>:  mov    0x38(%rdi),%r15
   0x0000000000571a24 <+1476>:  mov    %rax,(%rdx)
   0x0000000000571a27 <+1479>:  lea    0x40(%rdi),%rdi
   0x0000000000571a2b <+1483>:  addr32 mov %rbx,%r8
   0x0000000000571a2f <+1487>:  imul   0x28(%rsp),%rbx
=> 0x0000000000571a35 <+1493>:  mov    0x0(%rbp),%rax
   0x0000000000571a39 <+1497>:  mov    $0x8,%ecx
   0x0000000000571a3e <+1502>:  jmp    0x571a40 <bn_sqr8x_internal+1504>
   0x0000000000571a40 <+1504>:  mul    %rbx
   0x0000000000571a43 <+1507>:  mov    0x8(%rbp),%rax
   0x0000000000571a47 <+1511>:  neg    %r8
   0x0000000000571a4a <+1514>:  mov    %rdx,%r8
   0x0000000000571a4d <+1517>:  adc    $0x0,%r8
   0x0000000000571a51 <+1521>:  mul    %rbx
   0x0000000000571a54 <+1524>:  add    %rax,%r9
   0x0000000000571a57 <+1527>:  mov    0x10(%rbp),%rax
   0x0000000000571a5b <+1531>:  adc    $0x0,%rdx
```

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
