### ISSUE TITLE
Memory leak in EVP_MD_fetch?

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#17265]
Using the memory sanitizer, I possibly have identified a memory leak. It could still be within my own provider, but I don't see how my code could cause this.

I actually see multiple indirect leaks, but they might be all due to to one direct leak.

1.) Leak of `EVP_MD` (the `<unknown module>` is my provider code, it does not show the function names for whatever reason):
```
Direct leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x3ffb913085d in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb085d)
    #1 0x3ffb6f4c2b7 in CRYPTO_malloc crypto/mem.c:184
    #2 0x3ffb6f4c307 in CRYPTO_zalloc crypto/mem.c:191
    #3 0x3ffb6dd66dd in evp_md_new crypto/evp/digest.c:836
    #4 0x3ffb6dd7987 in evp_md_from_algorithm crypto/evp/digest.c:916
    #5 0x3ffb6e54045 in construct_evp_method crypto/evp/evp_fetch.c:217
    #6 0x3ffb6f3ae93 in ossl_method_construct_this crypto/core_fetch.c:70
    #7 0x3ffb6f39c59 in algorithm_do_this crypto/core_algorithm.c:65
    #8 0x3ffb6f8cf27 in ossl_provider_doall_activated crypto/provider_core.c:1352
    #9 0x3ffb6f3a41f in ossl_algorithm_do_all crypto/core_algorithm.c:109
    #10 0x3ffb6f3bdbb in ossl_method_construct crypto/core_fetch.c:122
    #11 0x3ffb6e54d7b in inner_evp_generic_fetch crypto/evp/evp_fetch.c:320
    #12 0x3ffb6e55313 in evp_generic_fetch crypto/evp/evp_fetch.c:372
    #13 0x3ffb6dd95ab in EVP_MD_fetch crypto/evp/digest.c:1046
    #14 0x3ffb169b6f3  (<unknown module>)
    #15 0x3ffb16b67c5  (<unknown module>)
    #16 0x3ffb6e933a9 in evp_keymgmt_import crypto/evp/keymgmt_meth.c:461
    #17 0x3ffb6e876c5 in evp_keymgmt_util_try_import crypto/evp/keymgmt_lib.c:50
    #18 0x3ffb73fa9bb in rsa_export providers/implementations/keymgmt/rsa_kmgmt.c:208
    #19 0x3ffb6e936d5 in evp_keymgmt_export crypto/evp/keymgmt_meth.c:477
    #20 0x3ffb6e87c59 in evp_keymgmt_util_export crypto/evp/keymgmt_lib.c:92
    #21 0x3ffb6e88a4b in evp_keymgmt_util_export_to_provider crypto/evp/keymgmt_lib.c:166
    #22 0x3ffb6ebfeff in evp_pkey_export_to_provider crypto/evp/p_lib.c:1957
    #23 0x3ffb6e971db in do_sigver_init crypto/evp/m_sigver.c:185
    #24 0x3ffb6e9a40f in EVP_DigestSignInit_ex crypto/evp/m_sigver.c:379
    #25 0x10ab981 in init_ctx apps/pkeyutl.c:611
    #26 0x10a999b in pkeyutl_main apps/pkeyutl.c:305
    #27 0x109001d in do_cmd apps/openssl.c:418
    #28 0x108f1cd in main apps/openssl.c:298
```
There are further indirect leaks from within `EVP_MD_fetch()`, which are most likely due to this direct leak.

When debugging this, I can see that I do an `EVP_MD_fetch()` and get an `EVP_MD` with a ref-count of **2**. I also do an `EVP_MD_free()` of the fetched `EVP_MD`, resulting in a ref-count of 1, but of course, the `EVP_MD` is not freed due to the ref-count not being zero.  So am quite sure that my code is NOT leaking the `EVP_MD`, but whoever allocated the `EVP_MD` originally does not free it. I guess its a cached method. I am not sure who would be supposed to free the cache at program termination....

2.) Leak of an `OSSL_PROVIDER` allocated by `OSSL_LIB_CTX_new_child()`.

```
Indirect leak of 224 byte(s) in 1 object(s) allocated from:
    #0 0x3ffb913085d in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb085d)
    #1 0x3ffb6f4c2b7 in CRYPTO_malloc crypto/mem.c:184
    #2 0x3ffb6f4c307 in CRYPTO_zalloc crypto/mem.c:191
    #3 0x3ffb6f82d1d in provider_new crypto/provider_core.c:454
    #4 0x3ffb6f84379 in ossl_provider_new crypto/provider_core.c:558
    #5 0x3ffb6f7b927 in provider_create_child_cb crypto/provider_child.c:141
    #6 0x3ffb6f91259 in ossl_provider_register_child_cb crypto/provider_core.c:1719
    #7 0x3ffb6f7cb2d in ossl_provider_init_as_child crypto/provider_child.c:261
    #8 0x3ffb6f36681 in OSSL_LIB_CTX_new_child crypto/context.c:223
    #9 0x3ffb1693aa5  (<unknown module>)
    #10 0x3ffb6f881b1 in provider_init crypto/provider_core.c:905
    #11 0x3ffb6f8a755 in provider_activate crypto/provider_core.c:1103
    #12 0x3ffb6f8b5d7 in ossl_provider_activate crypto/provider_core.c:1178
    #13 0x3ffb6f7e377 in provider_conf_load crypto/provider_conf.c:222
    #14 0x3ffb6f7ed65 in provider_conf_init crypto/provider_conf.c:304
    #15 0x3ffb6b70a4f in module_init crypto/conf/conf_mod.c:375
    #16 0x3ffb6b6fc3f in module_run crypto/conf/conf_mod.c:239
    #17 0x3ffb6b6f7f5 in CONF_modules_load crypto/conf/conf_mod.c:138
    #18 0x3ffb6b6f9af in CONF_modules_load_file_ex crypto/conf/conf_mod.c:181
    #19 0x3ffb6b6fa9d in CONF_modules_load_file crypto/conf/conf_mod.c:203
    #20 0x3ffb6b72d4d in ossl_config_int crypto/conf/conf_sap.c:64
    #21 0x3ffb6f48bd9 in ossl_init_config crypto/init.c:242
    #22 0x3ffb6f48ba5 in ossl_init_config_ossl_ crypto/init.c:240
    #23 0x3ffb5210cf5 in __pthread_once_slow pthread_once.c:116
    #24 0x3ffb6f9fb4d in CRYPTO_THREAD_run_once crypto/threads_pthread.c:144
    #25 0x3ffb6f49663 in OPENSSL_init_crypto crypto/init.c:584
    #26 0x3ffb89f49cd in OPENSSL_init_ssl ssl/ssl_init.c:127
    #27 0x108e901 in apps_startup apps/openssl.c:66
    #28 0x108eb0d in main apps/openssl.c:265
```
There are further indirect leaks from within `OSSL_LIB_CTX_new_child()`, which are most likely due to this leak.

My provider does a `OSSL_LIB_CTX_new_child()` in its OSSL_provider_init() and frees it via `OSSL_LIB_CTX_free()` in ist teardown function. I can see in the debugger that it really does so.

It might be that the `OSSL_PROVIDER` is not freed, because it is still referenced by something else. It is an indirect leak, so I guess this is the case. Most likely it is still referenced from the directly leaked `EVP_MD` from above.

**Comment by mattcaswell** [comment]
Are you able to get a reproducer for this issue?

**Comment by ifranzki** [comment]
I was able to identify the cause of the leak in my code (how else could it be... ;-) ).
So all is good, no memory leak in OpenSSL code. 

Sorry for the noise.
