### ISSUE TITLE
possible double-free in context.c (openssl-3.0.0)

### ISSUE THREAD

**Issue by easylyou** [openssl/openssl#17291]
Hi!
We are using improved fuzzing technology with fault injection. These are possible double-free issues.

*Different from traditional fuzzing, fault injection can test error-handling codes while the errors happen in some extreme conditions. (such as malloc() return NULL when out of memory). So it is hard to reproduce without our fault injection environment. I try to analysis the related codes to find the cause but not sure, needing your helps. I'm glad to provide more details if you need.*

Analysis:
```c
// in crypto/context.c:187
187 OSSL_LIB_CTX *OSSL_LIB_CTX_new(void)
188 {
        // step 1. context_init().
191     if (ctx != NULL && !context_init(ctx)) {
        // step 2. OSSL_LIB_CTX_free().
192         OSSL_LIB_CTX_free(ctx);

194     }

196 }

// in crypto/context.c:70
 70 static int context_init(OSSL_LIB_CTX *ctx)
 71 {
     ...
102     if (!ossl_property_parse_init(ctx))
103         goto err;

106  err:
        // first free here.
109     CRYPTO_THREAD_lock_free(ctx->oncelock);
        // return 0 and enter step 2.
112     return 0;
113 }

// in crypto/context.c:238
238 void OSSL_LIB_CTX_free(OSSL_LIB_CTX *ctx)
239 {

243     context_deinit(ctx);

245 }


// in crypto/context.c:115
115 static int context_deinit(OSSL_LIB_CTX *ctx)
116 {
        // free again, double free!
137     CRYPTO_THREAD_lock_free(ctx->oncelock);

141 }
```

error log:
```
==344136==ERROR: AddressSanitizer: attempting double-free on 0x606000000ce0 in thread T0:
    #0 0x494b6d in free (/home/r1/openssl/bin/client-test+0x494b6d)
    #1 0xad09f9 in CRYPTO_free /home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:252:5
    #2 0xb1fc0c in CRYPTO_THREAD_lock_free /home/r1/openssl/openssl-3.0.0/build/../crypto/threads_pthread.c:137:5
    #3 0xab2c0e in context_deinit /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:137:5
    #4 0xab3854 in OSSL_LIB_CTX_free /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:243:5
    #5 0xab2e97 in OSSL_LIB_CTX_new /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:192:9
    #6 0x4c57de in fuzz_rand_provider_init /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:148:16
    #7 0xb18a66 in provider_init /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:901:13
    #8 0xb0e495 in provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1090:14
    #9 0xb0e25a in ossl_provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1167:18
    #10 0xb0253c in OSSL_PROVIDER_try_load /home/r1/openssl/openssl-3.0.0/build/../crypto/provider.c:31:10
    #11 0x4c5693 in FuzzerSetRand /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:159:22
    #12 0x4c461e in FuzzerInitialize /home/r1/openssl/openssl-3.0.0/build/../fuzz/client.c:43:5
    #13 0x4c6879 in main /home/r1/openssl/openssl-3.0.0/build/../fuzz/test-corpus.c:64:5
    #14 0x7f68405fb0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #15 0x41c6ad in _start (/home/r1/openssl/bin/client-test+0x41c6ad)

0x606000000ce0 is located 0 bytes inside of 56-byte region [0x606000000ce0,0x606000000d18)
freed by thread T0 here:
    #0 0x494b6d in free (/home/r1/openssl/bin/client-test+0x494b6d)
    #1 0xad09f9 in CRYPTO_free /home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:252:5
    #2 0xb1fc0c in CRYPTO_THREAD_lock_free /home/r1/openssl/openssl-3.0.0/build/../crypto/threads_pthread.c:137:5
    #3 0xab361d in context_init /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:109:5
    #4 0xab2e30 in OSSL_LIB_CTX_new /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:191:25
    #5 0x4c57de in fuzz_rand_provider_init /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:148:16
    #6 0xb18a66 in provider_init /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:901:13
    #7 0xb0e495 in provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1090:14
    #8 0xb0e25a in ossl_provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1167:18
    #9 0xb0253c in OSSL_PROVIDER_try_load /home/r1/openssl/openssl-3.0.0/build/../crypto/provider.c:31:10
    #10 0x4c5693 in FuzzerSetRand /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:159:22
    #11 0x4c461e in FuzzerInitialize /home/r1/openssl/openssl-3.0.0/build/../fuzz/client.c:43:5
    #12 0x4c6879 in main /home/r1/openssl/openssl-3.0.0/build/../fuzz/test-corpus.c:64:5
    #13 0x7f68405fb0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

previously allocated by thread T0 here:
    #0 0x494ded in malloc (/home/r1/openssl/bin/client-test+0x494ded)
    #1 0xad0468 in CRYPTO_malloc /home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:184:12
    #2 0xad0594 in CRYPTO_zalloc /home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:191:11
    #3 0xb1f691 in CRYPTO_THREAD_lock_new /home/r1/openssl/openssl-3.0.0/build/../crypto/threads_pthread.c:38:17
    #4 0xab305e in context_init /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:79:21
    #5 0xab2e30 in OSSL_LIB_CTX_new /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:191:25
    #6 0x4c57de in fuzz_rand_provider_init /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:148:16
    #7 0xb18a66 in provider_init /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:901:13
    #8 0xb0e495 in provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1090:14
    #9 0xb0e25a in ossl_provider_activate /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:1167:18
    #10 0xb0253c in OSSL_PROVIDER_try_load /home/r1/openssl/openssl-3.0.0/build/../crypto/provider.c:31:10
    #11 0x4c5693 in FuzzerSetRand /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:159:22
    #12 0x4c461e in FuzzerInitialize /home/r1/openssl/openssl-3.0.0/build/../fuzz/client.c:43:5
    #13 0x4c6879 in main /home/r1/openssl/openssl-3.0.0/build/../fuzz/test-corpus.c:64:5
    #14 0x7f68405fb0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: double-free (/home/r1/openssl/bin/client-test+0x494b6d) in free
==344136==ABORTING
```

**Comment by t8m** [comment]
Fix in #17294

**Comment by t8m** [comment]
Nice find

**Comment by easylyou** [comment]
It seems fixed! Maybe I should close the issue?
Reopen it If needed.
