### ISSUE TITLE
possible NULL dereference in context.c (openssl-3.0.0)

### ISSUE THREAD

**Issue by easylyou** [openssl/openssl#17312]
Hi!
We are using improved fuzzing technology with fault injection. These are possible NULL dereference issues.

*Different from traditional fuzzing, fault injection can test error-handling codes while the errors happen in some extreme conditions. (such as malloc() return NULL when out of memory). So it is hard to reproduce without our fault injection environment. I try to analysis the related codes to find the cause but not sure, needing your helps. I'm glad to provide more details if you need.*

Analysis:
```c
// in crypto/context.c:346
346 void *ossl_lib_ctx_get_data( ...
348 {
        // `ossl_lib_ctx_get_concrete()` never return NULL even if `context_init()` fails, but `default_context_int` instead.
        // see below.
352     ctx = ossl_lib_ctx_get_concrete(ctx);
353     if (ctx == NULL)
354         return NULL;
        // `ctx->lock == NULL`, NULL point dereference.
356     if (!CRYPTO_THREAD_read_lock(ctx->lock)) 
357         return NULL;

418 }

// in crypto/context.c:169
169 static OSSL_LIB_CTX *get_default_context(void)
170 {
171     OSSL_LIB_CTX *current_defctx = get_thread_default_context();
173     if (current_defctx == NULL)
            // return `default_context_int`.
174         current_defctx = &default_context_int;
175     return current_defctx;
176 }
```

error logs:
```
==2096623==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7f79dcc373f0 bp 0x7ffe406a7b30 sp 0x7ffe406a7ad0 T0)
==2096623==The signal is caused by a READ memory access.
==2096623==Hint: address points to the zero page.
    #0 0x7f79dcc373f0 in __pthread_rwlock_rdlock_full /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_rwlock_common.c:299:7
    #1 0x7f79dcc373f0 in pthread_rwlock_rdlock /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_rwlock_rdlock.c:27:16
    #2 0xb1f88e in CRYPTO_THREAD_read_lock /home/r1/openssl/openssl-3.0.0/build/../crypto/threads_pthread.c:85:9
    #3 0xab473c in ossl_lib_ctx_get_data /home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:356:10
    #4 0xb07282 in get_provider_store /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:334:13
    #5 0xb07460 in ossl_provider_info_add_to_store /home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:360:39
    #6 0xb0377e in OSSL_PROVIDER_add_builtin /home/r1/openssl/openssl-3.0.0/build/../crypto/provider.c:125:10
    #7 0x4c55b2 in FuzzerSetRand /home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:157:10
    #8 0x4c461e in FuzzerInitialize /home/r1/openssl/openssl-3.0.0/build/../fuzz/client.c:43:5
    #9 0x4c6879 in main /home/r1/openssl/openssl-3.0.0/build/../fuzz/test-corpus.c:64:5
    #10 0x7f79dc8e90b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x41c6ad in _start (/home/r1/openssl/bin/client-test+0x41c6ad)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_rwlock_common.c:299:7 in __pthread_rwlock_rdlock_full
==2096623==ABORTING

```

**Comment by paulidale** [comment]
I don't see how `default_context_int` can have a NULL lock field.  The initialisation https://github.com/openssl/openssl/blob/0d4c52320d245be80bd69346fdda4b12b4961eae/crypto/context.c#L150-L154 indicates failure if the lock isn't created.  I only tracked the calls one step back, so I guess something might be ignoring a failure return.

Do you know how your fuzzer managed to get here?

**Comment by t8m** [comment]
I suppose when CRYPTO_THREAD_init_local() or context_init() fails the default_context_int will be uninitialized, i.e. all zeros.

Not sure we have to guard against such kind of failures. Similarly for #17313

**Comment by t8m** [comment]
I.e., should we really guard against situation when initialization of global data that is "always expected to be in there" fails?

**Comment by easylyou** [comment]
> I suppose when CRYPTO_THREAD_init_local() or context_init() fails the default_context_int will be uninitialized, i.e. all zeros.
> 
> Not sure we have to guard against such kind of failures. Similarly for #17313

Your supposition is right! Here is the injection log. 
Only one inject here. The log is the backtrack of the inject point.
```
===================FAULT INJECT===================
faultinject: error actived 1! name: malloc, file: ../crypto/mem.c, line: 184
??:?
/home/r1/src_git/mfuzz-project/wrapper/mfuzzrt/faultinject.c:45
/home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:184
/home/r1/openssl/openssl-3.0.0/build/../crypto/mem.c:191
/home/r1/openssl/openssl-3.0.0/build/../crypto/stack/stack.c:221
/home/r1/openssl/openssl-3.0.0/build/../crypto/stack/stack.c:130
/home/r1/openssl/openssl-3.0.0/build/../crypto/ex_data.c:470
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:312
/home/r1/openssl/openssl-3.0.0/build/../crypto/ex_data.c:458
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:407
/home/r1/openssl/openssl-3.0.0/build/../crypto/property/property_string.c:214
/home/r1/openssl/openssl-3.0.0/build/../crypto/property/property_parse.c:546
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:102
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:153   <---------   context_init(&default_context_int)      
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:150
/lib/x86_64-linux-gnu/libpthread.so.0(+0x1247f)[0x7faef2a2647f]
/home/r1/openssl/openssl-3.0.0/build/../crypto/threads_pthread.c:144
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:163
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:171
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:274
/home/r1/openssl/openssl-3.0.0/build/../crypto/context.c:352
/home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:334
/home/r1/openssl/openssl-3.0.0/build/../crypto/provider_core.c:360
/home/r1/openssl/openssl-3.0.0/build/../crypto/provider.c:125
/home/r1/openssl/openssl-3.0.0/build/../fuzz/fuzz_rand.c:157
/home/r1/openssl/openssl-3.0.0/build/../fuzz/client.c:43
/home/r1/openssl/openssl-3.0.0/build/../fuzz/test-corpus.c:64
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7faef26d40b3]
??:?
==================================================

```


```c
161 static OSSL_LIB_CTX *get_thread_default_context(void)
162 {
           // `default_context_init` fail, return NULL.
163     if (!RUN_ONCE(&default_context_init, default_context_do_init))
164         return NULL;
165 
166     return CRYPTO_THREAD_get_local(&default_context_thread_local);
167 }
168 
169 static OSSL_LIB_CTX *get_default_context(void)
170 {
           // `default_context_init` fail, `current_defctx = NULL`.
171     OSSL_LIB_CTX *current_defctx = get_thread_default_context();
172 
173     if (current_defctx == NULL)
              // Point to `default_context_int` again. In fact it is all zero.
174         current_defctx = &default_context_int;
175     return current_defctx;
176 }

```

**Comment by easylyou** [comment]
> I.e., should we really guard against situation when initialization of global data that is "always expected to be in there" fails?

I agree with you. Ignoring some errors and let it crash is also a good solution in some situations.
In fact I'm not familiar with openssl. In usual, if a software may request global resources such as shared-memory, global lock or modifying filesystem and so on, it's better not to simply ignore.

**Comment by paulidale** [comment]
> I.e., should we really guard against situation when initialization of global data that is "always expected to be in there" fails?

Shouldn't we detect that the initialisation failed and return an error?  If an application then continues using us, crash is acceptable, although more errors would be better IMO.

**Comment by ArturZaprzala** [comment]
A real life example from a program using libldap 2.6.2 and OpenSSL 3.0.1 (CentOS 9).
At first OPENSSL_cleanup() is called (registered with atexit()):
```
0  ossl_lib_ctx_default_deinit () at crypto/context.c:196
1  OPENSSL_cleanup () at crypto/init.c:424
2  OPENSSL_cleanup () at crypto/init.c:338
3  0x00007ffff7873475 in __run_exit_handlers (status=0, listp=0x7ffff7a11658 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:113
4  0x00007ffff78735f0 in __GI_exit (status=<optimized out>) at exit.c:143
5  0x00007ffff785be57 in __libc_start_call_main (main=main@entry=0x55555556aa20 <main>, argc=argc@entry=4, argv=argv@entry=0x7fffffffe2c8) at ../sysdeps/nptl/libc_start_call_main.h:74
6  0x00007ffff785befc in __libc_start_main_impl (main=0x55555556aa20 <main>, argc=4, argv=0x7fffffffe2c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2b8) at ../csu/libc-start.c:409
7  0x000055555556b575 in _start ()
```

Then SSL_CTX_free() is called indirectly by ldap_int_destroy_global_options() (not shown on stacktrace, registered with `__attribute__ ((destructor))`):

**Program received signal SIGSEGV, Segmentation fault.**
```
0  ___pthread_rwlock_rdlock (rwlock=0x0) at pthread_rwlock_rdlock.c:27
1  0x00007ffff7c92f3d in CRYPTO_THREAD_read_lock (lock=<optimized out>) at crypto/threads_pthread.c:85
2  0x00007ffff7c8b126 in ossl_lib_ctx_get_data (ctx=0x7ffff7eff540 <default_context_int.lto_priv>, index=1, meth=0x7ffff7eb8a00 <provider_store_method.lto_priv>) at crypto/context.c:398
3  0x00007ffff7c98bea in get_provider_store (libctx=<optimized out>) at crypto/provider_core.c:334
4  ossl_provider_deregister_child_cb (handle=0x5555555ed620) at crypto/provider_core.c:1752
5  0x00007ffff7c8bf2f in ossl_provider_deinit_child (ctx=0x5555555d2650) at crypto/provider_child.c:279
6  OSSL_LIB_CTX_free (ctx=0x5555555d2650) at crypto/context.c:283
7  OSSL_LIB_CTX_free (ctx=0x5555555d2650) at crypto/context.c:276
8  0x00007ffff7634af6 in legacy_teardown (provctx=0x5555555ee9f0) at providers/legacyprov.c:168
9  0x00007ffff7c9901b in ossl_provider_teardown (prov=0x5555555ed620) at crypto/provider_core.c:1477
10 ossl_provider_free (prov=0x5555555ed620) at crypto/provider_core.c:683
11 0x00007ffff7c63956 in ossl_provider_free (prov=<optimized out>) at crypto/provider_core.c:668
12 evp_cipher_free_int (cipher=0x555555916c10) at crypto/evp/evp_enc.c:1632
13 EVP_CIPHER_free (cipher=0x555555916c10) at crypto/evp/evp_enc.c:1647
14 0x00007ffff7a6bc1d in ssl_evp_cipher_free (cipher=0x555555916c10) at ssl/ssl_lib.c:5925
15 ssl_evp_cipher_free (cipher=0x555555916c10) at ssl/ssl_lib.c:5915
16 SSL_CTX_free (a=0x555555ec1020) at ssl/ssl_lib.c:3455
17 SSL_CTX_free (a=0x555555ec1020) at ssl/ssl_lib.c:3392
18 0x00007fffe95edb89 in ldap_int_tls_destroy (lo=0x7fffe9616000 <ldap_int_global_options>) at /usr/src/debug/openldap-2.6.2-1.el9_0.x86_64/openldap-2.6.2/libraries/libldap/tls2.c:104
19 0x00007ffff7fd100b in _dl_fini () at dl-fini.c:138
20 0x00007ffff7873475 in __run_exit_handlers (status=0, listp=0x7ffff7a11658 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:113
21 0x00007ffff78735f0 in __GI_exit (status=<optimized out>) at exit.c:143
22 0x00007ffff785be57 in __libc_start_call_main (main=main@entry=0x55555556aa20 <main>, argc=argc@entry=4, argv=argv@entry=0x7fffffffe2b8) at ../sysdeps/nptl/libc_start_call_main.h:74
23 0x00007ffff785befc in __libc_start_main_impl (main=0x55555556aa20 <main>, argc=4, argv=0x7fffffffe2b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2a8) at ../csu/libc-start.c:409
24 0x000055555556b575 in _start ()
```
Segfault happens only when legacy providers are loaded. But the point is that even when there is no segfault, the order of deinitialization is wrong and it is left undetected.

**Comment by rcmcdonald91** [comment]
I am seeing this exact issue with FreeBSD pkg using libcurl as a fetch backend on FreeBSD CURRENT (OpenSSL 3.0.11).

**Comment by rcmcdonald91** [comment]
So, it seems this issue is caused by libcurl not initializing OpenSSL with `OPENSSL_INIT_NOATEXIT`. I quick search has revealed that other OpenSSL consumers have experienced issues with atexit ordering and cleanup over the years. I'm not sure there is anything to do here on OpenSSL's side.

**Comment by ngie-eign** [comment]
I discovered a slight snag... I don't know what order `__attribute__((destructor))` items are executed in, but depending on how `atexit` functions relative to `__attribute__((destructor))`, there may be a conflict between how the destructor decorated functions are getting executed in relation to the atexit handler installed by libcrypto and libssl.

**Comment by ngie-eign** [comment]
What order `__attribute__((destructor))` is run in is OS/compiler/toolchain dependent.
In clang/llvm with FreeBSD at least, `__attribute__((destructor))` is run after any functions registered with `atexit` on FreeBSD.
I understand why the OpenSSL project did this from an architectural perspective, but it honestly seems like the default should be "don't clean up automatically" instead of "clean up automatically".. with anything remotely complicated with multiple libraries, I don't see how the consumer could reliably use OpenSSL with the default atexit behavior without doing an _extensive_ audit of the code in use in an application.

**Comment by Mekk** [comment]
(nothing particularly new but let me +1 with another example…)

I found this issue while analyzing mysterious coredumps which started to happen to me from time to time during apps shutdown (at the moment tested using openssl 3.0.13 from Ubuntu 24.04).

Backtrace is similar to the ones reported above (quoted below), after some digging looks like  coredump is triggered by
```CRYPTO_THREAD_read_lock(NULL)```
where this NULL turns out to be 
```default_context_int.lock```
and whole default_context looks so:
```
(gdb) print ctx
$19 = (OSSL_LIB_CTX *) 0x7b02e090ff20 <default_context_int>
(gdb) print *ctx
$20 = {lock = 0x0, data = {ctx = 0x0, sk = 0x0}, global = {ex_data_lock = 0x0, ex_data = {{meth = 0x0} <repeats 18 times>}}, dyn_indexes = {3, 5, 6, 1, 4, 2, 
    -1, -1, -1, -1, -1, 8, -1, -1, 7, -1, -1, -1, -1}, index_locks = {0x5060000d9e20, 0x5060000d9e80, 0x5060000d9ee0, 0x5060000d9f40, 0x5060000d9fa0, 
    0x5060000da000, 0x5060000da060, 0x5060000da0c0, 0x5060000da120, 0x5060000da180, 0x5060000da1e0, 0x5060000da240, 0x5060000da2a0, 0x5060000da300, 
    0x5060000da360, 0x5060000da3c0, 0x5060000da420, 0x5060000da480, 0x5060000da4e0}, oncelock = 0x5060000d9dc0, run_once_done = {0, 0, 0}, run_once_ret = {0, 
    0, 0}, onfreelist = 0x0, ischild = 0}
```

This context most likely was cleared as process performed some ssl-related ops earlier succesfully.

The app is complicated C++ app, uses various ssl-using libs (rabbitmq-c, rdkafka, curl, some custom code, …) and crash happens at the moment it is shutting down it's components, destructing objects, joining threads, etc (rdkafka seen in my backtrace is usually last to destruct as it takes its time to notify all its working threads).

My backtrace (which repeats fairly often) – it is one of the rdkafka worker threads which was not yet notified about the need to shut down, in fact it is using `HMAC` on password during authorization (and this call goes down to using already cleared context):

```
(gdb) bt
#0  __pthread_rwlock_rdlock_full64 (abstime=0x0, clockid=0, rwlock=0x0) at ./nptl/pthread_rwlock_common.c:298
#1  ___pthread_rwlock_rdlock (rwlock=0x0) at ./nptl/pthread_rwlock_rdlock.c:26
#2  0x00007b02e06305fd in CRYPTO_THREAD_read_lock (lock=<optimized out>) at ../crypto/threads_pthread.c:95
#3  0x00007b02e061ecd4 in ossl_lib_ctx_get_data (ctx=0x7b02e090ff20 <default_context_int>, index=index@entry=0, 
    meth=meth@entry=0x7b02e08c4f80 <evp_method_store_method>) at ../crypto/context.c:402
#4  0x00007b02e05fa5c2 in get_evp_method_store (libctx=<optimized out>) at ../crypto/evp/evp_fetch.c:82
#5  inner_evp_generic_fetch (methdata=methdata@entry=0x7b02cc9fe4a0, prov=<optimized out>, prov@entry=0x0, operation_id=operation_id@entry=3, 
    name_id=name_id@entry=0, name=name@entry=0x7b02e07eafc5 "HMAC", properties=properties@entry=0x0, new_method=0x7b02e06079f0 <evp_mac_from_algorithm>, 
    up_ref_method=0x7b02e0607940 <evp_mac_up_ref>, free_method=0x7b02e0607960 <evp_mac_free>) at ../crypto/evp/evp_fetch.c:270
#6  0x00007b02e05faae4 in evp_generic_fetch (libctx=libctx@entry=0x0, operation_id=operation_id@entry=3, name=name@entry=0x7b02e07eafc5 "HMAC", 
    properties=properties@entry=0x0, new_method=new_method@entry=0x7b02e06079f0 <evp_mac_from_algorithm>, 
    up_ref_method=up_ref_method@entry=0x7b02e0607940 <evp_mac_up_ref>, free_method=0x7b02e0607960 <evp_mac_free>) at ../crypto/evp/evp_fetch.c:409
#7  0x00007b02e0607de2 in EVP_MAC_fetch (libctx=libctx@entry=0x0, algorithm=algorithm@entry=0x7b02e07eafc5 "HMAC", properties=properties@entry=0x0)
    at ../crypto/evp/mac_meth.c:172
#8  0x00007b02e060765c in EVP_Q_mac (libctx=libctx@entry=0x0, name=name@entry=0x7b02e07eafc5 "HMAC", propq=propq@entry=0x0, subalg=0x7b02e07f2890 "SHA256", 
    params=params@entry=0x0, key=key@entry=0x7b02cc9fe910, keylen=4, data=0x7b02cc9fe6e0 "esk9a4416yj9maobh60yu8c9s", datalen=29, out=0x7b02cc9fe740 "", 
    outsize=32, outlen=0x7b02cc9fe680) at ../crypto/evp/mac_lib.c:249
#9  0x00007b02e0618fd8 in HMAC (evp_md=evp_md@entry=0x7b02e08c5fa0 <sha256_md>, key=0x7b02cc9fe910, key_len=4, data=0x7b02cc9fe6e0 "esk9a4416yj9maobh60yu8c9s", 
    data_len=data_len@entry=29, md=md@entry=0x7b02cc9fe740 "", md_len=0x7b02cc9fe73c) at ../crypto/hmac/hmac.c:231
#10 0x00007b02db38fc03 in rd_kafka_ssl_hmac (rkb=<optimized out>, evp=<optimized out>, in=in@entry=0x7b02cc9feb90, salt=salt@entry=0x7b02cc9fecc0, 
    itcnt=itcnt@entry=8192, out=out@entry=0x7b02cc9feba0) at rdkafka_ssl.c:1873
#11 0x00007b02db382cbe in rd_kafka_sasl_scram_Hi (rktrans=0x510000254240, rktrans=0x510000254240, out=0x7b02cc9feba0, itcnt=8192, salt=0x7b02cc9fecc0, 
    in=0x7b02cc9feb90) at rdkafka_sasl_scram.c:203
…
#25 0x00007b02db241b65 in rd_kafka_broker_thread_main (arg=0x51f000016c80) at rdkafka_broker.c:4605
#26 0x00007b02dfc9c86b in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#27 0x00007b02dfd29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Mekk** [comment]
My case was caused by race between openssl atexit and static object destructor (the former happened earlier, the latter used openssl), my - and possibly only - resolution is to avoid any cases where openssl api's are used after main (by static object destructors, and such).

Still, IMHO there is small fishy thing in openssl. I mean this code:
```c++
void *ossl_lib_ctx_get_data(OSSL_LIB_CTX *ctx, int index,
                            const OSSL_LIB_CTX_METHOD *meth)
{
    void *data = NULL;
    int dynidx;

    ctx = ossl_lib_ctx_get_concrete(ctx);     // NEVER returns NULL
    if (ctx == NULL)                                        
        return NULL;                                           // NEVER happens

    if (!CRYPTO_THREAD_read_lock(ctx->lock))  // SEGV when ctx->lock is NULL
        return NULL;
```

The thing is that `ossl_lib_ctx_get_concrete` never returns NULL, if param is null it calls `get_default_context` which
```c++
static OSSL_LIB_CTX *get_default_context(void)
{
    OSSL_LIB_CTX *current_defctx = get_thread_default_context();

    if (current_defctx == NULL)
        current_defctx = &default_context_int;
    return current_defctx;
}
```


So possibly either `get_default_context` should return NULL in case `default_context_int` is already cleared, or mayhaps `ossl_lib_ctx_get_data` should have if on `ctx->lock` instead of checking `ctx` (which is never null).

**Comment by t8m** [comment]
We are removing atexit calls in 4.0 version. Closing the issue.

**Comment by ngie-eign** [comment]
> We are removing atexit calls in 4.0 version. Closing the issue.

That's great to hear! Looking forward to the change when it arrives in 4.0.

**Comment by Mekk** [comment]
Could you take a look at https://github.com/openssl/openssl/issues/17312#issuecomment-2474461157 
?
atexit or not atexit, there is sth wrong in this code.
