### ISSUE TITLE
EVP_PKEY_derive_set_peer_ex segfaults when used with a peer key from a different provider

### ISSUE THREAD

**Issue by ifranzki** [openssl/openssl#17424]
I ran into a problem where I get a segfault within `EVP_PKEY_derive_set_peer_ex()` when the peer EC key (and the base EC key) has been generated with provider A (i.e. my own provider), but the exchange method is only provided by provider B (i.e. the default provider).

```
Program received signal SIGSEGV, Segmentation fault.
0x000003fffb86fd10 in EC_GROUP_get_field_type (group=group@entry=0x3fff6d784e0 <ibmca_keymgmt_ec_dup_cb>) at crypto/ec/ec_lib.c:502
502         return group->meth->field_type;
(gdb) bt
#0  0x000003fffb86fd10 in EC_GROUP_get_field_type (group=group@entry=0x3fff6d784e0 <ibmca_keymgmt_ec_dup_cb>)
    at crypto/ec/ec_lib.c:502
#1  0x000003fffb87428c in EC_GROUP_cmp (a=a@entry=0x610000001840, b=b@entry=0x3fff6d784e0 <ibmca_keymgmt_ec_dup_cb>,
    ctx=ctx@entry=0x607000003f20) at crypto/ec/ec_lib.c:631
#2  0x000003fffbc73e56 in ecdh_match_params (peer=0x60d0000006c0, priv=<optimized out>)
    at providers/implementations/exchange/ecdh_exch.c:134
#3  ecdh_set_peer (vpecdhctx=0x60600000b780, vecdh=0x60d0000006c0) at providers/implementations/exchange/ecdh_exch.c:149
#4  0x0000000001005c18 in check_eckey (nid=409, name=0x10077e0 "NID_X9_62_prime192v1") at eckey.c:581
#5  0x00000000010063ea in main (argc=1, argv=0x3fffffff028) at eckey.c:652
```

I am generating 2 EC keys using provider A (my own provider). I then setup a context using `EVP_PKEY_CTX_new_from_pkey()` with the base key. 

I then call `EVP_PKEY_derive_init()` and I can see that the base key is exported from provider A (my own provider) to provider B (the default provider), as expected, because my provider does not implement key exchange.

I then call `EVP_PKEY_derive_set_peer_ex()` setting the peer key, which was also generated by provider A (my own provider).
It first validates the peek key successfully (I can see that it calls the validate function of my provider's keymgmt method).

Then it calls `evp_pkey_export_to_provider()` in order to export the peer key to the right provider. However, it passes 
`&ctx->keymgmt` where `ctx->keymgmt` points to the keymgmt method of provider A (my own provider), because the context was initialized with the base key that was created by provider A (my own provider).

`evp_pkey_export_to_provider()` then calls `evp_keymgmt_util_export_to_provider()` which detects that the key's keymgmt is the same as the target keymgmt, and thus just returns they keys keydata, which is provider A's key data!

It then calls the context's exchange method to set the peer key. The exchange method however is from provider B (default provider). But it passes the key data from provider A to it.....

This finally leads to the segfault, because the keydata is not from provider B (default provider).

Looking at other places where `evp_pkey_export_to_provider()` is called, it never passes `&ctx->keymgmt`, but always `&tmp_keymgmt`, where `tmp_keymgmt` was fetched before using 
```
mp_keymgmt_tofree = tmp_keymgmt
            = evp_keymgmt_fetch_from_prov((OSSL_PROVIDER *)tmp_prov,
                                          EVP_KEYMGMT_get0_name(ctx->keymgmt),
                                          ctx->propquery);
```
and `tmp_prov` is the provider that implements the desired method. 

I would assume that something like this should also be done here, `tmp_prov` can probably be retrieved from `ctx->op.kex.exchange`. This would ensure that `tmp_keymgmt` then is the right keymgmt method from the same provider that implements the exchange method.

```
int EVP_PKEY_derive_set_peer_ex(EVP_PKEY_CTX *ctx, EVP_PKEY *peer,
                                int validate_peer)
{
    int ret = 0, check;
    void *provkey = NULL;
    EVP_PKEY_CTX *check_ctx = NULL;

    if (ctx == NULL) {
        ERR_raise(ERR_LIB_EVP, ERR_R_PASSED_NULL_PARAMETER);
        return -1;
    }

    if (!EVP_PKEY_CTX_IS_DERIVE_OP(ctx) || ctx->op.kex.algctx == NULL)
        goto legacy;

    if (ctx->op.kex.exchange->set_peer == NULL) {
        ERR_raise(ERR_LIB_EVP, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE);
        return -2;
    }

    if (validate_peer) {
        check_ctx = EVP_PKEY_CTX_new_from_pkey(ctx->libctx, peer, ctx->propquery);
        if (check_ctx == NULL)
            return -1;
        check = EVP_PKEY_public_check(check_ctx);
        EVP_PKEY_CTX_free(check_ctx);
        if (check <= 0)
            return -1;
    }

    provkey = evp_pkey_export_to_provider(peer, ctx->libctx, &ctx->keymgmt,     <------  ctx->keymgmt is probably wrong here
                                          ctx->propquery);
    /*
     * If making the key provided wasn't possible, legacy may be able to pick
     * it up
     */
    if (provkey == NULL)
        goto legacy;
    return ctx->op.kex.exchange->set_peer(ctx->op.kex.algctx, provkey);
...
```

**Comment by ifranzki** [comment]
With the following change it works for me (I can't tell if this is a complete fix tough, I did not check the legacy path for example):

```
 crypto/evp/exchange.c | 33 +++++++++++++++++++++++++++++----
 1 file changed, 29 insertions(+), 4 deletions(-)

diff --git a/crypto/evp/exchange.c b/crypto/evp/exchange.c
index e2ca30c94d..f7f9837ce7 100644
--- a/crypto/evp/exchange.c
+++ b/crypto/evp/exchange.c
@@ -380,6 +380,8 @@ int EVP_PKEY_derive_set_peer_ex(EVP_PKEY_CTX *ctx, EVP_PKEY *peer,
     int ret = 0, check;
     void *provkey = NULL;
     EVP_PKEY_CTX *check_ctx = NULL;
+    EVP_KEYMGMT *tmp_keymgmt_tofree, *tmp_keymgmt;
+    OSSL_PROVIDER *tmp_prov;
 
     if (ctx == NULL) {
         ERR_raise(ERR_LIB_EVP, ERR_R_PASSED_NULL_PARAMETER);
@@ -404,15 +406,38 @@ int EVP_PKEY_derive_set_peer_ex(EVP_PKEY_CTX *ctx, EVP_PKEY *peer,
             return -1;
     }
 
-    provkey = evp_pkey_export_to_provider(peer, ctx->libctx, &ctx->keymgmt,
-                                          ctx->propquery);
+    /*
+     * Ensure that the key is provided, either natively, or as a cached
+     * export.  We start by fetching the keymgmt with the same name as
+     * |ctx->pkey|, but from the provider of the keyexch method, using
+     * the same property query as when fetching the keyexch method.
+     * With the keymgmt we found (if we did), we try to export |ctx->pkey|
+     * to it (evp_pkey_export_to_provider() is smart enough to only actually
+     * export it if |tmp_keymgmt| is different from |ctx->pkey|'s keymgmt)
+     */
+    tmp_prov = EVP_KEYEXCH_get0_provider(ctx->op.kex.exchange);
+
+    tmp_keymgmt_tofree = tmp_keymgmt
+        = evp_keymgmt_fetch_from_prov(tmp_prov,
+                                      EVP_KEYMGMT_get0_name(ctx->keymgmt),
+                                      ctx->propquery);
+    if (tmp_keymgmt != NULL)
+        provkey = evp_pkey_export_to_provider(peer, ctx->libctx, &ctx->keymgmt,
+	                                      ctx->propquery);
+    if (tmp_keymgmt == NULL)
+        EVP_KEYMGMT_free(tmp_keymgmt_tofree);
+
     /*
      * If making the key provided wasn't possible, legacy may be able to pick
      * it up
      */
-    if (provkey == NULL)
+    if (provkey == NULL) {
+        EVP_KEYMGMT_free(tmp_keymgmt);
         goto legacy;
-    return ctx->op.kex.exchange->set_peer(ctx->op.kex.algctx, provkey);
+    }
+    ret = ctx->op.kex.exchange->set_peer(ctx->op.kex.algctx, provkey);
+    EVP_KEYMGMT_free(tmp_keymgmt);
+    return ret;
 
  legacy:
 #ifdef FIPS_MODULE
```

**Comment by t8m** [comment]
I have somewhat simpler patch already. But thank you for the thorough analysis.

**Comment by t8m** [comment]
Patch in #17425

**Comment by t8m** [comment]
A testcase would involve adding a fake provider of some type, not sure it is absolutely necessary.

**Comment by ifranzki** [comment]
Yes, your patch will work, too, and it is somewhat simpler.
Thanks for the quick turnaround!
