### ISSUE TITLE
X509_LOOKUP_load_file() causes a crash with Intel QAT engine enabled

### ISSUE THREAD

**Issue by cwyang** [openssl/openssl#17965]
Hi, all.

My app crashes when I load system default CA file with `X509_LOOKUP_load_file()`.
OpenSSL version is 3.0.2 and the gdb backtrace goes as follows:
```
(gdb) where
#0  0x000000000071e35c in doall_util_fn (lh=0x1bbbad0, use_arg=0, func=0x7672c3 <impl_cache_free>, func_arg=0x0, arg=0x0) at crypto/lhash/lhash.c:225
#1  0x000000000071e3e1 in OPENSSL_LH_doall (lh=0x1bbbad0, func=0x7672c3 <impl_cache_free>) at crypto/lhash/lhash.c:237
#2  0x0000000000766eee in lh_QUERY_doall (lh=0x1bbbad0, doall=0x7672c3 <impl_cache_free>) at crypto/property/property.c:54
#3  0x0000000000767dcf in impl_cache_flush_alg (idx=0, alg=0x1bbba50, arg=0x0) at crypto/property/property.c:493
#4  0x0000000000767eb5 in ossl_method_cache_flush (store=0x1b92bd0, nid=29194) at crypto/property/property.c:511
#5  0x0000000000767638 in ossl_method_store_add (store=0x1b92bd0, prov=0x1b96300, nid=29194, properties=0xa2bb33 "provider=default", method=0x7f0a8004f990, method_up_ref=0x6fe6c8 <EVP_KEYMGMT_up_ref>,
    method_destruct=0x6fe701 <EVP_KEYMGMT_free>) at crypto/property/property.c:292
#6  0x00000000006f22a8 in put_evp_method_in_store (store=0x1b92bd0, method=0x7f0a8004f990, prov=0x1b96300, names=0xa2d0ff "ED25519:1.3.101.112", propdef=0xa2bb33 "provider=default", data=0x7f0aa4ff1740) at crypto/evp/evp_fetch.c:188
#7  0x00000000007208f0 in ossl_method_construct_this (provider=0x1b96300, algo=0xda5420 <deflt_keymgmt+256>, no_store=0, cbdata=0x7f0aa4ff15d0) at crypto/core_fetch.c:87
#8  0x00000000007204b1 in algorithm_do_this (provider=0x1b96300, cbdata=0x7f0aa4ff1530) at crypto/core_algorithm.c:65
#9  0x0000000000732a64 in ossl_provider_doall_activated (ctx=0x0, cb=0x7203b4 <algorithm_do_this>, cbdata=0x7f0aa4ff1530) at crypto/provider_core.c:1355
#10 0x00000000007205e1 in ossl_algorithm_do_all (libctx=0x0, operation_id=10, provider=0x0, pre=0x720719 <ossl_method_construct_precondition>, fn=0x720848 <ossl_method_construct_this>,
    post=0x7207b3 <ossl_method_construct_postcondition>, data=0x7f0aa4ff15d0) at crypto/core_algorithm.c:109
#11 0x0000000000720a3d in ossl_method_construct (libctx=0x0, operation_id=10, provider_rw=0x7f0aa4ff1640, force_store=0, mcm=0x7f0aa4ff1650, mcm_data=0x7f0aa4ff1740) at crypto/core_fetch.c:122
#12 0x00000000006f26a5 in inner_evp_generic_fetch (methdata=0x7f0aa4ff1740, prov=0x0, operation_id=10, name_id=0, name=0x0, properties=0x0, new_method=0x6fdf75 <keymgmt_from_algorithm>, up_ref_method=0x6fe6c8 <EVP_KEYMGMT_up_ref>,
    free_method=0x6fe701 <EVP_KEYMGMT_free>) at crypto/evp/evp_fetch.c:320
#13 0x00000000006f31a5 in evp_generic_do_all (libctx=0x0, operation_id=10, user_fn=0x6ba41c <collect_keymgmt>, user_arg=0x7f0a8004e880, new_method=0x6fdf75 <keymgmt_from_algorithm>, up_ref_method=0x6fe6c8 <EVP_KEYMGMT_up_ref>,
    free_method=0x6fe701 <EVP_KEYMGMT_free>) at crypto/evp/evp_fetch.c:620
#14 0x00000000006fe863 in EVP_KEYMGMT_do_all_provided (libctx=0x0, fn=0x6ba41c <collect_keymgmt>, arg=0x7f0a8004e880) at crypto/evp/keymgmt_meth.c:289
#15 0x00000000006ba828 in ossl_decoder_ctx_setup_for_pkey (ctx=0x7f0a8004f920, pkey=0x7f0a8004e2a0, keytype=0x7f0aa4ff1930 "id-ecPublicKey", libctx=0x0, propquery=0x0) at crypto/encode_decode/decoder_pkey.c:347
#16 0x00000000006baaee in OSSL_DECODER_CTX_new_for_pkey (pkey=0x7f0a8004e2a0, input_type=0xa2aacd "DER", input_structure=0xa2aab8 "SubjectPublicKeyInfo", keytype=0x7f0aa4ff1930 "id-ecPublicKey", selection=134, libctx=0x0,
    propquery=0x0) at crypto/encode_decode/decoder_pkey.c:451
#17 0x00000000008077d3 in x509_pubkey_ex_d2i_ex (pval=0x7f0a8004e6a0, in=0x7f0aa4ff1b38, len=188, it=0xd7a480 <local_it.24640>, tag=-1, aclass=0, opt=0 '\000', ctx=0x7f0aa4ff2040, libctx=0x0, propq=0x0) at crypto/x509/x_pubkey.c:208
#18 0x00000000005bba27 in asn1_item_embed_d2i (pval=0x7f0a8004e6a0, in=0x7f0aa4ff1b38, len=188, it=0xd7a480 <local_it.24640>, tag=-1, aclass=0, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=3, libctx=0x0, propq=0x0)
    at crypto/asn1/tasn_dec.c:262
#19 0x00000000005bcda8 in asn1_template_noexp_d2i (val=0x7f0a8004e6a0, in=0x7f0aa4ff1c78, len=188, tt=0xda2050 <X509_CINF_seq_tt+240>, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=2, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:682
#20 0x00000000005bc835 in asn1_template_ex_d2i (val=0x7f0a8004e6a0, in=0x7f0aa4ff1c78, inlen=188, tt=0xda2050 <X509_CINF_seq_tt+240>, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=2, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:558
#21 0x00000000005bc22e in asn1_item_embed_d2i (pval=0x7f0aa4ff1d90, in=0x7f0aa4ff1d88, len=188, it=0xd7a600 <local_it.21425>, tag=16, aclass=0, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=2, libctx=0x0, propq=0x0)
    at crypto/asn1/tasn_dec.c:422
#22 0x00000000005bcda8 in asn1_template_noexp_d2i (val=0x7f0aa4ff1d90, in=0x7f0aa4ff1ec8, len=686, tt=0xda2100 <X509_seq_tt>, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=1, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:682
#23 0x00000000005bc835 in asn1_template_ex_d2i (val=0x7f0a8004e650, in=0x7f0aa4ff1ec8, inlen=686, tt=0xda2100 <X509_seq_tt>, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=1, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:558
#24 0x00000000005bc22e in asn1_item_embed_d2i (pval=0x7f0a8004efc0, in=0x7f0aa4ff2128, len=686, it=0xd7a640 <local_it.21466>, tag=16, aclass=0, opt=0 '\000', ctx=0x7f0aa4ff2040, depth=1, libctx=0x0, propq=0x0)
    at crypto/asn1/tasn_dec.c:422
#25 0x00000000005bb3f9 in asn1_item_ex_d2i_intern (pval=0x7f0a8004efc0, in=0x7f0aa4ff2128, len=690, it=0xd7a640 <local_it.21466>, tag=-1, aclass=0, opt=0 '\000', ctx=0x7f0aa4ff2040, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:118
#26 0x00000000005bb4e2 in ASN1_item_d2i_ex (pval=0x7f0a8004efc0, in=0x7f0aa4ff2128, len=690, it=0xd7a640 <local_it.21466>, libctx=0x0, propq=0x0) at crypto/asn1/tasn_dec.c:144
#27 0x00000000005bb536 in ASN1_item_d2i (pval=0x7f0a8004efc0, in=0x7f0aa4ff2128, len=690, it=0xd7a640 <local_it.21466>) at crypto/asn1/tasn_dec.c:154
#28 0x0000000000809f6e in d2i_X509 (a=0x7f0a8004efc0, in=0x7f0aa4ff2128, len=690) at crypto/x509/x_x509.c:138
#29 0x000000000074d2bf in PEM_X509_INFO_read_bio_ex (bp=0x7f0a80000eb0, sk=0x0, cb=0x0, u=0xa2587b, libctx=0x0, propq=0x0) at crypto/pem/pem_info.c:168
#30 0x00000000007d0aa9 in X509_load_cert_crl_file_ex (ctx=0x7f0a80000c10, file=0x7fff1f5a8e5c "/etc/pki/tls/cert.pem", type=1, libctx=0x0, propq=0x0) at crypto/x509/by_file.c:231
#31 0x00000000007d02f7 in by_file_ctrl_ex (ctx=0x7f0a80000c10, cmd=1, argp=0x0, argl=3, ret=0x0, libctx=0x0, propq=0x0) at crypto/x509/by_file.c:59
#32 0x00000000007f400c in X509_LOOKUP_ctrl_ex (ctx=0x7f0a80000c10, cmd=1, argc=0x0, argl=3, ret=0x0, libctx=0x0, propq=0x0) at crypto/x509/x509_lu.c:80
#33 0x00000000007f4099 in X509_LOOKUP_ctrl (ctx=0x7f0a80000c10, cmd=1, argc=0x0, argl=3, ret=0x0) at crypto/x509/x509_lu.c:89
#34 0x00000000004ed4a1 in ssl_load_CAs (id=id@entry=50, force=force@entry=1) at /home/cwyang/v10/xaguar/src/ssl_util.c:4022
```

Frame #34: I call `X509_LOOKUP_load_file`.
Frame #30: It's the file `/etc/pki/tls/cert.pem`, the default cert bundle of centos.
Frame #16: OpenSSL tries to decode DER publickey, with type id-ecPublicKey.
Frame #6: OpenSSL tries to put evp method in store, with names "ED25519" curve.
Frame #0~#4: OpenSSL tries to flush cahe and get a crash in `doall_util_fn()` of crypto/lhash/lhash.c:225

```
static void doall_util_fn(OPENSSL_LHASH *lh, int use_arg,
                          OPENSSL_LH_DOALL_FUNC func,
                          OPENSSL_LH_DOALL_FUNCARG func_arg, void *arg)
{
    int i;
    OPENSSL_LH_NODE *a, *n;

    if (lh == NULL)
        return;

    /*
     * reverse the order so we search from 'top to bottom' We were having
     * memory leaks otherwise
     */
    for (i = lh->num_nodes - 1; i >= 0; i--) {
        a = lh->b[i];
        while (a != NULL) {
            n = a->next;                // <-------- Line 225
            if (use_arg)
                func_arg(a->data, arg);
            else
                func(a->data);
            a = n;
        }
    }
}
```

I marked line 225 above. and `a` gets invalid pointer.
```
(gdb) p a
$3 = (OPENSSL_LH_NODE *) 0x200
(gdb) p a->next
Cannot access memory at address 0x208
```

Best regards,
Chul-Woong

**Comment by t8m** [comment]
Is this a multithreaded application?

**Comment by cwyang** [comment]
Yes, but above backtrace happend at init state, before spawning multithread workers.
It happend with Intel QAT OpenSSL engine enabled, and we roll-backed the app for above crash.

**Comment by t8m** [comment]
Hmm, the important information is that the Intel QAT engine is enabled.

**Comment by t8m** [comment]
Please note we are looking for community help implementing this issue. Please comment if you are interested in fixing the bug or if you have reasons why this bug is important enough so we should consider implementing it with higher priority than other requests. The issue will be closed after 2 months otherwise.

**Comment by t8m** [comment]
This issue was closed because it was marked with the help wanted label and there was no interest in implementing this issue or any other activity for more than 2 months.
