### ISSUE TITLE
SIGSEGV when registering an engine for default ciphers used by drbg (occurred inside sshd)

### ISSUE THREAD

**Issue by juergenchrist** [openssl/openssl#18578]
When registering an engine for default ciphers used by the DRBG implementation, a process receives a SIGSEGV when running cleanup hooks at exit.  This occurs, e.g., in the monitor child of sshd and leads to a connection termination.  Debugging it, I get this stack trace when the SIGSEGV hits:
```
(gdb) where
#0  0x000003fffd3ac9d8 in pthread_rwlock_wrlock@GLIBC_2.2 () from /lib64/libc.so.6
#1  0x000003fffdaafeb2 in CRYPTO_THREAD_write_lock (lock=<optimized out>) at crypto/threads_pthread.c:100
#2  0x000003fffda5aaf2 in ENGINE_finish (e=0x2aa00105690) at crypto/engine/eng_init.c:106
#3  0x000003fffda7ddd4 in EVP_CIPHER_CTX_reset (ctx=ctx@entry=0x2aa001c4ae0) at crypto/evp/evp_enc.c:61
#4  0x000003fffda7de1c in EVP_CIPHER_CTX_free (ctx=0x2aa001c4ae0) at crypto/evp/evp_enc.c:76
#5  EVP_CIPHER_CTX_free (ctx=0x2aa001c4ae0) at crypto/evp/evp_enc.c:72
#6  0x000003fffdb71acc in drbg_ctr_free (vdrbg=0x2aa00106b20) at providers/implementations/rands/drbg_ctr.c:617
#7  0x000003fffda83af0 in EVP_RAND_CTX_free (ctx=0x2aa001b4d80) at crypto/evp/evp_rand.c:385
#8  EVP_RAND_CTX_free (ctx=<optimized out>) at crypto/evp/evp_rand.c:373
#9  0x000003fffdadeec2 in rand_ossl_ctx_free (vdgbl=0x2aa001af760) at crypto/rand/rand_lib.c:482
#10 rand_ossl_ctx_free (vdgbl=0x2aa001af760) at crypto/rand/rand_lib.c:472
#11 0x000003fffdaa7e7c in CRYPTO_free_ex_data (class_index=class_index@entry=16, obj=<optimized out>, obj@entry=0x0, ad=ad@entry=0x3fffdcbf148 <default_context_int.lto_priv+8>) at crypto/ex_data.c:402
#12 0x000003fffdaa7ffa in context_deinit (ctx=0x3fffdcbf140 <default_context_int.lto_priv>) at crypto/context.c:167
#13 0x000003fffdaaad1e in context_deinit (ctx=<optimized out>) at crypto/context.c:155
#14 ossl_lib_ctx_default_deinit () at crypto/context.c:194
#15 OPENSSL_cleanup () at crypto/init.c:423
#16 OPENSSL_cleanup () at crypto/init.c:337
#17 0x000003fffd35b90c in __run_exit_handlers () from /lib64/libc.so.6
#18 0x000003fffd35b9d0 in exit () from /lib64/libc.so.6
#19 0x000002aa000116c6 in main (ac=<optimized out>, av=<optimized out>) at sshd.c:2362
```

Looking into the details I found that `global_engine_lock` is already NULL since it was already deleted in `engine_cleanup_int` which already finished (see `OPENSSL_cleanup`).  However, the RAND_GLOBAL structure for the default library context still has a reference to an EVP_CTX that is associated with the engine.

This was detected in OpenSSL version 3.0.1, but should still be present.

**Comment by bernd-edlinger** [comment]
This seems to be the same underlying issue as #18024
originally reported as #17995 #17532
