### ISSUE TITLE
OpenSSL segmentation fault

### ISSUE THREAD

**Issue by tom130380** [openssl/openssl#18582]
Issue was found in OpenSSL 1.1.1o but was there already in older versions.
root@mymachine~]# python3
Python 3.8.2 (default, Jun 14 2022, 12:56:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1o  3 May 2022'

I'm getting a segmentation fault when do_handshake() is being called after a client was connected before, got disconnected and reconnects again. 
```
 Fatal Python error: Segmentation fault
 Thread 0x00007faf075e4700 (most recent call first):
  File "/tmp/sims_venv/lib/python3.8/site-packages/dtls/sslconnection.py", line 495 in _wrap_socket_library_call
  File "/tmp/sims_venv/lib/python3.8/site-packages/dtls/sslconnection.py", line 782 in read
  File "/usr/local/lib/python3.8/ssl.py", line 1101 in read
  File "/usr/local/lib/python3.8/ssl.py", line 1226 in recv
  File "/my_repos/mysim/dtls/dtls_server.py", line 254 in _recv_procedure
  File "/my_repos/mysim/helpers/connection_handler.py", line 167 in receive
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81 in _run
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859 in _run_once
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570 in run_forever
  File "/my_repos/mysim/dtls/dtls_server.py", line 440 in handle
  File "/usr/local/lib/python3.8/socketserver.py", line 720 in __init__
  File "/usr/local/lib/python3.8/socketserver.py", line 360 in finish_request
  File "/usr/local/lib/python3.8/socketserver.py", line 650 in process_request_thread
  File "/usr/local/lib/python3.8/threading.py", line 870 in run
  File "/usr/local/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/lib/python3.8/threading.py", line 890 in _bootstrap
```
This is the gdb backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2188700 (LWP 21873)]
_PyFunction_Vectorcall (func=func@entry=0x7fffe8a1d1f0, stack=0x7fffe31c0218, nargsf=nargsf@entry=3, kwnames=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:406
406     /tmp/python3.8/Python-3.8.2/Objects/call.c: No such file or directory.
(gdb)   backtrace
#0  _PyFunction_Vectorcall (func=func@entry=0x7fffe8a1d1f0, stack=0x7fffe31c0218, nargsf=nargsf@entry=3, kwnames=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:406
#1  0x00007ffff78dd8fc in PyVectorcall_Call (callable=0x7fffe8a1d1f0, tuple=<optimized out>, kwargs=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:199
#2  0x00007fffebb4a24e in _CallPythonObject (pArgs=<optimized out>, flags=257, converters=0x7fffebf7cac0, callable=0x7fffe8a1d1f0, setfunc=0x0, restype=0x7fffebd596e0 <ffi_type_void>, mem=0x7fffe2186110)
    at /tmp/python3.8/Python-3.8.2/Modules/_ctypes/callbacks.c:237
#3  closure_fcn (cif=<optimized out>, resp=0x7fffe2186110, args=0x7fffe2185f70, userdata=<optimized out>) at /tmp/python3.8/Python-3.8.2/Modules/_ctypes/callbacks.c:297
#4  0x00007fffeb937bdb in ffi_closure_unix64_inner () from /lib64/libffi.so.6
#5  0x00007fffeb937f54 in ffi_closure_unix64 () from /lib64/libffi.so.6
#6  0x00007fffee443859 in state_machine () from /opt/openssl/lib/libssl.so.1.1
#7  0x00007fffee42ee78 in SSL_do_handshake () from /opt/openssl/lib/libssl.so.1.1
#8  0x00007fffeb937dec in ffi_call_unix64 () from /lib64/libffi.so.6
#9  0x00007fffeb937715 in ffi_call () from /lib64/libffi.so.6
#10 0x00007fffebb4bf5b in _call_function_pointer (argcount=1, resmem=0x7fffe21863b0, restype=<optimized out>, atypes=<optimized out>, avalues=0x7fffe2186390, pProc=0x7fffee42ee30 <SSL_do_handshake>, flags=4353)
    at /tmp/python3.8/Python-3.8.2/Modules/_ctypes/callproc.c:871
#11 _ctypes_callproc (pProc=pProc@entry=0x7fffee42ee30 <SSL_do_handshake>, argtuple=argtuple@entry=0x7fffe96ff0a0, flags=4353, argtypes=argtypes@entry=0x7fffeb903700, restype=0x8940f0, checker=0x0)
    at /tmp/python3.8/Python-3.8.2/Modules/_ctypes/callproc.c:1199
#12 0x00007fffebb45a5f in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=0x0) at /tmp/python3.8/Python-3.8.2/Modules/_ctypes/_ctypes.c:4201
#13 0x00007ffff78db8c1 in _PyObject_MakeTpCall (callable=0x7fffeb90a340, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:159
#14 0x00007ffff78b2ba3 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:125
#15 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4987
#16 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3500
#17 0x00007ffff79cf62a in _PyEval_EvalCodeWithName (_co=0x7fffebfce7c0, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=0, kwnames=0x0, kwargs=kwargs@entry=0x7fffd8000ef8, kwcount=0, 
    kwstep=kwstep@entry=1, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x7fffe96f7280, name=0x7ffff7e4fd70, qualname=0x7fffebfc5c90)
    at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4298
#18 0x00007ffff78db6a2 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:435
#19 0x00007ffff78b12a4 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#20 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#21 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#22 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3500
#23 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=3, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#24 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#25 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#26 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#27 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#28 0x00007ffff79cf62a in _PyEval_EvalCodeWithName (_co=0x7fffebfce870, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=kwargs@entry=0x7fffe3192b30, kwcount=0, 
    kwstep=kwstep@entry=1, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=0x7fffefea36f0, qualname=0x7fffebfcdd50) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4298
#29 0x00007ffff78db6a2 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:435
#30 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#31 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#32 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#33 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#34 0x00007ffff79cf62a in _PyEval_EvalCodeWithName (_co=0x7fffee8c4870, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=kwargs@entry=0x7fffe31ba568, kwcount=0, 
    kwstep=kwstep@entry=1, defs=defs@entry=0x7fffee8bfc88, defcount=defcount@entry=1, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=0x7fffefea36f0, qualname=0x7fffee8c3e40)
    at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4298
#35 0x00007ffff78db6a2 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:435
#36 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#37 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#38 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#39 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#40 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#41 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#42 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#43 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#44 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#45 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=4, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#46 0x00007ffff78dd78f in _PyObject_FastCallDict (callable=callable@entry=0x7fffeff20940, args=args@entry=0x7fffe2187370, nargsf=nargsf@entry=4, kwargs=kwargs@entry=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:96
#47 0x00007ffff78dd87e in _PyObject_Call_Prepend (callable=callable@entry=0x7fffeff20940, obj=obj@entry=0x7fffe31c2a30, args=args@entry=0x7fffe319e740, kwargs=kwargs@entry=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:887
#48 0x00007ffff7942b29 in slot_tp_init (self=0x7fffe31c2a30, args=0x7fffe319e740, kwds=0x0) at /tmp/python3.8/Python-3.8.2/Objects/typeobject.c:6755
#49 0x00007ffff793c453 in type_call (type=<optimized out>, args=0x7fffe319e740, kwds=0x0) at /tmp/python3.8/Python-3.8.2/Objects/typeobject.c:991
#50 0x00007ffff78db8c1 in _PyObject_MakeTpCall (callable=0xc147f0, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /tmp/python3.8/Python-3.8.2/Objects/call.c:159
#51 0x00007ffff78b4e29 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:125
#52 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4987
#53 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3469
#54 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=3, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#55 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#56 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#57 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#58 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#59 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=3, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#60 0x00007ffff78df444 in _PyObject_Vectorcall (kwnames=0x0, nargsf=3, args=0x7fffe2187830, callable=0x7fffeff20790) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#61 method_vectorcall (method=method@entry=0x7fffe31c0540, args=0x7fffe319ef18, nargsf=nargsf@entry=2, kwnames=0x0) at /tmp/python3.8/Python-3.8.2/Objects/classobject.c:89
#62 0x00007ffff78dd8fc in PyVectorcall_Call (callable=0x7fffe31c0540, tuple=<optimized out>, kwargs=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:199
#63 0x00007ffff78b18dd in do_call_core (kwdict=0x7fffe31c3400, callargs=0x7fffe319ef00, func=0x7fffe31c0540, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:5034
#64 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3559
#65 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#66 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#67 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#68 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
---Type <return> to continue, or q <return> to quit---  
#69 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#70 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#71 0x00007ffff78ad77b in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#72 trace_call_function (kwnames=<optimized out>, nargs=<optimized out>, args=<optimized out>, func=<optimized out>, tstate=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4968
#73 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x7fffdc02bff0) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:4984
#74 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/ceval.c:3486
#75 0x00007ffff78ab790 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:283
#76 0x00007ffff78df48b in _PyObject_Vectorcall (kwnames=0x0, nargsf=1, args=0x7fffe2187e10, callable=0x7fffeff19ee0) at /tmp/python3.8/Python-3.8.2/Include/cpython/abstract.h:127
#77 method_vectorcall (method=method@entry=0x7fffe31c0800, args=0x7ffff7f9f058, nargsf=nargsf@entry=0, kwnames=0x0) at /tmp/python3.8/Python-3.8.2/Objects/classobject.c:67
#78 0x00007ffff78dd8fc in PyVectorcall_Call (callable=0x7fffe31c0800, tuple=<optimized out>, kwargs=<optimized out>) at /tmp/python3.8/Python-3.8.2/Objects/call.c:199
#79 0x00007ffff7a7fe9a in t_bootstrap (boot_raw=boot_raw@entry=0x7fffe31c2960) at /tmp/python3.8/Python-3.8.2/Modules/_threadmodule.c:1002
#80 0x00007ffff7a25617 in pythread_wrapper (arg=<optimized out>) at /tmp/python3.8/Python-3.8.2/Python/thread_pthread.h:232
#81 0x00007ffff73f4ea5 in start_thread () from /lib64/libpthread.so.0
#82 0x00007ffff6a14b0d in clone () from /lib64/libc.so.6
```

Any idea how to further debug of fix this would be much appreciated.

**Comment by mattcaswell** [comment]
Using a debug build of OpenSSL might help to give a better stack trace.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
