### ISSUE TITLE
openssl3.0.5 dlopen failed: "/data/data/com.huawei.caas.agent/lib/libcryptotsc.so" has unexpected e_machine: 40

### ISSUE THREAD

**Issue by 18709226050** [openssl/openssl#19288]
I am using the Android emulator, but loading openssl3.x fails.
![Uploading image.png…]()
09-27 02:37:30.595 D/dalvikvm(32035): Trying to load lib /data/data/com.huawei.caas.agent/lib/libcryptotsc.so 0xb0f8bc78

09-27 02:37:30.595 D/houdini (32035): [32035] Open Native Library /data/data/com.huawei.caas.agent/lib/libcryptotsc.so failed.

09-27 02:37:30.595 E/dalvikvm(32035): dlopen("/data/data/com.huawei.caas.agent/lib/libcryptotsc.so") failed: dlopen failed: "/data/data/com.huawei.caas.agent/lib/libcryptotsc.so" has unexpected e_machine: 40

09-27 02:37:30.595 W/dalvikvm(32035): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/huawei/sci/SciDefaultTls;

09-27 02:37:30.595 D/AndroidRuntime(32035): Shutting down VM

09-27 02:37:30.595 W/dalvikvm(32035): threadid=1: thread exiting with uncaught exception (group=0xb0cacb20)

09-27 02:37:30.595 E/RCSCrashHandler(32035): saveCrashInfo2File only for test

09-27 02:37:30.595 E/AndroidRuntime(32035): FATAL EXCEPTION: main

09-27 02:37:30.595 E/AndroidRuntime(32035): Process: com.huawei.caas.agent, PID: 32035

09-27 02:37:30.595 E/AndroidRuntime(32035): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.huawei.caas.agent/lib/libcryptotsc.so" has unexpected e_machine: 40

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at java.lang.Runtime.load(Runtime.java:333)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at java.lang.System.load(System.java:512)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.huawei.sci.SciSys.loadLib(SciSys.java:198)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.huawei.sci.SciDefaultTls.<clinit>(SciDefaultTls.java:11)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.huawei.rcs.tls.DefaultTlsHelper.load(DefaultTlsHelper.java:28)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.huawei.rcs.system.SysApi.loadTls(SysApi.java:925)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.huawei.caas.agent.DemoApplication.onCreate(DemoApplication.java:63)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.os.Handler.dispatchMessage(Handler.java:102)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.os.Looper.loop(Looper.java:136)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at android.app.ActivityThread.main(ActivityThread.java:5001)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at java.lang.reflect.Method.invokeNative(Native Method)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at java.lang.reflect.Method.invoke(Method.java:515)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

09-27 02:37:30.595 E/AndroidRuntime(32035): 	at dalvik.system.NativeStart.main(Native Method)

09-27 02:37:30.595 W/ActivityManager( 1163):   Force finishing activity com.huawei.caas.agent/.Agent

09-27 02:37:30.945 I/WindowManager( 1163): Screenshot max retries 4 of Token{589e18a4 ActivityRecord{58977fd0 u0 com.huawei.caas.agent/.Agent t681 f}} appWin=Window{5891fa20 u0 Starting com.huawei.caas.agent} drawState=3

09-27 02:37:30.945 W/WindowManager( 1163): Screenshot failure taking screenshot for (768x1280) to layer 21005

**Comment by xtkoba** [comment]
Seems like you are using ARM binaries. If your Android emulator is for x86_64, then of course it won't work.

**Comment by 18709226050** [comment]
> Seems like you are using ARM binaries. If your Android emulator is for x86_64, then of course it won't work.

I use other binaries is ARM , no problem, only openssl binaries has a problem.

**Comment by t8m** [comment]
This question has help wanted label for extended period of time. Closing as we depend on community support for Android.
