### ISSUE TITLE
test_thread intermittently hangs while running tests

### ISSUE THREAD

**Issue by tmshort** [openssl/openssl#19437]
When running tests, I have noticed that test_threads hangs intermittently. I don't know the exact cause nor where it's hanging. On the master branch:
```
$ ./config -g --strict-warnings
...
$ make -sj4
...
$ make test HARNESS_JOBS=4
...
80-test_cmp_http.t ................. ok
90-test_store.t .................... ok
90-test_threads.t .................. ^Cmake[1]: *** [Makefile:3373: run_tests] Interrupt
make: *** [Makefile:3369: tests] Interrupt
$
```
It had been hanging for about 16 hours.

This is a placeholder in case others see this issue, and so that I can have a place to put additional information.

**Comment by tmshort** [comment]
Can easily be reproduced:
```
$ uname -a
Linux tshort-vm 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ git log --oneline -1
fdc5043d58 (HEAD -> master, upstream/master) ripemd: document as being present in the default provider
$ git clean -fdxq
$ ./config -g --strict-warnings && make -sj4
...
$ while /bin/true; do make test TESTS=test_threads; done
...
```
The above eventually hangs.

GDB info:
```
(gdb) info threads
  Id   Target Id                                         Frame 
  1    Thread 0x7efdc1ce9740 (LWP 2025474) "threadstest" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7efdbc011248) at ../sysdeps/nptl/futex-internal.h:183
* 2    Thread 0x7efdbb7fe700 (LWP 2025538) "threadstest" __pthread_clockjoin_ex (threadid=139628220761856, thread_return=thread_return@entry=0x7efdbb7fdea0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:145
(gdb) info stack
#0  __pthread_clockjoin_ex (threadid=139628220761856, thread_return=thread_return@entry=0x7efdbb7fdea0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:145
#1  0x00007efdc1ee79f3 in __pthread_join (threadid=<optimized out>, thread_return=thread_return@entry=0x7efdbb7fdea0) at pthread_join.c:24
#2  0x000055580d2503af in ossl_crypto_thread_native_join (thread=0x55580d70ceb0, retval=0x0) at crypto/thread/arch/thread_posix.c:90
#3  0x000055580d1e20cf in test_thread_native_multiple_joins_fn3 () at test/threadstest.c:286
#4  0x000055580d250469 in thread_start_thunk (vthread=0x55580d6e8f60) at crypto/thread/arch/thread_posix.c:28
#5  0x00007efdc1ee6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007efdc1e0b133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread 1
[Switching to thread 1 (Thread 0x7efdc1ce9740 (LWP 2025474))]
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7efdbc011248) at ../sysdeps/nptl/futex-internal.h:183
183	../sysdeps/nptl/futex-internal.h: No such file or directory.
(gdb) info stack
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7efdbc011248) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55580d6bbde0, cond=0x7efdbc011220) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7efdbc011220, mutex=0x55580d6bbde0) at pthread_cond_wait.c:647
#3  0x000055580d250339 in ossl_crypto_condvar_wait (cv=<optimized out>, mutex=<optimized out>) at crypto/thread/arch/thread_posix.c:244
#4  0x000055580d25038d in ossl_crypto_thread_native_join (thread=thread@entry=0x55580d6e8f60, retval=retval@entry=0x0) at crypto/thread/arch/thread_posix.c:83
#5  0x000055580d1e0d40 in test_thread_native_multiple_joins () at test/threadstest.c:1049
#6  0x000055580d1e7c87 in run_tests (test_prog_name=<optimized out>) at test/testutil/driver.c:334
#7  0x000055580d1e0076 in main (argc=<optimized out>, argv=0x7ffec3849c78) at test/testutil/main.c:30
(gdb)
```
AFAICT, three additional threads are created, but there are only 2 threads running by the time I attach (so two have gone away). The main thread is waiting on a join of thread `t2`:
```
    if (!TEST_int_eq(ossl_crypto_thread_native_join(t2, NULL), 1))
```
Thread 2 is `t2`, based on the thread function (`#3 test_thread_native_multiple_joins_fn3` in the stack above)

**Comment by t8m** [comment]
This is already being worked on in https://github.com/openssl/openssl/pull/19433

**Comment by t8m** [comment]
@ckalina might be interested in the above comment.

**Comment by t8m** [comment]
Fixed now for linux and macosx builds. There is still some problem with the threadstest on Windows on buildbot so I'll keep this open.

**Comment by mouse07410** [comment]
It's not intermittent on MacOS at all - it's 100% consistent.

```
$ make test TESTS="test_threads" V=1
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _tests
( SRCTOP=. \
	  BLDTOP=. \
	  PERL="/opt/local/bin/perl5.34" \
	  FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
	  EXE_EXT= \
	  /opt/local/bin/perl5.34 ./test/run_tests.pl test_threads )
00-prep_fipsmodule_cnf.t .. 
# The results of this test will end up in test-runs/prep_fipsmodule
1..0 # SKIP FIPS module config file only supported in a fips build
skipped: FIPS module config file only supported in a fips build
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr  0.01 sys +  0.13 cusr  0.03 csys =  0.17 CPU)
Result: NOTESTS
90-test_threads.t .. 
# The results of this test will end up in test-runs/test_threads
1..2
    # Subtest: ../../test/threadstest
    1..19
    ok 1 - test_multi_default
    ok 2 - test_lock
    ok 3 - test_once
    ok 4 - test_thread_local
    ok 5 - test_atomic
    ok 6 - test_multi_load
    ok 7 - test_multi_general_worker_default_provider
    # SKIP:  @ test/threadstest.c:512
    # FIPS not supported
    ok 8 - test_multi_general_worker_fips_provider # skipped
    ok 9 - test_multi_fetch_worker
    ok 10 - test_multi_shared_pkey
    ok 11 - test_multi_downgrade_shared_pkey
    ok 12 - test_multi_load_unload_provider
    ok 13 - test_obj_add
    ok 14 - test_lib_ctx_load_config
    ok 15 - test_bio_dgram_pair
    ok 16 - test_thread_reported_flags


[and here it hangs]
```

**Comment by ckalina** [comment]
@mouse07410 do you have https://github.com/openssl/openssl/commit/6ca4bd2e4c92531e74acba3e1ff08e6fbb664b20 and https://github.com/openssl/openssl/commit/4e43bc06f7673597a99f61325543449e72070c8c applied? does it still hang with the 2 patches?

**Comment by mouse07410** [comment]
@ckalina I confirm that the above commits remedy the MacOS problem.

```
All tests successful.
Files=265, Tests=3411, 565 wallclock secs ( 4.93 usr  0.79 sys + 229.48 cusr 102.40 csys = 337.60 CPU)
Result: PASS
```
