### ISSUE TITLE
OpenSSL build failing CentOS 5.5

### ISSUE THREAD

**Issue by manavchouhan** [openssl/openssl#20053]
Install for Open SSL 3.0.7 is failing on CentOS. 

Commands used-
1. ./Configure --prefix=$PREFIX threads shared
2. make
3. make test

make test is failing.
failed test - 90-test_threads.t

Above test is failing on executing "make test".

The Software configurations for the machine are-
1. CentOS version - 5.5 
5. gcc version- 4.1.2
6. Perl version - 5.20.0

Is there any minimum software requirement for OpenSSL 3.0.x?

Thank you so much in advance.

**Comment by t8m** [comment]
Could you please run `make test TESTS='test_threads' V=1` and show us the output?

**Comment by manavchouhan** [comment]
Thanks for the reply

Please find the output below:
-----------------------------------------------------------------------------------------
( SRCTOP=. \
          BLDTOP=. \
          PERL="/mnt/disk1/runtime/perl-5.20_thread/perl_build/bin/perl" \
          FIPSKEY="f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813" \
          EXE_EXT= \
          /mnt/disk1/runtime/perl-5.20_thread/perl_build/bin/perl ./test/run_tests.pl test_threads )
00-prep_fipsmodule_cnf.t ..
# The results of this test will end up in test-runs/prep_fipsmodule
1..0 # SKIP FIPS module config file only supported in a fips build
skipped: FIPS module config file only supported in a fips build
Files=1, Tests=0,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.14 cusr  0.01 csys =  0.17 CPU)
Result: NOTESTS
90-test_threads.t ..
# The results of this test will end up in test-runs/test_threads
1..2
    # Subtest: ../../test/threadstest
    1..8
    ok 1 - test_multi_default
    ok 2 - test_lock
    ok 3 - test_once
    ok 4 - test_thread_local
    ok 5 - test_atomic
    ok 6 - test_multi_load
        # Subtest: test_multi
        1..6
        ok 1 - iteration 1
        # SKIP:
        # FIPS not supported
        #
        ok 2 - iteration 2 # skipped
        ok 3 - iteration 3
        ok 4 - iteration 4
        ok 5 - iteration 5
        ok 6 - iteration 6
    ok 7 - test_multi
../../util/wrap.pl ../../test/threadstest -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf ../../test/recipes/90-test_threads_data => 139
not ok 1 - running test_threads

#   Failed test 'running test_threads'
#   at test/recipes/90-test_threads.t line 28.
readline() on closed filehandle CFGINC at test/recipes/90-test_threads.t line 49.
    # Subtest: ../../test/threadstest_fips
    1..1
    ok 1 - test_fips_rand_leak
../../util/wrap.pl ../../test/threadstest_fips => 0
ok 2 - running test_threads_fips
# Looks like you failed 1 test of 2.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests

Test Summary Report
-------------------
90-test_threads.t (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=2,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.16 cusr  0.03 csys =  0.20 CPU)
Result: FAIL
make[1]: *** [run_tests] Error 1
make[1]: Leaving directory `/mnt/disk1/runtime/OpenSSL3/openssl-3.0.7'
make: *** [tests] Error 2

**Comment by t8m** [comment]
Hmm, the threadstest is crashing. Would you be able to run it under a debugger to find out the backtrace:

```
$ util/wrap.pl gdb test/threadstest

run -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf test/recipes/90-test_threads_data
```

**Comment by manavchouhan** [comment]
On running it under debugger, its failing as below

$ util/wrap.pl gdb test/threadstest 
run -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf test/recipes/90-test_threads_data
Search pattern not terminated at /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/util/perl/OpenSSL/Util.pm line 251.
Compilation failed in require at util/wrap.pl line 12.
BEGIN failed--compilation aborted at util/wrap.pl line 14.

**Comment by t8m** [comment]
That's unfortunately not really useful output.

Could you instead try this:
```
$ LD_LIBRARY_PATH=/mnt/disk1/runtime/OpenSSL3/openssl-3.0.7 gdb test/threadstest
```

And then in the debugger:
```
run -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf test/recipes/90-test_threads_data
```

**Comment by manavchouhan** [comment]
Please find the output below- 

$ run -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf test/recipes/90-test_threads_data
Starting program: /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/threadstest -config /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/test/default.cnf test/recipes/90-test_threads_data
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x2aaaaaaab000
[Thread debugging using libthread_db enabled]
1..8
[New Thread 0x40a00940 (LWP 24385)]
[New Thread 0x41401940 (LWP 24386)]
[Thread 0x40a00940 (LWP 24385) exited]
[Thread 0x41401940 (LWP 24386) exited]
ok 1 - test_multi_default
ok 2 - test_lock
[New Thread 0x41401940 (LWP 24387)]
ok 3 - test_once
[Thread 0x41401940 (LWP 24387) exited]
[New Thread 0x41401940 (LWP 24388)]
[Thread 0x41401940 (LWP 24388) exited]
ok 4 - test_thread_local
ok 5 - test_atomic
 INFO:
 Cannot load legacy provider - assuming this is a no-legacy build
[New Thread 0x41401940 (LWP 24389)]
[New Thread 0x40a00940 (LWP 24390)]
[Thread 0x41401940 (LWP 24389) exited]
[New Thread 0x41e02940 (LWP 24391)]
[Thread 0x40a00940 (LWP 24390) exited]
[New Thread 0x42803940 (LWP 24392)]
[Thread 0x41e02940 (LWP 24391) exited]
[New Thread 0x43204940 (LWP 24393)]
[Thread 0x42803940 (LWP 24392) exited]
[New Thread 0x43c05940 (LWP 24394)]
[Thread 0x43204940 (LWP 24393) exited]
[New Thread 0x44606940 (LWP 24395)]
[Thread 0x43c05940 (LWP 24394) exited]
[New Thread 0x45007940 (LWP 24396)]
[Thread 0x44606940 (LWP 24395) exited]
[New Thread 0x45a08940 (LWP 24397)]
[Thread 0x45007940 (LWP 24396) exited]
[New Thread 0x46409940 (LWP 24398)]
[Thread 0x45a08940 (LWP 24397) exited]
ok 6 - test_multi_load
     Subtest: test_multi
    1..6
[Thread 0x46409940 (LWP 24398) exited]
[New Thread 0x46409940 (LWP 24399)]
[New Thread 0x45a08940 (LWP 24400)]
[Thread 0x46409940 (LWP 24399) exited]
    ok 1 - iteration 1
     SKIP:
     [Thread 0x45a08940 (LWP 24400) exited]
FIPS not supported
    
    ok 2 - iteration 2  skipped
[New Thread 0x45a08940 (LWP 24401)]
[New Thread 0x46409940 (LWP 24402)]
[Thread 0x46409940 (LWP 24402) exited]
    ok 3 - iteration 3
[Thread 0x45a08940 (LWP 24401) exited]
[New Thread 0x46409940 (LWP 24403)]
[New Thread 0x45a08940 (LWP 24404)]
[Thread 0x45a08940 (LWP 24404) exited]
[Thread 0x46409940 (LWP 24403) exited]
    ok 4 - iteration 4
[New Thread 0x45a08940 (LWP 24405)]
[New Thread 0x46409940 (LWP 24406)]
[Thread 0x45a08940 (LWP 24405) exited]
[Thread 0x46409940 (LWP 24406) exited]
    ok 5 - iteration 5
[New Thread 0x46409940 (LWP 24407)]
[New Thread 0x45a08940 (LWP 24408)]
[Thread 0x46409940 (LWP 24407) exited]
[Thread 0x45a08940 (LWP 24408) exited]
    ok 6 - iteration 6
ok 7 - test_multi
[New Thread 0x45a08940 (LWP 24409)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x45a08940 (LWP 24409)]
0x00002aaaaac5e52f in ERR_clear_error () from /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/libcrypto.so.3

**Comment by t8m** [comment]
Could you please use the `bt -full` in the debugger to print the backtrace?

**Comment by manavchouhan** [comment]
Its not providing any additional information

(gdb) bt -full
#0  0x00002aaaaac5e52f in ERR_clear_error () from /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/libcrypto.so.3
No symbol table info available.
#1  0x00002aaaaac5e52f in ERR_clear_error () from /mnt/disk1/runtime/OpenSSL3/openssl-3.0.7/libcrypto.so.3
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

**Comment by t8m** [comment]
Then please configure the openssl build with -d option.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
