### ISSUE TITLE
Configuration for OpenSSL for Ubuntu Machine with Java and Python

### ISSUE THREAD

**Issue by Johny-Kandhari** [openssl/openssl#20092]
I have a ubuntu image running in docker container and have python and Java both installed. With image we have installed openssl 3.0.2 and configuration used is as below:
https://github.com/openssl/openssl/blob/master/apps/openssl.cnf

The problem we are facing is that when we start the docker container HTTPS Call get timeout for almost 10 to 15 mins. But after that all calls are successful, so want to know if anything needs to be changed in openssl.cnf

Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[na:na]
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[na:na]
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[na:na]
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[httpclient-4.5.13.jar!/:4.5.13]

**Comment by paulidale** [comment]
At a guess, OpenSSL is trying to locate some entropy to seed it's random number generator.  Make sure your docker contains a reasonable entropy source and that OpenSSL was built such that it can use it.  This often amount to allowing RDRAND or RDSEED instructions in the container.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
