### ISSUE TITLE
x509/verify tools spin CPU high for unexpected processing of PKCS12 files

### ISSUE THREAD

**Issue by MarcSchoenefeld** [openssl/openssl#21103]
The "x509" tool also accepts PKCS#12 files and processes any complex PBE-MAC without further ado. This undocumented and unexpected behavior could allow attackers to disrupt user workflows based on automatic usage of the x509 tool. The attached file is a simple PKCS12 with an empty password and an iteration count of 2147483647. 

     openssl x509 -in mac_sha_iter_maxint.p12

[mac_sha_iter_maxint.zip](https://github.com/openssl/openssl/files/11623613/mac_sha_iter_maxint.zip)

The result is that the x509 spins the CPU to 100% for as long as the iteration needs. For the attached file about half an hour was measured with the time utility. 

Similar result with the "verify" tool.  

Here is the corresponding stack trace in case of the x509 tool, as in current 3.0.x on Ubuntu 22.04: 

(gdb) bt
#0  sha256_block_data_order_avx () at crypto/sha/sha256-x86_64.s:3917
#1  0x00007fa59f12a004 in SHA256_Final (
    md=0x55b5053b8b40 "\377\353\335\373S\341Ҹ\333\301Z\310\017\364\254\246\212*\314PW\232\177\250\365\226\306\352\226\357", <incomplete sequence \374>,
    c=0x55b5053f1070) at ../include/crypto/md32_common.h:215
#2  0x00007fa59f180957 in sha256_internal_final (outsz=<optimized out>, outl=0x7fffd212b6a0, out=<optimized out>, ctx=<optimized out>)
    at ../providers/implementations/digests/sha2_prov.c:72
#3  sha256_internal_final (ctx=<optimized out>, out=<optimized out>, outl=0x7fffd212b6a0, outsz=<optimized out>)
    at ../providers/implementations/digests/sha2_prov.c:72
#4  0x00007fa59f0a4b86 in EVP_DigestFinal_ex (ctx=0x55b5053f0ef0,
    md=0x55b5053b8b40 "\377\353\335\373S\341Ҹ\333\301Z\310\017\364\254\246\212*\314PW\232\177\250\365\226\306\352\226\357", <incomplete sequence \374>,
    isize=0x0) at ../crypto/evp/digest.c:446
#5  0x00007fa59f195f8f in pkcs12kdf_derive (n=32, out=0x7fffd212ba90 "E", md_type=0x55b5053d9dc0, iter=2147483647, id=3, saltlen=<optimized out>,
    salt=<optimized out>, passlen=<optimized out>, pass=<optimized out>) at ../providers/implementations/kdfs/pkcs12kdf.c:103
#6  kdf_pkcs12_derive (params=<optimized out>, keylen=<optimized out>, key=<optimized out>, vctx=<optimized out>)
    at ../providers/implementations/kdfs/pkcs12kdf.c:220
#7  kdf_pkcs12_derive (vctx=<optimized out>, key=<optimized out>, keylen=<optimized out>, params=<optimized out>)
    at ../providers/implementations/kdfs/pkcs12kdf.c:200
#8  0x00007fa59f103bb7 in PKCS12_key_gen_uni_ex (pass=0x55b5053e6460 "", passlen=2, salt=salt@entry=0x55b5053b8a90 "\026", <incomplete sequence \350>,
    saltlen=saltlen@entry=8, id=<optimized out>, id@entry=3, iter=<optimized out>, iter@entry=2147483647, n=32, out=0x7fffd212ba90 "E", md_type=0x55b5053d9dc0,
    libctx=0x0, propq=0x0) at ../crypto/pkcs12/p12_key.c:121
#9  0x00007fa59f1053bc in PKCS12_key_gen_utf8_ex (pass=<optimized out>, passlen=<optimized out>, salt=0x55b5053b8a90 "\026", <incomplete sequence \350>,
    saltlen=8, id=3, iter=2147483647, n=32, out=0x7fffd212ba90 "E", md_type=0x55b5053d9dc0, ctx=0x0, propq=0x0) at ../crypto/pkcs12/p12_key.c:65
#10 0x00007fa59f1b9b16 in pkcs12_gen_mac.constprop.0 (p12=p12@entry=0x55b5053b8b20, pass=0x7fa59f26dd3c "", passlen=0, mac=mac@entry=0x7fffd212bb90 "",
    maclen=maclen@entry=0x7fffd212bb84, pkcs12_key_gen=<optimized out>) at ../crypto/pkcs12/p12_mutl.c:143
#11 0x00007fa59f1040fe in PKCS12_verify_mac (p12=0x55b5053b8b20, pass=<optimized out>, passlen=<optimized out>) at ../crypto/pkcs12/p12_mutl.c:185
#12 0x00007fa59f1b9466 in try_pkcs12.constprop.0 (data=0x7fffd212c140, v=0x7fffd212c630, ctx=0x55b5053a7ca0, propq=<optimized out>, libctx=<optimized out>)
    at ../crypto/store/store_result.c:538
#13 0x00007fa59f133496 in ossl_store_handle_load_result (params=<optimized out>, arg=0x7fffd212c630) at ../crypto/store/store_result.c:146
#14 0x00007fa59f090693 in decoder_process (params=params@entry=0x7fffd212c2e0, arg=arg@entry=0x7fffd212c440) at ../crypto/encode_decode/decoder_lib.c:737
#15 0x00007fa59f1b8939 in any2obj_decode_final.constprop.0 (objtype=<optimized out>, objtype@entry=0, mem=0x55b5053b78c0,
    data_cb=data_cb@entry=0x7fa59f0905f0 <decoder_process>, data_cbarg=data_cbarg@entry=0x7fffd212c440, provctx=<optimized out>)
    at ../providers/implementations/storemgmt/file_store_any2obj.c:76
#16 0x00007fa59f1b126f in der2obj_decode (provctx=<optimized out>, cin=<optimized out>, selection=<optimized out>, data_cb=0x7fa59f0905f0 <decoder_process>,
    data_cbarg=0x7fffd212c440, pw_cb=<optimized out>, pw_cbarg=0x55b505399918) at ../providers/implementations/storemgmt/file_store_any2obj.c:104
#17 0x00007fa59f0908cb in decoder_process (params=params@entry=0x0, arg=arg@entry=0x7fffd212c4d0) at ../crypto/encode_decode/decoder_lib.c:961
#18 0x00007fa59f090ba1 in OSSL_DECODER_from_bio (ctx=0x55b5053998e0, in=0x55b5053a7bf0) at ../crypto/encode_decode/decoder_lib.c:81
#19 0x00007fa59f1b08de in file_load_file (pw_cbarg=0x55b5053a7ce8, pw_cb=0x7fa59f0ef680 <ossl_pw_passphrase_callback_dec>, object_cbarg=0x7fffd212c630,
    object_cb=0x7fa59f133270 <ossl_store_handle_load_result>, ctx=0x55b5053964d0) at ../providers/implementations/storemgmt/file_store.c:536
#20 file_load (loaderctx=0x55b5053964d0, object_cb=0x7fa59f133270 <ossl_store_handle_load_result>, object_cbarg=0x7fffd212c630,
    pw_cb=0x7fa59f0ef680 <ossl_pw_passphrase_callback_dec>, pw_cbarg=0x55b5053a7ce8) at ../providers/implementations/storemgmt/file_store.c:704
#21 0x00007fa59f13184c in OSSL_STORE_load (ctx=0x55b5053a7ca0) at ../crypto/store/store_lib.c:428

The described behavior was observed on  3.0.x as on Ubuntu as well as on a self-compiled 3.1 static build. 

This report was originally filed as security issue, however the project team considered this functional, hence the additional public report.

**Comment by MarcSchoenefeld** [comment]
Similar considerations would apply to any third-party-apps that call ```PKCS12_parse```. This function would also benefit from a safe upper limit, as well as preventing to run all maxint iterations when having a zero length password.

**Comment by t8m** [comment]
The question is what would a safe limit be. I assume that some paranoid people would like to use iteration count high enough for the computation to take 1 minute on contemporary HW for example.

**Comment by nhorman** [comment]
marking as inactive. will close at the end of 3.4 dev barring further input

**Comment by MarcSchoenefeld** [comment]
Yeah, finally inactive. One year after filing this bug not much feedback. 

NIST recommends at least 10000 iterations. (https://pages.nist.gov/800-63-3/sp800-63b.html) . And here are many implementations with a safe (and configurable) limit : 

- .NET has a limit of 600000 iterations (can be changed with setting env var COMPlus_Pkcs12UnspecifiedPasswordIterationLimit, https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b)

- Java has a default of 200000 (https://github.com/openjdk/jdk/blob/6968770b1e918c74fc009e3562a827bb4acbe2d7/src/java.base/share/conf/security/java.security#L1176) 

A probable approach could be to set a default rejection threshold to the maximum of what the above examples do  (this prevents surprises). Furthermore allowing to override this value in the config would keep the "paranoid people" happy for their environments.

**Comment by nhorman** [comment]
Is that not something that can/should be done external to the inner workings of the x509 verify applet however?  Given that the iteration count is extracted from the pcks12 file, which is unknown until such time as we begin verifying the mac, any threshold would just be a guess as to what an appropriate threshold on that particular pkcs12 file would be for the hardware it was validated on.

A better solution would be to recognize that this is a user decision.  I.e. the number of iterations to tolerate (based on the measured run time a user can measure on their hardware), is an instance specific decision.  As such the option to accept or reject a given pkcs12 file is predicated on the users ability to identify what the number of iteration reported in the file is listed as.  i.e. a user should prior to dumping an untrusted pkcs12 file should, as a matter of best practice first identify the number of iterations that the mac in the file reports, and based on that decide weather to commit cpu resources to validating it.

fortunately, we can already almost do this:
```
openssl pkcs12 -in <filename> --nomacver -noout -info
```
reports the number of iterations to the user for us.  The only problem is that, after reporting that information, the pkcs12 applet blindly starts decoding the remainder of the file, which begins consuming large amounts of cpu for this very reason.

A much simpler fix would be something like this

```
diff --git a/apps/pkcs12.c b/apps/pkcs12.c
index e6fbc574a5..16b9883926 100644
--- a/apps/pkcs12.c
+++ b/apps/pkcs12.c
@@ -836,10 +836,12 @@ int pkcs12_main(int argc, char **argv)
     if (out == NULL)
         goto end;
 
-    if (!dump_certs_keys_p12(out, p12, cpass, -1, options, passout, enc)) {
-        BIO_printf(bio_err, "Error outputting keys and certificates\n");
-        ERR_print_errors(bio_err);
-        goto end;
+    if ((options & (NOCERTS | NOKEYS)) != (NOCERTS | NOKEYS)) {
+        if (!dump_certs_keys_p12(out, p12, cpass, -1, options, passout, enc)) {
+            BIO_printf(bio_err, "Error outputting keys and certificates\n");
+            ERR_print_errors(bio_err);
+            goto end;
+        }
     }
```

Which would allow this command:
```
openssl pkcs12 -in <filename> -noout -info -nomacver -nocerts -nokeys
```
To dump the top level pkcs12 information, and skip the decoding of any internal bags, and the cpu cost that comes with it, which gives  a user the information they need to make an informed decision on weather or not to commit to further processing of the embedded data.

**Comment by t8m** [comment]
We could also add a `-nopkcs12` option to these tools that would disable the processing of PKCS12 files completely.
