### ISSUE TITLE
a performance problem in non-blocking mode 

### ISSUE THREAD

**Issue by rdwr-vitalyk** [openssl/openssl#21106]
we noticed that our program(ssl server) spends much time doing __ecp_nistz256_mul_montq

we performed a following test
we used a non-blocking ssl server from this example : 
https://gist.github.com/darrenjs/4645f115d10aa4b5cebf57483ec82eca
linked with openssl 3.1
we connect to it using s_client and establish a session using ECDHE-ECDSA-AES256-GCM-SHA384 ;
added breakpoint in this function ( __ecp_nistz256_mul_montq )

a single handshake in non-blocking server called the function 302 times,
while a usual s_server does it 16 times only.

most of backtraces looked like this(with different addresses): 
```
#0    in __ecp_nistz256_mul_montq () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#1    in ecp_nistz256_point_add_affine () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#2    in ecp_nistz256_points_mul () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#3    in EC_POINTs_mul () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#4    in EC_POINT_mul () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#5    in ecdsa_sign_setup () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#6    in ossl_ecdsa_sign_sig () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#7    in ossl_ecdsa_sign () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#8    in ECDSA_sign () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#9    in pkey_ec_sign () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#10   in EVP_DigestSignFinal () from /disk/opt/openssl11/lib/libcrypto.so.1.1
#11   in tls_construct_server_key_exchange () from /disk/opt/openssl11/lib/libssl.so.1.1
#12   in state_machine () from /disk/opt/openssl11/lib/libssl.so.1.1
#13   in SSL_do_handshake () from /disk/opt/openssl11/lib/libssl.so.1.1
#14   in on_read_cb (src=  "", len=0) at ssl_server_nonblock.c:250
#15   in do_sock_read () at ssl_server_nonblock.c:356
#16   in main (argc=1, argv= ) at ssl_server_nonblock.c:487

```

there is a separate test that is based on proprietary program (non blocking ssl server) that suffers from a similar problem.
it has about 6000 calls of __ecp_nistz256_mul_montq  per handshake.
here is one of many different backtraces ( I refer to it as "ec_validate" trace, and traces of such kind may happen 3000 times in single handshake).
for this proprietary server(linked with openssl 3.1) , there is also a big degradation related to this function, in comparison to  openssl 1.1.1

Please advise , is it possible to prevent some of these calls?
what has changed in 3.1 that could cause increase of number of such calls?
Thank you!

```
  __ecp_nistz256_mul_montq () at crypto/ec/ecp_nistz256-x86_64.s:3484
#1  0x0000000001c82e71 in ecp_nistz256_point_add () at crypto/ec/ecp_nistz256-x86_64.s:4992
#2  0x0000000001ad9387 in ecp_nistz256_windowed_mul (ctx=0xad07180, num=1, point=0x7d, scalar=0xac6f280, r=0xac6f160, group=<optimized out>) at crypto/ec/ecp_nistz256.c:754
#3  ecp_nistz256_points_mul (group=0xacedcb0, r=0xacdec30, scalar=<optimized out>, num=<optimized out>, points=<optimized out>, scalars=<optimized out>, ctx=0xad07180) at crypto/ec/ecp_nistz256.c:1152
#4  0x0000000001ab33b9 in EC_POINT_mul (group=<optimized out>, r=r@entry=0xacdec30, g_scalar=g_scalar@entry=0x0, point=0xaccb620, p_scalar=p_scalar@entry=0xaccc6b0, ctx=<optimized out>,
    ctx@entry=0xad07180) at crypto/ec/ec_lib.c:1143
#5  0x0000000001aafa1d in ossl_ec_key_public_check (eckey=eckey@entry=0xacc0bf0, ctx=ctx@entry=0xad07180) at crypto/ec/ec_key.c:542
#6  0x0000000001bee05b in ec_validate (checktype=<optimized out>, selection=2, keydata=0xacc0bf0) at providers/implementations/keymgmt/ec_kmgmt.c:966
#7  ec_validate (keydata=0xacc0bf0, selection=2, checktype=<optimized out>) at providers/implementations/keymgmt/ec_kmgmt.c:936
#8  0x0000000001b0ef68 in try_provided_check (checktype=<optimized out>, selection=2, ctx=0xacda0b0) at crypto/evp/pmeth_check.c:44
#9  evp_pkey_public_check_combined (ctx=ctx@entry=0xacda0b0, checktype=checktype@entry=0) at crypto/evp/pmeth_check.c:57
#10 0x0000000001b0f08c in EVP_PKEY_public_check (ctx=ctx@entry=0xacda0b0) at crypto/evp/pmeth_check.c:83
#11 0x0000000001b03907 in EVP_PKEY_derive_set_peer_ex (ctx=ctx@entry=0xacbcb30, peer=peer@entry=0xad066f0, validate_peer=validate_peer@entry=1) at crypto/evp/exchange.c:402
#12 0x0000000001b03b6f in EVP_PKEY_derive_set_peer (ctx=ctx@entry=0xacbcb30, peer=peer@entry=0xad066f0) at crypto/evp/exchange.c:502
#13 0x0000000001a12696 in ssl_derive (s=s@entry=0xacded80, privkey=privkey@entry=0xacc0b30, pubkey=pubkey@entry=0xad066f0, gensecret=gensecret@entry=1) at ssl/s3_lib.c:4803
#14 0x0000000001a6121e in tls_process_cke_ecdhe (pkt=0xac6f5c0, s=0xacded80) at ssl/statem/statem_srvr.c:3086
#15 tls_process_client_key_exchange (s=0xacded80, pkt=0xac6f5c0) at ssl/statem/statem_srvr.c:3354
#16 0x0000000001a4d058 in read_state_machine (s=0xacded80) at ssl/statem/statem.c:666
#17 state_machine (s=0xacded80, server=1) at ssl/statem/statem.c:452
#18 0x0000000001a3b609 in ssl3_read_bytes (s=0xacded80, type=23, recvd_type=0x0, buf=0xacf2130 "", len=65536, peek=0, readbytes=0xacdfff0) at ssl/record/rec_layer_s3.c:1335
#19 0x0000000001a11c71 in ssl3_read_internal (readbytes=0xacdfff0, peek=0, len=65536, buf=0xacf2130, s=0xacded80) at ssl/s3_lib.c:4462
#20 ssl3_read (s=0xacded80, buf=0xacf2130, len=65536, readbytes=0xacdfff0) at ssl/s3_lib.c:4486
#21 0x0000000001a7dd67 in async_start_func () at crypto/async/async.c:201
#22 0x00007ffff6afc310 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#23 0x0000000000000000 in ?? ()
 ```

**Comment by t8m** [comment]
It sounds really strange that there would be a difference in number of the calls to this function based on whether the server is using blocking or non-blocking mode. Could it be possibly something else that triggers this difference?

**Comment by nhorman** [comment]
marking as inactive. will close at the end of 3.4 dev barring further input

**Comment by t8m** [comment]
Most likely #24816 is going to resolve the problem.

**Comment by fwh-dc** [comment]
Fix PR was merged. Closing manually.
