### ISSUE TITLE
Can't read a same pfx certificate file after upgrade the openssl to 3.0.2 from 1.1.1f with FIPS enabled.

### ISSUE THREAD

**Issue by Samcoder2000** [openssl/openssl#21270]
Hi there,
We used to use openssl 1.1.1f and we upgraded it to openssl 3.0.2. Our application is using dotnet 7.0. We are seeing this error:
ThrowLevel: 0 >>>>>>
Exception: Interop+Crypto+OpenSslCryptographicException EX79C8A527
Message: error:020000AB:rsa routines::invalid keypair
StackTrace: 
   at Interop.Crypto.DecodePkcs8PrivateKey(ReadOnlySpan`1 source, EvpAlgorithmId algorithmId)
   at System.Security.Cryptography.RSAOpenSsl.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.X509Certificates.OpenSslPkcs12Reader.LoadKey(ReadOnlyMemory`1 pkcs8)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.LoadKey(SafeBagAsn safeBag, ReadOnlySpan`1 password)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.BuildCertsWithKeys(ReadOnlySpan`1 password, CertBagAsn[] certBags, AttributeAsn[][] certBagAttrs, CertAndKey[] certs, Int32 certBagIdx, SafeBagAsn[] keyBags, RentedSubjectPublicKeyInfo[] publicKeyInfos, AsymmetricAlgorithm[] keys, Int32 keyBagIdx)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)

We don't have an issue reading the same certificate when using openssl 1.1.1f, the OS is ubuntu 22.04 with FIPS enabled.
Can you pls let us know why we are seeing this error and how can solve this issue? Thanks.

**Comment by t8m** [comment]
Do you have an example of such pfx file that you could attach here?

**Comment by Samcoder2000** [comment]
I apologise, unfortunately, we are unable to share the PFX file. The error message looks very confusing to me. Is it possible that this issue is caused by "the private key is created with pkcs8 and the cert with pkcs12"?

**Comment by Samcoder2000** [comment]
Thank you for your honesty. I was using the following commands on a FIPS environment using openssl 3.0.2 to generate a test certificate:
```
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -out private_key.pem -aes256
openssl req -new -key private_key.pem -config /etc/ssl/openssl.cnf  -out csr.pem -sha256
openssl x509 -req -in csr.pem -signkey private_key.pem -out certificate.pem -sha256
openssl pkcs12 -export -out certificate.pfx -inkey private_key.pem -in certificate.pem
```
However, I got this error:
```
No cert in -in file 'certificate.pem' matches private key
40A7F2ECA47F0000:error:05800074:x509 certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:405:
```
I was able to use the same commands by using openssl 1.1.1f to create a test certificate on a FIPS environment.  Are there any errors in my commands or what could cause this failure?

**Comment by sriramva-uipath** [comment]
I have the same issue. Is there a resolution?

**Comment by wilsonmpp** [comment]
> Thank you for your honesty. I was using the following commands on a FIPS environment using openssl 3.0.2 to generate a test certificate:
> 
> ```
> openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -out private_key.pem -aes256
> openssl req -new -key private_key.pem -config /etc/ssl/openssl.cnf  -out csr.pem -sha256
> openssl x509 -req -in csr.pem -signkey private_key.pem -out certificate.pem -sha256
> openssl pkcs12 -export -out certificate.pfx -inkey private_key.pem -in certificate.pem
> ```
> 
> However, I got this error:
> 
> ```
> No cert in -in file 'certificate.pem' matches private key
> 40A7F2ECA47F0000:error:05800074:x509 certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:405:
> ```
> 
> I was able to use the same commands by using openssl 1.1.1f to create a test certificate on a FIPS environment. Are there any errors in my commands or what could cause this failure?

Looks like you might have missed a step between creating the certificate.pem client certificate and creating the certificate.pfx key store. Check the certificate.pem contains the correct key chain and they are ordered correctly in the file.
top down e.g.
ClientCert
CAroot

or

ClientCert
CAintermediate
CAroot
