### ISSUE TITLE
coredump in the openssl_1_1_1 when malloc failed

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#21605]
Branch:  https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable

```
#0  __GI___pthread_rwlock_wrlock (rwlock=rwlock@entry=0x0)
    at pthread_rwlock_wrlock.c:27
#1  0x00007ffff7e3bf7d in CRYPTO_THREAD_write_lock (lock=lock@entry=0x0)
    at crypto/threads_pthread.c:78
#2  0x00007ffff7e3c0c1 in CRYPTO_atomic_add (
    val=val@entry=0x55555564e0a0, amount=amount@entry=-1, 
    ret=ret@entry=0x7fffffffd3a4, lock=0x0)
    at crypto/threads_pthread.c:171
#3  0x00007ffff7f6f3fe in SSL_SESSION_free (ss=0x55555564ded0)
    at ssl/ssl_sess.c:753
#4  0x00007ffff7f6f7dc in ssl_session_dup (src=0x55555564ecc0, 
    ticket=ticket@entry=0) at ssl/ssl_sess.c:222
#5  0x00007ffff7f81473 in tls_process_new_session_ticket (
    s=0x55555563caf0, pkt=0x7fffffffd4c0)
    at ssl/statem/statem_clnt.c:2619
#6  0x00007ffff7f7c89d in read_state_machine (s=0x55555563caf0)
    at ssl/statem/statem.c:636
#7  state_machine (s=0x55555563caf0, server=0) at ssl/statem/statem.c:434
#8  0x00007ffff7f53ec1 in ssl3_read_bytes (s=0x55555563caf0, type=23, 
    recvd_type=0x0, buf=0x555555630780 "", len=1024, peek=0, 
    readbytes=0x7fffffffd640) at ssl/record/rec_layer_s3.c:1658
#9  0x00007ffff7f5ac15 in ssl3_read_internal (s=0x55555563caf0, 
    buf=0x555555630780, len=1024, peek=0, readbytes=0x7fffffffd640)
    at ssl/s3_lib.c:4465
#10 0x00007ffff7f65fb7 in SSL_read (s=s@entry=0x55555563caf0, 
    buf=buf@entry=0x555555630780, num=num@entry=1024)
    at ssl/ssl_lib.c:1783
```

**Comment by yangyangtiantianlonglong** [comment]
> Have you seen https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/?

I understand, it's just an issue with my outdated version.
