### ISSUE TITLE
Openssl 3.0.2 crashes in RSAZ_exp52x20_x2_256 call.

### ISSUE THREAD

**Issue by reshke** [openssl/openssl#21890]
Hi! recently we faced following problem with openssl 3.0.2. We compiled new version of our connection pooler to use in on ubuntu-jammy. This is how it crashes:
```
Thread 6 "worker: 1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6daa640 (LWP 2502363)]
0x00007ffff7a8a3aa in RSAZ_exp52x20_x2_256 (out=0x0, base=0x0, exp=0x0, m=0x0, rr=0x0, k0=0x0) at crypto/bn/rsaz_exp_x2.c:263
263	{
(gdb) bt
#0  0x00007ffff7a8a3aa in RSAZ_exp52x20_x2_256 (out=0x0, base=0x0, exp=0x0, m=0x0, rr=0x0, k0=0x0) at crypto/bn/rsaz_exp_x2.c:263
#1  0x00007ffff7a8a283 in ossl_rsaz_mod_exp_avx512_x2 (res1=0x7fffe4062130, base1=0x7fffe4062130, exp1=0x7fffe4053840, m1=0x7fffe404c7d0, rr1=0x7fffe4062f80, k0_1=11420174470509851067,
    res2=0x7fffe4063090, base2=0x7fffe4063090, exp2=0x7fffe4053790, m2=0x7fffe404c200, rr2=0x7fffe4062de0, k0_2=4259672194434942059, factor_size=1024) at crypto/bn/rsaz_exp_x2.c:217
#2  0x00007ffff7a71157 in BN_mod_exp_mont_consttime_x2 (rr1=0x7fffe404c4e0, a1=0x7fffe404c4e0, p1=0x7fffe4053820, m1=0x7fffe4053750, in_mont1=0x7fffe4043aa0, rr2=0x7fffe404c4b0, a2=0x7fffe404c4b0,
    p2=0x7fffe4053770, m2=0x7fffe4053730, in_mont2=0x7fffe404da00, ctx=0x7fffe4061680) at crypto/bn/bn_exp.c:1468
#3  0x00007ffff7c2a86c in rsa_ossl_mod_exp (r0=0x7fffe404c498, I=0x7fffe404c480, rsa=0x7fffe40535c0, ctx=0x7fffe4061680) at crypto/rsa/rsa_ossl.c:701
#4  0x00007ffff7c29578 in rsa_ossl_private_encrypt (flen=256,
    from=0x7fffe4052500 "\\;\207\235\311B\r\220\004J\304~\275\345R?3y\370\266P\342\272\375!R\255\276\364.y\223\265\272\021{\203\060v\203\350\304X\025\326\177c\227\333\033\067.\255̶\224\bO\253,\316\"\243\242\071\260b\032\003\243w0\356J\256s\a\302\325\r\334z\240)c\203\021\200~?hbq\021?\035F\207\274\245O\360\005\065\267%\236\322\343\026\361\355\331*nr\035_Rq\020\262\232\361\036\376\023?qB\347\241$j\tD\200\f7y3{Jk\004W\213\371\200\326\034\364\351۴\322\346g\311\335\037\327릫4g\225N\341\033\273x{C,,\344\005\217\304\364\204G\200m\227\255\303/\030]\245\236K*\214\207\371", <incomplete sequence \304>...,
    to=0x7fffe4043b10 "Ce\373\033\370\177", rsa=0x7fffe40535c0, padding=3) at crypto/rsa/rsa_ossl.c:323
#5  0x00007ffff7c223a1 in RSA_private_encrypt (flen=256,
    from=0x7fffe4052500 "\\;\207\235\311B\r\220\004J\304~\275\345R?3y\370\266P\342\272\375!R\255\276\364.y\223\265\272\021{\203\060v\203\350\304X\025\326\177c\227\333\033\067.\255̶\224\bO\253,\316\"\243\242\071\260b\032\003\243w0\356J\256s\a\302\325\r\334z\240)c\203\021\200~?hbq\021?\035F\207\274\245O\360\005\065\267%\236\322\343\026\361\355\331*nr\035_Rq\020\262\232\361\036\376\023?qB\347\241$j\tD\200\f7y3{Jk\004W\213\371\200\326\034\364\351۴\322\346g\311\335\037\327릫4g\225N\341\033\273x{C,,\344\005\217\304\364\204G\200m\227\255\303/\030]\245\236K*\214\207\371", <incomplete sequence \304>...,
    to=0x7fffe4043b10 "Ce\373\033\370\177", rsa=0x7fffe40535c0, padding=3) at crypto/rsa/rsa_crpt.c:42
#6  0x00007ffff7d1cd86 in rsa_sign (vprsactx=0x7fffe4061530, sig=0x7fffe4043b10 "Ce\373\033\370\177", siglen=0x7ffff6da98b0, sigsize=256,
    tbs=0x7ffff6da9720 "\217\255\032\347\355SX\033ؙiMj\351\035\020\276\332n\327\060\310ܣ\362\060 \002`Ǟ\024\340\230\332\366\377\177", tbslen=32) at providers/implementations/signature/rsa_sig.c:633
#7  0x00007ffff7d1da48 in rsa_digest_sign_final (vprsactx=0x7fffe4061530, sig=0x7fffe4043b10 "Ce\373\033\370\177", siglen=0x7ffff6da98b0, sigsize=256) at providers/implementations/signature/rsa_sig.c:928
#8  0x00007ffff7ba149d in EVP_DigestSignFinal (ctx=0x7fffe4068070, sigret=0x7fffe4043b10 "Ce\373\033\370\177", siglen=0x7ffff6da98b0) at crypto/evp/m_sigver.c:488
#9  0x00007ffff7ba1a0c in EVP_DigestSign (ctx=0x7fffe4068070, sigret=0x7fffe4043b10 "Ce\373\033\370\177", siglen=0x7ffff6da98b0,
    tbs=0x7ffff6da98e0 ' ' <repeats 64 times>, "TLS 1.3, server CertificateVerify", tbslen=146) at crypto/evp/m_sigver.c:589
#10 0x00007ffff7f06c42 in tls_construct_cert_verify (s=0x7fffe4055770, pkt=0x7ffff6da9a10) at ssl/statem/statem_lib.c:360
#11 0x00007ffff7ef7484 in write_state_machine (s=0x7fffe4055770) at ssl/statem/statem.c:855
#12 0x00007ffff7ef6764 in state_machine (s=0x7fffe4055770, server=1) at ssl/statem/statem.c:451
#13 0x00007ffff7ef61ab in ossl_statem_accept (s=0x7fffe4055770) at ssl/statem/statem.c:270
#14 0x00007ffff7eb5907 in SSL_do_handshake (s=0x7fffe4055770) at ssl/ssl_lib.c:3937
#15 0x00007ffff7eb0b7d in SSL_accept (s=0x7fffe4055770) at ssl/ssl_lib.c:1749
#16 0x0000555555598abd in mm_tls_handshake_cb (handle=<optimized out>) at /home/reshke/odyssey/build/third_party/machinarium/sources/tls.c:457
#17 0x000055555559f0a9 in mm_epoll_step (poll=0x7fffec004500, timeout=<optimized out>) at /home/reshke/odyssey/build/third_party/machinarium/sources/epoll.c:79
#18 0x000055555559e575 in mm_loop_step (loop=loop@entry=0x7fffec004458) at /home/reshke/odyssey/build/third_party/machinarium/sources/loop.c:64
#19 0x0000555555597578 in machine_main (arg=0x7fffec004250) at /home/reshke/odyssey/build/third_party/machinarium/sources/machine.c:56
#20 0x00007ffff76e3b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#21 0x00007ffff7775a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
```

This behavior reproduces every time. I have tried to use openssl 1.1.1v - it works fine, no problem detected.

**Comment by t8m** [comment]
Could you please try to build and run this against unmodified openssl-3.0.9 release if it is still reproducible?

**Comment by nhorman** [comment]
marking as inactive, will close at the end of the 3.4 dev cycle unless there is updated input

**Comment by rkhapov** [comment]
For anyone else who has met the same problem, the reason of the SIGSEGV was too small stack size of the thread. We solve this with patch that looks like https://github.com/yandex/odyssey/pull/781
