### ISSUE TITLE
quic client fuzzer OOM

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#21912]
The fuzzer from #19743 can trigger an OOM with this 366 byte file: [oom-db3167c24e178461e363e9fc9c4121d688f8fe34.gz](https://github.com/openssl/openssl/files/12484030/oom-db3167c24e178461e363e9fc9c4121d688f8fe34.gz)
==3625683== ERROR: libFuzzer: out-of-memory (used: 9329Mb; limit: 2048Mb)

**Comment by kroeckx** [comment]
I'm getting this as backtrace:
```
==3926329== ERROR: libFuzzer: out-of-memory (malloc(14460049744))
   To change the out-of-memory limit use -rss_limit_mb=<N>

    #0 0x55d5b3970c61 in __sanitizer_print_stack_trace (/home/kurt/openssl/openssl/fuzz/quic-client+0x113fc61) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #1 0x55d5b39d6385 in fuzzer::PrintStackTrace() (/home/kurt/openssl/openssl/fuzz/quic-client+0x11a5385) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #2 0x55d5b39bb2b5 in fuzzer::Fuzzer::HandleMalloc(unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x118a2b5) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #3 0x55d5b39bb1a6 in fuzzer::MallocHook(void const volatile*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x118a1a6) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #4 0x55d5b3977822 in __sanitizer::RunMallocHooks(void*, unsigned long) (/home/kurt/openssl/openssl/fuzz/quic-client+0x1146822) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #5 0x55d5b38e3d0b in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (/home/kurt/openssl/openssl/fuzz/quic-client+0x10b2d0b) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #6 0x55d5b38e3673 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (/home/kurt/openssl/openssl/fuzz/quic-client+0x10b2673) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #7 0x55d5b3966c7e in malloc (/home/kurt/openssl/openssl/fuzz/quic-client+0x1135c7e) (BuildId: dd59a2d143068b5869dec2c40abfad0b1a81b12e)
    #8 0x55d5b431aedb in CRYPTO_malloc /home/kurt/openssl/openssl/crypto/mem.c:196:11
    #9 0x55d5b431b120 in CRYPTO_zalloc /home/kurt/openssl/openssl/crypto/mem.c:216:11
    #10 0x55d5b3e95180 in depack_do_frame_ack /home/kurt/openssl/openssl/ssl/quic/quic_rx_depack.c:72:26
    #11 0x55d5b3e92952 in depack_process_frames /home/kurt/openssl/openssl/ssl/quic/quic_rx_depack.c:1120:18
    #12 0x55d5b3e9195a in ossl_quic_handle_frames /home/kurt/openssl/openssl/ssl/quic/quic_rx_depack.c:1444:13
    #13 0x55d5b3e456c6 in ch_rx_handle_packet /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:2281:9
    #14 0x55d5b3e3f973 in ch_rx /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:2040:9
    #15 0x55d5b3e390b6 in ch_tick /home/kurt/openssl/openssl/ssl/quic/quic_channel.c:1868:13
    #16 0x55d5b3b664a5 in ossl_quic_reactor_tick /home/kurt/openssl/openssl/ssl/quic/quic_reactor.c:79:5
    #17 0x55d5b3b49ca4 in quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:1488:9
    #18 0x55d5b3b48d1f in ossl_quic_do_handshake /home/kurt/openssl/openssl/ssl/quic/quic_impl.c:1511:11
    #19 0x55d5b3a46bcc in SSL_do_handshake /home/kurt/openssl/openssl/ssl/ssl_lib.c:4689:16
    #20 0x55d5b39a4f89 in FuzzerTestOneInput /home/kurt/openssl/openssl/fuzz/quic-client.c:120:13
```

**Comment by hlandau** [comment]
Isn't this just a standard issue with fuzzer memory usage? It is going to be a bit random whether the memory allocation that ultimately fails when the limit is hit is inside the fuzzer itself or inside OpenSSL code.

Having said that I am not too happy having a malloc in our RXDP code. This can easily be replaced with a scratch area allocated by the QUIC_CHANNEL and I may look at doing this. Probably post-alpha though.

**Comment by kroeckx** [comment]
We should never allow such a large allocation. In this example it's allocating 14 GB. There should be some reasonable size we allow.

**Comment by hlandau** [comment]
Agreed. Working on a fix.

**Comment by hlandau** [comment]
Fix in https://github.com/openssl/openssl/pull/21917

**Comment by kroeckx** [comment]
This was fixed, the commit message didn't say it fixed it.
