### ISSUE TITLE
Memory leaks in CMS_EncryptedData_encrypt

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#21985]
```
../../util/shlib_wrap.sh ../../apps/openssl cms -EncryptedData_encrypt -in ../smcont.txt -outform PEM -aes128 -secretkey 000102030405060708090A0B0C0D0E0F -stream -out test.cms -noout

=================================================================
==5858==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f82d1bab09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f82d13f2be4 in ossl_cms_EncryptedContent_init crypto/cms/cms_enc.c:213
    #2 0x7f82d140926e in CMS_EncryptedData_encrypt_ex crypto/cms/cms_smime.c:238
    #3 0x443891 in cms_main apps/cms.c:1019
    #4 0x467522 in do_cmd apps/openssl.c:418
    #5 0x42611e in main apps/openssl.c:298
    #6 0x7f82d0939f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1 allocation(s).
ed@w-ed:~/ossl/openssl/test/testutil$ ../../util/shlib_wrap.sh ../../apps/openssl cms -EncryptedData_encrypt -in ../smcont.txt -outform PEM -aes128 -stream -out test.cms -noout
Error creating CMS structure
C0E72ED8C37F0000:error:17000082:CMS routines:CMS_EncryptedData_set1_key:no key:crypto/cms/cms_enc.c:231:

=================================================================
==5864==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fc3d7cbb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fc3d76e17b0 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x7fc3d746cba3 in asn1_item_embed_new crypto/asn1/tasn_new.c:136
    #3 0x7fc3d746cdbc in ASN1_item_new_ex crypto/asn1/tasn_new.c:41
    #4 0x7fc3d750c8a9 in CMS_ContentInfo_new_ex crypto/cms/cms_lib.c:54
    #5 0x7fc3d7519255 in CMS_EncryptedData_encrypt_ex crypto/cms/cms_smime.c:235
    #6 0x443891 in cms_main apps/cms.c:1019
    #7 0x467522 in do_cmd apps/openssl.c:418
    #8 0x42611e in main apps/openssl.c:298
    #9 0x7fc3d6a49f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
```

**Comment by t8m** [comment]
Is this on master branch only or other branches too?

**Comment by t8m** [comment]
Interestingly we do not see it in CI - we have similar commands there and we have runs with leaksanitizer.  Is it possibly a consequence of the -noout option?

**Comment by bernd-edlinger** [comment]
> Is this on master branch only or other branches too?

I only tried encountered this on 1.1.1 and 3.0 so far.  I assume it affects all branches.

> nterestingly we do not see it in CI - we have similar commands there and we have runs with leaksanitizer. Is it possibly a consequence of the -noout option?

Yes, I took the command from the test case, and added the -noout option to jump directly from
CMS_EncryptedData_encrypt to CMS_ContentInfo_free as it happened once in my error injection test run,
then I accidentally removed the key and got a slightly different leak.

**Comment by bernd-edlinger** [comment]
Working on a fix, but it is not easy, because the code depends too much on
CMS_dataInit to clean up the key data, but a memory error here leaks memory:
```
diff --git a/crypto/cms/cms_lib.c b/crypto/cms/cms_lib.c
index be4c2c703f..74e28582c3 100644
--- a/crypto/cms/cms_lib.c
+++ b/crypto/cms/cms_lib.c
@@ -59,7 +59,7 @@ BIO *CMS_dataInit(CMS_ContentInfo *cms, BIO *icont)
     if (icont)
         cont = icont;
     else
-        cont = cms_content_bio(cms);
+        cont = NULL; //cms_content_bio(cms);
     if (!cont) {
         CMSerr(CMS_F_CMS_DATAINIT, CMS_R_NO_CONTENT);
         return NULL;
```
