### ISSUE TITLE
Memory leaks in make test get ignored

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#22049]
I noticed a couple of memory leaks are reported by address sanitizer
every time I configure 3.0/3.1 or master with `./config enable-asan`
and run this command `make test V=1 |& tee debug.log`
and although all tests are passed there are memory leaks:
```
$ grep SUMMARY debug.log 
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 40 byte(s) leaked in 1 allocation(s).
SUMMARY: AddressSanitizer: 1452 byte(s) leaked in 24 allocation(s).
SUMMARY: AddressSanitizer: 1452 byte(s) leaked in 24 allocation(s).
SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).
```
the leaks are:

```
Direct leak of 208 byte(s) in 1 object(s) allocated from:
    #0 0x14d1f5afb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x14d1f55217b0 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x14d1f5627ce0 in OSSL_STORE_LOADER_new crypto/store/store_register.c:46
    #3 0x4daa86 in setup_engine_loader apps/lib/engine_loader.c:171
    #4 0x425f4c in apps_startup apps/openssl.c:71
    #5 0x425f4c in main apps/openssl.c:265
    #6 0x14d1f4889f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 208 byte(s) leaked in 1 allocation(s).
```

```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x153ead71b09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x153ead1417b0 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x153ead14539d in wpacket_intern_init_len crypto/packet.c:107
    #3 0x153ead14539d in WPACKET_init_null_der crypto/packet.c:195
    #4 0x153ead3026a9 in prepare_rsa_params providers/implementations/encode_decode/encode_key2any.c:855
    #5 0x153ead30aeca in key_to_pki_pem_priv_bio providers/implementations/encode_decode/encode_key2any.c:289
    #6 0x153ead3072d4 in key2any_encode providers/implementations/encode_decode/encode_key2any.c:1055
    #7 0x153ead3079de in rsapss_to_PrivateKeyInfo_pem_encode providers/implementations/encode_decode/encode_key2any.c:1356
    #8 0x153ead3079de in rsapss_to_PrivateKeyInfo_pem_encode providers/implementations/encode_decode/encode_key2any.c:1356
    #9 0x153ead06d032 in encoder_process crypto/encode_decode/encoder_lib.c:634
    #10 0x153ead06d5fa in OSSL_ENCODER_to_bio crypto/encode_decode/encoder_lib.c:62
    #11 0x484955 in rsa_main apps/rsa.c:400
    #12 0x467522 in do_cmd apps/openssl.c:418
    #13 0x42611e in main apps/openssl.c:298
    #14 0x153eac4a9f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 40 byte(s) leaked in 1 allocation(s).
```

```
Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x1494de4fb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5fc090 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x5d2275 in EVP_PKEY_new crypto/evp/p_lib.c:1447
    #3 0x5de6a3 in EVP_PKEY_fromdata crypto/evp/pmeth_gn.c:378
    #4 0x414673 in get_dh_from_pg_bn test/helpers/predefined_dhparams.c:38
    #5 0x414727 in get_dh_from_pg test/helpers/predefined_dhparams.c:63
    #6 0x414727 in get_dh512 test/helpers/predefined_dhparams.c:86
    #7 0x40de0a in main test/ssl_old_test.c:1516
    #8 0x1494ddc69f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

Indirect leak of 224 byte(s) in 1 object(s) allocated from:
    #0 0x1494de4fb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5fc090 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x612582 in provider_new crypto/provider_core.c:459
    #3 0x612830 in ossl_provider_new crypto/provider_core.c:570
    #4 0x8b8cca in provider_conf_load crypto/provider_conf.c:208
    #5 0x8b8cca in provider_conf_init crypto/provider_conf.c:304
    #6 0x5426de in module_init crypto/conf/conf_mod.c:427
    #7 0x5426de in module_run crypto/conf/conf_mod.c:272
    #8 0x5426de in CONF_modules_load crypto/conf/conf_mod.c:165
    #9 0x543822 in CONF_modules_load_file_ex crypto/conf/conf_mod.c:214
    #10 0x5f3eec in OSSL_LIB_CTX_load_config crypto/context.c:237
    #11 0x4f0945 in test_get_libctx test/testutil/provider.c:36
    #12 0x40aba2 in main test/ssl_old_test.c:1383
    #13 0x1494ddc69f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
...
Indirect leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x1494de4fb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5fe41e in CRYPTO_strdup crypto/o_str.c:27
    #2 0x60e441 in infopair_add crypto/provider_core.c:761
    #3 0x8b8376 in provider_conf_params crypto/provider_conf.c:111
    #4 0x8b82fe in provider_conf_params crypto/provider_conf.c:102
    #5 0x8b8afc in provider_conf_load crypto/provider_conf.c:219
    #6 0x8b8afc in provider_conf_init crypto/provider_conf.c:304
    #7 0x5426de in module_init crypto/conf/conf_mod.c:427
    #8 0x5426de in module_run crypto/conf/conf_mod.c:272
    #9 0x5426de in CONF_modules_load crypto/conf/conf_mod.c:165
    #10 0x543822 in CONF_modules_load_file_ex crypto/conf/conf_mod.c:214
    #11 0x5f3eec in OSSL_LIB_CTX_load_config crypto/context.c:237
    #12 0x4f0945 in test_get_libctx test/testutil/provider.c:36
    #13 0x40aba2 in main test/ssl_old_test.c:1383
    #14 0x1494ddc69f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 1452 byte(s) leaked in 24 allocation(s).
```

```
Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x14969cef309f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x40248d in main test/memleaktest.c:49
    #2 0x14969bc81f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)

SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).
```

Only the last one from memleaktest is not an error.

**Comment by nhorman** [comment]
```
Direct leak of 208 byte(s) in 1 object(s) allocated from:
    #0 0x14d1f5afb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x14d1f55217b0 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x14d1f5627ce0 in OSSL_STORE_LOADER_new crypto/store/store_register.c:46
    #3 0x4daa86 in setup_engine_loader apps/lib/engine_loader.c:171
    #4 0x425f4c in apps_startup apps/openssl.c:71
    #5 0x425f4c in main apps/openssl.c:265
    #6 0x14d1f4889f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
```
looks like a failure to call destroy_engine_loader in apps_startup

```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x153ead71b09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x153ead1417b0 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x153ead14539d in wpacket_intern_init_len crypto/packet.c:107
    #3 0x153ead14539d in WPACKET_init_null_der crypto/packet.c:195
    #4 0x153ead3026a9 in prepare_rsa_params providers/implementations/encode_decode/encode_key2any.c:855
    #5 0x153ead30aeca in key_to_pki_pem_priv_bio providers/implementations/encode_decode/encode_key2any.c:289
    #6 0x153ead3072d4 in key2any_encode providers/implementations/encode_decode/encode_key2any.c:1055
    #7 0x153ead3079de in rsapss_to_PrivateKeyInfo_pem_encode providers/implementations/encode_decode/encode_key2any.c:1356
    #8 0x153ead3079de in rsapss_to_PrivateKeyInfo_pem_encode providers/implementations/encode_decode/encode_key2any.c:1356
    #9 0x153ead06d032 in encoder_process crypto/encode_decode/encoder_lib.c:634
    #10 0x153ead06d5fa in OSSL_ENCODER_to_bio crypto/encode_decode/encoder_lib.c:62
    #11 0x484955 in rsa_main apps/rsa.c:400
    #12 0x467522 in do_cmd apps/openssl.c:418
    #13 0x42611e in main apps/openssl.c:298
    #14 0x153eac4a9f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
```
looks like a missed call to WPACKET_cleanup in an error case in prepare_rsa_params

```
Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x1494de4fb09f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5fc090 in CRYPTO_zalloc crypto/mem.c:197
    #2 0x5d2275 in EVP_PKEY_new crypto/evp/p_lib.c:1447
    #3 0x5de6a3 in EVP_PKEY_fromdata crypto/evp/pmeth_gn.c:378
    #4 0x414673 in get_dh_from_pg_bn test/helpers/predefined_dhparams.c:38
    #5 0x414727 in get_dh_from_pg test/helpers/predefined_dhparams.c:63
    #6 0x414727 in get_dh512 test/helpers/predefined_dhparams.c:86
    #7 0x40de0a in main test/ssl_old_test.c:1516
    #8 0x1494ddc69f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
```
looks like it might be an imbalanced ref counting issue in ssl_old_test.c when we get the dhpkey.  The next two leaks appear to be related. needs a closer look

```
Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x14969cef309f in __interceptor_malloc ../../../../gcc-trunk/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x40248d in main test/memleaktest.c:49
    #2 0x14969bc81f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
```
This is expected, the memleaktest explicitly leaks an allocation to test that asan detects it.

**Comment by paulidale** [comment]
We run with `enable-asan` as part of our on merge testing and fuzzing.  This should have been caught a long time ago.

**Comment by bernd-edlinger** [comment]
Yes, indeed but some test expect a failure exit code, but of course not a memory leak, or a crash.
It looks like the exit code is just 1 when asan has reported something.
We could set `ASAN_OPTIONS=exitcode=2` in those test cases, and check the correct exit code
in the test framework.
