### ISSUE TITLE
call SSL_CTX_new in diffenent thread, received signal SIGSEGV

### ISSUE THREAD

**Issue by didarpin** [openssl/openssl#23172]
I use my own compiled OpenSSL 3.0.12, and run the the following C++ code
```
int main() {
    bool flag = false;                                           

    std::thread thd1([&flag] {
        while (true) {                                           
            while (!flag) continue;
            SSL_CTX_new(TLS_client_method());                    
            sleep(1);
        }                                                        
    });                                                          
    thd1.detach();                                               
                                                                 
    std::thread thd2([&flag] {                                   
        while (true) {                                           
            while (!flag) continue;                                                     
            SSL_CTX_new(TLS_client_method());                    
            sleep(1);                     
        }
    });
    thd2.detach();                                               

     sleep(2);                                     
    flag = true;                                                 
                                                                 
    while (true) sleep(1);        
}   
```

I got a error Segmentation fault.
the callstack is

```
received signal SIGSEGV, Segmentation fault.
3368    ./malloc/malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff751f3fe in __GI___libc_free (mem=0x395de6a1517c3c1e) at ./malloc/malloc.c:3368
#1  0x00007ffff7aed350 in EVP_KEYMGMT_free () from libcrypto.so.3
#2  0x00007ffff7afa5fd in EVP_PKEY_CTX_free () from libcrypto.so.3
#3  0x00007ffff7db41b4 in ?? () from libssl.so.3
#4  0x00007ffff7da9f89 in SSL_CTX_new_ex () from libssl.so.3
#5  0x00005555555b0e00 in operator() (__closure=0x555555c8f548) at test.cpp:275
```

**Comment by nhorman** [comment]
If you could build your library with debugging enabled, it would provide more information as to what might have gone wrong, though by the looks of it, it would seem that an invalid memory address was passed to EVP_KEYMGMT_free.

That said, the reproducer above isn't really a good use case.  It leaks memory on every call to SSL_CTX_new, and so it may be possible that you just hit a memory exhaustion case.

FWIW, however, I built your test case on the latest master, and it seems to run indifinately, so it may be worth trying a bisect on master to see what fixed it.

**Comment by nhorman** [comment]
I also built 3.0.12 this morning, but seem to be unable to reproduce your error with the above test case.  My build/exec commands are:
```
g++ -I/home/nhorman/git/worktrees/openssl/include -L/home/nhorman/git/worktrees/openssl -g -pthread -std=c++11 ./test.cc -lcrypto -lssl

LD_LIBRARY_PATH=$PWD ./a.out
```

**Comment by didarpin** [comment]
Thanks! @nhorman 
To avoid some unnecessary misunderstandings, I have made some modifications to the code: 

```
#include <unistd.h>
#include <thread>
#include <openssl/ssl.h>

void Test1() {
    bool flag = false;

    std::thread thd1([&flag] {
        while (!flag) continue;
        SSL_CTX_new(TLS_client_method());
    });
    thd1.detach();

    std::thread thd2([&flag] {
        while (!flag) continue;
        SSL_CTX_new(TLS_client_method());
        sleep(1);
    });
    thd2.detach();

    sleep(2);
    flag = true;

    while (true) sleep(1);
}
                                         
int main(int argc, char const* argv[]) { 
    Test1();                             
    return 0;                            
}            
```

I have compiled a debug version of OpenSSL so that more detailed call stack information can be displayed during debugging.
I ran the above code and the result is as follows:

```
Starting program: test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7465640 (LWP 4102669)]
[New Thread 0x7ffff6c64640 (LWP 4102670)]

Thread 2 "test_openssl-1." received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7465640 (LWP 4102669)]
0x00007ffff77b1b3e in getrn (lh=0x7ffff0000bd0, data=0x7fffe8000ff0, rhash=0x7ffff7464bb8) at ../src/crypto/lhash/lhash.c:307
307             if (n1->hash != hash) {
(gdb) bt
#0  0x00007ffff77b1b3e in getrn (lh=0x7ffff0000bd0, data=0x7fffe8000ff0, rhash=0x7ffff7464bb8) at ../src/crypto/lhash/lhash.c:307
#1  0x00007ffff77b13a5 in OPENSSL_LH_insert (lh=0x7ffff0000bd0, data=0x7fffe8000ff0) at ../src/crypto/lhash/lhash.c:117
#2  0x00007ffff77d936f in lh_OBJ_NAME_insert (lh=0x7ffff0000bd0, d=0x7fffe8000ff0) at ../src/crypto/objects/obj_local.h:12
#3  0x00007ffff77d9a94 in OBJ_NAME_add (name=0x7ffff7951a54 "DES3", type=2, data=0x7ffff7951a47 "DES-EDE3-CBC") at ../src/crypto/objects/o_names.c:214
#4  0x00007ffff7759254 in openssl_add_all_ciphers_int () at ../src/crypto/evp/c_allc.c:42
#5  0x00007ffff77b7c91 in ossl_init_add_all_ciphers () at ../src/crypto/init.c:211
#6  0x00007ffff77b7c7c in ossl_init_add_all_ciphers_ossl_ () at ../src/crypto/init.c:203
#7  0x00007ffff77cabdb in CRYPTO_THREAD_run_once (once=0x7ffff7a63cb0 <add_all_ciphers>, init=0x7ffff77b7c6f <ossl_init_add_all_ciphers_ossl_>) at ../src/crypto/threads_none.c:70
#8  0x00007ffff77b8281 in OPENSSL_init_crypto (opts=2097228, settings=0x0) at ../src/crypto/init.c:558
#9  0x00007ffff7f1cfdb in OPENSSL_init_ssl (opts=2097228, settings=0x0) at ../src/ssl/ssl_init.c:115
#10 0x00007ffff7f24c8c in SSL_CTX_new_ex (libctx=0x0, propq=0x0, meth=0x7ffff7fb42c0 <TLS_client_method_data.14>) at ../src/ssl/ssl_lib.c:3211
#11 0x00007ffff7f25334 in SSL_CTX_new (meth=0x7ffff7fb42c0 <TLS_client_method_data.14>) at ../src/ssl/ssl_lib.c:3414
#12 0x00005555555552b7 in operator() (__closure=0x55555556beb8) at test_openssl.cpp:10
#13 0x0000555555555ade in std::__invoke_impl<void, Test1()::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#14 0x0000555555555a64 in std::__invoke<Test1()::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:96
#15 0x00005555555559be in std::thread::_Invoker<std::tuple<Test1()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55555556beb8) at /usr/include/c++/11/bits/std_thread.h:259
#16 0x0000555555555966 in std::thread::_Invoker<std::tuple<Test1()::<lambda()> > >::operator()(void) (this=0x55555556beb8) at /usr/include/c++/11/bits/std_thread.h:266
#17 0x000055555555592e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Test1()::<lambda()> > > >::_M_run(void) (this=0x55555556beb0) at /usr/include/c++/11/bits/std_thread.h:211
#18 0x00007ffff7d8d253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff7afdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007ffff7b8f660 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

My development environment and runtime environment are as follows:
```
OS: ubuntu22.04
kernel version: 5.15.0-91-generic
openssl: 3.0.12
gcc: 11.4.0
gdb: 12.1
glibc: 2.35
```

**Comment by mattcaswell** [comment]
I just tried this on my ubuntu 22.04 system with OpenSSL 3.0.12 and your test case and I cannot seem to reproduce it.

Please can you provide the output from the following command (run from the top of the OpenSSL build tree):

````
perl configdata.pm --dump
````

**Comment by didarpin** [comment]
[a.tar.gz](https://github.com/openssl/openssl/files/13830455/a.tar.gz)
I use conan build openssl.
The file “output” contains the output of the "perl configdata.pm --dump" command
The file "20-conan.conf" will be placed in the "Configurations" directory.

**Comment by mattcaswell** [comment]
The cause of your problem is immediately apparent from the configdata.pm output. This tells me what compile time options OpenSSL was built with:

````
    /usr/bin/perl ../src/Configure dp_conan shared no-unit-test no-threads no-tests no-md2 enable-fips --prefix=/home/ubuntu/.conan2/p/b/opens2737afeb59b50/p --libdir=lib --debug
````

Note that OpenSSL was built with the "no-threads" option. That option is described as following in our documentation:

````
### no-threads

Don't build with support for multi-threaded applications.
````

Importantly this build won't do any kind of locking to protect shared/global data. This is why it is failing in your test. Clearly shared/global data is becoming corrupted hence the crash. The solution is not to build OpenSSL with the no-threads option.

**Comment by didarpin** [comment]
Ahh! I didn't notice this option, this is my foolish oversight, thank you for your help!
