### ISSUE TITLE
Failed to download OpenSSL - Incorrect link provided.

### ISSUE THREAD

**Issue by StarSupreme** [openssl/openssl#23351]
I was compiling a kivy app into android. It'd worked fine enough a few days ago. But now, this is the error I'm getting:-
[INFO]:    Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1262, in <module>
    main()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 680, in __init__
    getattr(self, command)(args)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 99, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 158, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 349, in download_if_necessary
    self.download()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 399, in download
    self.download_file(self.versioned_url, filename)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 203, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Download failed: HTTP Error 404: Not Found; retrying in 1 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 2 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 4 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 8 second(s)...

**Comment by 0xdeadbeer** [comment]
Which application are you talking about? The URL for v1.1.1h has probably changed and now returns a 404. Though you can still access it through the [tarball archive](https://ftp.openssl.org/source/old/1.1.1/). Have you considered filing an issue to the application's bug tracker / issues tab?

**Comment by shenyingge** [comment]
Url changed. [https://www.openssl.org/source/old/1.1.1/openssl-1.1.1m.tar.gz](url)

**Comment by mattcaswell** [comment]
The URL should work with or without the "old" in it. There were some technical changes on the website that seem to have broken the version without the "old".
