### ISSUE TITLE
conf_ssl.c is not thread-safe

### ISSUE THREAD

**Issue by space88man** [openssl/openssl#23772]
`conf_ssl.c` is not thread-safe due to the use of static variables - but this begs the question on whether potential callers like `CONF_modules_load_file` are intended to be thread-safe.

Result of the test program below:

```
OPENSSL_CONF=/etc/pki/tls/openssl.cnf ./testprog
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
ending thread...
ending thread...
ending thread...
ending thread...
starting thread.../etc/pki/tls/openssl.cnf
ending thread...
malloc(): unaligned tcache chunk detected
double free or corruption (out)
starting thread.../etc/pki/tls/openssl.cnf
ending thread...
Segmentation fault (core dumped)
```

Create a config that loads conf_ssl
```
...
[openssl_init]
ssl_conf = ssl_module

[ ssl_module ]
system_default = crypto_policy

[ crypto_policy ]
CipherString = @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:kRSAPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
TLS.MinProtocol = TLSv1.2
TLS.MaxProtocol = TLSv1.3
DTLS.MinProtocol = DTLSv1.2
DTLS.MaxProtocol = DTLSv1.2
SignatureAlgorithms = ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ed25519:ed448:rsa_pss_pss_sha256:rsa_pss_pss_sha384:rsa_pss_pss_sha512:rsa_pss_rsae_sha256:rsa_pss_rsae_sha384:rsa_pss_rsae_sha512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224
Groups = X25519:secp256r1:X448:secp521r1:secp384r1:ffdhe2048:ffdhe3072:ffdhe4096:ffdhe6144:ffdhe8192
```

```
#include <stdio.h>
#include <pthread.h>

#include <openssl/conf.h>
#include <openssl/ssl.h>

void *worker(void * arg)
{
    printf("starting thread...%s\n", CONF_get1_default_config_file());
    OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL);
    CONF_modules_load_file(CONF_get1_default_config_file(), NULL, 0UL);
    printf("ending thread...\n");
}

int main(int argc, char** argv)
{

    pthread_t tids[2];

    OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);
    for (int i = 0; i < 16; i++) {
        pthread_create(tids+i, NULL, worker, NULL);
    }
    for (int i = 0; i < 16; i++) {
        pthread_join(tids[i], NULL);
    }
}
```

**Comment by nhorman** [comment]
what version of openssl are you testing with here?

**Comment by space88man** [comment]
> what version of openssl are you testing with here?

Reproduced on 3.2.1

(First encountered on RHEL 9 (3.0.7) and Fedora 39 (3.1.1) - but they heavily patch OpenSSL).

**Comment by nhorman** [comment]
Looking at the code, it certainly doesn't appear thread safe to me.    Though it doesn't really make sense to do what your test case is doing either (why would you want N threads sharing a library instance to initalize the library separately).

We could probably just lock the OSSL_LIB_CTX->lock while loading the config file to avoid the issues, but as a matter of correctness, it doesn't make sense for multiple threads to reload a config file as, dependent on how exactly the threads obtain the config file path, you won't ever be sure what configuration you are working with

**Comment by space88man** [comment]
> Looking at the code, it certainly doesn't appear thread safe to me. Though it doesn't really make sense to do what your test case is doing either (why would you want N threads sharing a library instance to initalize the library separately).
> 
Is there ever a case that one might want to load up a different library context with the config file?

This worker, with a new library contexts, obtains the same segfault

```
void *worker(void * arg)
{
    printf("starting thread...%s\n", CONF_get1_default_config_file());
    //OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL);

    OSSL_LIB_CTX *newlib = OSSL_LIB_CTX_new();
    OSSL_LIB_CTX_load_config(newlib, CONF_get1_default_config_file());
    printf("ending thread...\n");
}
```

**Comment by nhorman** [comment]
Yes, that makes more sense.  If you're getting the same default with separate contexts, that's a problem.

**Comment by space88man** [comment]
Revised reproducer with a more sensible use case — each worker want so use a different library context:


```
#include <pthread.h>

#include <openssl/conf.h>
#include <openssl/ssl.h>

void *worker(void * arg)
{
    printf("starting thread...%s\n", CONF_get1_default_config_file());

    OSSL_LIB_CTX *newlib = OSSL_LIB_CTX_new();
    OSSL_LIB_CTX_load_config(newlib, CONF_get1_default_config_file());
    printf("ending thread...\n");
}

int main(int argc, char** argv)
{

    pthread_t tids[16];

    OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);
    for (int i = 0; i < 16; i++) {
        pthread_create(tids+i, NULL, worker, NULL);
    }
    for (int i = 0; i < 16; i++) {
        pthread_join(tids[i], NULL);
    }
}
```

Typical segfault due to contention of static variables
```
Module libz.so.1 from rpm zlib-1.2.13-4.fc39.x86_64
Module libcrypto.so.3 from rpm openssl-3.1.1-4.fc39.x86_64
Module libssl.so.3 from rpm openssl-3.1.1-4.fc39.x86_64
Stack trace of thread 2024305:
#0  0x00007fa2c62bd385 free (libc.so.6 + 0x9f385)
#1  0x00007fa2c6511021 ssl_module_free.part.0 (libcrypto.so.3 + 0x111021)
#2  0x00007fa2c6514c51 ssl_module_init (libcrypto.so.3 + 0x114c51)
#3  0x00007fa2c6517c25 CONF_modules_load (libcrypto.so.3 + 0x117c25)
#4  0x00007fa2c65181da CONF_modules_load_file_ex (libcrypto.so.3 + 0x1181da)
#5  0x00007fa2c65b90b1 OSSL_LIB_CTX_load_config (libcrypto.so.3 + 0x1b90b1)
#6  0x00000000004011d9 worker (breaker + 0x11d9)
#7  0x00007fa2c62ac897 start_thread (libc.so.6 + 0x8e897)
#8  0x00007fa2c633380c __clone3 (libc.so.6 + 0x11580c)
```

**Comment by nhorman** [comment]
you've got a few issues in your test case.  I can reproduce your issue as-is, but the test case leaks memory.  Specifically:
1) The call to CONF_get1_default_config_file returns a string that the caller is responsible for freeing (the get1 notation indicates that)
2) Each thread has to clean up its library context.  If you don't do that memory will leak

If I modify your test case as follows:
```
#include <pthread.h>

#include <openssl/conf.h>
#include <openssl/ssl.h>

void *worker(void * arg)
{
    char *file = CONF_get1_default_config_file();

    printf("starting thread...%s\n", file);

    OSSL_LIB_CTX *newlib = OSSL_LIB_CTX_new();
    OSSL_LIB_CTX_load_config(newlib, file);
    printf("ending thread...\n");
    OSSL_LIB_CTX_free(newlib);
    OPENSSL_free(file);
}

int main(int argc, char** argv)
{

    pthread_t tids[16];

    OPENSSL_init_crypto(OPENSSL_INIT_NO_ATEXIT, NULL);
    for (int i = 0; i < 16; i++) {
        pthread_create(tids+i, NULL, worker, NULL);
    }
    for (int i = 0; i < 16; i++) {
        pthread_join(tids[i], NULL);
    }
}
```

and build with asan enabled, it runs without issue, on the master branch, and the releases you've specified.

```
nhorman@hmsvengance:~/git/worktrees/quic$ LD_LIBRARY_PATH=$PWD ./a.out 
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
starting thread.../usr/local/ssl/openssl.cnf
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
ending thread...
nhorman@hmsvengance:~/git/worktrees/quic$ 
```

**Comment by space88man** [comment]
> you've got a few issues in your test case. I can reproduce your issue as-is, but the test case leaks memory. Specifically:
> 
> and build with asan enabled, it runs without issue, on the master branch, and the releases you've specified.

Hmmm ... still getting ...segfault ...

```
gcc -o testfile testfile.c  -O2 -g -fsanitize=address  -lssl -lcrypto

...
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
starting thread.../etc/pki/tls/openssl.cnf
=================================================================
==2038993==ERROR: AddressSanitizer: attempting double-free on 0x602000010c30 in thread T5:
ending thread...
ending thread...
ending thread...
...

0x602000010c30 is located 0 bytes inside of 15-byte region [0x602000010c30,0x602000010c3f)
freed by thread T9 here:
    #0 0x7ff873cd7fb8 in __interceptor_free.part.0 (/lib64/libasan.so.8+0xd7fb8) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x7ff873710ff2 in ssl_module_free.part.0 (/lib64/libcrypto.so.3+0x110ff2) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #2 0x7ff873714c50 in ssl_module_init (/lib64/libcrypto.so.3+0x114c50) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #3 0x7ff873717c24 in CONF_modules_load (/lib64/libcrypto.so.3+0x117c24) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #4 0x7ff8737181d9 in CONF_modules_load_file_ex (/lib64/libcrypto.so.3+0x1181d9) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #5 0x7ff8737b90b0 in OSSL_LIB_CTX_load_config (/lib64/libcrypto.so.3+0x1b90b0) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #6 0x4013cf in worker /work/richard/Projects/openssl/temp/breaker1.c:13

previously allocated by thread T10 here:
    #0 0x7ff873cd92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x7ff8737b6672 in CRYPTO_strdup (/lib64/libcrypto.so.3+0x1b6672) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #2 0x7ff873714ce3 in ssl_module_init (/lib64/libcrypto.so.3+0x114ce3) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #3 0x7ff873717c24 in CONF_modules_load (/lib64/libcrypto.so.3+0x117c24) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
    #4 0x7ff8737181d9 in CONF_modules_load_file_ex (/lib64/libcrypto.so.3+0x1181d9) (BuildId: 5d012dcc6f62f35dabb8a129d641e3df7b731f11)
```

**Comment by nhorman** [comment]
to your questions:
I used this config, set via OPENSSL_CONF
```
openssl_conf = openssl_init

# Comment out the next line to ignore configuration errors
config_diagnostics = 1

[openssl_init]
ssl_conf = ssl_module

[ ssl_module ]
system_default = crypto_policy

[ crypto_policy ]
CipherString = @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:kRSAPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
TLS.MinProtocol = TLSv1.2
TLS.MaxProtocol = TLSv1.3
DTLS.MinProtocol = DTLSv1.2
DTLS.MaxProtocol = DTLSv1.2
SignatureAlgorithms = ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ed25519:ed448:rsa_pss_pss_sha256:rsa_pss_pss_sha384:rsa_pss_pss_sha512:rsa_pss_rsae_sha256:rsa_pss_rsae_sha384:rsa_pss_rsae_sha512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224
Groups = X25519:secp256r1:X448:secp521r1:secp384r1:ffdhe2048:ffdhe3072:ffdhe4096:ffdhe6144:ffdhe8192
```
Which was taken from your initial report.  If there are changes required, please let me know

Built against the head of the master branch and the head of the openssl-3.2 branch (I can try again with the openssl-3.2.1 tag, though if it breaks, that would imply that its already been fixed for the next patch release)

Built with enable-asan, which adds -fsanitize=address to the compiler flags.

**Comment by space88man** [comment]
Strange - I still reproduce on both HEAD of 3.2 and master.

Try 3.2 HEAD
```
$ git log
commit 0a59fc590d1ed281fede85c13bca1cc7bd6f1bba
Author: Bernd Edlinger <bernd.edlinger@hotmail.de>
Date:   Wed Feb 28 07:14:08 2024 +0100

    Try to fix intermittent CI failures in sslapitest

$ SSLDIR=/openssl/builds
$ BUILD=3.2.x-asan
$ ./Configure --prefix=$SSLDIR/$BUILD --openssldir=$SSLDIR/$BUILD \
            zlib enable-camellia enable-seed enable-rfc3779 enable-sctp \
            enable-cms enable-md2 enable-rc5 enable-ktls enable-fips\
            no-mdc2 no-ec2m no-sm2 no-sm4 enable-asan --debug

$ OPENSSL_CONF=/etc/pki/tls/openssl.cnf LD_LIBRARY_PATH=../builds/3.2.x-asan/lib64 ./testfile
=================================================================
==157161==ERROR: AddressSanitizer: attempting double-free on 0x602000013c30 in thread T4:
    #0 0x7f7b3d6d7fb8 in __interceptor_free.part.0 (/lib64/libasan.so.8+0xd7fb8) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x7f7b3cf32105 in CRYPTO_free crypto/mem.c:282
    #2 0x7f7b3cd3e107 in ssl_module_free crypto/conf/conf_ssl.c:49
    #3 0x7f7b3cd3e3b8 in ssl_module_init crypto/conf/conf_ssl.c:80
    #4 0x7f7b3cd3cfb8 in module_init crypto/conf/conf_mod.c:425
    #5 0x7f7b3cd3c87f in module_run crypto/conf/conf_mod.c:272
    #6 0x7f7b3cd3c542 in CONF_modules_load crypto/conf/conf_mod.c:165
    #7 0x7f7b3cd3c6ad in CONF_modules_load_file_ex crypto/conf/conf_mod.c:214
    #8 0x7f7b3cf26c5e in OSSL_LIB_CTX_load_config crypto/context.c:468
    #9 0x4013cf in worker /work/richard/Projects/openssl/temp/breaker1.c:13
    #10 0x7f7b3c8ac896 in start_thread (/lib64/libc.so.6+0x8e896) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)
    #11 0x7f7b3c93380b in clone3 (/lib64/libc.so.6+0x11580b) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)

0x602000013c30 is located 0 bytes inside of 15-byte region [0x602000013c30,0x602000013c3f)
freed by thread T6 here:
    #0 0x7f7b3d6d7fb8 in __interceptor_free.part.0 (/lib64/libasan.so.8+0xd7fb8) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x7f7b3cf32105 in CRYPTO_free crypto/mem.c:282
    #2 0x7f7b3cd3e107 in ssl_module_free crypto/conf/conf_ssl.c:49
    #3 0x7f7b3cd3e3b8 in ssl_module_init crypto/conf/conf_ssl.c:80
    #4 0x7f7b3cd3cfb8 in module_init crypto/conf/conf_mod.c:425
    #5 0x7f7b3cd3c87f in module_run crypto/conf/conf_mod.c:272
    #6 0x7f7b3cd3c542 in CONF_modules_load crypto/conf/conf_mod.c:165
    #7 0x7f7b3cd3c6ad in CONF_modules_load_file_ex crypto/conf/conf_mod.c:214
    #8 0x7f7b3cf26c5e in OSSL_LIB_CTX_load_config crypto/context.c:468
    #9 0x4013cf in worker /work/richard/Projects/openssl/temp/breaker1.c:13

previously allocated by thread T13 here:
    #0 0x7f7b3d6d92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x7f7b3cf31e79 in CRYPTO_malloc crypto/mem.c:202
    #2 0x7f7b3cf348ae in CRYPTO_strdup crypto/o_str.c:27
    #3 0x7f7b3cd3e5ad in ssl_module_init crypto/conf/conf_ssl.c:100
    #4 0x7f7b3cd3cfb8 in module_init crypto/conf/conf_mod.c:425
    #5 0x7f7b3cd3c87f in module_run crypto/conf/conf_mod.c:272
    #6 0x7f7b3cd3c542 in CONF_modules_load crypto/conf/conf_mod.c:165
    #7 0x7f7b3cd3c6ad in CONF_modules_load_file_ex crypto/conf/conf_mod.c:214
    #8 0x7f7b3cf26c5e in OSSL_LIB_CTX_load_config crypto/context.c:468
    #9 0x4013cf in worker /work/richard/Projects/openssl/temp/breaker1.c:13

Thread T4 created by T0 here:
    #0 0x7f7b3d648956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x4011c8 in main /work/richard/Projects/openssl/temp/breaker1.c:30

Thread T6 created by T0 here:
    #0 0x7f7b3d648956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x4011c8 in main /work/richard/Projects/openssl/temp/breaker1.c:30

Thread T13 created by T0 here:
    #0 0x7f7b3d648956 in pthread_create (/lib64/libasan.so.8+0x48956) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
    #1 0x4011c8 in main /work/richard/Projects/openssl/temp/breaker1.c:30

SUMMARY: AddressSanitizer: double-free (/lib64/libasan.so.8+0xd7fb8) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c) in __interceptor_free.part.0
==157161==ABORTING
```

**Comment by space88man** [comment]
Debian carries this patch located here: http://deb.debian.org/debian/pool/main/o/openssl/openssl_3.0.11-1~deb12u2.debian.tar.xz

```
 From: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
Date: Mon, 19 Sep 2022 20:51:31 +0200
Subject: conf: Serialize allocation/free of ssl_names.

The access to `ssl_names' is not fully serialized. With multiple threads
it is possible that more than one thread starts to clean up `ssl_names'.
This leads to occasional segfaults if more than one terminates and
performs the clean up.

Fixes: #19243

Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
---
 crypto/conf/conf_ssl.c | 35 ++++++++++++++++++++++++++++++++---
 1 file changed, 32 insertions(+), 3 deletions(-)

diff --git a/crypto/conf/conf_ssl.c b/crypto/conf/conf_ssl.c
index 84c5b2afe581..d6596e60c3b5 100644
--- a/crypto/conf/conf_ssl.c
+++ b/crypto/conf/conf_ssl.c
@@ -12,6 +12,7 @@
 #include <openssl/conf.h>
 #include <openssl/err.h>
 #include "internal/sslconf.h"
+#include "internal/thread_once.h"
 #include "conf_local.h"
 
 /*
@@ -35,12 +36,25 @@ struct ssl_conf_cmd_st {
     char *arg;
 };
 
+static CRYPTO_ONCE init_ssl_names_lock = CRYPTO_ONCE_STATIC_INIT;
+static CRYPTO_RWLOCK *ssl_names_lock;
 static struct ssl_conf_name_st *ssl_names;
 static size_t ssl_names_count;
 
-static void ssl_module_free(CONF_IMODULE *md)
+DEFINE_RUN_ONCE_STATIC(do_init_ssl_names_lock)
+{
+	ssl_names_lock = CRYPTO_THREAD_lock_new();
+	if (ssl_names_lock == NULL) {
+		ERR_raise(ERR_LIB_CONF, ERR_R_MALLOC_FAILURE);
+		return 0;
+	}
+	return 1;
+}
+
+static void ssl_module_free_unlocked(CONF_IMODULE *md)
 {
     size_t i, j;
+
     if (ssl_names == NULL)
         return;
     for (i = 0; i < ssl_names_count; i++) {
@@ -58,6 +72,14 @@ static void ssl_module_free(CONF_IMODULE *md)
     ssl_names_count = 0;
 }
 
+static void ssl_module_free(CONF_IMODULE *md)
+{
+    if (!CRYPTO_THREAD_write_lock(ssl_names_lock))
+	    return;
+    ssl_module_free_unlocked(md);
+    CRYPTO_THREAD_unlock(ssl_names_lock);
+}
+
 static int ssl_module_init(CONF_IMODULE *md, const CONF *cnf)
 {
     size_t i, j, cnt;
@@ -65,6 +87,12 @@ static int ssl_module_init(CONF_IMODULE *md, const CONF *cnf)
     const char *ssl_conf_section;
     STACK_OF(CONF_VALUE) *cmd_lists;
 
+    if (!RUN_ONCE(&init_ssl_names_lock, do_init_ssl_names_lock))
+        return 0;
+
+    if (!CRYPTO_THREAD_write_lock(ssl_names_lock))
+	    return 0;
+
     ssl_conf_section = CONF_imodule_get_value(md);
     cmd_lists = NCONF_get_section(cnf, ssl_conf_section);
     if (sk_CONF_VALUE_num(cmd_lists) <= 0) {
@@ -77,7 +105,7 @@ static int ssl_module_init(CONF_IMODULE *md, const CONF *cnf)
         goto err;
     }
     cnt = sk_CONF_VALUE_num(cmd_lists);
-    ssl_module_free(md);
+    ssl_module_free_unlocked(md);
     ssl_names = OPENSSL_zalloc(sizeof(*ssl_names) * cnt);
     if (ssl_names == NULL)
         goto err;
@@ -126,7 +154,8 @@ static int ssl_module_init(CONF_IMODULE *md, const CONF *cnf)
     rv = 1;
  err:
     if (rv == 0)
-        ssl_module_free(md);
+        ssl_module_free_unlocked(md);
+    CRYPTO_THREAD_unlock(ssl_names_lock);
     return rv;
 }
```

**Comment by space88man** [comment]
Duplicate of https://github.com/openssl/openssl/pull/19244
See also: https://github.com/openssl/openssl/issues/19243

Closing as deferring to the other issues.
