### ISSUE TITLE
[rt.openssl.org #4596] OpenSSL TLS Version Handling Errors

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2500]
Migrated from [rt.openssl.org#4596](https://rt.openssl.org/Ticket/Display.html?id=4596) (status was 'new')

Requestors:
* hkario@redhat.com

Attachments:
* [signature.asc](https://rt.openssl.org/Ticket/Attachment/69856/43820/signature.asc)

From hkario@redhat.com on 2016-06-28 17:25:56:
```
from RT#2777

On Monday 27 June 2016 20:43:07 Rich Salz via RT wrote:
> please open a new ticket if this is still an issue with current (at least
> 1.0.2, ideally master) sources.

Current 1.0.2 still doesn't handle ClientHello.client_version set to 0x00,0x00
correctly in a 0x03, 0x00 record layer, the connection is just closed without
sending an Alert message.

current master handles all correctly

all test performed:
3, 3 version in 3, 0 record - passed
3, 3 version in 3, 254 record - passed 
254, 254 version in 3, 254 record - passed
254, 254 version in 3, 0 record - passed
0, 0 version in 3, 0 record - fail

(if you think any other values should be checked, feel free to contact me)

reproducer script:
https://github.com/tomato42/tlsfuzzer/blob/master/scripts/test-version-numbers.py

to reproduce:
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/ecdsa ecdsa
PYTHONPATH=. python scripts/test-version-numbers.py
popd
kill $openssl_pid
-- 
Regards,
Hubert Kario
Senior Quality Engineer, QE BaseOS Security team
Web: www.cz.redhat.com
Red Hat Czech s.r.o., PurkyÅova 99/71, 612 45, Brno, Czech Republic
```

**Comment by richsalz** [comment]
@tomato42 is this still an issue ?

**Comment by tomato42** [comment]
yes

<details>
  <summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

low record version (3, 0), TLS1.2 (sanity check) ...
OK

high record version (3, 254), very high protocol version (254, 254) ...
OK

high record version (3, 254), TLS1.2 ...
OK

very high version (254, 254) ...
OK

very low version (0, 0) ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f8b35abe0d0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f8b35abe110>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-version-numbers.py", line 222, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    raise AssertionError("Unexpected closure from peer")
AssertionError: Unexpected closure from peer

sanity ...
OK

Test end
successful: 6
failed: 1
  'very low version (0, 0)'
```
  </p>
</details>

<details>
   <summary>openssl 279bf3e0 output</summary><p>

```
140620332762768:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:643:
```
   </p>
</details>

**Comment by richsalz** [comment]
@tomato42 is this still an issue?
