### ISSUE TITLE
Padding (extra bytes) in CertificateVerify message are not detected

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25298]
using bcf082d130a4

when server is configured to request client certificates, it does not check if the length of the signature in the CertificateVerify message matches the overall length of the message. If there are bytes following the `signature` field, they're ignored.

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www -client_sigalgs RSA+SHA384:rsa_pss_rsae_sha384:rsa_pss_pss_sha384 -verify 1 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-certificate-verify-malformed.py  -k /tmp/localhost.key -c /tmp/localhost.crt  'pad CertificateVerify'
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
verify depth is 1
Using default temp DH parameters
ACCEPT
depth=0 CN=localhost
verify error:num=18:self-signed certificate
verify return:1
depth=0 CN=localhost
verify return:1
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
pad CertificateVerify ...
Error encountered while processing node ExpectAlert(level=2, description=50) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f4556b99520>) with last message being: <tlslite.messages.Message object at 0x7f4556c7d370>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-certificate-verify-malformed.py", line 434, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: ChangeCipherSpec()

Malformed CertificateVerify test

Test end
====================
version: 6
====================
TOTAL: 3
SKIP: 0
PASS: 0
XFAIL: 0
FAIL: 1
XPASS: 0
====================
FAILED:
        'pad CertificateVerify'
```
   </p></details>

**Comment by vdukhovni** [comment]
Does the below patch address this issue:
```c
--- a/ssl/statem/statem_lib.c
+++ b/ssl/statem/statem_lib.c
@@ -516,6 +516,10 @@ MSG_PROCESS_RETURN tls_process_cert_verify(SSL_CONNECTION *s, PACKET *pkt)
         SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_R_LENGTH_MISMATCH);
         goto err;
     }
+    if (PACKET_remaining(pkt) != 0) {
+        SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_R_LENGTH_MISMATCH);
+        goto err;
+    }
 
     if (!get_cert_verify_tbs_data(s, tls13tbs, &hdata, &hdatalen)) {
         /* SSLfatal() already called */
```

**Comment by tomato42** [comment]
yes, it does

**Comment by mattcaswell** [comment]
The suggested patch looks ok to me. @vdukhovni will you raise a PR for it?
