### ISSUE TITLE
Incorrect Alert description for ClientHello with no cipher_suites

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25309]
using 17cb182ad8fa816 (3.2.3-dev)

When the server receives a ClientHello message that doesn't list any cipher suites (the length of the `cipher_suites` field is 0) it rejects the message with `illegal_parameter` instead of `decode_error`, this is despite the field being declared as being at least 2 bytes long:
```
     struct {
          ...
          CipherSuite cipher_suites<2..2^16-2>;
          ...
      } ClientHello;
```

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be necessary after https://github.com/tlsfuzzer/tlsfuzzer/pull/945 is merged
git checkout invalid-client-hello-w-record-overflow-fips
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-invalid-client-hello-w-record-overflow.py -n 0 -C TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -d --ems 'session ID len fuzz to 5 w/ext'
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
403717F1197F0000:error:0A0000B7:SSL routines:ssl_cache_cipherlist:no ciphers specified:ssl/ssl_lib.c:6792:
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

session ID len fuzz to 5 w/ext ...
Error encountered while processing node ExpectAlert(level=2, description=(50,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f39e4efade0>) with last message being: <tlslite.messages.Message object at 0x7f39e493bf80>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-invalid-client-hello-w-record-overflow.py", line 387, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1926, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"

sanity ...
OK

Test end
====================
version: 4
====================
TOTAL: 3
SKIP: 0
PASS: 2
XFAIL: 0
FAIL: 1
XPASS: 0
====================
FAILED:
        'session ID len fuzz to 5 w/ext'
```
   </p></details>

**Comment by vdukhovni** [comment]
I guess the relevant RFC text is from [Section 6 of RFC8446](https://www.rfc-editor.org/rfc/rfc8446.html#section-6):
```
   Note: TLS defines two generic alerts (see Section 6) to use upon
   failure to parse a message.  Peers which receive a message which
   cannot be parsed according to the syntax (e.g., have a length
   extending beyond the message boundary or contain an out-of-range
   length) MUST terminate the connection with a "decode_error" alert.
   Peers which receive a message which is syntactically correct but
   semantically invalid (e.g., a DHE share of p - 1, or an invalid enum)
   MUST terminate the connection with an "illegal_parameter" alert.
```
And it can be reasonably argued that the problem is syntactic, but on the other hand, if the client is not pedantic about the exact ranges needed to ensure interoperability and does manage to parse the message, then the problem is arguably semantic, or perhaps even just a case of no shared ciphers.

So while in principle we should consider to change the code to signal a syntax problem, I don't see this as a priority, can the fuzzer be more forgiving here???

**Comment by ldlb9527** [comment]
Using a `handshake_failure` alert seems appropriate, as the message type (ClientHello) is expected, but the content (an empty cipher suite list) is what causes the failure. Both RFC 5246 and RFC 8446 specify `Mandatory Cipher Suites`, which require the client to propose at least some cipher suites that the server can accept.

**Comment by tomato42** [comment]
>  if the client is not pedantic about the exact ranges needed to ensure interoperability and does manage to parse the message

well, the RFC expects that the client is pedantic... :slightly_smiling_face: 

> So while in principle we should consider to change the code to signal a syntax problem, I don't see this as a priority, can the fuzzer be more forgiving here???

the point of the tlsfuzzer test cases is to be as strict as the RFC descriptions allow, if you think that a particular test is not a big problem you can always run it with `-x 'session ID len fuzz to 5 w/ext' -X 'received "illegal_parameter"'` and the test case will make treat is as expected failure and sure that the server behaviour doesn't change

and yes, it's not a big issue, but when I use those `-x` options to waive the result I also add a comment with a link to the issue so that it's clear that the failure was investigated, root cause found, and either explicitly ignored or fixed on some future version

**Comment by nhorman** [comment]
Wouldn't a zero length cipher suite list be considered "out of range"?  referencing the above RFC outtake above?

the attached patch seems like it should fix it
