### ISSUE TITLE
TLSInnerPlaintext length check missing/incorrect

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25396]
When OpenSSL receives a message that has a TLS record that decrypts to a `TLSInnerPlaintext` of length 2^14 + 2 bytes but with `content` smaller than 2^14 bytes, the record is not rejected. This is in conflict with RFC 8446 section 5.4:
```
   The presence of padding does not change the overall record size
   limitations: the full encoded TLSInnerPlaintext MUST NOT exceed 2^14
   + 1 octets.
```

Reproduced using e2448e622191cc, 3.2.2, and 1.1.1k

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-tls13-record-layer-limits.py "too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_AES_128_GCM_SHA256" "too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256"
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_AES_128_GCM_SHA256 ...
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: <tlslite.messages.Message object at 0x7f73221f37a0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-record-layer-limits.py", line 640, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: ApplicationData(len=3790)

too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256 ...
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: <tlslite.messages.Message object at 0x7f73220fd430>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-record-layer-limits.py", line 640, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: ApplicationData(len=3808)

Verify that too big Application Data messages, with
different ciphers or fuzzed AEAD tag in TLS 1.3 communication 
are rejected with record_overflow alert.

Note that there are three limits: one for TLSCiphertext (encrypted
records, as visible on the line), a second one for
TLSInnertPlaintext (the data that the ciphertext decrypts to) and
a third one for TLSPlaintext (the records that are not encrypted,
like ClientHello).
This test checks all three of them.

See RFC 8446 Section 5.1, 5.2 and 5.4.

Test end
====================
version: 4
====================
TOTAL: 4
SKIP: 0
PASS: 0
XFAIL: 0
FAIL: 2
XPASS: 0
====================
FAILED:
        'too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_AES_128_GCM_SHA256'
        'too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256'
```
   </p></details>

**Comment by andrewkdinh** [comment]
After following the steps, I can reproduce this issue (including from the second comment). OpenSSL will only reject the message if the `TLSInnerPlainText` is much longer than the length of 2^14+2 bytes and print this error to `server.err`:

```
80CBFB0509710000:error:0A0000C6:SSL routines:tls_get_more_records:packet length too long:ssl/record/methods/tls_common.c:662:
80CBFB0509710000:error:0A000139:SSL routines::record layer failure:ssl/record/rec_layer_s3.c:690:
```

I believe this is the required code to update: https://github.com/openssl/openssl/blob/5c82588173d33222b33693f698bc9c7614675e9f/ssl/record/methods/tls_common.c#L660-L664

<details>
<summary>Updated reproducer steps</summary>

```shell
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tlsfuzzer/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-record-layer-limits.py "too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_AES_128_GCM_SHA256" "too big plaintext, size: 2**14 - 8, with an additional 9 bytes of padding, cipher TLS_CHACHA20_POLY1305_SHA256"
popd
kill $openssl_pid
```

If you'd like to manually change the padding, edit the file `scripts/test-tls13-record-layer-limits.py`. For example, I added 1000 extra bytes of padding.

</details>

**Comment by tomato42** [comment]
yes, the external limit of 2^14+256 is actually enforced, so a very long padding will be rejected, it's just the intermediate sizes that aren't
