### ISSUE TITLE
Publicly invalid FFDHE and ECDHE key shares are rejected with internal_error alert

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25402]
When OpenSSL receives a ClientKeyShare message that has a FFDHE key share that's publicly invalid (0, 1, p, p-1), it rejects it with `internal_error` alert instead of the `illegal_parameter`.

Reproduced using e2448e622191cc, 3.2.2, and 1.1.1k

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-dhe-rsa-key-exchange-with-bad-messages.py
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
40B7D365637F0000:error:02800066:Diffie-Hellman routines:ossl_dh_buf2key:invalid public key:crypto/dh/dh_key.c:411:
40B7D365637F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:3085:
40B7D365637F0000:error:02800066:Diffie-Hellman routines:ossl_dh_buf2key:invalid public key:crypto/dh/dh_key.c:411:
40B7D365637F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:3085:
40B7D365637F0000:error:02800066:Diffie-Hellman routines:ossl_dh_buf2key:invalid public key:crypto/dh/dh_key.c:411:
40B7D365637F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:3085:
40B7D365637F0000:error:0A000094:SSL routines:tls_process_cke_dhe:dh public value length is wrong:ssl/statem/statem_srvr.c:3060:
40B7D365637F0000:error:0A000094:SSL routines:tls_process_cke_dhe:dh public value length is wrong:ssl/statem/statem_srvr.c:3060:
40B7D365637F0000:error:02800066:Diffie-Hellman routines:ossl_dh_buf2key:invalid public key:crypto/dh/dh_key.c:411:
40B7D365637F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:3085:
40B7D365637F0000:error:02800066:Diffie-Hellman routines:ossl_dh_buf2key:invalid public key:crypto/dh/dh_key.c:411:
40B7D365637F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:3085:
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

invalid dh_Yc value - p ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fc53b0eee70>) with last message being: <tlslite.messages.Message object at 0x7fc53b0efad0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py", line 380, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

invalid dh_Yc value - 8192b ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fc53b0ecce0>) with last message being: <tlslite.messages.Message object at 0x7fc53b0efa70>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py", line 380, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

invalid dh_Yc value - 1 ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fc53b0eeba0>) with last message being: <tlslite.messages.Message object at 0x7fc53b0efd40>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py", line 380, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

truncated dh_Yc value ...
OK

padded Client Key Exchange ...
OK

invalid dh_Yc value - p-1 ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fc53b0ef170>) with last message being: <tlslite.messages.Message object at 0x7fc53b104b30>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py", line 380, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

invalid dh_Yc value - 0 ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fc53b0ee8a0>) with last message being: <tlslite.messages.Message object at 0x7fc53b1047a0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py", line 380, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

sanity ...
OK

Check if server properly verifies received Client Key Exchange
message. That the extra data (pad) at the end is noticed, that
too short message is rejected and a message with "obviously"
wrong client key share is rejected
Test end
====================
version: 5
====================
TOTAL: 9
SKIP: 0
PASS: 4
XFAIL: 0
FAIL: 5
XPASS: 0
====================
FAILED:
        'invalid dh_Yc value - 0'
        'invalid dh_Yc value - 1'
        'invalid dh_Yc value - 8192b'
        'invalid dh_Yc value - p'
        'invalid dh_Yc value - p-1'
```
   </p></details>

**Comment by tomato42** [comment]
Same thing happens for ECDHE key shares


   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-ecdhe-rsa-key-exchange-with-bad-messages.py
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
40E74313A77F0000:error:0800006B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:879:
40E74313A77F0000:error:0A080010:SSL routines:tls_process_cke_ecdhe:EC lib:ssl/statem/statem_srvr.c:3139:
40E74313A77F0000:error:0A00009F:SSL routines:tls_process_cke_ecdhe:length mismatch:ssl/statem/statem_srvr.c:3124:
40E74313A77F0000:error:0800006B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:879:
40E74313A77F0000:error:0A080010:SSL routines:tls_process_cke_ecdhe:EC lib:ssl/statem/statem_srvr.c:3139:
40E74313A77F0000:error:0800006B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:879:
40E74313A77F0000:error:0A080010:SSL routines:tls_process_cke_ecdhe:EC lib:ssl/statem/statem_srvr.c:3139:
40E74313A77F0000:error:0800006B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:879:
40E74313A77F0000:error:0A080010:SSL routines:tls_process_cke_ecdhe:EC lib:ssl/statem/statem_srvr.c:3139:
40E74313A77F0000:error:0A00009F:SSL routines:tls_process_cke_ecdhe:length mismatch:ssl/statem/statem_srvr.c:3124:
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

invalid point (0, 1) ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f721ae7a420>) with last message being: <tlslite.messages.Message object at 0x7f721adc83b0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-ecdhe-rsa-key-exchange-with-bad-messages.py", line 328, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

truncated ecdh_Yc value ...
OK

invalid point (self-inconsistent) ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f721ac69400>) with last message being: <tlslite.messages.Message object at 0x7f721ac69fa0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-ecdhe-rsa-key-exchange-with-bad-messages.py", line 328, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

invalid point (self-inconsistent, y all zero) ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f721ac69100>) with last message being: <tlslite.messages.Message object at 0x7f721ac6a6c0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-ecdhe-rsa-key-exchange-with-bad-messages.py", line 328, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

invalid point (0, 0) ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f721ac68e00>) with last message being: <tlslite.messages.Message object at 0x7f721ac69fd0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-ecdhe-rsa-key-exchange-with-bad-messages.py", line 328, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

padded Client Key Exchange ...
OK

sanity ...
OK

Test end
====================
version: 4
====================
TOTAL: 8
SKIP: 0
PASS: 4
XFAIL: 0
FAIL: 4
XPASS: 0
====================
FAILED:
        'invalid point (0, 0)'
        'invalid point (0, 1)'
        'invalid point (self-inconsistent)'
        'invalid point (self-inconsistent, y all zero)'
```
   </p></details>

**Comment by andrewkdinh** [comment]
I'm able to reproduce. This is the RFC that says we must return "illegal_parameter": https://www.rfc-editor.org/rfc/rfc8446#section-4.2.8

> Peers which receive a message which is syntactically correct but
   semantically invalid (e.g., a DHE share of p - 1, or an invalid enum)
   MUST terminate the connection with an "illegal_parameter" alert.

**Comment by t8m** [comment]
@andrewkdinh no need to add the `branch: 1.1.1` label. Also please always clear the `issue: ` label when adding a `triaged: label`
