### ISSUE TITLE
unexpected close of connection with compressed certificate in s390x

### ISSUE THREAD

**Issue by GeorgePantelakis** [openssl/openssl#25473]
When a compressed certificate is used we send the following compressed certificate message:

struct {
CertificateCompressionAlgorithm algorithm;
uint24 uncompressed_length;
opaque compressed_certificate_message<1..2^24-1>;
} CompressedCertificate;

When we have a zlib compression bomb in compressed_certificate_message in s390x machines, OpenSSL closes the connection unexpectedly rather than sending a bad_certificate alert.

**Comment by holger-dengler** [comment]
Is this a duplicate to #25470? If not, what is the s390x-specific part of this issue?

**Comment by GeorgePantelakis** [comment]
The specific part is that for this we are not using just a big input but we are using a compression bomb. This is much much bigger than the uncompressed_size variable. In other arches, this is handled correctly and sends back a bad_certificate alert, only in s390x the connection hands. The corresponding test in https://github.com/tlsfuzzer/tlsfuzzer/blob/master/scripts/test-tls13-client-certificate-compression.py is the 'zlib bomb' one.

**Comment by ifranzki** [comment]
I tried to reproduce this on s390x with OpenSSL from the master branch.

I started the server with 
`# openssl s_server -key server.key -cert server.crt -www -Verify 1`
and the script with
`# PYTHONPATH=. python scripts/test-tls13-client-certificate-compression.py -c client.crt -k client.key "zlib bomb"`

And I got the following:

```
# PYTHONPATH=. python scripts/test-tls13-client-certificate-compression.py -c localhost.crt -k localhost.key "zlib bomb"
Log: Preparing compression bombs, this might take a while...
sanity ...
OK

zlib bomb ...
OK

sanity ...
OK

Basic communications with TLS 1.3 servers to test the
compressed certificate message. This test DOES expect that the
server will sent a RequestCertificate message so the clint then
can send its certificate.

Test end
====================
version: 1
====================
TOTAL: 3
SKIP: 0
PASS: 3
XFAIL: 0
FAIL: 0
XPASS: 0
====================

```

When I increased the bomb-size from the default 100MB to 500MB I got the following:

```
# PYTHONPATH=. python scripts/test-tls13-client-certificate-compression.py -c localhost.crt -k localhost.key --bomb-size 500 "zlib bomb"
Log: Preparing compression bombs, this might take a while...
sanity ...
OK

zlib bomb ...
Error encountered while processing node <tlsfuzzer.messages.CompressedCertificateGenerator object at 0x3ffb8c1c5d0> (child: <tlsfuzzer.messages.CertificateVerifyGenerator object at 0x3ffb8c1c610>) with last message being: Compressed Certificate(request_context=b'', certificate_list=[CertificateEntry(certificate=<tlslite.x509.X509 object at 0x3ffb8bd5710>, extensions=[])])
Error while processing
Traceback (most recent call last):
  File "/root/tlsfuzzer/tlsfuzzer/runner.py", line 257, in run
    self.state.msg_sock.sendMessageBlocking(msg)
  File "/usr/local/lib/python3.11/site-packages/tlslite/messagesocket.py", line 186, in sendMessageBlocking
    for _ in self.sendMessage(msg):
  File "/usr/local/lib/python3.11/site-packages/tlslite/messagesocket.py", line 181, in sendMessage
    for res in self.flush():
  File "/usr/local/lib/python3.11/site-packages/tlslite/messagesocket.py", line 121, in flush
    for res in self.sendRecord(msg):
  File "/usr/local/lib/python3.11/site-packages/tlslite/recordlayer.py", line 636, in sendRecord
    for result in self._recordSocket.send(encryptedMessage, padding):
  File "/usr/local/lib/python3.11/site-packages/tlslite/recordlayer.py", line 102, in send
    for result in self._sockSendAll(data):
  File "/usr/local/lib/python3.11/site-packages/tlslite/recordlayer.py", line 68, in _sockSendAll
    bytesSent = self.sock.send(data)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tlslite/bufferedsocket.py", line 35, in send
    return self.socket.send(data)
           ^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tlsfuzzer/scripts/test-tls13-client-certificate-compression.py", line 983, in main
    runner.run()
  File "/root/tlsfuzzer/tlsfuzzer/runner.py", line 271, in run
    raise AssertionError("Unexpected closure from peer")
AssertionError: Unexpected closure from peer

sanity ...
OK

Basic communications with TLS 1.3 servers to test the
compressed certificate message. This test DOES expect that the
server will sent a RequestCertificate message so the clint then
can send its certificate.

Test end
====================
version: 1
====================
TOTAL: 3
SKIP: 0
PASS: 2
XFAIL: 0
FAIL: 1
XPASS: 0
====================
FAILED:
        'zlib bomb'

```

and on the server side:

```
# openssl s_server -key localhost.key -cert localhost.crt -www -Verify 1
verify depth is 1, must return a certificate
Using default temp DH parameters
ACCEPT
depth=0 CN=localhost
verify error:num=18:self-signed certificate
verify return:1
depth=0 CN=localhost
verify return:1
000003FFBF574720:error:0A000098:SSL routines:read_state_machine:excessive message size:ssl/statem/statem.c:649:
```

Is this what you also got? 

I do see that it sends back an 'illegal parameter' alert, which seems to we 'working as designed' in my opinion:

```
Sent TLS Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 19
  Inner Content Type = Alert (21)
    Level=fatal(2), description=illegal parameter(47)
```

I then played a bit with the bomb sizes, and got a different behavior with a 110MB size.  
The difference between a 110MB bomb and a 500BM bomb is that the **client side** seems to behave differently.

With a 110MB bomb I get:

```
zlib bomb ...
Error encountered while processing node ExpectAlert(level=2, description=(42,)) (child: None) with last message being: <tlslite.messages.Message object at 0x3ffab1c4a90>
Error while processing
Traceback (most recent call last):
  File "/root/tlsfuzzer/scripts/test-tls13-client-certificate-compression.py", line 983, in main
    runner.run()
  File "/root/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/root/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "bad_certificate" does not match received "illegal_parameter"
```
which is kind of expected when sending an excessive message, but for a 500MB bomb it fails during sending the message already. This is probably because the server closes the connection after sending the "illegal parameter" alert, and the client has not yet finished sending the bomb data at that point in time. So it fails during send, and has no chance to receive the alert. 

Anyway, this all sounds like working as designed for me.....

**Comment by ifranzki** [comment]
Please also note that earlier OpenSSL versions might behave differently. 
For example a 3.0.9 being part of Fedora 37 sends am "unexpected message" alert even for a 100MB bomb, so the test fails there. However, this seems to have been fixed, the current master version sends a "bad certificate" as expected.

**Comment by GeorgePantelakis** [comment]
@ifranzki maybe that is the case and you are right (the client doesn't have the chance) 

First question: Why does OpenSSL abort without getting the whole message since the message is inside the allowed compressed certificate size?
`opaque compressed_certificate_message<1..2^24-1>;`  so the message can be up to 16,777,215 bytes.

Second Question: Why does it send an "illegal parameter" since in https://www.rfc-editor.org/rfc/rfc8879.html we have 
` If, after decompression, the specified length does not match the actual length, the party receiving the invalid message MUST abort the connection with the "bad_certificate" alert.`
and 
`If the received CompressedCertificate message cannot be decompressed, the connection MUST be terminated with the "bad_certificate" alert.`
I believe it should be a "bad certificate alert".

**Comment by ifranzki** [comment]
First: I am not an expert in the TLS protocol, so I can only assume what is going on from what I see.... The OpenSSL experts may be able to help here better than I do. I am mainly looking at it from an s390x arch specific point of view, and I don't think that this is architecture specific at all. 

> First question: Why does OpenSSL abort without getting the whole message since the message is inside the allowed compressed certificate size?

I guess its because the detection of excessive message length takes place while receiving the message and the 'illegal parameter' is sent as soon as it detects that the message is too long. At this point in time the message probably has not been analyzed (and potentially not even fully received), so it does not even know about the allowed compressed size.

> Second Question: Why does it send an "illegal parameter" ...

Like for your first question, the excessive length check comes first, it probably does not even know about allowed compressed size at that point where it detects the excessive length condition.

So, the excessive size checks seem to have priority over "bad_certificate" checks. 
I don't know if that's correct behavior or not.... I leave this to the OpenSSL experts to answer.

**Comment by tmshort** [comment]
Note that compressed certificates were not introduced until 3.2

**Comment by tmshort** [comment]
It does appear that OpenSSL is not even reaching the processing of the compressed certificate, and is instead failing insode the record processing.
