### ISSUE TITLE
Segment faults due to lack of NULL ptr check on EC_POINT *point

### ISSUE THREAD

**Issue by citypw** [openssl/openssl#25493]
Reproducible:
Initialization of OpenSC/HSM and key generation:
    ```
    $alias p11="pkcs11-tool --module /vault1317/libckteec.so"

    $p11 --init-token --label mytoken --so-pin 1234567890

    $p11 --label mytoken --login --so-pin 1234567890 --init-pin --pin 12345

    $p11 -l --pin 12345 --keypairgen --key-type EC:secp521r1 --label mykey
    ```

Trigger the bug:
    ```
    $/usr/local/ssl/bin/openssl pkey -engine pkcs11 -inform engine -in "pkcs11:token=mytoken;pin-value=12345;object=mykey" -pubout -text
    ```

coredump:
```
(gdb) bt
#0  0x0000007fb2d13588 in EC_POINT_point2oct () from /lib/aarch64-linux-gnu/libcrypto.so.3
#1  0x0000007fb2d08938 in i2o_ECPublicKey () from /lib/aarch64-linux-gnu/libcrypto.so.3
#2  0x0000007fb2d05e28 in ?? () from /lib/aarch64-linux-gnu/libcrypto.so.3
#3  0x0000007fb2e4cecc in i2d_PUBKEY () from /lib/aarch64-linux-gnu/libcrypto.so.3
#4  0x0000007fb2dc789c in PEM_ASN1_write_bio () from /lib/aarch64-linux-gnu/libcrypto.so.3
#5  0x0000007fb2dc59f0 in PEM_write_bio_PUBKEY () from /lib/aarch64-linux-gnu/libcrypto.so.3
#6  0x000000556852a444 in ?? ()
#7  0x00000055685245a4 in ?? ()
#8  0x00000055685020ec in ?? ()
#9  0x0000007fb2a07740 in __libc_start_call_main (main=main@entry=0x5568501f40, argc=argc@entry=10, argv=argv@entry=0x7fdb9b12a8) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x0000007fb2a07818 in __libc_start_main_impl (main=0x5568501f40, argc=10, argv=0x7fdb9b12a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>)
    at ../csu/libc-start.c:360
#11 0x0000005568502230 in ?? ()

```
I'll send a workaround patch over a PR afterward. Thanks

**Comment by fwh-dc** [comment]
Closing this issue since the related PR has been merged.
