### ISSUE TITLE
Malformed ML-KEM key shares are not handled correctly

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25781]
(this is a follow up to https://github.com/open-quantum-safe/oqs-provider/issues/553)

**Describe the bug**
When malformed key shares are sent to the server, the server doesn't abort the connection or aborts it with wrong alerts

**To Reproduce**

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www -curves X25519MLKEM768:SecP256r1MLKEM768 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tlsfuzzer/tlsfuzzer/pull/968 is merged
git checkout full-fuzz-for-mlkem-share
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
git clone https://github.com/GiacomoPope/kyber-py .kyber-py
ln -s .kyber-py/src/kyber_py kyber_py
PYTHONPATH=. python scripts/test-tls13-mlkem.py  --no-fuzz --kems x25519mlkem768,secp256r1mlkem768
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
8022C3703E7F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:689:
8022C3703E7F0000:error:0800006B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:crypto/ec/ec_lib.c:879:
8022C3703E7F0000:error:0A0C0103:SSL routines:ssl_encapsulate:internal error:ssl/s3_lib.c:5006:
8022C3703E7F0000:error:1C8000A4:Provider routines:ossl_ecx_compute_key:failed during derivation:crypto/ec/ecx_key.c:143:
8022C3703E7F0000:error:0A0C0103:SSL routines:ssl_encapsulate:internal error:ssl/s3_lib.c:5006:
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
8022C3703E7F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:689:
8022C3703E7F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:689:
8022C3703E7F0000:error:0A000065:SSL routines:final_key_share:no suitable key share:ssl/statem/extensions.c:1470:
8022C3703E7F0000:error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:689:
8022C3703E7F0000:error:0A000132:SSL routines:tls_parse_ctos_key_share:bad ecpoint:ssl/statem/extensions_srvr.c:693:
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

x25519mlkem768: padded key share ...
OK

secp256r1mlkem768: basic connection ...
OK

x25519mlkem768: malformed pqc part, variable 1 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0f0b0>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0cda0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

x25519mlkem768: malformed pqc part, variable 2 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0c260>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0cda0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: malformed classical part ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1baef560>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0cda0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

x25519mlkem768: basic connection with HRR ...
OK

x25519mlkem768: malformed classical part ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0c4a0>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0ecf0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1973, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

secp256r1mlkem768: invalid ECDH point format: raw ...
OK

secp256r1mlkem768: invalid ECDH point format: hybrid ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0d910>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0dbe0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

x25519mlkem768: truncated key share ...
OK

secp256r1mlkem768: padded key share ...
OK

secp256r1mlkem768: truncated key share ...
OK

x25519mlkem768: malformed pqc part, variable 0 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0c860>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0c800>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: basic connection with HRR ...
OK

x25519mlkem768: malformed pqc part, variable 3 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0d430>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0e540>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: malformed pqc part, variable 2 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bad4d10>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0eab0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: malformed pqc part, variable 1 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bad42f0>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0cc50>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp384r1mlkem1024: basic connection ...
OK

x25519mlkem768: basic connection ...
OK

secp256r1mlkem768: malformed pqc part, variable 0 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1baefb90>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0c800>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: malformed pqc part, variable 3 ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7fcf1bb0c1d0>) with last message being: <tlslite.messages.Message object at 0x7fcf1bb0f1d0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: invalid ECDH point format: compressed ...
OK

sanity ...
OK

Test hybrid ML-KEM key share support
Verify that hybrid ML-KEM key exchange groups are supported and
basic error handling is implemented correctly.

Test end
====================
version: 4
====================
TOTAL: 24
SKIP: 0
PASS: 13
XFAIL: 0
FAIL: 11
XPASS: 0
====================
FAILED:
        'secp256r1mlkem768: invalid ECDH point format: hybrid'
        'secp256r1mlkem768: malformed classical part'
        'secp256r1mlkem768: malformed pqc part, variable 0'
        'secp256r1mlkem768: malformed pqc part, variable 1'
        'secp256r1mlkem768: malformed pqc part, variable 2'
        'secp256r1mlkem768: malformed pqc part, variable 3'
        'x25519mlkem768: malformed classical part'
        'x25519mlkem768: malformed pqc part, variable 0'
        'x25519mlkem768: malformed pqc part, variable 1'
        'x25519mlkem768: malformed pqc part, variable 2'
        'x25519mlkem768: malformed pqc part, variable 3'
```
   </p></details>

**Expected behavior**

1. The server should check validity of the client encapsulation key, failure in that should generate `illegal_parameter` alert
2. The server should check the validity of the client ECDH key share, failure in that should generate `illegal_parameter` alert
3. The server should validate that the client ECDH key share is in the _uncompressed_ point format, it should reject shares in `hybrid` point format

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: RHEL-10
 - OpenSSL version: 3.2.2
 - oqsprovider version: 0.7.1-dev
 - liboqs version: 0.11.0

**Comment by mattcaswell** [comment]
Currently unclear if this is an OpenSSL or an oqs-provider issue. Needs further investigation.

**Comment by beldmit** [comment]
I believe it's an OpenSSL issue - the providers have nothing to do with alerts, and the stack doesn't contain anything from the provider

**Comment by baentsch** [comment]
Is this issue still existing in current "master" @tomato42 ?

**Comment by tomato42** [comment]
> Is this issue still existing in current "master" [@tomato42](https://github.com/tomato42) ?

you mean with the ml-kem feature branch merged? or when still using oqs-provider?

**Comment by baentsch** [comment]
> you mean with the ml-kem feature branch merged? or when still using oqs-provider?

The former. If it'd be OK (t)here, we'd know `oqsprovider` might stand a chance of also maybe getting it right.

**Comment by tomato42** [comment]
@baentsch tested with 71a4de5084fb :

```

sanity ...
OK

Test hybrid ML-KEM key share support
Verify that hybrid ML-KEM key exchange groups are supported and
basic error handling is implemented correctly.

Test end
====================
version: 4
====================
TOTAL: 2583
SKIP: 0
PASS: 2580
XFAIL: 0
FAIL: 3
XPASS: 0
====================
FAILED:
        'secp256r1mlkem768: invalid ECDH point format: hybrid'
        'secp384r1mlkem1024: invalid ECDH point format: hybrid'
        'x25519mlkem768: malformed classical part'
```

**Comment by baentsch** [comment]
Thanks for sharing @tomato42 -- so if I understand it right, the problem still persists.

The above is output from a tool other than `openssl` testing, right? So, is this test changing some arbitrary bit in the classic part of a persisted hybrid KEM key and then tries to operate it? I'd guess the failure then is "just" the error message (you're expecting a server "illegal parameter" alert if I get it right from the above?!). So your basic ask is to add an equivalent test to the `openssl` test suite (and fix this), right? Any chance you could contribute a pointer to the code of your test to help this?

**Comment by tomato42** [comment]
It's the output for tlsfuzzer... as described in the OP, just executed with `PYTHONPATH=. python scripts/test-tls13-mlkem.py -n 0  --kems x25519mlkem768,secp256r1mlkem768,secp384r1mlkem1024`

and no, the issues aren't just with the alert, in case of hybrid shares, the openssl server continues the connection:
```
$ PYTHONPATH=. python scripts/test-tls13-mlkem.py -n 0  --kems x25519mlkem768,secp256r1mlkem768,secp384r1mlkem1024 'secp256r1mlkem768: invalid ECDH point format: hybrid' 'secp384r1mlkem1024: invalid ECDH point format: hybrid' 'x25519mlkem768: malformed classical part'
sanity ...
OK

secp384r1mlkem1024: invalid ECDH point format: hybrid ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1240536a20>) with last message being: <tlslite.messages.Message object at 0x7f124055bb60>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

secp256r1mlkem768: invalid ECDH point format: hybrid ...
Error encountered while processing node ExpectAlert(level=2, description=47) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f12449f5760>) with last message being: <tlslite.messages.Message object at 0x7f124055bb60>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 235, in run
    raise AssertionError("Unexpected message from peer: " +
AssertionError: Unexpected message from peer: Handshake(server_hello)

x25519mlkem768: malformed classical part ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f12449f69f0>) with last message being: <tlslite.messages.Message object at 0x7f124055bb60>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-mlkem.py", line 454, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 2006, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "internal_error"

sanity ...
OK

Test hybrid ML-KEM key share support
Verify that hybrid ML-KEM key exchange groups are supported and
basic error handling is implemented correctly.

Test end
====================
version: 4
====================
TOTAL: 5
SKIP: 0
PASS: 2
XFAIL: 0
FAIL: 3
XPASS: 0
====================
FAILED:
        'secp256r1mlkem768: invalid ECDH point format: hybrid'
        'secp384r1mlkem1024: invalid ECDH point format: hybrid'
        'x25519mlkem768: malformed classical part'
```

**Comment by tomato42** [comment]
I've retested f7feb2d937ac1bb5551da66d80009e73ca462597 (master as of 21-10-2025), and while it fixes the `'x25519mlkem768: malformed classical part'` case, the ECDH key shares in hybrid format are still accepted (with the server accepting client's key_share)
