### ISSUE TITLE
Apparent use-of-uninitialized-value in quic_tserver_test

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#26277]
When experimenting with the new memory sanitizer that comes with ubuntu-24.04 (see #26269)
there was an undefined value reported, where I am not sure if it is a real issue of not:
```
==43006==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5650d0ab182f in ch_rx_handle_packet /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2211:5
    #1 0x5650d0ab182f in ch_rx /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2066:9
    #2 0x5650d0ab182f in ossl_quic_channel_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:1897:13
    #3 0x5650d09d1c8f in ossl_quic_port_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:379:13
    #4 0x5650d0ac0651 in qeng_tick /home/runner/work/openssl/openssl/ssl/quic/quic_engine.c:137:9
    #5 0x5650d09d2ecc in ossl_quic_reactor_tick /home/runner/work/openssl/openssl/ssl/quic/quic_reactor.c:109:5
    #6 0x5650d09c013f in quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1685:9
    #7 0x5650d09bf87f in ossl_quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1759:11
    #8 0x5650d096e3b8 in do_test /home/runner/work/openssl/openssl/test/quic_tserver_test.c:210:19
    #9 0x5650d096e3b8 in test_tserver /home/runner/work/openssl/openssl/test/quic_tserver_test.c:415:12
    #10 0x5650d0b04c03 in run_tests /home/runner/work/openssl/openssl/test/testutil/driver.c:377:21
    #11 0x5650d0b05b90 in main /home/runner/work/openssl/openssl/test/testutil/main.c:31:15
    #12 0x7f4f8742a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #13 0x7f4f8742a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #14 0x5650d08d5684 in _start (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xb5684) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
  Uninitialized value was stored to memory at
    #0 0x5650d0ab1828 in ch_rx_handle_packet /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2213:60
    #1 0x5650d0ab1828 in ch_rx /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2066:9
    #2 0x5650d0ab1828 in ossl_quic_channel_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:1897:13
    #3 0x5650d09d1c8f in ossl_quic_port_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:379:13
    #4 0x5650d0ac0651 in qeng_tick /home/runner/work/openssl/openssl/ssl/quic/quic_engine.c:137:9
    #5 0x5650d09d2ecc in ossl_quic_reactor_tick /home/runner/work/openssl/openssl/ssl/quic/quic_reactor.c:109:5
    #6 0x5650d09c013f in quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1685:9
    #7 0x5650d09bf87f in ossl_quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1759:11
    #8 0x5650d096e3b8 in do_test /home/runner/work/openssl/openssl/test/quic_tserver_test.c:210:19
    #9 0x5650d096e3b8 in test_tserver /home/runner/work/openssl/openssl/test/quic_tserver_test.c:415:12
    #10 0x5650d0b04c03 in run_tests /home/runner/work/openssl/openssl/test/testutil/driver.c:377:21
    #11 0x5650d0b05b90 in main /home/runner/work/openssl/openssl/test/testutil/main.c:31:15
    #12 0x7f4f8742a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #13 0x7f4f8742a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #14 0x5650d08d5684 in _start (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xb5684) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
  Uninitialized value was stored to memory at
    #0 0x5650d09d8ee9 in ossl_qrx_read_pkt /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1238:29
    #1 0x5650d0aadcbc in ch_rx /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2053:14
    #2 0x5650d0aadcbc in ossl_quic_channel_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:1897:13
    #3 0x5650d09d1c8f in ossl_quic_port_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:379:13
    #4 0x5650d0ac0651 in qeng_tick /home/runner/work/openssl/openssl/ssl/quic/quic_engine.c:137:9
    #5 0x5650d09d2ecc in ossl_quic_reactor_tick /home/runner/work/openssl/openssl/ssl/quic/quic_reactor.c:109:5
    #6 0x5650d09c013f in quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1685:9
    #7 0x5650d09bf87f in ossl_quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1759:11
    #8 0x5650d096e3b8 in do_test /home/runner/work/openssl/openssl/test/quic_tserver_test.c:210:19
    #9 0x5650d096e3b8 in test_tserver /home/runner/work/openssl/openssl/test/quic_tserver_test.c:415:12
    #10 0x5650d0b04c03 in run_tests /home/runner/work/openssl/openssl/test/testutil/driver.c:377:21
    #11 0x5650d0b05b90 in main /home/runner/work/openssl/openssl/test/testutil/main.c:31:15
    #12 0x7f4f8742a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #13 0x7f4f8742a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #14 0x5650d08d5684 in _start (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xb5684) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
  Uninitialized value was stored to memory at
    #0 0x5650d09d8102 in qrx_process_pkt /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1059:25
    #1 0x5650d09d8102 in qrx_process_datagram /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1149:13
    #2 0x5650d09d8102 in qrx_process_one_urxe /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1172:20
    #3 0x5650d09d8102 in qrx_process_pending_urxl /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1204:14
    #4 0x5650d09d8102 in ossl_qrx_read_pkt /home/runner/work/openssl/openssl/ssl/quic/quic_record_rx.c:1215:14
    #5 0x5650d0aadcbc in ch_rx /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2053:14
    #6 0x5650d0aadcbc in ossl_quic_channel_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:1897:13
    #7 0x5650d09d1c8f in ossl_quic_port_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:379:13
    #8 0x5650d0ac0651 in qeng_tick /home/runner/work/openssl/openssl/ssl/quic/quic_engine.c:137:9
    #9 0x5650d09d2ecc in ossl_quic_reactor_tick /home/runner/work/openssl/openssl/ssl/quic/quic_reactor.c:109:5
    #10 0x5650d09c013f in quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1685:9
    #11 0x5650d09bf87f in ossl_quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1759:11
    #12 0x5650d096e3b8 in do_test /home/runner/work/openssl/openssl/test/quic_tserver_test.c:210:19
    #13 0x5650d096e3b8 in test_tserver /home/runner/work/openssl/openssl/test/quic_tserver_test.c:415:12
    #14 0x5650d0b04c03 in run_tests /home/runner/work/openssl/openssl/test/testutil/driver.c:377:21
    #15 0x5650d0b05b90 in main /home/runner/work/openssl/openssl/test/testutil/main.c:31:15
    #16 0x7f4f8742a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #17 0x7f4f8742a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #18 0x5650d08d5684 in _start (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xb5684) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
  Uninitialized value was created by a heap allocation
    #0 0x5650d09112f6 in malloc (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xf12f6) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
    #1 0x5650d0cb9592 in CRYPTO_malloc /home/runner/work/openssl/openssl/crypto/mem.c:211:11
    #2 0x5650d0abd7e3 in demux_alloc_urxe /home/runner/work/openssl/openssl/ssl/quic/quic_demux.c:162:9
    #3 0x5650d0abd7e3 in demux_ensure_free_urxe /home/runner/work/openssl/openssl/ssl/quic/quic_demux.c:215:13
    #4 0x5650d0abc636 in ossl_quic_demux_pump /home/runner/work/openssl/openssl/ssl/quic/quic_demux.c:385:15
    #5 0x5650d09d1b8e in port_rx_pre /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:413:11
    #6 0x5650d09d1b8e in ossl_quic_port_subtick /home/runner/work/openssl/openssl/ssl/quic/quic_port.c:373:13
    #7 0x5650d0ac0651 in qeng_tick /home/runner/work/openssl/openssl/ssl/quic/quic_engine.c:137:9
    #8 0x5650d09d2ecc in ossl_quic_reactor_tick /home/runner/work/openssl/openssl/ssl/quic/quic_reactor.c:109:5
    #9 0x5650d09c013f in quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1685:9
    #10 0x5650d09bf87f in ossl_quic_do_handshake /home/runner/work/openssl/openssl/ssl/quic/quic_impl.c:1759:11
    #11 0x5650d096e3b8 in do_test /home/runner/work/openssl/openssl/test/quic_tserver_test.c:210:19
    #12 0x5650d096e3b8 in test_tserver /home/runner/work/openssl/openssl/test/quic_tserver_test.c:415:12
    #13 0x5650d0b04c03 in run_tests /home/runner/work/openssl/openssl/test/testutil/driver.c:377:21
    #14 0x5650d0b05b90 in main /home/runner/work/openssl/openssl/test/testutil/main.c:31:15
    #15 0x7f4f8742a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #16 0x7f4f8742a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #17 0x5650d08d5684 in _start (/home/runner/work/openssl/openssl/test/quic_tserver_test+0xb5684) (BuildId: f6bd1657c8942ff34c8e0862afbc2ca88ac5f16b)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/runner/work/openssl/openssl/ssl/quic/quic_channel.c:2211:5 in ch_rx_handle_packet
Exiting
../../util/wrap.pl ../../test/quic_tserver_test ../../test/certs/servercert.pem ../../test/certs/serverkey.pem => 1
not ok 1
# ------------------------------------------------------------------------------
#   Failed test at test/recipes/70-test_quic_tserver.t line 19.
# Looks like you failed 1 test of 1.70-test_quic_tserver.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

A possible fix would be e.g. like this
```
diff --git a/ssl/quic/quic_record_rx.c b/ssl/quic/quic_record_rx.c
index 722b957a43..64fe8de1ff 100644
--- a/ssl/quic/quic_record_rx.c
+++ b/ssl/quic/quic_record_rx.c
@@ -245,6 +245,7 @@ void ossl_qrx_inject_urxe(OSSL_QRX *qrx, QUIC_URXE *urxe)
     urxe->processed     = 0;
     urxe->hpr_removed   = 0;
     urxe->deferred      = 0;
+    urxe->datagram_id   = 0;
     ossl_list_urxe_insert_tail(&qrx->urx_pending, urxe);
 
     if (qrx->msg_callback != NULL)
```
but I am not sure if it is a correct fix.

**Comment by bernd-edlinger** [comment]
Hi, @Sashan your suggested fix works for me.
