### ISSUE TITLE
 android version16:Couldn't load sqlcipher: findLibrary returned null 

### ISSUE THREAD

**Issue by stxkwynfv** [openssl/openssl#2829]
java.lang.UnsatisfiedLinkError: Couldn't load sqlcipher: findLibrary returned null
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                 at java.lang.System.loadLibrary(System.java:535)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:195)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:188)
                                                                                 at cn.isimba.application.SimbaApplication.initAccountDb(SimbaApplication.java:137)
                                                                                 at cn.isimba.application.SimbaApplication.onCreate(SimbaApplication.java:109)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
                                                                                 at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by richsalz** [comment]
This is not an openssl issue.  Which BTW is written in C :)
