### ISSUE TITLE
Python Cryptography external tests failing

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#3005]
The Python Cryptography external tests are failing when run in Travis. It looks like they never really get started:
````
../test/recipes/95-test_external_pyca.t ....... 
1..1
------------------------------------------------------------------
Testing OpenSSL using Python Cryptography:
   CWD:                /home/travis/build/openssl/openssl/test
   SRCTOP:             ..
   BLDTOP:             ..
   OpenSSL version:    1.1.1-dev
------------------------------------------------------------------
New python executable in venv-pycrypto/bin/python
Installing setuptools, pip, wheel...done.
/home/travis/build/openssl/openssl/venv-pycrypto/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QChgAv/pyenchant
../util/shlib_wrap.sh sh recipes/95-test_external_pyca_data/cryptography.sh => 1
not ok 1 - running Python Cryptography tests

#   Failed test 'running Python Cryptography tests'
#   at ../test/recipes/95-test_external_pyca.t line 27.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
````
Ping @alex, @jon-oracle - Any ideas?

**Comment by alex** [comment]
There seems to be some missing stdout/sderr, I don't see any of the expected output of `python setup.py egg_info`.

**Comment by mattcaswell** [comment]
@levitte - any idea where the missing stdout/stderr went?

**Comment by levitte** [comment]
I assume `python setup.py egg_info` gets executed as part of this line, right?:

``` python
pip install -q --requirement dev-requirements.txt
```

All I know is that before the building stage, there isn't much output when I run `cryptography.py` manually:

```
: ; BLDTOP=. SRCTOP=../master ../master/test/recipes/95-test_external_pyca_data/cryptography.sh
------------------------------------------------------------------
Testing OpenSSL using Python Cryptography:
   CWD:                /home/levitte/gitwrk/openssl.net/official/_build
   SRCTOP:             ../master
   BLDTOP:             .
   OpenSSL version:    1.1.1-dev
------------------------------------------------------------------
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/levitte/gitwrk/openssl.net/official/master/venv-pycrypto/bin/python2
Also creating executable in /home/levitte/gitwrk/openssl.net/official/master/venv-pycrypto/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
------------------------------------------------------------------
Building cryptography
------------------------------------------------------------------
...
```

**Comment by alex** [comment]
Can you remove the `-q` from the `pip install` line?

**Comment by levitte** [comment]
That can be done, of course.

**Comment by levitte** [comment]
#3007 is a PR where I'll experiment with what's needed.  Note: I'm a python neophyte, so I will need help and suggestions.

**Comment by levitte** [comment]
So from a finally working #3007, is seems this is the issue

```
Collecting pyenchant (from cryptography==1.8.dev1->-r dev-requirements.txt (line 7))
  Downloading pyenchant-1.6.8.tar.gz (63kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-S1jl4l/pyenchant/setup.py", line 210, in <module>
        import enchant
      File "enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
```
