### ISSUE TITLE
Memory leak in OPENSSL_cleanup

### ISSUE THREAD

**Issue by dvorszkid** [openssl/openssl#3128]
In version 1.1.0e.

```
ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55ec3a881040 in malloc /var/tmp/portage/sys-libs/compiler-rt-sanitizers-4.0.0/work/compiler-rt-4.0.0.src/lib/asan/asan_malloc_linux.cc:66
    #1 0x7fd15f3df482 in CRYPTO_malloc my_project/third_party/openssl-1.1.0e/crypto/mem.c:92:11
    #2 0x7fd15f3df4dd in CRYPTO_zalloc my_project/third_party/openssl-1.1.0e/crypto/mem.c:100:17
    #3 0x7fd15f3d597b in ossl_init_get_thread_local my_project/third_party/openssl-1.1.0e/crypto/init.c:45:17
    #4 0x7fd15f3d59f2 in ossl_init_thread_start my_project/third_party/openssl-1.1.0e/crypto/init.c:357:44
    #5 0x7fd15f369c9d in ERR_get_state my_project/third_party/openssl-1.1.0e/crypto/err/err.c:664:9
    #6 0x7fd15f36cae1 in ERR_set_mark my_project/third_party/openssl-1.1.0e/crypto/err/err.c:744:10
    #7 0x7fd15f363491 in engine_table_select my_project/third_party/openssl-1.1.0e/crypto/engine/eng_table.c:205:5
    #8 0x7fd15f3685e9 in ENGINE_get_default_RAND my_project/third_party/openssl-1.1.0e/crypto/engine/tb_rand.c:58:12
    #9 0x7fd15f452db9 in RAND_get_rand_method my_project/third_party/openssl-1.1.0e/crypto/rand/rand_lib.c:43:21
    #10 0x7fd15f452f31 in rand_cleanup_int my_project/third_party/openssl-1.1.0e/crypto/rand/rand_lib.c:82:31
    #11 0x7fd15f3d5c6f in OPENSSL_cleanup my_project/third_party/openssl-1.1.0e/crypto/init.c:477:5
    #12 0x7fd15cc3fd57  (/lib64/libc.so.6+0x36d57)

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```

`OPENSSL_cleanup` calls `ossl_init_thread_stop(ossl_init_get_thread_local(0))` before `rand_cleanup_int()` which calls another `ossl_init_thread_start()` which is never cleaned up.

**Comment by richsalz** [comment]
Please see #3033 and #3035; closing as duplicate.

**Comment by mattcaswell** [comment]
I'm not sure if that is the same issue. Needs more investigation I think.

**Comment by richsalz** [comment]
Maybe the poster can try the patch and see if it fixes things.

**Comment by dvorszkid** [comment]
Tried the patch suggested in #3035, it does not fix this leak.

**Comment by levitte** [comment]
Ah, I think you found a possible race condition.  What happens if you try this patch?

``` diff
diff --git a/crypto/rand/rand_lib.c b/crypto/rand/rand_lib.c
index fc47dc97a2..ad452504e6 100644
--- a/crypto/rand/rand_lib.c
+++ b/crypto/rand/rand_lib.c
@@ -74,7 +74,7 @@ int RAND_set_rand_engine(ENGINE *engine)
 
 void rand_cleanup_int(void)
 {
-    const RAND_METHOD *meth = RAND_get_rand_method();
+    const RAND_METHOD *meth = default_RAND_meth;
     if (meth && meth->cleanup)
         meth->cleanup();
     RAND_set_rand_method(NULL);
```

**Comment by dvorszkid** [comment]
Awesome, this solves it, thank you. :)

**Comment by levitte** [comment]
Thanks for trying it, there's now a PR (#3136) with exactly that patch.

**Comment by levitte** [comment]
The fix is in, will appear in the next release.
