### ISSUE TITLE
runtime error: unsigned integer overflow: 58 - 66 cannot be represented in type 'unsigned long' (crypto/err/err.c:165:27)

### ISSUE THREAD

**Issue by geeknik** [openssl/openssl#3885]
Built on a fresh Debian 9 x64 machine per the fuzzing instructions [here](https://github.com/openssl/openssl/tree/master/fuzz) with the addition of `-fsanitize=integer -fsanitize-address-use-after-scope -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow`.

Running any of the fuzzers results in the following runtime error:

```
crypto/err/err.c:165:27: runtime error: unsigned integer overflow: 58 - 66 cannot be represented in type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/err/err.c:165:27 in
```

The runtime error goes away after removing `-fsanitize=integer` and re-compiling OpenSSL.

**Comment by richsalz** [comment]
Does this patch fix it?
```
; g diff crypto/err/err.c
diff --git a/crypto/err/err.c b/crypto/err/err.c
index e50c6d6..7a3f954 100644
--- a/crypto/err/err.c
+++ b/crypto/err/err.c
@@ -162,7 +162,9 @@ static unsigned long err_string_data_hash(const ERR_STRING_DATA *a)
 static int err_string_data_cmp(const ERR_STRING_DATA *a,
                                const ERR_STRING_DATA *b)
 {
-    return (int)(a->error - b->error);
+    if (a->error == b->error)
+        return 0;
+    return a->error > b->error : 1 : -1;
 }

 static ERR_STRING_DATA *int_err_get_item(const ERR_STRING_DATA *d)
```

**Comment by geeknik** [comment]
I've got a better stack trace this time, but it still fails even with the changes in your patch:

```
UBSAN_OPTIONS=print_stacktrace=1 fuzz/helper.py client
/root/openssl/fuzz/client -artifact_prefix=/root/openssl/fuzz/corpora/client-crash/ /root/openssl/fuzz/corpora/client /root/openssl/fuzz/corpora/client-crash
crypto/err/err.c:165:27: runtime error: unsigned integer overflow: 58 - 66 cannot be represented in type 'unsigned long'
    #0 0xcb5a00 in err_string_data_cmp /root/openssl/crypto/err/err.c:165:27
    #1 0xe3d71e in getrn /root/openssl/crypto/lhash/lhash.c:296:13
    #2 0xe388cd in OPENSSL_LH_insert /root/openssl/crypto/lhash/lhash.c:83:10
    #3 0xcb5a6e in lh_ERR_STRING_DATA_insert /root/openssl/include/openssl/err.h:214:1
    #4 0xca3736 in err_load_strings /root/openssl/crypto/err/err.c:304:15
    #5 0xca3595 in ERR_load_ERR_strings /root/openssl/crypto/err/err.c:317:5
    #6 0x1592cab in err_load_crypto_strings_int /root/openssl/crypto/err/err_all.c:45:9
    #7 0xe2c02f in ossl_init_load_crypto_strings /root/openssl/crypto/init.c:150:11
    #8 0xe2ba44 in ossl_init_load_crypto_strings_ossl_ /root/openssl/crypto/init.c:138:1
    #9 0x7fe2b432a738 in __pthread_once_slow (/lib/x86_64-linux-gnu/libpthread.so.0+0xe738)
    #10 0x10c0517 in CRYPTO_THREAD_run_once /root/openssl/crypto/threads_pthread.c:107:9
    #11 0xe2a292 in OPENSSL_init_crypto /root/openssl/crypto/init.c:536:17
    #12 0x4ed771 in FuzzerInitialize /root/openssl/fuzz/client.c:48:5
    #13 0x4edd5e in LLVMFuzzerInitialize /root/openssl/fuzz/driver.c:20:12
    #14 0x4f0be9 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /root/test/Fuzzer/FuzzerDriver.cpp:527:5
    #15 0x4eddf0 in main /root/test/Fuzzer/FuzzerMain.cpp:20:10
    #16 0x7fe2b3b7e2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #17 0x420259 in _start (/root/openssl/fuzz/client+0x420259)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/err/err.c:165:27 in
```

**Comment by geeknik** [comment]
Fails to compile and I see this error amongst the warnings:

```
crypto/err/err.c:168:32: error: expected ';' after return statement
    return a->error > b->error : 1 : -1;
                               ^
                               ;

```

**Comment by richsalz** [comment]
Yeah, sorry, typo.  It should be “? 1 : -1”

**Comment by geeknik** [comment]
Okay, fixed the typo using the patch from #3887, but I still see this:
```
UBSAN_OPTIONS=print_stacktrace=1 fuzz/client fuzz/corpora/client/
crypto/err/err.c:165:27: runtime error: unsigned integer overflow: 58 - 66 cannot be represented in type 'unsigned long'
    #0 0xcb5a00 in err_string_data_cmp /root/openssl/crypto/err/err.c:165:27
    #1 0xe3d71e in getrn /root/openssl/crypto/lhash/lhash.c:296:13
    #2 0xe388cd in OPENSSL_LH_insert /root/openssl/crypto/lhash/lhash.c:83:10
    #3 0xcb5a6e in lh_ERR_STRING_DATA_insert /root/openssl/include/openssl/err.h:214:1
    #4 0xca3736 in err_load_strings /root/openssl/crypto/err/err.c:304:15
    #5 0xca3595 in ERR_load_ERR_strings /root/openssl/crypto/err/err.c:317:5
    #6 0x1592cab in err_load_crypto_strings_int /root/openssl/crypto/err/err_all.c:45:9
    #7 0xe2c02f in ossl_init_load_crypto_strings /root/openssl/crypto/init.c:150:11
    #8 0xe2ba44 in ossl_init_load_crypto_strings_ossl_ /root/openssl/crypto/init.c:138:1
    #9 0x7f4f12949738 in __pthread_once_slow (/lib/x86_64-linux-gnu/libpthread.so.0+0xe738)
    #10 0x10c0517 in CRYPTO_THREAD_run_once /root/openssl/crypto/threads_pthread.c:107:9
    #11 0xe2a292 in OPENSSL_init_crypto /root/openssl/crypto/init.c:536:17
    #12 0x4ed771 in FuzzerInitialize /root/openssl/fuzz/client.c:48:5
    #13 0x4edd5e in LLVMFuzzerInitialize /root/openssl/fuzz/driver.c:20:12
    #14 0x4f0be9 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /root/test/Fuzzer/FuzzerDriver.cpp:527:5
    #15 0x4eddf0 in main /root/test/Fuzzer/FuzzerMain.cpp:20:10
    #16 0x7f4f1219d2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #17 0x420259 in _start (/root/openssl/fuzz/client+0x420259)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/err/err.c:165:27 in
```

**Comment by richsalz** [comment]
Are you sure you ran the right binary?  There is no subtraction in the patched version.

**Comment by geeknik** [comment]
All good now. #3887 fixes this bug.
