### ISSUE TITLE
runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long' (crypto/asn1/asn1_lib.c:131:21)

### ISSUE THREAD

**Issue by geeknik** [openssl/openssl#3891]
Similar to #3885 and #3889, built on a fresh Debian 9 x64 machine per the fuzzing instructions with the addition of `-fsanitize=integer -fsanitize-address-use-after-scope -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow`. This one only triggers with the server fuzzer and the server corpora.

`UBSAN_OPTIONS=print_stacktrace=1 fuzz/server fuzz/corpora/server`
```
INFO: Seed: 1068961649
INFO: Loaded 1 modules (54730 guards): [0x22232c0, 0x22589e8),
Loading corpus dir: fuzz/corpora/server
Loaded 1024/2656 files from fuzz/corpora/server
Loaded 2048/2656 files from fuzz/corpora/server
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 20001 bytes
#0      READ units: 2655
crypto/asn1/asn1_lib.c:131:21: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
    #0 0x96b061 in asn1_get_length /root/openssl/crypto/asn1/asn1_lib.c:131:21
    #1 0x96a0ca in ASN1_get_object /root/openssl/crypto/asn1/asn1_lib.c:84:10
    #2 0x97e162 in asn1_check_tlen /root/openssl/crypto/asn1/tasn_dec.c:1079:13
    #3 0x977470 in asn1_item_embed_d2i /root/openssl/crypto/asn1/tasn_dec.c:271:15
    #4 0x974af3 in ASN1_item_ex_d2i /root/openssl/crypto/asn1/tasn_dec.c:114:10
    #5 0x9748d9 in ASN1_item_d2i /root/openssl/crypto/asn1/tasn_dec.c:104:9
    #6 0xf98222 in d2i_RSAPrivateKey /root/openssl/crypto/rsa/rsa_asn1.c:91:1
    #7 0x4edbe6 in FuzzerTestOneInput /root/openssl/fuzz/server.c:545:15
    #8 0x4ed6be in LLVMFuzzerTestOneInput /root/openssl/fuzz/driver.c:25:12
    #9 0x4fa38a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /root/test/Fuzzer/FuzzerLoop.cpp:460:13
    #10 0x4fa5f1 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) /root/test/Fuzzer/FuzzerLoop.cpp:399:3
    #11 0x4fa1e1 in fuzzer::Fuzzer::RunOne(std::vector<unsigned char, std::allocator<unsigned char> > const&) /root/test/Fuzzer/./FuzzerInternal.h:98:41
    #12 0x4fa1e1 in fuzzer::Fuzzer::ShuffleAndMinimize(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >*) /root/test/Fuzzer/FuzzerLoop.cpp:380
    #13 0x4f31b1 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /root/test/Fuzzer/FuzzerDriver.cpp:742:6
    #14 0x4eeaf0 in main /root/test/Fuzzer/FuzzerMain.cpp:20:10
    #15 0x7f4308f582b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #16 0x420259 in _start (/root/openssl/fuzz/server+0x420259)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/asn1/asn1_lib.c:131:21 in
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x43,0x3,0x4f,0x4e,0x54,0xf8,
C\x03ONT\xf8
artifact_prefix='./'; Test unit written to ./crash-706666f9802fc452daf8d3f3e929df399b0946b4
Base64: QwNPTlT4
```

Like the other bugs this issue is only visible if you compile OpenSSL with UBSan and `-fsanitize=integer`.

**Comment by levitte** [comment]
Now this is starting to get problematic.  Here's the deal:

``` C
    unsigned long i;

...

            while (i-- > 0) {
```

Line 131 is the `while` lines.  It looks like a perfectly legitimate test, even for an unsigned integer.  I have no idea how to fix it, and quite frankly, this looks like a false positive more than anything else.

**Comment by richsalz** [comment]
```
for ( ; i != 0; i--)
```

??

**Comment by paulidale** [comment]
See #3912

**Comment by paulidale** [comment]
This should be fixed now.

**Comment by mattcaswell** [comment]
Linked PR was merged so closing.
