### ISSUE TITLE
runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int' (crypto/ec/curve25519.c)

### ISSUE THREAD

**Issue by geeknik** [openssl/openssl#3892]
Similar to the previously reported overflows, built on a fresh Debian 9 x64 machine per the fuzzing instructions with the addition of `-fsanitize=integer -fsanitize-address-use-after-scope -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow`. This one only triggers with the client fuzzer and the client corpora.

`UBSAN_OPTIONS=print_stacktrace=1 fuzz/client fuzz/corpora/client`

```
INFO: Seed: 726001437
INFO: Loaded 1 modules (54706 guards): [0x2220ee0, 0x22565a8),
Loading corpus dir: fuzz/corpora/client
Loaded 1024/3127 files from fuzz/corpora/client
Loaded 2048/3127 files from fuzz/corpora/client
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 16645 bytes
#0      READ units: 3062
crypto/ec/curve25519.c:1246:5: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
    #0 0x15144ca in equal /root/openssl/crypto/ec/curve25519.c:1246:5
    #1 0x150ff3a in table_select /root/openssl/crypto/ec/curve25519.c:3385:35
    #2 0x14dea07 in ge_scalarmult_base /root/openssl/crypto/ec/curve25519.c:3432:5
    #3 0x14ff837 in X25519_public_from_private /root/openssl/crypto/ec/curve25519.c:4707:3
    #4 0xc94cc9 in ecx_key_op /root/openssl/crypto/ec/ecx_meth.c:90:13
    #5 0xc91b8f in pkey_ecx_keygen /root/openssl/crypto/ec/ecx_meth.c:418:12
    #6 0xddba52 in EVP_PKEY_keygen /root/openssl/crypto/evp/pmeth_gn.c:107:11
    #7 0x5dda1c in ssl_generate_pkey_curve /root/openssl/ssl/s3_lib.c:4140:9
    #8 0x6f7fbe in add_key_share /root/openssl/ssl/statem/extensions_clnt.c:551:25
    #9 0x6f750d in tls_construct_ctos_key_share /root/openssl/ssl/statem/extensions_clnt.c:637:10
    #10 0x6d5448 in tls_construct_extensions /root/openssl/ssl/statem/extensions.c:747:15
    #11 0x76f9ce in tls_construct_client_hello /root/openssl/ssl/statem/statem_clnt.c:1147:10
    #12 0x7548b6 in write_state_machine /root/openssl/ssl/statem/statem.c:792:45
    #13 0x74cf15 in state_machine /root/openssl/ssl/statem/statem.c:401:21
    #14 0x749efd in ossl_statem_connect /root/openssl/ssl/statem/statem.c:229:12
    #15 0x651cd5 in SSL_do_handshake /root/openssl/ssl/ssl_lib.c:3327:19
    #16 0x4edb2e in FuzzerTestOneInput /root/openssl/fuzz/client.c:91:9
    #17 0x4eddae in LLVMFuzzerTestOneInput /root/openssl/fuzz/driver.c:25:12
    #18 0x4f968a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /root/test/Fuzzer/FuzzerLoop.cpp:460:13
    #19 0x4f98f1 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) /root/test/Fuzzer/FuzzerLoop.cpp:399:3
    #20 0x4f94e1 in fuzzer::Fuzzer::RunOne(std::vector<unsigned char, std::allocator<unsigned char> > const&) /root/test/Fuzzer/./FuzzerInternal.h:98:41
    #21 0x4f94e1 in fuzzer::Fuzzer::ShuffleAndMinimize(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >*) /root/test/Fuzzer/FuzzerLoop.cpp:380
    #22 0x4f24b1 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /root/test/Fuzzer/FuzzerDriver.cpp:742:6
    #23 0x4eddf0 in main /root/test/Fuzzer/FuzzerMain.cpp:20:10
    #24 0x7fa6758da2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #25 0x420259 in _start (/root/openssl/fuzz/client+0x420259)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior crypto/ec/curve25519.c:1246:5 in
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x50,0x4f,0x53,0x54,0x20,
POST
artifact_prefix='./'; Test unit written to ./crash-1d92f5bfe0270ab938b478dcc770f6f9843cc92a
Base64: UE9TVCA=
```

Like the other bugs this issue is only visible if you compile OpenSSL with UBSan and `-fsanitize=integer`.

**Comment by levitte** [comment]
Does this patch help?

``` diff
diff --git a/crypto/ec/curve25519.c b/crypto/ec/curve25519.c
index e467eef7d3..dd588c3907 100644
--- a/crypto/ec/curve25519.c
+++ b/crypto/ec/curve25519.c
@@ -1242,10 +1242,7 @@ static uint8_t equal(signed char b, signed char c) {
   uint8_t ub = b;
   uint8_t uc = c;
   uint8_t x = ub ^ uc; /* 0: yes; 1..255: no */
-  uint32_t y = x;      /* 0: yes; 1..255: no */
-  y -= 1;              /* 4294967295: yes; 0..254: no */
-  y >>= 31;            /* 1: yes; 0: no */
-  return y;
+  return x == 0;
 }
 
 static void cmov(ge_precomp *t, const ge_precomp *u, uint8_t b) {
```

**Comment by bernd-edlinger** [comment]
That's funny, because unsigned integer underflow is not supposed to be undefined behaviour.
Is this GCC and which version do you use?

**Comment by geeknik** [comment]
clang version 5.0.0 (trunk 305735)

'''
git clone https://chromium.googlesource.com/chromium/src/tools/clang
clang/scripts/update.py
'''

**Comment by bernd-edlinger** [comment]
While signed integer overflow is clearly undefined behaviour, unsigned integer overflow is not.
If there a clang option to get warnings for signed but not for unsigned integer overflow?

**Comment by richsalz** [comment]
yeah, don't make this change; i worry about the constant-time lossage.

**Comment by bernd-edlinger** [comment]
me too.
