### ISSUE TITLE
openssl: error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by ltfschoen** [openssl/openssl#4833]
I have Dockerfile and docker-compose.yml files with the following contents to install OpenSSL 1.1.0g:

**Dockerfile**
```
FROM ubuntu:trusty
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y build-essential
RUN apt-get install -y zlib1g-dev
ARG OPENSSL_VERSION=1.1.0g
RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
RUN tar xvfz openssl-${OPENSSL_VERSION}.tar.gz && cd openssl-${OPENSSL_VERSION} && ./config && make && make install
RUN openssl version
```

**docker-compose.yml**
```
version: '3'
services:
  sandbox:
    build:
      context: .
    image: microraiden_sandbox:tag
    volumes:
      - .:/code
    command: tail -f /dev/null
```

But the last line of code `RUN openssl version` returns the following error:
```
openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
ERROR: Service 'sandbox' failed to build: The command '/bin/sh -c openssl version' returned a non-zero code: 127
```

Fixing the error required changing it to the following code (having an extra six lines of code before running `openssl version`, resulting in the output being `OpenSSL 1.1.0g  2 Nov 2017`

**Dockerfile**
```
FROM ubuntu:trusty
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y build-essential
RUN apt-get install -y zlib1g-dev
ARG OPENSSL_VERSION=1.1.0g
RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
RUN tar xvfz openssl-${OPENSSL_VERSION}.tar.gz && cd openssl-${OPENSSL_VERSION} && ./config && make && make install
RUN cd openssl-*/ && ./config shared && make && make install
RUN echo 'export LD_LIBRARY_PATH=/usr/local/ssl/lib' >> ~/.bash_profile && . ~/.bash_profile
RUN ln -s /usr/local/lib/libcrypto.so.1.1 /usr/lib
RUN ln -s /usr/local/lib/libcrypto.a /usr/lib
RUN ln -s /usr/local/lib/libssl.so /usr/lib
RUN ln -s /usr/local/lib/libssl.so.1.1 /usr/lib
RUN openssl version
```

Is this an appropriate way to resolve this error?

**Comment by richsalz** [comment]
Why are you doing cd/config/make/make twice?
You can configure to install in /usr/lib; see the INSTALL docs.

**Comment by ltfschoen** [comment]
@richsalz Thanks. I followed the [OpenSSL INSTALL](https://github.com/openssl/openssl/blob/master/INSTALL) document and ended up changing the code in the Dockerfile to the following, which works:
```
FROM ubuntu:trusty
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y build-essential
RUN apt-get install -y zlib1g-dev

# Setup Python
ARG PYTHON_VERSION=3.6.3
RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
RUN tar xf Python-${PYTHON_VERSION}.tgz && cd Python-${PYTHON_VERSION} && ./configure && make && make install
RUN echo 'PATH="$HOME/bin/python3:$PATH"; export PATH' >> ~/.bash_profile && . ~/.bash_profile
RUN echo 'export PYTHONDONTWRITEBYTECODE=1' >> ~/.bash_profile && . ~/.bash_profile

# Setup OpenSSL
ARG OPENSSL_VERSION=1.1.0g
RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
RUN tar xvfz openssl-${OPENSSL_VERSION}.tar.gz
# Fix error `openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`. Reference: https://github.com/openssl/openssl/issues/3993
RUN cd openssl-${OPENSSL_VERSION} && \
    ./config \
    --debug \
    --prefix=/usr/local \
    --libdir=/lib \
    --openssldir=/usr/local/ssl && \
    make && make install
# Add /usr/local/openssl/lib to /etc/ld.so.conf and then run the command `ldconfig`
RUN echo '/usr/local/ssl/lib' >> /etc/ld.so.conf
RUN cat /etc/ld.so.conf
RUN ldconfig
RUN echo 'export LD_LIBRARY_PATH=/usr/local/ssl/lib' >> ~/.bash_profile && . ~/.bash_profile
RUN openssl version
```

But then when I add additional code that uses OpenSSL at the bottom of the Dockerfile as follows:
```
# Setup Microraiden
ARG MICRORAIDEN_VERSION=0.1.0
# https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
RUN pip3 install http://github.com/raiden-network/microraiden/archive/v${MICRORAIDEN_VERSION}.zip
``` 

It returns the following errors:
```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting http://github.com/raiden-network/microraiden/archive/v0.1.0.zip
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 808, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
ERROR: Service 'sandbox' failed to build: The command '/bin/sh -c pip3 install http://github.com/raiden-network/microraiden/archive/v${MICRORAIDEN_VERSION}.zip' returned a non-zero code: 2
```

Do you know I can add the Python SSL module?
So far I've tried adding the following before the line of code that tries to install the Pip dependency from its Github (i.e. before `RUN pip3 install ...`), but without any luck

**Comment by levitte** [comment]
You keep trying to find the libraries in `/usr/local/ssl/lib`, but if you look, I'm pretty sure you'll find them in `/usr/local/lib`

Actually, your first attempt was pretty good, except for this line:

```
RUN echo 'export LD_LIBRARY_PATH=/usr/local/ssl/lib' >> ~/.bash_profile && . ~/.bash_profile
```

It should be this:

```
RUN echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bash_profile && . ~/.bash_profile
```

To sum it up, this should do it (note how I consistently changed `/usr/local/ssl/lib` to `/usr/local/lib`):

```
FROM ubuntu:trusty
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y build-essential
RUN apt-get install -y zlib1g-dev
ARG OPENSSL_VERSION=1.1.0g
RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
RUN tar xvfz openssl-${OPENSSL_VERSION}.tar.gz
RUN cd openssl-${OPENSSL_VERSION} && ./config && make && make install
RUN echo '/usr/local/lib' >> /etc/ld.so.conf
RUN cat /etc/ld.so.conf
RUN ldconfig
RUN echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bash_profile && . ~/.bash_profile
RUN openssl version
```

**Comment by dot-asm** [comment]
I'd say it was only matter of time for somebody to get hit by this since automatic rpath was removed :-) I mean correct answer is to configure with `-Wl,-rpath,$(LIBRPATH)`, isn't it? Trouble with LD_LIBRARY_PATH is that is can be ignored, or you can into irreconcilable contradiction. BTW, why would one want to setup both ld.so.cache and set LD_LIBRARY_PATH? [On side note, Ubuntu libc-bin does add /usr/local/lib to ld.so.cache...]

**Comment by levitte** [comment]
> [On side note, Ubuntu libc-bin does add /usr/local/lib to ld.so.cache...]

I think all Debian based distros do, so I was surprised to see that it might be needed.  Perhaps it's docker (I have zero experience with docker, so what do I know?), or perhaps it's just making tripply sure...
