### ISSUE TITLE
High Siearra  Openssl Issue 

### ISSUE THREAD

**Issue by cah-sachin** [openssl/openssl#5167]
We are facing issue with Mac OS High Sierra 10.13.2 (17C88).

We are using oscrypto library which internally uses openssl of OS.  While accessing it we are receiving following error. 

We don't receive below error in sierra operating system of MAC

```
Traceback (most recent call last):
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/cli.py", line 413, in main
    environments=options.environments, tasks=arguments)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/reactor.py", line 128, in build
    return self.build_execution_plan(tasks, execution_plan)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/reactor.py", line 166, in build_execution_plan
    reactor=self)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/execution.py", line 351, in execute_execution_plan
    summaries.append(self.execute_task(task, **keyword_arguments))
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/execution.py", line 298, in execute_task
    task.execute(self.logger, keyword_arguments)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/execution.py", line 169, in execute
    executable.execute(argument_dict)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/execution.py", line 100, in execute
    self.callable(*arguments)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/plugins/python/unittest_plugin.py", line 61, in run_unit_tests
    run_tests(project, logger, "unittest", "unit tests")
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/plugins/python/unittest_plugin.py", line 71, in run_tests
    project, logger, execution_prefix, execution_name))
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/utils.py", line 323, in fork_process
    raise_exception(result[1], result[2])
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/utils.py", line 305, in instrumented_target
    send_value = (target(*args, **kwargs), None, None)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/plugins/python/unittest_plugin.py", line 101, in do_run_tests
    test_method_prefix)
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/pybuilder/plugins/python/unittest_plugin.py", line 136, in execute_tests_matching
    tests = loader.loadTestsFromNames(test_modules)
  File "/Users/rodrigo.velez/.pyenv/versions/2.7.14/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/rodrigo.velez/.pyenv/versions/2.7.14/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/src/unittest/python/services/test_certificate_service.py", line 13, in <module>
    from deeplaser.certificate.crypto.standard import TokenGeneratorOsCrypto
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/src/main/python/deeplaser/certificate/crypto/standard.py", line 11, in <module>
    from oscrypto import asymmetric
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/asymmetric.py", line 15, in <module>
    from .kdf import pbkdf2, pbkdf2_iteration_calculator
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/util.py", line 10, in <module>
    from ._osx.util import rand_bytes
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/_osx/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/_openssl/_libcrypto.py", line 14, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/rodrigo.velez/First_steps/deeplaser-core/deeplaser-core-env/lib/python2.7/site-packages/oscrypto/_openssl/_libcrypto_ctypes.py", line 668, in <module>
    raise FFIEngineError('Error initializing ctypes')
FFIEngineError: Error initializing ctypes
------------------------------------------------------------
BUILD FAILED - Error initializing ctypes
------------------------------------------------------------
```

**Comment by levitte** [comment]
I suggest you go to the [oscrypto](https://github.com/wbond/oscrypto) project.
