### ISSUE TITLE
EVP_DigestSignInit() fails silently if no key is loaded

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#5838]
I noticed just recently that `int_ctx_new()` (and as a consequence `EVP_DigestSignInit()` fails silently if no key is loaded, see [crypto/evp/pmeth_lib.c, #L105](https://github.com/openssl/openssl/blob/master/crypto/evp/pmeth_lib.c#L105) and the callstack below.

```
    #0  int_ctx_new (pkey=0x0, e=0x0, id=-1) at pmeth_lib.c:138
    #1  0x00007ffff6dd6cdd in EVP_PKEY_CTX_new (pkey=0x0, e=0x0) at pmeth_lib.c:273
    #2  0x00007ffff6dd8c95 in do_sigver_init (ctx=0x5555557a35b0, pctx=0x0, type=0x0, e=0x0, pkey=0x0, ver=0) at m_sigver.c:72
    #3  0x00007ffff6dd8efc in EVP_DigestSignInit (ctx=0x5555557a35b0, pctx=0x0, type=0x0, e=0x0, pkey=0x0) at m_sigver.c:119
```

And there are probably some more locations of that kind:

```
msp@msppc:~/src/openssl$ pcregrep -rnM '\([!]pkey[ )].*\n.*return'  crypto ssl
crypto/cms/cms_env.c:62:        if (!pkey)
            return 0;
crypto/pkcs7/pk7_doit.c:98:    if (!pkey)
        return 0;
crypto/evp/pmeth_lib.c:105:        if (!pkey || !pkey->ameth)
            return NULL;
crypto/x509/x_pubkey.c:226:    if (!pkey)
        return NULL;
crypto/x509/x_pubkey.c:266:    if (!pkey)
        return NULL;
crypto/x509/x_pubkey.c:306:    if (!pkey)
        return NULL;
crypto/pkcs12/p12_kiss.c:194:        if (!pkey || *pkey)
            return 1;
crypto/pkcs12/p12_kiss.c:202:        if (!pkey || *pkey)
            return 1;
```

@FdaSilvaYY offered to fix these issues.

**Comment by mspncp** [comment]
Issue was noticed with 1.0.2, might be worth backporting.

**Comment by richsalz** [comment]
we have fixed all of these in master.
We can open 1.0.2 issues if we want to fix them there.
