### ISSUE TITLE
90-test_shlibload.t fails with 1.1.0h on cygwin build

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#5960]
I used 32bit build with default config.

```
Test Summary Report
-------------------
../test/recipes/90-test_shlibload.t      (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=96, Tests=555, 1228 wallclock secs ( 3.11 usr  2.19 sys + 214.48 cusr 567.22 csys = 787.00 CPU)
Result: FAIL
Makefile:157: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/SofAdmin/openssl-1.1.0h'
Makefile:155: recipe for target 'tests' failed
make: *** [tests] Error 2

$ make test TESTS=test_shlibload V=1
make depend && make _tests
make[1]: Entering directory '/home/SofAdmin/openssl-1.1.0h'
make[1]: Leaving directory '/home/SofAdmin/openssl-1.1.0h'
make[1]: Entering directory '/home/SofAdmin/openssl-1.1.0h'
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="/usr/bin/perl" \
  EXE_EXT=.exe \
  OPENSSL_ENGINES=`cd .././engines; pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    /usr/bin/perl .././test/run_tests.pl test_shlibload )
../test/recipes/90-test_shlibload.t ..
1..3
../../util/shlib_wrap.sh ../../test/shlibloadtest.exe -crypto_first cygcrypto-1.1.dll cygssl-1.1.dll => 139
not ok 1 - running shlibloadtest -crypto_first

#   Failed test 'running shlibloadtest -crypto_first'
#   at ../test/recipes/90-test_shlibload.t line 32.
../../util/shlib_wrap.sh ../../test/shlibloadtest.exe -ssl_first cygcrypto-1.1.dll cygssl-1.1.dll => 0
ok 2 - running shlibloadtest -ssl_first
../../util/shlib_wrap.sh ../../test/shlibloadtest.exe -just_crypto cygcrypto-1.1.dll cygssl-1.1.dll => 0
ok 3 - running shlibloadtest -just_crypto
# Looks like you failed 1 test of 3.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
../test/recipes/90-test_shlibload.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=3, 22 wallclock secs ( 0.14 usr  0.50 sys +  0.60 cusr  2.02 csys =  3.26 CPU)
Result: FAIL
Makefile:157: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/SofAdmin/openssl-1.1.0h'
Makefile:155: recipe for target 'tests' failed
make: *** [tests] Error 2

(gdb) r
Starting program: C:\cygwin\home\SofAdmin\openssl-1.1.0h\test\shlibloadtest.exe -crypto_first cygcrypto-1.1.dll cygssl-1.1.dll
[New Thread 4160.0x13bc]
warning: cYgFFFFFFFF 611E6890 0
[New Thread 4160.0xbd4]
[New Thread 4160.0xe94]
[New Thread 4160.0x14e8]
warning: cYgstd 0x22cbef d 3

Thread 1 received signal SIGSEGV, Segmentation fault.
0x690d9260 in ?? ()
(gdb) bt
#0  0x690d9260 in ?? ()
#1  0x6dc40692 in OPENSSL_cleanup ()
   from C:\cygwin\home\SofAdmin\openssl-1.1.0h\test\cygcrypto-1.1.dll
#2  0x611a07b5 in __call_exitprocs () from C:\cygwin\bin\cygwin1.dll
#3  0x61158637 in __cxa_finalize () from C:\cygwin\bin\cygwin1.dll
#4  0x61028deb in dll_list::detach(void*) () from C:\cygwin\bin\cygwin1.dll
#5  0x61029619 in cygwin_detach_dll () from C:\cygwin\bin\cygwin1.dll
#6  0x610f18c5 in _sigfe () from C:\cygwin\bin\cygwin1.dll
#7  0x00000000 in ?? ()
```

**Comment by bernd-edlinger** [comment]
The same test succeeds on master.

**Comment by t8m** [comment]
1.1.0 is out of support for a long time.
