### ISSUE TITLE
Server accepts early data after 2nd handshake in HRR case

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#6734]
if the first ClientHello advertises early_data but its key_shares are not acceptable to the server, the server sends HelloRetryRequest, in second ClientHello the client must not send the early_data and early data is not allowed after HelloRetryRequest ([section 4.1.2 of draft 28](https://tools.ietf.org/html/draft-ietf-tls-tls13-28#section-4.1.2)):
```
   -  Removing the "early_data" extension (Section 4.2.10) if one was
      present.  Early data is not permitted after HelloRetryRequest.
```

despite that, if the client sends random garbage in place of Finished message, the server does not abort the connection with `bad_record_mac` if the sum of the lengths of the messages doesn't exceed the set maximum for early data; if it does, it sends `unexpected_message` alert

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tomato42/tlsfuzzer/pull/423 is merged
git checkout 0rtt-garbage-resumption
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-0rtt-garbage.py --num-bytes 16428
PYTHONPATH=. python scripts/test-tls13-0rtt-garbage.py
popd
kill $openssl_pid

```

  </p></details>

  <details><summary>tlsfuzzer output</summary><p>

```
$ PYTHONPATH=. python scripts/test-tls13-0rtt-garbage.py --num-bytes 16428
sanity ...
OK

handshake with invalid 0-RTT and CCS ...
OK

handshake with invalid 0-RTT and HRR ...
OK

handshake with invalid 0-RTT with fragmented early data ...
OK

undecryptable record later in handshake together with early_data ...
OK

handshake with invalid 0-RTT and CCS between early data records ...
OK

handshake with invalid PSK ...
OK

handshake with 0-RTT, HRR and early data after 2nd Client Hello ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f789ec8d750> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f789ec8d710>) with last message being: <tlslite.messages.Message object at 0x7f789ecb3350>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-0rtt-garbage.py", line 674, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 212, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1080, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "bad_record_mac" does not match received "unexpected_message"

handshake with invalid 0-RTT ...
OK

sanity ...
OK

Basic check if TLS 1.3 server can handle 0-RTT handshake
Verify that the server can handle a 0-RTT handshake from client
even if (or rather, especially if) it doesn't support 0-RTT.

version: 1

Test end
successful: 9
failed: 1
  'handshake with 0-RTT, HRR and early data after 2nd Client Hello'
```
```
$ PYTHONPATH=. python scripts/test-tls13-0rtt-garbage.py
sanity ...
OK

handshake with invalid 0-RTT and CCS ...
OK

handshake with invalid 0-RTT and HRR ...
OK

handshake with invalid 0-RTT with fragmented early data ...
OK

undecryptable record later in handshake together with early_data ...
OK

handshake with invalid 0-RTT and CCS between early data records ...
OK

handshake with invalid PSK ...
OK

handshake with 0-RTT, HRR and early data after 2nd Client Hello ...
Error encountered while processing node <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f143b4b57d0> (child: <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f143b4b57d0>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-0rtt-garbage.py", line 674, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
    raise AssertionError("Unexpected closure from peer")
AssertionError: Unexpected closure from peer

handshake with invalid 0-RTT ...
OK

sanity ...
OK

Basic check if TLS 1.3 server can handle 0-RTT handshake
Verify that the server can handle a 0-RTT handshake from client
even if (or rather, especially if) it doesn't support 0-RTT.

version: 1

Test end
successful: 9
failed: 1
  'handshake with 0-RTT, HRR and early data after 2nd Client Hello'
```

  </p></details>

  <details><summary>openssl output</summary><p>

```
Using default temp DH parameters
ACCEPT
140656046446400:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:674:
140656046446400:error:142140A4:SSL routines:early_data_count_ok:too much early data:ssl/record/ssl3_record.c:143:
140656046446400:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:674:
```

  </p></details>

**Comment by mattcaswell** [comment]
Fix in #6737.
