### ISSUE TITLE
s_server does not support fragmented GET request with KeyUpdate in the middle

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8188]
using 1980ce45d6bdd

When OpenSSL s_server receives the HTTP GET split over two records (with KeyUpdate in between), the connection hangs. The communication from client:

 1. ApplicationData "GET"
 2. KeyUpdate update_requested
 3. ApplicationData " / HTTP/1.0\r\n"

Server replies with KeyUpdate and then connection hangs

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tomato42/tlsfuzzer/pull/501 is merged
git checkout key-update-handshake
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
pushd .tlslite-ng
# won't be needed after https://github.com/tomato42/tlslite-ng/pull/341 is merged
git checkout key-update-support
popd
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-tls13-keyupdate.py "app data split, conversation with KeyUpdate msg"
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
Error encountered while processing node <tlsfuzzer.expect.ExpectApplicationData object at 0x7f0250faad90> (child: <tlsfuzzer.messages.AlertGenerator object at 0x7f0250faadd0>) with last message being: None
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-keyupdate.py", line 575, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 204, in run
    "Timeout when waiting for peer message")
AssertionError: Timeout when waiting for peer message

Test with KeyUpdate msg with different msg_type or fragmented msg.
Verify that server will correctly handle updating the keys
or refuse the connection with relevant Alert msg.
version: 1

Test end
successful: 0
failed: 1
  'app data split, conversation with KeyUpdate msg'
```
   </p></details>

I am filing it as separate issue, as it looks to me like it's a problem of the HTTP implementation in s_server rather than a bug in handling KeyUpdate requests

**Comment by nhorman** [comment]
@tomato42 is this still an issue on 3.3?

**Comment by tomato42** [comment]
Yes, exact same behaviour with the 3.3.1 tag (db2ac4f6ebd8f3)

**Comment by nhorman** [comment]
@tomato42 ok, thank you, I'm not quite sure how to handle this.  Its clearly a bug, but I'm not sure how robust s_server is meant to be for the use case you are providing.  Are you willing to investigate the root cause and provide a PR?  If so, I'll gladly assign this to you as a community issue.  If not, I'll move it to be considered for inclusion in a future minor release, but I'm not sure how much priority it will receive during our issue scheduling.  Given that its already 5 years old, the former may be the faster path forward.

**Comment by tomato42** [comment]
the issue is that the server is assuming that every text line is in a single ApplicationData packet; so the fix would be to implement a "read line" API on top of the regular socket

it would be useful as example code of what to do, but it's not severe

**Comment by nhorman** [comment]
ah, ok.  Cool.  I don't suppose you have interest in submitting a PR for that, do you?

**Comment by tomato42** [comment]
definitely not a priority :)

**Comment by nhorman** [comment]
ok, understood :)

I'll mark this as a community issue then, and hopefully someone  will get to it

**Comment by t8m** [comment]
Please note we are looking for community help implementing this issue. Please comment if you are interested in implementing this feature or if you have reasons why this feature is important enough so we should consider implementing it with higher priority than other requested features. The issue will be closed after 3 months otherwise.

**Comment by t8m** [comment]
This issue was closed because it was marked with the help wanted label and there was no interest in implementing this issue or any other activity for more than 2 months.
