### ISSUE TITLE
Incorrect alert for ClientHello with data after extensions field

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8293]
When a ClientHello with data trailing extensions field is present, the server is expected to send `decode_error`, per [section 4.1.2 of RFC 8446](https://tools.ietf.org/html/rfc8446#page-30):
```
   If negotiating a version of TLS prior to 1.3,
   a server MUST check that the message either contains no data after
   legacy_compression_methods or that it contains a valid extensions
   block with no data following.  If not, then it MUST abort the
   handshake with a "decode_error" alert.
```
OpenSSL c8147d37c sends `illegal_parameter` when the overall message size is large

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tomato42/tlsfuzzer/pull/518 is merged
git checkout strict-client-hello-checks
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-truncating-of-client-hello.py
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
Using default temp DH parameters
ACCEPT
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1505:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1505:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1537:
139715565307712:error:14160098:SSL routines:read_state_machine:excessive message size:ssl/statem/statem.c:603:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1543:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D0A0:SSL routines:tls_process_client_hello:length too short:ssl/statem/statem_srvr.c:1438:
139715565307712:error:1417D0A0:SSL routines:tls_process_client_hello:length too short:ssl/statem/statem_srvr.c:1438:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1543:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1537:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1537:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:14160098:SSL routines:read_state_machine:excessive message size:ssl/statem/statem.c:603:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1537:
139715565307712:error:1417D09F:SSL routines:tls_process_client_hello:length mismatch:ssl/statem/statem_srvr.c:1554:

```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

small truncate: 5 of bytes truncated ...
OK

extension past extensions ...
OK

hello truncate: 32 of bytes truncated ...
OK

hello truncate: 39 of bytes truncated ...
OK

big pad: 65536 of "0" byte padding ...
OK

small pad: 2 of "255" byte padding ...
OK

small truncate: 4 of bytes truncated ...
OK

small truncate: 1 of bytes truncated ...
OK

large pad: 4096 of "0" byte padding ...
OK

small truncate: 2 of bytes truncated ...
OK

hello truncate: 12 of bytes truncated ...
OK

huge pad: 131584 of "0" byte padding ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7faf61e72cd0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7faf61e72d10>) with last message being: <tlslite.messages.Message object at 0x7faf60377090>
Error while processing
Traceback (most recent call last):
  File "scripts/test-truncating-of-client-hello.py", line 198, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 223, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1412, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"

hello truncate: 9 of bytes truncated ...
OK

small pad: 2 of "0" byte padding ...
OK

hello truncate: 47 of bytes truncated ...
OK

full message truncate: 48 of bytes truncated ...
OK

hello truncate: 8 of bytes truncated ...
OK

small pad: 1 of "0" byte padding ...
OK

hello truncate: 13 of bytes truncated ...
OK

hello truncate: 10 of bytes truncated ...
OK

small pad: 3 of "0" byte padding ...
OK

small truncate: 6 of bytes truncated ...
OK

small pad: 1 of "255" byte padding ...
OK

max pad: 16777167 of "0" byte padding ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7faf61e72ed0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7faf61e72f10>) with last message being: <tlslite.messages.Message object at 0x7faf6039ad90>
Error while processing
Traceback (most recent call last):
  File "scripts/test-truncating-of-client-hello.py", line 198, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 223, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1412, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"

small truncate: 3 of bytes truncated ...
OK

small pad: 3 of "255" byte padding ...
OK

hello truncate: 11 of bytes truncated ...
OK

medium pad: 256 of "0" byte padding ...
OK

sanity ...
OK

Check if ClientHello length checking is correct in server
version: 2

Test end
successful: 28
failed: 2
  'huge pad: 131584 of "0" byte padding'
  'max pad: 16777167 of "0" byte padding'
```
   </p></details>

**Comment by mattcaswell** [comment]
There are no plans to fix this. Closing.

**Comment by tomato42** [comment]
@mattcaswell that's not how you build healthy community around your software

**Comment by t8m** [comment]
@tomato42 Please, this is by no way a RFC non-compliant behavior. It is just a matter of interpretation so there is no need for such kind of angry reaction.

**Comment by tomato42** [comment]
@t8m telling me that facts are not facts but opinions is exactly what I have issue with
