### ISSUE TITLE
Wrong alerts/error handling in case some algorithms are disabled

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#8443]
using bcf082d130a4

when server is configured with only some algorithms for client certificates and the client selects something else the server rejects the connection with `handshake_failure` instead of `illegal_parameter` (that is being sent for pkcs#1 signatures or rsa_pss_pss signatures with rsae certificates or vice-versa)

this would indicate that the the checks between CertificateRequest and CertificateVerify are incorrect or missing

   <details><summary>reproducer</summary><p>

```
openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -www -client_sigalgs RSA+SHA384:rsa_pss_rsae_sha384:rsa_pss_pss_sha384 -verify 0 2>server.err >server.out &
openssl_pid=$!
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python python scripts/test-tls13-certificate-verify.py -n 10 -k /tmp/localhost.key -c /tmp/localhost.crt -s "sha384+rsa rsa_pss_rsae_sha384 rsa_pss_pss_sha384"
popd
kill $openssl_pid
```
   </p></details>

   <details><summary>OpenSSL output</summary><p>

```
verify depth is 0
Using default temp DH parameters
ACCEPT
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E088:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length check failed:crypto/rsa/rsa_pss.c:110:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1030:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1030:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E088:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length check failed:crypto/rsa/rsa_pss.c:110:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1030:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1091:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1091:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E086:rsa routines:RSA_verify_PKCS1_PSS_mgf1:last octet invalid:crypto/rsa/rsa_pss.c:88:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E088:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length check failed:crypto/rsa/rsa_pss.c:110:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E088:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length check failed:crypto/rsa/rsa_pss.c:110:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1023:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
140256657028928:error:0407E087:rsa routines:RSA_verify_PKCS1_PSS_mgf1:salt length recovery failed:crypto/rsa/rsa_pss.c:106:
140256657028928:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:ssl/statem/statem_lib.c:493:
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
```
   </p></details>

   <details><summary>tlsfuzzer output</summary><p>

```
sanity ...
OK

check rsa_pss_rsae_sha384 signature works ...
OK

check signature with salt length 47 ...
OK

check rsa_pss_pss_sha512 signature is refused ...
OK

check (1, 1) signature is refused ...
OK

check rsa_pss_pss_sha256 signature is refused ...
OK

check signature with salt length 49 ...
OK

check rsa_pkcs1_sha256 signature is refused ...
OK

check rsa_pss_pss_sha384 signature is refused ...
OK

check rsa_pss_rsae_sha512 signature is refused ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f7832b9e090> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f7832b9e0d0>) with last message being: <tlslite.messages.Message object at 0x7f7831ac8990>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-certificate-verify.py", line 583, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 227, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1412, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "handshake_failure"

check rsa_pss_rsae_sha256 signature is refused ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f7832b97550> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f7832b97590>) with last message being: <tlslite.messages.Message object at 0x7f7831862210>
Error while processing
Traceback (most recent call last):
  File "scripts/test-tls13-certificate-verify.py", line 583, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 227, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1412, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "handshake_failure"

check rsa_pkcs1_sha384 signature is refused ...
OK

check pkcs1 signature with rsa-pss envelope fails ...
OK

check sigalgs in cert request ...
OK

check signature with salt length 0 ...
OK

check rsa_pkcs1_sha1 signature is refused ...
OK

check rsa-pss signature with mismatched hash fails ...
OK

check rsa-pss signature with mismatched mgf1 fails ...
OK

check rsa_pkcs1_sha224 signature is refused ...
OK

check rsa_pkcs1_sha512 signature is refused ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x2 at 218 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x2 at 219 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 142 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 143 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 140 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 141 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 146 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 147 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 144 ...
OK

check that fuzzed signatures are rejected. Malformed rsa - xor 0x8 at 145 ...
OK

sanity ...
OK

Test to verify that server properly accepts or refuses
signatures in TLS1.3; PKCS1 signatures are always refused.
Other signatures are accepted or refused accordingly to
the certificate type provided ('rsa' vs 'rsa-pss').

version: 1

Test end
successful: 29
failed: 2
  'check rsa_pss_rsae_sha256 signature is refused'
  'check rsa_pss_rsae_sha512 signature is refused'
```
   </p></details>

**Comment by nhorman** [comment]
@tomato42 does the patch referenced above solve this problem?

**Comment by tomato42** [comment]
I'm sorry, which patch? I only see a link to the tpm2-software module, I don't use it...

**Comment by nhorman** [comment]
@tomato42 I'm referring to the merged PR referenced above by @dnoliver.  I've not read over the patch in any depth admittedly, but given the age of this issue, I thought I would ask before I look at this more deeply.  The question in short is, does the latest release fix this problem?

**Comment by tomato42** [comment]
no, still happening with 3.3.1:
```
check rsa_pss_rsae_sha256 signature is refused ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1d8ce67e00>) with last message being: <tlslite.messages.Message object at 0x7f1d8c5366f0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-certificate-verify.py", line 481, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1919, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "handshake_failure"

check rsa_pss_rsae_sha384 signature works ...
OK

check rsa_pss_rsae_sha512 signature is refused ...
Error encountered while processing node ExpectAlert(level=2, description=(47,)) (child: <tlsfuzzer.expect.ExpectClose object at 0x7f1d8cc88650>) with last message being: <tlslite.messages.Message object at 0x7f1d8c536cc0>
Error while processing
Traceback (most recent call last):
  File "/home/hkario/dev/tlsfuzzer/scripts/test-tls13-certificate-verify.py", line 481, in main
    runner.run()
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/runner.py", line 242, in run
    node.process(self.state, msg)
  File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/expect.py", line 1919, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "illegal_parameter" does not match received "handshake_failure"

```

**Comment by nhorman** [comment]
Understood, thank you

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues

**Comment by cryptechsurpport** [comment]
I started trading Crypto on Binary options, at first everything was going smoothly till I tried withdrawing. I was made to believe that I had to build my account to a certain point before withdrawing, I had lost total sum of 10.000btc. After weeks of turmoil and sadness that investment brought me and my family. I saw recommendations to 
P E R F E C T R E C L A I M R E C O V E R I N G O N   I N S T A and i was lucky they helped me recover all of my funds without any hassle in less than 48 hours, I am so happy doing this because I know how many people would benefit from this useful information. Fortunately for me I was able to recover all i lost P E R F E C T R E C L A I M RECOVERY CONSULTANT is a real refund professional feel free to reach out to them for quick response if you’re having similar issues
