### ISSUE TITLE
Adding dirName to subject_alt_name causes segfault on openssl 1.0.2.o

### ISSUE THREAD

**Issue by jparris** [openssl/openssl#8539]
Hi there,
I'm attempting to programmatically add a dirName as Subject Alternative Name to a CSR. I started with the openssl-1.0.2.o/demos/x509/mkreq.c, added `add_ext(exts, NID_subject_alt_name, "dirName:\\C=UK"); ` and removed the the `ifndef` around the exts code. I've include the entire source at the bottom of this report.

# OpenSSL Version (Note FIPS is not enabled)
```
$ openssl version
OpenSSL 1.0.2o-fips  27 Mar 2018
$ env | grep OPENSSL_FIPS
$ 
```
# Backtace
```
$ gcc mkreq.c -lssl -lcrypto -ggdb
$ gdb a.out 
...
(gdb) r
Starting program: <snipped out>/demos/x509/a.out 
...........++++++++++++
.++++++++++++

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78bdf37 in X509V3_get_section () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) bt
#0  0x00007ffff78bdf37 in X509V3_get_section () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff78c12ec in a2i_GENERAL_NAME () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007ffff78c1a37 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007ffff78bd974 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#4  0x00007ffff78bdcae in X509V3_EXT_nconf_nid () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#5  0x00007ffff78be0bf in X509V3_EXT_conf_nid () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00000000004011cb in add_ext (sk=0x603630, nid=85, value=0x4012e2 "dirName:\\C=UK") at mkreq.c:161
#7  0x000000000040111e in mkreq (req=0x7fffffffe5e0, pkeyp=0x7fffffffe5d8, bits=512, serial=0, days=365)
    at mkreq.c:121
#8  0x0000000000400ed7 in main (argc=1, argv=0x7fffffffe6d8) at mkreq.c:30
```
# Entire Code
```
/*
 * Certificate request creation. Demonstrates some request related
 * operations.
 */

#include <stdio.h>
#include <stdlib.h>

#include <openssl/pem.h>
#include <openssl/conf.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#ifndef OPENSSL_NO_ENGINE
# include <openssl/engine.h>
#endif

int mkreq(X509_REQ **x509p, EVP_PKEY **pkeyp, int bits, int serial, int days);
int add_ext(STACK_OF(X509_EXTENSION) *sk, int nid, char *value);

int main(int argc, char **argv)
{
    BIO *bio_err;
    X509_REQ *req = NULL;
    EVP_PKEY *pkey = NULL;

    CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);

    bio_err = BIO_new_fp(stderr, BIO_NOCLOSE);

    mkreq(&req, &pkey, 512, 0, 365);

    RSA_print_fp(stdout, pkey->pkey.rsa, 0);
    X509_REQ_print_fp(stdout, req);

    PEM_write_X509_REQ(stdout, req);

    X509_REQ_free(req);
    EVP_PKEY_free(pkey);

#ifndef OPENSSL_NO_ENGINE
    ENGINE_cleanup();
#endif
    CRYPTO_cleanup_all_ex_data();

    CRYPTO_mem_leaks(bio_err);
    BIO_free(bio_err);
    return (0);
}

static void callback(int p, int n, void *arg)
{
    char c = 'B';

    if (p == 0)
        c = '.';
    if (p == 1)
        c = '+';
    if (p == 2)
        c = '*';
    if (p == 3)
        c = '\n';
    fputc(c, stderr);
}

int mkreq(X509_REQ **req, EVP_PKEY **pkeyp, int bits, int serial, int days)
{
    X509_REQ *x;
    EVP_PKEY *pk;
    RSA *rsa;
    X509_NAME *name = NULL;
    STACK_OF(X509_EXTENSION) *exts = NULL;

    if ((pk = EVP_PKEY_new()) == NULL)
        goto err;

    if ((x = X509_REQ_new()) == NULL)
        goto err;

    rsa = RSA_generate_key(bits, RSA_F4, callback, NULL);
    if (!EVP_PKEY_assign_RSA(pk, rsa))
        goto err;

    rsa = NULL;

    X509_REQ_set_pubkey(x, pk);

    name = X509_REQ_get_subject_name(x);

    /*
     * This function creates and adds the entry, working out the correct
     * string type and performing checks on its length. Normally we'd check
     * the return value for errors...
     */
    X509_NAME_add_entry_by_txt(name, "C", MBSTRING_ASC, "UK", -1, -1, 0);
    X509_NAME_add_entry_by_txt(name, "CN",
                               MBSTRING_ASC, "OpenSSL Group", -1, -1, 0);

    /*
     * Certificate requests can contain extensions, which can be used to
     * indicate the extensions the requestor would like added to their
     * certificate. CAs might ignore them however or even choke if they are
     * present.
     */

    /*
     * For request extensions they are all packed in a single attribute. We
     * save them in a STACK and add them all at once later...
     */

    exts = sk_X509_EXTENSION_new_null();
    /* Standard extenions */

    add_ext(exts, NID_key_usage, "critical,digitalSignature,keyEncipherment");

    /*
     * This is a typical use for request extensions: requesting a value for
     * subject alternative name.
     */

    add_ext(exts, NID_subject_alt_name, "email:steve@openssl.org");
    add_ext(exts, NID_subject_alt_name, "dirName:\\C=UK");

    /* Some Netscape specific extensions */
    add_ext(exts, NID_netscape_cert_type, "client,email");

# ifdef CUSTOM_EXT
    /* Maybe even add our own extension based on existing */
    {
        int nid;
        nid = OBJ_create("1.2.3.4", "MyAlias", "My Test Alias Extension");
        X509V3_EXT_add_alias(nid, NID_netscape_comment);
        add_ext(x, nid, "example comment alias");
    }
# endif

    /* Now we've created the extensions we add them to the request */

    X509_REQ_add_extensions(x, exts);

    sk_X509_EXTENSION_pop_free(exts, X509_EXTENSION_free);


    if (!X509_REQ_sign(x, pk, EVP_sha1()))
        goto err;

    *req = x;
    *pkeyp = pk;
    return (1);
 err:
    return (0);
}

/*
 * Add extension using V3 code: we can set the config file as NULL because we
 * wont reference any other sections.
 */

int add_ext(STACK_OF(X509_EXTENSION) *sk, int nid, char *value)
{
    X509_EXTENSION *ex;
    ex = X509V3_EXT_conf_nid(NULL, NULL, nid, value);
    if (!ex)
        return 0;
    sk_X509_EXTENSION_push(sk, ex);

    return 1;
}
```

**Comment by levitte** [comment]
So first late impression is that `\\C=UK` looks like an odd RDN...  Surely, it should be `/C=UK`.  I currently dunno if our code even supports the backslash syntax.

Also, 1.0.2 being on security issues only support, even when this issue was raised, and is near EOL makes it unlikely to be fixed in 1.0.2 specifically, so it would be good if you checked this against a current OpenSSL version (that would be 1.1.1d).

**Comment by davenpcj5542009** [comment]
I can confirm this still occurs with both OpenSSL 1.1.1d and OpenSSL 1.0.2x.

```
linux-asdf:~ # gcc -o openssl_bug_test -lssl -lcrypto openssl_bug_test.c
openssl_bug_test.c: In function ‘mkreq’:
openssl_bug_test.c:79:5: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
     rsa = RSA_generate_key(bits, RSA_F4, callback, NULL);
     ^~~
In file included from /usr/include/openssl/e_os2.h:13:0,
                 from /usr/include/openssl/pem.h:13,
                 from openssl_bug_test.c:9:
/usr/include/openssl/rsa.h:234:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
linux-asdf:~ # ./openssl_bug_test
.........+++++++++++++++++++++++++++
....................+++++++++++++++++++++++++++
Segmentation fault (core dumped)
linux-asdf:~ # openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

And further, this is caused by a NULL dereference in `a2i_GENERIC_NAME` after passing `NULL` to `X509V3_ext_conf_nid` as the second argument. Which works fine for other types.

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
