### ISSUE TITLE
CAST_encrypt shift overflow

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#9375]
I used to think this was a false positive but apparently unsigned int overshift might be undefined: https://stackoverflow.com/questions/33736337/large-bitwise-left-shift-on-unsigned-type/33736410

Stack trace from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14351

```
/src/libressl/crypto/cast/c_enc.c:73:2: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'
--
  | #0 0xb29152 in CAST_encrypt libressl/crypto/cast/c_enc.c:73:2
  | #1 0xb2aa58 in CAST_ecb_encrypt libressl/crypto/cast/c_ecb.c:71:3
  | #2 0xb073cb in cast5_ecb_cipher libressl/crypto/evp/e_cast.c:80:1
  | #3 0xb2345e in CMAC_Init libressl/crypto/cmac/cmac.c:182:8

```

**Comment by guidovranken** [comment]
Oh it's LibreSSL lol. sorry.
