### ISSUE TITLE
ARIA CMAC OOB read

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#9500]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16129

```cpp
#define CF_CHECK_EQ(expr, res) if ( (expr) != (res) ) { goto end; }
#define CF_CHECK_NE(expr, res) if ( (expr) == (res) ) { goto end; }

#include <openssl/cmac.h>

int main(void)
{
    const unsigned char key[2] = { 0 };
    CMAC_CTX* ctx = CMAC_CTX_new();
    const EVP_CIPHER* cipher = NULL;

    /* Initialize */
    {
        CF_CHECK_NE(cipher = EVP_aria_192_gcm(), NULL);
        CF_CHECK_EQ(CMAC_Init(ctx, key, sizeof(key), cipher, NULL), 1);
    }

end:
    return 0;
}
```

```

==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000000952 at pc 0x000000ee1f20 bp 0x7fffa40c1870 sp 0x7fffa40c1868
--
  | READ of size 1 at 0x603000000952 thread T0
  | SCARINESS: 12 (1-byte-read-heap-buffer-overflow)
  | #0 0xee1f1f in aria_set_encrypt_key openssl/crypto/aria/aria.c:559:13
  | #1 0x111fa7a in aria_gcm_init_key openssl/providers/common/ciphers/gcm_hw.c:277:5
  | #2 0xe6c7dc in CMAC_Init openssl/crypto/cmac/cmac.c:128:14
```

**Comment by slontis** [comment]
Thank you for finding an easy to reproduce test case..

**Comment by guidovranken** [comment]
Probably introduced somewhere in here: https://github.com/openssl/openssl/compare/35f6fe7ac4fbde98d4fd6af968dfe320011bbe1e...59b2cb2638dda3e07385ad36a41f0e141b36987b

**Comment by slontis** [comment]
I think I know who introduced it (i.e me :))

**Comment by mattcaswell** [comment]
Almost certainly this is a672a02

**Comment by slontis** [comment]
Found it ... Fix is coming.

**Comment by slontis** [comment]
Basically it should be returning an error, but currently due to the replumbing it just ignores trying to set the key len to a bad value..
