### ISSUE TITLE
unable to load Private Key

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#9610]
```
OpenSSL> version -a
OpenSSL 1.0.1f 6 Jan 2014
built on: Tue Dec  4 20:09:18 UTC 2018
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx)
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"
OpenSSL> rsa -in server_error.key -inform PEM -text -noout
unable to load Private Key
140095589111456:error:0906D066:PEM routines:PEM_read_bio:bad end line:pem_lib.c:802:
error in rsa
```
```
OpenSSL> version -a
OpenSSL 1.1.1a  20 Nov 2018
built on: Sat Jul 27 06:49:51 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific
OpenSSL> rsa -in server_error.key -inform PEM -text -noout
unable to load Private Key
error in rsa
```
Here is the private key：
```
 Bag Attributes
  2     localKeyID: 50 A7 C7 86 5C F8 EF D3 94 CE E5 EA 20 50 31 CF 38 1B D2 90
  3 Key Attributes: <No Attributes>
  4 -----BEGIN RSA PRIVATE KEY-----
  5 Proc-Type: 4,ENCRYPTED
  6 DEK-Info: DES-EDE3-CBC,D3C703E8ECA8DDA4
  7
  8 k/LxATxDVrTVNz553VUcsf2/0wiTq7ASo5twltNU6lsEmzIfBjGJUmsxHARyWTsJkW4z75oz9ToaraVan3PwRRjURJyd2++fmNmoIzbaWnMDWKYz0r1wdN4QSzAH8aMa
  9 YpxzXNB/+5Py3AI6gLGPdaKzzknONdShMB2ITM/7IGTwjSztkaOVvPEeTGvN16Rv
 10 NGiP6RewWQ7PjwbPq/00kvD9bCM5Mz0j08gaWWNBeLTEMEMZ5rBI99k3SQWIfcis
 11 1btGp0/T/AcVXexafp6jtS73s6dLW1wsZK5ZT/NYNGT7jooRZybrQ9OIb7U3MzcA
 12 Zze/WeW+T6ESlvCvsxDDiuoHHZoXp47aWGYqe/5mVoQv0VPjpdNsIMGivRARCo1i
 13 wZQRNBQLaOng3tNP6T9QySRYzLvEA7MBTzwKQigsWMOt1s83mlRTqe4xy7jnW6gW
 14 B38kCk5FXjTJCn554twVZ117hAycUt3Gs4ITvjFyA7DfM2cHPNHrvMTib586kpoN
 15 I8vfkpHP/kToxKIlnDK22S3dfmtL+cs2OzeB5vEtVXKM+TDf3blqGCmDp8lm/aIH
 16 PCNmm68n7m2seLSkQbr6vYEkC1rQXF5LoHsJ3GHUBM1jf3uapSu03CRNYky02zcW
 17 eU44lc8U4CmUAKo5yICabI9e7dgFk0F/0d7YiD3Hxd4N9/W6fhXckoXBO7sCCzQh
 18 wEfCzMKvgWbOTXsjK78xWLTgPfZwdSUKFvET+xrUEYxAA0kY9LZwnUNNF90OUI5S
 19 V8m+RFCfCkYCNkuVfBko1yb8mYwXkghTzgTpC/WQKku8p8A32fky5W7d7QEp4I9C
 20 6nMh1XZWky8IcZ9YDPQIJdpz+KMOToIfuIU+DUanxWxidAbE7gQ3M3UeN/l1AYwp
 21 0b7U4xeThyJf0Ed5slP8TQdFmsnpoo0vYAYpqgBhOAkSTDGPlmtTSXm3rIooG/kd
 22 zrzMSroD34t4t5cVi5X9ltnx0fUK++UR0vmabw7rGyQQtTWEH/W9SE2iLX9UZHQhQaZ3IAspRdRNt8Gp6fadmNZPBcluBYzuSOdnMuue1vqC5a4ZciyvpbFfQJx6g7nc
 23 iqjRdVXopeBxw8XG+s1nXombHGqy/4lHik7vzUono76OuzLG4nm7txRmKSL4flaQ
 24 hOGC5OR73wajf6703d66EO6Xr80vUdDtdcXtgrkvs+Yjtw8MlnA0i3EkuZwNkagT
 25 Vhez7+LEn0pjkct67h37/1ogXyoiaRDjLLma9Vt9Zs9D3W0TTvbZVwMXr1MvPy1r
 26 XTGmrgxKgN2yelEIrJJkDo2VfNlmpCEpx7dCV5Gyo0w4cZnWRVlQe+hWxITOZ4V2
 27 XEWPeBvPMyg/d0sENSAIk+xSKEiJUq+4A7pKDnRcZso0Zht3j4o5Ig/BkRrs7O7/
 28 ucaGBbbUquBxffhW+26grGGqXbq3ueYJOv/JwWLlXn7IB2oBXG0iZLVWhlJKHCep
 29 HDMC2Qkw9K2THk4PHbBrMeDuktpexFbRShbtYH5WEmeYsw8rO8hvD9l0uw/NJhO8
 30 WjDaxGa843CS7SfFE4MO3n/vvNxwGPljDhDHd292kFBTK4Dm4uzZ4Q==
 31 -----END RSA PRIVATE KEY-----

```
```
#0  get_header_and_data (bp=0x93b600, header=0x7fffffffe178, data=0x7fffffffe180, name=0x942a90 "CERTIFICATE", flags=2) at crypto/pem/pem_lib.c:791
#1  0x0000000000505e59 in PEM_read_bio_ex (bp=0x93b600, name_out=0x7fffffffe220, header=0x7fffffffe228, data=0x7fffffffe230, len_out=0x7fffffffe238, flags=2)
    at crypto/pem/pem_lib.c:919
#2  0x000000000050402e in pem_bytes_read_bio_flags (pdata=0x7fffffffe350, plen=0x7fffffffe358, pnm=0x0, name=0x656622 "CERTIFICATE", bp=0x93b600, cb=0x0,
    u=0x0, flags=2) at crypto/pem/pem_lib.c:247
#3  0x00000000005041df in PEM_bytes_read_bio (pdata=0x7fffffffe350, plen=0x7fffffffe358, pnm=0x0, name=0x656622 "CERTIFICATE", bp=0x93b600, cb=0x0, u=0x0)
    at crypto/pem/pem_lib.c:278
#4  0x0000000000506249 in PEM_ASN1_read_bio (d2i=0x55b8ff <d2i_X509>, name=0x656622 "CERTIFICATE", bp=0x93b600, x=0x0, cb=0x0, u=0x0)
    at crypto/pem/pem_oth.c:28
#5  0x0000000000506f4c in PEM_read_bio_X509 (bp=0x93b600, x=0x0, cb=0x0, u=0x0) at crypto/pem/pem_x509.c:18

```
https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/crypto/pem/pem_lib.c#L861-L867

In 865 lines of characters greater than 65 went to error, what is the basis for this behavior?

**Comment by levitte** [comment]
[RFC1421](https://tools.ietf.org/html/rfc1421), section 4.3.2.4  "Step 4: Printable Encoding", says this:

> To represent the encapsulated text of a PEM message, the encoding
> function's output is delimited into text lines (using local
> conventions), with each line except the last containing exactly 64
> printable characters and the final line containing 64 or fewer
> printable characters.

That is the basis for this behavior.

**Comment by yangyangtiantianlonglong** [comment]
Thanks Reply！
