### ISSUE TITLE
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF') 

### ISSUE THREAD

**Issue by kchetna** [openssl/openssl#9739]
Python 3.7.0
version - 
pyOpenSSL                      0.15.1
CherryPy                       18.1.1
cryptography                   2.2

Error is not reported for all request its reported for some request, but if same request retired it may get suceed.

Getting  OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF') time to time (for 1 request in 5-6 request)

```
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/ssl/pyopenssl.py", line 74, in _safe_call
    return call(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/_pyio.py", line 513, in readline
    b = self.read(nreadahead())
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/_pyio.py", line 492, in nreadahead
    readahead = self.peek(1)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/_pyio.py", line 1076, in peek
    return self._peek_unlocked(size)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/_pyio.py", line 1083, in _peek_unlocked
    current = self.raw.read(to_read)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1349, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1180, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/server.py", line 1242, in communicate
    req.parse_request()
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/server.py", line 712, in parse_request
    success = self.read_request_line()
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/server.py", line 764, in read_request_line
    request_line = self.rfile.readline()
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/server.py", line 300, in readline
    data = self.rfile.readline(256)
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/ssl/pyopenssl.py", line 126, in readline
    size,
  File "/usr/local/pyenv/versions/3.7.0/lib/python3.7/site-packages/cheroot/ssl/pyopenssl.py", line 86, in _safe_call
```

**Comment by levitte** [comment]
I think this should be asked of the pyOpenSSL folks: https://github.com/pyca/pyopenssl/
