### ISSUE TITLE
Wrong alert on resuming a session while dropping the Extended Master Secret extension.

### ISSUE THREAD

**Issue by t184256** [openssl/openssl#9791]
If a client attempts to resume a session that was previously negotiated with the Extended Master Secret extension, but does not send the extension on the resumption attempt,
the connection is aborted with `illegal parameter` instead of `handshake_failure` prescribed by the [RFC7627#5.3](https://tools.ietf.org/html/rfc7627#section-5.3):

```
   o  If the original session used the "extended_master_secret"
      extension but the new ClientHello does not contain it, the server
      MUST abort the abbreviated handshake.
```

"Abort the handshake" implies `handshake_failure`, see [RFC7627#5.2](https://tools.ietf.org/html/rfc7627#section-5.2)
```
   In the following, we use the phrase "abort the handshake" as
   shorthand for terminating the handshake by sending a fatal
   "handshake_failure" alert.
```

Tested with c7bfb138acf6103ae6fd178eb212b110bfb39c0d.

<details><summary>reproducing with tlsfuzzer</summary>
relevant line of the test: https://github.com/tomato42/tlsfuzzer/blob/345f1ffb109f4be761e68dbe59878f89dcd8f8ad/scripts/test-extended-master-secret-extension.py#L508

```
#!/usr/bin/env bash
set -uex

PYTHON=/usr/bin/python3
OPENSSL=./openssl/apps/openssl  # built with ./config no-shared for simplicity

openssl req -x509 -newkey rsa -keyout /tmp/localhost.key -out /tmp/localhost.crt -subj /CN=localhost -nodes -batch

git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
git checkout 345f1ffb109f4be761e68dbe59878f89dcd8f8ad

git clone https://github.com/tomato42/tlslite-ng .tlslite-ng
pushd .tlslite-ng
git checkout a328159326bb8aef43e5384ddbd6b31734239658
popd
ln -s .tlslite-ng/tlslite tlslite

git clone https://github.com/warner/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
pushd .python-ecdsa
git checkout 72621b15a7c37f2c7cb7f11a2bc8feaac68b3914
popd
popd

$OPENSSL s_server -tlsextdebug -security_debug -security_debug_verbose -debug \
    -key /tmp/localhost.key -cert /tmp/localhost.crt -www &>server.log &
openssl_pid=$!

PYTHONPATH=tlsfuzzer $PYTHON tlsfuzzer/scripts/test-extended-master-secret-extension.py \
    'EMS with session resume without extension' || true
kill $openssl_pid
```

</details>

<details><summary>tlsfuzzer output</summary>

```
EMS with session resume without extension ...
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f0ff25f5dd0> (child: <tlsfuzzer.expect.ExpectAlert object at 0x7f0ff25f5e10>) with last message being: <tlslite.messages.Message object at 0x7f0ff2611250>
Error while processing
Traceback (most recent call last):
  File "tlsfuzzer/scripts/test-extended-master-secret-extension.py", line 734, in
main
    runner.run()
  File "/home/asosedki/tmp/openssl-reproducer/tlsfuzzer/tlsfuzzer/runner.py", line 227, in run
    node.process(self.state, msg)
  File "/home/asosedki/tmp/openssl-reproducer/tlsfuzzer/tlsfuzzer/expect.py", line 1433, in process
    raise AssertionError(problem_desc)
AssertionError: Expected alert description "handshake_failure" does not match received "illegal_parameter"

Test end
successful: 0
failed: 1
  'EMS with session resume without extension'
```

</details>

<details><summary>openssl output</summary>

```
Using default temp DH parameters
Security callback: Certificate chain EE key=RSA, bits=2048, security bits=112: yes
ACCEPT
Security callback: Version=TLS 1.3: yes
Security callback: Version=TLS 1.3: yes
Security callback: Version=TLS 1.2: yes
Security callback: Version=TLS 1.1: yes
Security callback: Version=TLS 1.0: yes
read from 0x2132940 [0x2111813] (5 bytes => 5 (0x5))
0000 - 16 03 00 00 38                                    ....8
read from 0x2132940 [0x2111818] (56 bytes => 56 (0x38))
0000 - 01 00 00 34 03 03 00 00-00 00 00 00 00 00 00 00   ...4............
0010 - 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
0020 - 00 00 00 00 00 00 00 00-02 00 2f 01 00 00 09 ff   ........../.....
0030 - 01 00 01 00 00 17 00 00-                          ........
TLS client extension "renegotiation info" (id=65281), len=1
0000 - 00                                                .
TLS client extension "extended master secret" (id=23), len=0
Security callback: Version=TLS 1.2: yes
Security callback: Version=TLS 1.3: yes
Security callback: : yes
Security callback: Shared Ciphersuite=AES128-SHA, security bits=128: yes
Security callback: Certificate chain EE key=RSA, bits=2048, security bits=112: yes
write to 0x2132940 [0x212e210] (895 bytes => 895 (0x37F))
0000 - 16 03 03 00 55 02 00 00-51 03 03 dd 1c b2 69 c0   ....U...Q.....i.
0010 - aa 87 cf 55 c4 fc 81 5e-70 60 69 3e 0e da 11 b5   ...U...^p`i>....
0020 - 7a d8 46 44 4f 57 4e 47-52 44 01 20 ce 2f ee 81   z.FDOWNGRD. ./..
0030 - 96 8c 6e cb af 32 23 ed-43 80 e8 b3 16 90 91 05   ..n..2#.C.......
0040 - ca 10 aa 7e 17 ff 4e b6-44 0a 03 fd 00 2f 00 00   ...~..N.D..../..
0050 - 09 ff 01 00 01 00 00 17-00 00 16 03 03 03 17 0b   ................
0060 - 00 03 13 00 03 10 00 03-0d 30 82 03 09 30 82 01   .........0...0..
0070 - f1 a0 03 02 01 02 02 14-7a d8 02 a4 61 e8 50 96   ........z...a.P.
0080 - 43 ab a7 f4 b7 51 d0 1f-ff 56 81 37 30 0d 06 09   C....Q...V.70...
0090 - 2a 86 48 86 f7 0d 01 01-0b 05 00 30 14 31 12 30   *.H........0.1.0
00a0 - 10 06 03 55 04 03 0c 09-6c 6f 63 61 6c 68 6f 73   ...U....localhos
00b0 - 74 30 1e 17 0d 31 39 30-39 30 36 31 32 31 36 33   t0...19090612163
00c0 - 35 5a 17 0d 31 39 31 30-30 36 31 32 31 36 33 35   5Z..191006121635
00d0 - 5a 30 14 31 12 30 10 06-03 55 04 03 0c 09 6c 6f   Z0.1.0...U....lo
00e0 - 63 61 6c 68 6f 73 74 30-82 01 22 30 0d 06 09 2a   calhost0.."0...*
00f0 - 86 48 86 f7 0d 01 01 01-05 00 03 82 01 0f 00 30   .H.............0
0100 - 82 01 0a 02 82 01 01 00-c8 b0 79 a8 96 a5 b1 1c   ..........y.....
0110 - 68 80 83 ef b5 04 d9 e5-f7 2f 09 5c 28 a4 32 a7   h......../.\(.2.
0120 - 80 cc 56 d4 2d 4d 4a d9-0c 4f eb 4d d6 13 16 ec   ..V.-MJ..O.M....
0130 - 6a 49 3f 18 c8 5d 5e bf-78 94 c3 f2 d8 0a a8 1d   jI?..]^.x.......
0140 - e0 d4 5d 4d 9e 50 77 91-db 7b cd f8 b8 6a 91 dc   ..]M.Pw..{...j..
0150 - ba 71 4f 37 d3 97 58 4e-14 4d 2f 6a 6c b7 dc 06   .qO7..XN.M/jl...
0160 - 58 f9 78 09 9a 5b 0e da-b3 65 38 b5 95 5c 03 0d   X.x..[...e8..\..
0170 - 8b 56 25 95 e4 44 46 a0-78 f5 cd e5 08 63 60 12   .V%..DF.x....c`.
0180 - e9 80 51 67 f9 2a 7a a2-18 99 f8 11 43 61 45 43   ..Qg.*z.....CaEC
0190 - ea 44 73 72 31 d9 ef 84-93 d0 d7 75 b8 6e 9d 03   .Dsr1......u.n..
01a0 - ad 88 c1 8b 84 3a 21 90-68 82 a1 a9 40 db b6 7e   .....:!.h...@..~
01b0 - 7f 76 a9 90 7e c9 8f ec-dc 80 c2 56 34 f3 5d 09   .v..~......V4.].
01c0 - bd d5 54 c6 15 77 f4 c7-65 52 ac 23 8b 64 a3 fa   ..T..w..eR.#.d..
01d0 - 13 4f 9b fa bc 27 98 a9-e2 c6 8a 1c c7 b8 58 2b   .O...'........X+
01e0 - 95 f4 69 10 a2 31 8a dd-90 7f 98 ef 2e aa 9d ed   ..i..1..........
01f0 - c6 31 ad 1e 43 6a 3f 43-8e 52 79 d6 fd de 85 43   .1..Cj?C.Ry....C
0200 - 0a dc 8f 55 45 bf d6 df-02 03 01 00 01 a3 53 30   ...UE.........S0
0210 - 51 30 1d 06 03 55 1d 0e-04 16 04 14 c0 e5 5f 38   Q0...U........_8
0220 - 86 c5 3f b1 2f 91 db da-95 3e 82 8c 76 ea 33 b3   ..?./....>..v.3.
0230 - 30 1f 06 03 55 1d 23 04-18 30 16 80 14 c0 e5 5f   0...U.#..0....._
0240 - 38 86 c5 3f b1 2f 91 db-da 95 3e 82 8c 76 ea 33   8..?./....>..v.3
0250 - b3 30 0f 06 03 55 1d 13-01 01 ff 04 05 30 03 01   .0...U.......0..
0260 - 01 ff 30 0d 06 09 2a 86-48 86 f7 0d 01 01 0b 05   ..0...*.H.......
0270 - 00 03 82 01 01 00 6b f1-b5 94 83 a6 08 af e2 6d   ......k........m
0280 - 91 6d 76 8c 3d 63 41 60-b0 16 fd 57 ea 73 16 9c   .mv.=cA`...W.s..
0290 - d4 94 e6 1a 6c f1 b4 a7-1a e2 77 a7 cb f6 ed 5f   ....l.....w...._
02a0 - cf 12 a1 a5 f6 ae a8 73-ea f1 8f 3c 8f 5b 47 9a   .......s...<.[G.
02b0 - 03 82 33 dd 25 d1 f5 8a-b2 eb e7 34 20 f2 6d 26   ..3.%......4 .m&
02c0 - 76 a7 ff 6e 2b f2 fc da-d4 94 25 be 86 47 99 07   v..n+.....%..G..
02d0 - a6 5d 48 03 ac f8 ac 1a-48 f1 bc fb 42 84 c5 d0   .]H.....H...B...
02e0 - f4 d3 e4 25 af ab c7 f0-bf ef 4c cb af c1 a7 85   ...%......L.....
02f0 - 0e e6 55 6f d6 d8 b4 8f-f3 93 72 39 78 f5 e0 e0   ..Uo......r9x...
0300 - 15 2b 90 ef 61 28 ed 9a-43 85 21 95 9d b3 6f 98   .+..a(..C.!...o.
0310 - d8 54 75 bd 34 83 b6 07-33 73 a7 7a 35 ee 85 71   .Tu.4...3s.z5..q
0320 - 17 ca c5 31 4a bc 44 7d-99 ae 76 cf 53 3d f9 84   ...1J.D}..v.S=..
0330 - 08 d4 d5 c6 8d 94 5b d5-03 f5 88 72 f3 4b 6f a7   ......[....r.Ko.
0340 - 59 5d 76 bb 2c 78 a2 5c-a0 05 99 51 4a be bb d6   Y]v.,x.\...QJ...
0350 - 3b 67 49 85 68 57 84 12-8f 7b 79 0c c3 82 ad e3   ;gI.hW...{y.....
0360 - 46 c0 f3 9a 60 ce c0 b2-7e 78 b9 61Security callback: Version=TLS 1.3: yes
Security callback: Version=TLS 1.3: yes
Security callback: Version=TLS 1.2: yes
Security callback: Version=TLS 1.1: yes
Security callback: Version=TLS 1.0: yes
 8a 82 a9 8f   F...`...~x.a....
0370 - 89 2f 1b 98 36 db 16 03-03 00 04 0e 00 00 00      ./..6..........
read from 0x2132940 [0x2111813] (5 bytes => 5 (0x5))
0000 - 16 03 03 01 06                                    .....
read from 0x2132940 [0x2111818] (262 bytes => 262 (0x106))
0000 - 10 00 01 02 01 00 41 59-8d d2 56 97 82 de 60 3c   ......AY..V...`<
0010 - c1 e8 18 14 7e f2 a5 68-12 08 d0 d3 9a fe 6c 93   ....~..h......l.
0020 - 2d 14 8f e1 17 2f ce ae-aa 9c 7c e4 41 6b 52 29   -..../....|.AkR)
0030 - fa 4a 22 db 0a 5c dc 45-12 47 22 0a 38 58 18 6f   .J"..\.E.G".8X.o
0040 - f6 bb a7 50 33 a3 7f bc-da c8 db c1 f7 0e eb 62   ...P3..........b
0050 - 05 38 c4 a2 82 62 2f 72-be b8 1b 1d 81 77 b0 67   .8...b/r.....w.g
0060 - b3 4a 88 7c 7e ca c6 07-6c f6 3b fc f6 d8 30 04   .J.|~...l.;...0.
0070 - ed 54 76 ee 36 65 7d 9e-90 04 ae a2 aa 41 e8 01   .Tv.6e}......A..
0080 - 22 ae f9 71 7c 87 8c 19-d2 3a fd 1b d3 02 18 ea   "..q|....:......
0090 - 5e f6 68 91 a9 47 b6 09-27 dd 1e 11 72 c5 e1 74   ^.h..G..'...r..t
00a0 - f7 24 49 18 bd fd 7e 71-67 47 7f 04 49 cb 4c d4   .$I...~qgG..I.L.
00b0 - 68 a4 d2 c8 18 bc 9f c1-b9 b7 df 17 57 00 46 7b   h...........W.F{
00c0 - ea 10 62 55 b3 6c f2 13-46 8f 8f 0d ed b0 79 1c   ..bU.l..F.....y.
00d0 - 9e a2 84 63 ec 0d c7 e4-b7 08 2e 46 e8 d7 10 fc   ...c.......F....
00e0 - f2 6f 29 af 22 a6 c5 fc-c4 51 ed 59 ec ee d0 54   .o)."....Q.Y...T
00f0 - 8b 04 4b 98 3b 8f 40 09-f5 98 d4 db 8b 2d 5d e2   ..K.;.@......-].
0100 - b4 e1 36 8b 89 c5                                 ..6...
read from 0x2132940 [0x2111813] (5 bytes => 5 (0x5))
0000 - 14 03 03 00 01                                    .....
read from 0x2132940 [0x2111818] (1 bytes => 1 (0x1))
0000 - 01                                                .
read from 0x2132940 [0x2111813] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 40                                    ....@
read from 0x2132940 [0x2111818] (64 bytes => 64 (0x40))
0000 - 59 99 92 9a ab d4 8d c8-22 23 97 3a 4e 80 52 0e   Y......."#.:N.R.
0010 - 53 83 2c 1f d6 72 88 6f-a3 47 76 75 94 81 df 28   S.,..r.o.Gvu...(
0020 - 61 73 07 bd 20 85 67 4c-e5 78 df eb f7 3e 88 61   as.. .gL.x...>.a
0030 - 43 7a 00 26 ab 42 86 b4-81 f9 ac 8e 52 3d 62 92   Cz.&.B......R=b.
write to 0x2132940 [0x212e210] (75 bytes => 75 (0x4B))
0000 - 14 03 03 00 01 01 16 03-03 00 40 55 e6 b6 b5 7c   ..........@U...|
0010 - 42 57 e5 35 74 ba 0f 46-55 e2 94 c8 56 9a 10 92   BW.5t..FU...V...
0020 - ab 1d fe 0d e0 b5 08 28-18 90 a4 e0 e9 21 91 53   .......(.....!.S
0030 - 1d 3f b7 c5 c8 2d 5d 74-a3 29 88 76 2d 8a 5b 59   .?...-]t.).v-.[Y
0040 - 50 49 6a f5 52 b2 57 37-58 0d bb                  PIj.R.W7X..
read from 0x2132940 [0x2111813] (5 bytes => 5 (0x5))
0000 - 15 03 03 00 30                                    ....0
read from 0x2132940 [0x2111818] (48 bytes => 48 (0x30))
0000 - 1d 2f ac 4c 22 7d d0 8f-a5 d4 07 b9 2f 30 16 58   ./.L"}....../0.X
0010 - 5c 35 06 d0 c5 4f 90 f2-9e 8d 64 40 ab 6e 98 09   \5...O....d@.n..
0020 - 35 55 97 df 70 75 33 1f-85 f7 95 20 1e 98 e1 01   5U..pu3.... ....
read from 0x20c87e0 [0x21291f3] (5 bytes => 5 (0x5))
0000 - 16 03 00 00 54                                    ....T
read from 0x20c87e0 [0x21291f8] (84 bytes => 84 (0x54))
0000 - 01 00 00 50 03 03 00 00-00 00 00 00 00 00 00 00   ...P............
0010 - 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
0020 - 00 00 00 00 00 00 20 ce-2f ee 81 96 8c 6e cb af   ...... ./....n..
0030 - 32 23 ed 43 80 e8 b3 16-90 91 05 ca 10 aa 7e 17   2#.C..........~.
0040 - ff 4e b6 44 0a 03 fd 00-02 00 2f 01 00 00 05 ff   .N.D....../.....
0050 - 01 00 01 00                                       ....
TLS client extension "renegotiation info" (id=65281), len=1
0000 - 00                                                .
Security callback: Version=TLS 1.2: yes
Security callback: Version=TLS 1.3: yes
Security callback: : yes
40:B7:FF:94:82:7F:00:00:error:14000068:SSL routines::inconsistent extms:ssl/ssl_sess.c:596:
```

</details>

**Comment by beldmit** [comment]
Is this issue still relevant?

**Comment by t184256** [comment]
Yes. With today's master openssl / tlsfuzzer / tlslite and -d tlsfuzzer script option I still observe the same `AssertionError: Expected alert description "handshake_failure" does not match received "illegal_parameter"`.
