### ISSUE TITLE
shlibload test failure in atexit handlers

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#9914]
One of my co-workers analysed a crash we are seeing when using the atexit handling of openssl cleanup in the shlibload test. The failing test (only one of 10) is below.

Don't mind the library versioning we use internally.

----

When running "./shlibloadtest -crypto_first ../libcrypto.so.2.1 ../libssl.so.2.1 /tmp/whatever", 'shibloadtest' does following things
(1) libssl.so.2.1 depends on libcrypto.so.2.1. This can be verified by 'readelf -d libssl.so.2.1'

(2) dlopen(libcrypto). libcrypto calls atexit(OPENSSL_cleanup).

(3) dlopen(libssl). Note libssl does not call atexit()

(4) get function symbol SSL_CTX_new() from libssl

(5) call SSL_CTX_new(). This will add ssl_library_stop() to "stop_handlers", which locates in libcrypto. "stop_handlers" is a list of function pointers. ssl_library_stop() is a local symbol in libssl.

(6) get function symbol OPENSSL_atexit from libcrypto

(7) call OPENSSL_atexit(atexit_handler). This will add atexit_handler() to stop_handlers. atexit_handler() is a local function in shlibloadtest. At this time, stop_handlers contains two elements: atexit_handler()-->ssl_library_stop().

(8) call dlclose(libcrypto). Because libssl depends on libcrypto, libcrypto is not unloaded at this time.

(9) call dlclose(libssl). Since libssl() did not call atexit(), no atexit handler is called and libssl is unloaded. Now, we can unload libcrypto. OPENSSL_cleanup() is called as part of the unloading due to the atexit() call. OPENSSL_cleanup() will go through the 'stop_handlers" list and call each function. When calling ssl_library_stop(), it tries to refer to a symbol belongs to libssl which has already been unloaded. Hence, the crash.

-----------------------------------------------------------
Following is some gdb outputs:

```
Breakpoint 1, OPENSSL_atexit (handler=0x9f7de06df <ssl_library_stop>) at ../../dist/crypto/init.c:843
843 if ((newhand = OPENSSL_malloc(sizeof(*newhand))) == NULL) {
(gdb) bt
#0 OPENSSL_atexit (handler=0x9f7de06df <ssl_library_stop>) at ../../dist/crypto/init.c:843
#1 0x00000009f7de0685 in ossl_init_ssl_base () at ../../dist/ssl/ssl_init.c:113
#2 0x00000009f7de047c in ossl_init_ssl_base_ossl_ () at ../../dist/ssl/ssl_init.c:24
#3 0x00000009f75c960f in __pthread_once () from /target/qnx7/x86_64/lib/libc.so.5
#4 0x00000009f7a9520d in CRYPTO_THREAD_run_once (once=0x9f8053698 <ssl_base>, init=0x9f7de0473 <ossl_init_ssl_base_ossl_>) at ../../dist/crypto/threads_pthread.c:113
#5 0x00000009f7de07bf in OPENSSL_init_ssl (opts=2097228, settings=0x0) at ../../dist/ssl/ssl_init.c:208
#6 0x00000009f7de721e in SSL_CTX_new (meth=0x9f804cc40 <TLS_method_data.23022>) at ../../dist/ssl/ssl_lib.c:2908
#7 0x00000000131128c4 in test_lib () at ../../dist/test/shlibloadtest.c:195
#8 0x0000000013112d5d in main (argc=5, argv=0x35be60eb58) at ../../dist/test/shlibloadtest.c:338

(gdb) p &stop_handlers
$1 = (OPENSSL_INIT_STOP **) 0x9f7d982e8 <stop_handlers>

p handler
$2 = (void (void)) 0x9f7de06df <ssl_library_stop>

--------------------------------------------------
Breakpoint 1, OPENSSL_atexit (handler=0x1311257e <atexit_handler>) at ../../dist/crypto/init.c:843
843 if ((newhand = OPENSSL_malloc(sizeof(*newhand))) == NULL) {
(gdb) bt
#0 OPENSSL_atexit (handler=0x1311257e <atexit_handler>) at ../../dist/crypto/init.c:843
#1 0x0000000013112a20 in test_lib () at ../../dist/test/shlibloadtest.c:223
#2 0x0000000013112d5d in main (argc=5, argv=0x35be60eb58) at ../../dist/test/shlibloadtest.c:338

p &stop_handlers
$4 = (OPENSSL_INIT_STOP **) 0x9f7d982e8 <stop_handlers>

(gdb) p *stop_handlers
$5 =

{handler = 0x1311257e <atexit_handler>, next = 0x28bfda11b0}
(gdb) p *(OPENSSL_INIT_STOP *)0x28bfda11b0
$6 =

{handler = 0x9f7de06df <ssl_library_stop>, next = 0x0}
-------------------------------------------------

dlclose(cryto)
Breakpoint 2, OPENSSL_cleanup () at ../../dist/crypto/init.c:513
513 {
(gdb) bt
#0 OPENSSL_cleanup () at ../../dist/crypto/init.c:513
#1 0x00000009f75d3c2a in __cxa_finalize () from /target/qnx7/x86_64/lib/libc.so.5
#2 0x00000009f78ce103 in __do_global_dtors_aux () from /target/qnx7/x86_64/usr/lib/libcrypto.so.2.1
#3 0x0000000000000002 in ?? ()
#4 0x00000009f711736b in fini_array.part () from /target/qnx7/x86_64/usr/lib/ldqnx-64.so.2
#5 0x00000009f7119a35 in _dl_free_handle () from /target/qnx7/x86_64/usr/lib/ldqnx-64.so.2
#6 0x00000009f711a42e in _dlclose () from /target/qnx7/x86_64/usr/lib/ldqnx-64.so.2
#7 0x00000009f711a4b8 in dlclose () from /target/qnx7/x86_64/usr/lib/ldqnx-64.so.2
#8 0x0000000013112574 in shlib_close (lib=0x28bfd8ee48) at ../../dist/test/shlibloadtest.c:74
#9 0x0000000013112b75 in test_lib () at ../../dist/test/shlibloadtest.c:269
#10 0x0000000013112d5d in main (argc=5, argv=0x35be60eb58) at ../../dist/test/shlibloadtest.c:338

p stopped
$8 = 0
```

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input
